### ISSUE TITLE
Manipuri numbers are pronounced wrongly

### ISSUE THREAD

**Issue by prasenjit-mahiti** [espeak-ng/espeak-ng#100]
manipuri pronounces the thousand onward numbers in a reverse way.

for example:

> 2000 should be pronounced as "l,isiN~tS'a:ni"

**Comment by ValdisVitolins** [comment]
Even though eSpeakNG has [sound inventory](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_manipuri) (phoneme list) for Manipuri language, I couldn't find pronunciation rules for it. Closest language I could find is Bengali ([bn_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/bn_list) and [bn_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/bn_rules) files). Is this appropriate language to look at?

**Comment by valdisvi** [comment]
Do to historically extended design and changes in language codes, [tr_languages.c](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/tr_languages.c), language definition for Manipuri was actually ineffective.
