### ISSUE TITLE
please add tie bars

### ISSUE THREAD

**Issue by martino-vic** [espeak-ng/espeak-ng#1002]
English transcriptions don't use tie bars, which I argue is wrong. Using espeak-ng 1.50 through phonemizer 2.2.2 on Windows 10 and Python 3.9:

```
>>> from phonemizer import phonemize
>>> phonemize("Jackiechan", backend="espeak", language="en-us")
'dʒækaɪtʃən '
```
But the correct output should be ```'d͡ʒækit͡ʃæn '``` (with tie bars), imo.

The [official documentation](https://www.internationalphoneticassociation.org/content/ipa-other-symbols) reads: "Affricates and double articulations *can* be represented by two symbols joined by a bar *if necessary*". However, those tie bars *are* necessary because ipa-tokenisers can't handle the output otherwise. E.g. with lingpy 2.6.8:
```
>>> from lingpy import *
>>> ipa2tokens("dʒækitʃæn")
['d', 'ʒ', 'æ', 'k', 'i', 't', 'ʃ', 'æ', 'n']
```
or with ipatok 0.2.0:
```
>>> from ipatok import tokenise
>>> tokenise("dʒækitʃæn")
['d', 'ʒ', 'æ', 'k', 'i', 't', 'ʃ', 'æ', 'n']
```
The correct output should be ```['dʒ', 'æ', 'k', 'i', 'tʃ', 'æ', 'n']```, but this can only be achieved with a tie bar:
```
>>> from lingpy import *
>>> ipa2tokens("d͡ʒækit͡ʃæn")
['d͡ʒ', 'æ', 'k', 'i', 't͡ʃ', 'æ', 'n']
```
```
>>> from ipatok import tokenise
>>> tokenise("d͡ʒækit͡ʃæn")
['d͡ʒ', 'æ', 'k', 'i', 't͡ʃ', 'æ', 'n']
```

As [reddit user vokzhen](https://www.reddit.com/r/asklinguistics/comments/7dovxv/when_should_i_use_tie_bars_for_affricates_in_ipa/) points out: "[Tie bars] generally only need to be used when the language or topic makes the distinction between the two. In English, it's strictly speaking /kæts/ and /kæt͡ʃ/, but as there's no /kætʃ/ or /kæt͡s/ that contrasts with it, you don't really need it." This means that the tie bar is only unnecessary, as long as you are handling monolingual data. As soon as you have multilingual data, where there *is* a distinction between e.g. <dʒ> and <d͡ʒ>, the tie bar *is* necessary. This connects also to the fact that ipa-tokensiers are not written specifically for English, but for any kind of ipa-string.

Therefore please consider adding tie bars where they *can* be used because they *are* necessary in certain contexts.

**Comment by jaacoppi** [comment]
The "--tie" command line argument produces the tie bar. See espeak-ng --help for more information.

Example:
espeak-ng --tie --ipa Jackiechan
d͡ʒˈaka͡ɪt͡ʃən

The question is, should tie bars be used by default or not? I am not familiar with them.

**Comment by martino-vic** [comment]
Thank you! This answers my question :)
