### ISSUE TITLE
espeak-ng 1.51-dev / mbrola 3.4-dev error: "mbrola: Warning: w-O2 unknown, replaced with _-_"

### ISSUE THREAD

**Issue by ScottMonaghan** [espeak-ng/espeak-ng#1007]
OS: Ubuntu 18.04
espeak-ng version: 1.51-dev
mbrola version: 3.4-dev

Hello,

When I use the voice us-mbrola-1, I get the error below for all "ah" sounds.

```
espeak-ng -v us-mbrola-1 "I want to be your friend" -x
aI w'O2nt t@bi jU@ fr'End
mbrola: Warning: w-O2 unknown, replaced with _-_
mbrola: Warning: O2-n unknown, replaced with _-_
```
This seems similar to https://github.com/espeak-ng/espeak-ng/issues/566

I have classic espeak on another device and I don't get this error with this voice.

Any advice on how I can fix this?

**Comment by ScottMonaghan** [comment]
In contrast here's what I get when I run this in classic espeak (1.48.03, Ubuntu 20.04.2):

```
espeak -m -v us-mbrola-1 "I want to be your friend" -x
 aI w'0nt t@bi jU@ fr'End
```

**Comment by valdisvi** [comment]
Previous versions of eSpeak didn't show these warning, which comes from non-existent phoneme transitions in MBROLA phoneme database. To fix such warnings you have to make translation rule in [MBROLA phoneme translation file](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md#2-add-mbrola-phoneme-translation-file), e.g. replace [O2 phoneme with O](https://github.com/espeak-ng/espeak-ng/commit/b8fd44837ab02cadce33518a1cb8baad0a9ec123).

**Comment by valdisvi** [comment]
By the way, proper way for MBROLA voice is `mb-us1`, if some other way also works, it is not official and is not documented.

**Comment by ScottMonaghan** [comment]
Thank you. Do I need to recompile after making this change?

**Comment by valdisvi** [comment]
In general, yes. But you may try to replace only `.../espeak-ng-data/mbrola_ph/es_phtrans` file, which is binary file compiled from translation rules.

**Comment by ScottMonaghan** [comment]
Thanks @valdisvi! I was able to build and test this today and it worked perfectly!

**Comment by CILT** [comment]
Hi, I have the same issue and I'm not sure about how to solve it/.

Versions:
OS: `Debian GNU/Linux 12 (bookworm)`
Espeak-ng: `espeak-ng/stable 1.51`
Mbrola: `mbrola/stable 3.3`

Here's what I get with an easy example (using mb-mx1):
```
$ espeak-ng "Hola, cómo estás. Este es un texto de prueba."  -v mb-mx1 -x
'ola
k'omo est'as
mbrola: Warning: m-o/ unknown, replaced with _-_
mbrola: Warning: o/-e/ unknown, replaced with _-_
mbrola: Warning: e/-s unknown, replaced with _-_
'este 'es 'un t'eksto De p**u'eBa
mbrola: Warning: t-e/ unknown, replaced with _-_
mbrola: Warning: e/-e unknown, replaced with _-_
mbrola: Warning: t-o/ unknown, replaced with _-_
mbrola: Warning: o/-d unknown, replaced with _-_
mbrola: Warning: d-e/ unknown, replaced with _-_
mbrola: Warning: e/-p unknown, replaced with _-_
```
The same happens for mb-es3, but this is better:
```
$ espeak-ng "Hola, cómo estás. Este es un texto de prueba."  -v mb-es3 -x
'ola
k'omo est'as
'este 'es 'un t'eksto De p**u'eBa
mbrola: Warning: p-h unknown, replaced with _-_
mbrola: Warning: h-u unknown, replaced with _-_
```

**Comment by jaacoppi** [comment]
The root cause is that the mapping between espeak NG and mbrola does not contain all the possible phonemes. The mappings are in phsource/mbrola/<language code>.

Add the missing mappings, recompile and it should work.
