### ISSUE TITLE
Setswana language  is not supported by the espeak backend

### ISSUE THREAD

**Issue by Godsownchild** [espeak-ng/espeak-ng#1008]
Setswana is listed as part of languages support in the documentation [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages.md). But when I run the command ` espeak --voice` it is not listed there.

**Comment by jaacoppi** [comment]
The file says:

"Development version of eSpeak NG supports 126 languages and accents,
which are listed in table below."

Are you running the develoment version? Check your version with: espeak-ng --version

Current is 1.51-dev. According to CHANGELOG.md, Setswana has been available since 1.49.1.

**Comment by Godsownchild** [comment]
Thank you very much,  I am using the 1.48.03 version my bad. 

1. Is there a difference between `espeak`  and `espeak-ng`,when i run `espeak --version ` it gives me `speak text-to-speech: 1.48.03  04.Mar.14   Data at: /usr/local/Cellar/espeak/1.48.04_1/share/espeak-data` but `espeak-ng ` gives this `zsh: command not found: espeak-ng`.
2. How do I upgrade for mac OS, I installed the one I am using currently with homebrew.

**Comment by Godsownchild** [comment]
Thank you very much.
