### ISSUE TITLE
mbrola voices get reset

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#1011]
Hello,

Here is a testcase:

```
#include <espeak-ng/espeak_ng.h>
#include <stdio.h>
#include <unistd.h>

int main(void) {
	espeak_ERROR err;
	espeak_Initialize(AUDIO_OUTPUT_SYNCH_PLAYBACK, 0, NULL, 0);

	err = espeak_SetVoiceByName("mb-fr4");
	printf("%d\n", err);
	espeak_Synth("<speak>Bonjour</speak>", 22, 0, POS_CHARACTER, 0, espeakSSML, NULL, NULL);
	espeak_Synth("<speak>Bonjour</speak>", 22, 0, POS_CHARACTER, 0, espeakSSML, NULL, NULL);
}
```

It is supposed to speak "Bonjour" twice with the `fr4` mbrola voice. The first utterance indeed does so, but the second one does not: the voice gets reset to a default espeak french voice.

Non-mbrola voices (e.g. specifying "en" instead of "mb-fr4") do not seem to be affected. Avoiding the use of SSML also avoids the issue.

This prevents speech-dispatcher from directly using espeak-ng for mbrola voices, and makes it have to use the external /usr/bin/espeak-ng tool, thus lowering the quality of support for mbrola voices.

Samuel

**Comment by jaacoppi** [comment]
This is most probably an SSML issue. The SSML voice stack is known to have many bugs. I've tried but  haven't been able to fix them.
