### ISSUE TITLE
Memory leak: oldFrameRequest allocated at speechPlayer/src/frame.cpp:87

### ISSUE THREAD

**Issue by brawer** [espeak-ng/espeak-ng#1012]
According to clang’s [LeakSanitizer](https://clang.llvm.org/docs/LeakSanitizer.html), there is a memory leak on `src/speechPlayer/src/frame.cpp:87:19`. It seems that the freshly allocated `frameRequest_t` isn’t always getting correctly freed.

```cpp
FrameManagerImpl(): curFrame(), curFrameIsNULL(true), sampleCounter(0), newFrameRequest(NULL), lastUserIndex(-1)  {
	oldFrameRequest=new frameRequest_t();
	oldFrameRequest->NULLFrame=true;
}
```

To reproduce, build a Docker container with the following Dockerfile:

```Dockerfile
FROM debian:bullseye-backports
RUN apt-get update
RUN apt-get install -y clang make autoconf automake libtool pkg-config libsonic-dev ronn kramdown libpcaudio-dev libsox-dev
```

And then, inside the container, run this command:

```sh
./autogen.sh
CFLAGS="-fsanitize=address,undefined -g" LDFLAGS="-fsanitize=address,undefined" CC=clang ./configure
make
```

Eventually, it leads to this error (among others):

```
Direct leak of 408 byte(s) in 1 object(s) allocated from:
    #0 0x4ca1ed in operator new(unsigned long) (/espeak/src/.libs/espeak-ng+0x4ca1ed)
    #1 0x7effd71218cc in FrameManagerImpl::FrameManagerImpl() /espeak/src/speechPlayer/src/frame.cpp:87:19
    #2 0x7effd71218cc in FrameManager::create() /espeak/src/speechPlayer/src/frame.cpp:132:51
    #3 0x7effd7113ea4 in KlattInit /espeak/src/libespeak-ng/klatt.c:1080:2
    #4 0x7effd70e41f1 in WavegenInit /espeak/src/libespeak-ng/wavegen.c:363:2
    #5 0x7effd6ef5eac in espeak_ng_CompilePhonemeDataPath /espeak/src/libespeak-ng/compiledata.c:2547:2
    #6 0x7effd6ef5ae6 in espeak_ng_CompilePhonemeData /espeak/src/libespeak-ng/compiledata.c:2515:9
    #7 0x4ce9aa in main /espeak/src/espeak-ng.c:560:14
    #8 0x7effd6898d09 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26d09)
```

**Comment by valdisvi** [comment]
@datajake1999, as SpeechPlayer was included in eSpeak NG project by you, can you investigate it? Otherwise it is easier to remove it and SpeachPlayer users will need to rely on https://bitbucket.org/nvaccess/speechplayer/src/master/.

**Comment by datajake1999** [comment]
I will look In to this and contribute a fix If I can find one. This isn't a problem in most real world situations, so I wouldn't consider removing SpeechPlayer unless It had crippling side effects.

**Comment by TheQuinbox** [comment]
I see no memory leak, from looking at the code. Clang Analyzer might be incorrect. Plus, it doesn't effect the performance of Espeak itself. I used speech player with Espeak for months, and noticed nothing. I vote for a close of this issue; no need to remove code that isn't effecting things and just makes things better.

**Comment by sthibaul** [comment]
This was fixed recently

**Comment by sthibaul** [comment]
thus closing, since fixed
