### ISSUE TITLE
Add luxembourgish

### ISSUE THREAD

**Issue by hozosch** [espeak-ng/espeak-ng#1013]
Ok, I know, another of those add this or that language things and there are plenty of other difficult issues for you to deal with, not just concerning this project. Really, if I had the time and patience, I'd add the language myself and create a pull request instead. Saying that, so far, all I did is improve existing languages, and adding a completely new language feels like a much more intimidating task for me. Sure, I could read all the guidelines and stuff, but here go time and patience again. When it comes to the language itself, one argument not to add this language could be that German and French, which already exist in ESpeak, are spoken and / or understood by luxembourgers as well, so why add this language? Well, ESpeak has all kinds of minority languages, artificial languages, and whatnot. So I don't see the point in not adding it when I think about it like that. Besides, there's luxembourgish as a display language in Windows, and wouldn't a blind person in luxembourg who uses luxembourgish on a regular basis want to have a TTS being able to speak in that language to him / her? NVDA doesn't speak it yet, but that should be fairly easy to do. All I ask is that you create an initial basis on which I'll provide patches later on if needed. You may use this as your base:
https://en.wikipedia.org/wiki/Luxembourgish_phonology
Thanks very, very much in advance for considering this!

**Comment by valdisvi** [comment]
Adding artificial languages is actually easier than adding native ones, because they are simpler and more consistent.

**Comment by hozosch** [comment]
Ok, I do get your point about that. But Maori, for example, is no artificial language, is it?

**Comment by mbarnig** [comment]
I started creating an [luxembourgish voice for espeak-ng](https://www.web3.lu/espeak-formant-synthesizer/) a few years ago. The project was never finalized and didn't reach a state where a Github pull-request was sensible. In the mean time I switched to deep-machine learning to create speech synthesis voices for luxembourgish. Recent posts about this topic are available in the [blog of my website](https://www.web3.lu/category/audio-technologies/).

A few days ago I resumed my ancient works on espeak-ng and [forked the latest master branch](https://github.com/mbarnig/espeak-ng-lb) of the related Github repository, this time with the goal to launch a pull-request to add luxembourgish as additional language and voice to espeak-ng. A prototype of the project is currently working on my Ubuntu Desktop PC.

**Comment by hozosch** [comment]
Wow, that's some great news! My friend and I discovered the luxembourgish Pack in windows 10 recently and I thought it's a pity ESpeak can't speak it. WE have a mutual friend from Luxembourg, so this really got us into it.

**Comment by mbarnig** [comment]
I just created a [pull request](https://github.com/espeak-ng/espeak-ng/pull/1038) to add Luxembourgish as 127th language to eSpeak-NG. My forked repository is at [mbarnig/espeak-ng-lb](https://github.com/mbarnig/espeak-ng-lb).

**Comment by hozosch** [comment]
Oh yes! I think I will close it at this point. I hope I'll be able to test it soon, be it in NVDA or on odo.lv. For this, it needs to be merged.

**Comment by errotech** [comment]
Moien! 🇱🇺

You may improve the pronunciation since it sounds a bit weird and my friend had problems to understand a whole sentence.

But anyway: cool that we can realize this with eSpeak! Long life OpenSource, long liveEspeak! :)
