### ISSUE TITLE
The pronunciation of Mandarin Chinese using ESpeak NJ in NVDA is not normal

### ISSUE THREAD

**Issue by cary-rowen** [espeak-ng/espeak-ng#1028]
When reading a Chinese character aloud, in addition to reporting the Chinese character itself, the tones of the Chinese character will also be read out in English numbers. This is abnormal.
This looks similar to [this Issue](https://github.com/espeak-ng/espeak-ng/issues/499)
I have created the same issue in NVDA's Repo:
https://github.com/nvaccess/nvda/issues/12952

### Steps to reproduce:
1. Use NVDA 2021.2 or the latest Alpha version to read the following text, The Chinese meaning of 'this text is(Today's weather is good.':
  - 今天的天气很好
2. Use NVDA2021.1 to read the Same sample text:
  - "今天的天气很好".

### Actual behavior:
In step (1)
NVDA reports ("今One 天 One 的 Five 天 One 气 Four 很 Three 好 Three").
The following is the incorrect recording demonstration (from NVDA-2021.2):
https://drive.google.com/file/d/1wBNLbUzQpPMx-5zLfXYC-XbEg0d6_1fo/view?usp=sharing

### Expected behavior:
NVDA reports sample text ("  - 今天的天气很好") in Mandarin, just like NVDA-2021.1.
The following is the correct recording demonstration (from NVDA-2021.1):
https://drive.google.com/file/d/1EdaSVpDq8kLXCaAEqZmFcaHRpMwfiJOU/view?usp=sharing

**Comment by cary-rowen** [comment]
Is there the latest news about this issue? Can we fix this error?

**Comment by jaacoppi** [comment]
I can't repdoruce this, but it's probably connected to #1044.

**Comment by jaacoppi** [comment]
Sorry, my bad. I can reproduce this. The discussion is in the other thread.

**Comment by cary-rowen** [comment]
At present, Chinese users are still plagued by this problem. Is there any progress on this issue?

**Comment by jaacoppi** [comment]
Unfortunately there has been no progress. I can't find the root cause. Reverting to older behavior would cause mandarin and cantonese work differently and cause different kind of problems.

**Comment by cary-rowen** [comment]
Hi,

Please default ESpeak NG's voice role to "Chinese (Mandarin, latin as Pinyin)" for Chinese to fix this issue.
I've created the issue in the NVDA Repo, but it seems like it should be reported to ESpeak.
Please see [#13572](https://github.com/nvaccess/nvda/issues/13572)

Thanks
