### ISSUE TITLE
Maximum group number which works is actually 62

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#103]
Tested in ```dictsource/lv_rules```
add lines:
```
// These are used for "." like padding
.L62 a ā b c č d e ē f g ģ h ḩ i ī j k ķ l ļ m n ņ o ō p q r ŗ s š t u ū v w x y z ž 
```

and in
```
...
.group o
...
_zL62L62L62) o (L62L62L62z_ o:        // !!! for test purposes only
...
```
Then compile and run:
   espeak-ng -vlv -X "zarvonikz"
Produces:
```
Translate 'zarvonikz'
  1	z        [z]
  1	a        [a]
  1	r        [R]
  1	v        [v]
145	_zL62L62L62) o (L62L62L62z_ [o:]
  1	o        [uo]
  1	n        [n]
  1	i        [i]
  1	k        [k]
  1	z        [z]
 z'aRvo:nikz
```
Replace group **L62** with **L63**:
and 
   espeak-ng -vlv -X "zarvonikz"
produces:
```
Translate 'zarvonikz'
  1	z        [z]
  1	a        [a]
  1	r        [R]
  1	v        [v]
  1	o        [uo]
  1	n        [n]
  1	i        [i]
  1	k        [k]
  1	z        [z]
 z'aRvuonikz
```
so, group L63 (or higher doesn't work)

**Comment by rhdunn** [comment]
Some comments:

1.  Don't add comments referencing bugs in the code -- the behaviour is clear from the code, so it does not need a comment anyway.
2.  `RULE_LETTERGP` only accepts `A-Z`, so does not need the check -- maybe validate that this is actually in the `A-Z` range.
3.  `N_LETTER_GROUPS` has a comment saying the number of groups is calculated as `127-32`. Here, `127` is the maximum signed byte value, and `32` corresponds to the space (` `) character. Presumably `A` should be replaced by space (` `) in the `RULE_LETTERGP` branches.
4.  The `RULE_PRE` case (line 1924) is not updated.
5.  Need to make sure that the places that set `letterGroups` and that convert the rule to a string are consistent with the new behaviour.

**Comment by ValdisVitolins** [comment]
> 1\. Don't add comments referencing bugs in the code -- the behaviour is clear from the code, so it does not need a comment anyway.

Fixed.
> 2\. RULE_LETTERGP only accepts A-Z, so does not need the check -- maybe validate that this is actually in the A-Z range.

Fixed. **letter_group** actually should be checked only for **RULE_LETTERGP2** case

> 3\. N_LETTER_GROUPS has a comment saying the number of groups is calculated as 127-32. Here, 127 is the maximum signed byte value, and 32 corresponds to the space () character. Presumably A should be replaced by space () in the RULE_LETTERGP branches.

'A' is subtracted to make value of **letter_group** equal to number in **.Lxx** definition

> 4\. The RULE_PRE case (line 1924) is not updated.

Fixed.

>5\.  Need to make sure that the places that set letterGroups and that convert the rule to a string are consistent with the new behaviour.

I run [espeak-ng-spellcheck](/ValdisVitolins/espeak-ng-spellcheck) for English to check, there is no regressions.
