### ISSUE TITLE
espeak-ng defaults to -grandma version if no voice is selected in Qt Speech with speechd >0.10.0

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [espeak-ng/espeak-ng#1034]
There is a problem with Qt apps (`QGroundControl` is a popular example) on new distros (Fedora 34, Ubuntu 21.10 ) that are using newer version of `speechd`. The voice generated by these apps is always a `grandma` version. We had a long talk about this in this issue: https://github.com/brailcom/speechd/issues/627 but here is a TLDR:

Since `speech-dispatcher` ~v0.10.0 they have exposed new variations of voices to the users. In apps like `QGroundControl` developers only sets locale according to system settings and generated voice changed from normal to grandma with the distro upgrade.

I have tested it and to manually set the voice one need to ask Qt for all voices and select one by name string. In my opinion the `espeak-ng` should default to "normal" voice if no other is selected. According to Qt the first voice in the list is `grandma` version.

The problem can be easily verified by running a Qt example called `Hello Speak`: https://code.qt.io/cgit/qt/qtspeech.git/tree/examples/speech/hello_speak?h=5.15

**Comment by sthibaul** [comment]
I don't think this is an espeak-ng problem, but rather a misunderstanding between libspeechd and qtspeech

**Comment by sthibaul** [comment]
A fix was submitted to qt speech: https://github.com/brailcom/speechd/issues/627

**Comment by ArkadiuszNiemiec** [comment]
Yes, thank you.
https://github.com/brailcom/speechd/releases/tag/0.11.1

**Comment by sthibaul** [comment]
The fix is not in speechd, but in qt speech. I don't know if the fix was applied, but at any rate the bug is not in espeak-ng so closing was right indeed :)

**Comment by ArkadiuszNiemiec** [comment]
I have assumed that `Fix listing voices of the default module.` fixes the issue described by https://github.com/brailcom/speechd/issues/627#issuecomment-955298950
But yes, sorry for not closing this issue before.

**Comment by sthibaul** [comment]
> I have assumed that `Fix listing voices of the default module.` fixes the issue

No, that's unrelated.
