### ISSUE TITLE
Errors in Italian phonetic transcription

### ISSUE THREAD

**Issue by donand** [espeak-ng/espeak-ng#1037]
Hello everyone,

I'm using espeak-ng to get the phonetic transcription of some Italian texts but I find some errors.
The errors are:
- `e` vs `ɛ`
- `o` vs `ɔ`
- primary stress on the wrong syllable

The foreign names are not really an error, but would it be possible to add some sort of dictionary?

I'm using `eSpeak NG text-to-speech: 1.50`

Here are some errors I found.
Format `text, espeak-ng output, correct phonetic transcription`
### Verbs
 ```
avresti, avrˌɛstɪ, avrˌestɪ
avrebbe, avrˌɛbːe, avrˌebːe
avremmo, avrˌɛmmo, avrˌemmo
avreste, avrˌɛste, avrˌeste
avesse, avˌɛsse, avˌesse
avessi, avˌɛssɪ, avˌessɪ
aveste, avˌɛste, avˌeste
sapeva, sapˈɛva, sapˈeva
sapevo, sapˈɛvo, sapˈevo
sapevi, sapˈɛvɪ, sapˈevɪ
dovresti, dovrˈɛstɪ, dovrˈestɪ
dovrebbe, dovrˈɛbːe, dovrˈebːe
dovremmo, dovrˈɛmmo, dovrˈemmo
dovreste, dovrˈɛste, dovrˈeste
dicevo, ditʃˈɛvo, ditʃˈevo
dicevɪ, ditʃˈɛvɪ, ditʃˈevɪ
diceva, ditʃˈɛva, ditʃˈeva
temevo, temˈɛvo, temˈevo
temeva, temˈɛva, temˈeva
potessi, potˈɛssɪ, potˈessɪ
potesse, potˈɛsse, potˈesse
saresti, sarˌɛstɪ, sarˌestɪ
sarebbe, sarˌɛbːe, sarˌebːe
saremmo, sarˌɛmmo, sarˌemmo
sareste, sarˌɛste, sarˌeste
fosse, fˌɔsse, fˌosse
```
### Foreign Names
```
gargoyle, ɡarɡoˈile, ɡarɡˈɔil
voldemort, voldˈemort, vˈɔldemɔrt
Peeves, peˈɛves, pˈivs
Umbridge, ʊmbrˈiddʒe, ambrˈiddʒ
Weasley, weˈazleɪ, wˈizleɪ
Ron, rˈon, rˈɔn
Wood, wˈɔod, wˈud
Percy, pˈɛrtʃɪ, pˈɛrsɪ
Roberts, rˈoberts, rˈɔberts
Azkaban, atskˈaban, ˈatskaban
```
### Other
```
incantesimi, inkantˈɛzimɪ, inkantˈezimɪ
quello, kwˈɛllo, kwˈello
quella, kwˌɛlla, kwˌella
questa, kwˌɛsta, kwˌesta
questo, kwˌɛsto, kwˌesto
queste, kwˌɛste, kwˌeste
questi, kwˌɛstɪ, kwˌestɪ
chicchessia, kikːˈessia, kikːessˈia
lettera, lˈɛtːera, lˈetːera
professor, professˈɔr, professˈor
è, e, ɛ
nella, nˌɛlla, nˌella
nello, nˌɛllo, nˌello
nelle, nˌɛlle, nˌelle
pareti, parˈɛtɪ, parˈetɪ
loro, lˌɔro, lˌoro
```

**Comment by jaacoppi** [comment]
The dictionary for italian is in dictsource/it_list. You can add the foreign words there. See the files in docs/ for information.

I'm not sure where the wrong IPA comes from.

**Comment by Christianlm** [comment]
I can fix these mistakes at the weekend.

Just some comments:
regarding open or closed e pronunciation, in certain areas of Italy is used the open e, in others the closed e.

So what is the correct pronunciation?
Are there any reliable references regarding the correct pronunciation of open or closed vowels?
Same thing for the vowel "o" pronunciation.

About  foreign words, I have included common words in Italian, such as, internet, backup, bijoux, blackout, bypass, computer, wireless, zoom, etc... 
Proper names of people or countries/cities, such as james, jonathan, juan, sean, shakespeare, bucarest, cambridge, canterbury, chicago, düsseldorf, houston, manchester, washington, etc...

Any new entry in the Italian dictionary as foreign word is welcome.

Thanks for your collaboration in Italian language!

**Comment by donand** [comment]
Yes, you are right.

I ran an evaluation on a text transcribed with espeak and I found some other errors.
I also checked the pronunciation against the following Italian Pronunciation Dictionaries:

- http://www.dipionline.it/dizionario/ - gives the pronunciation in IPA
- http://www.dizionario.rai.it/index.aspx?treeID=1 - very rich dictionary, but it does not have the IPA transcription, only the information about the accent and if the accented vowel is open or close, but this is usually enough
- https://www.garzantilinguistica.it/ricerca/ - useful for some verbs where i couldn't find the transcription in the previous two

After the check I found out that some of the words I listed in the issue are actually correct, like `sarebbe` and `avrebbe` with an open `e`.

Here there's a more complete list of errors and updated with the check using the dictionaries.
Of course there could be mistakes since this evaluation was done manually on a large text, but I hope that there won't be many of them.

## Verbs
Here the most common error is with `è` that is transcribed with a closed `e`.
```
è, e, ɛ
accede, atʃːˈede, atʃːˈɛde
avresti, avrˌɛstɪ, avrˌestɪ
avremmo, avrˌɛmmo, avrˌemmo
avreste, avrˌɛste, avrˌeste
avesse, avˌɛsse, avˌesse
avessi, avˌɛssɪ, avˌessɪ
aveste, avˌɛste, avˌeste
contendono, kontˈendono, kontˈɛndono
dovresti, dovrˈɛstɪ, dovrˈestɪ
dovremmo, dovrˈɛmmo, dovrˈemmo
dovreste, dovrˈɛste, dovrˈeste
dicevo, ditʃˈɛvo, ditʃˈevo
dicevɪ, ditʃˈɛvɪ, ditʃˈevɪ
diceva, ditʃˈɛva, ditʃˈeva
eretto, erˈetːo, erˈɛtːo
fosse, fˌɔsse, fˌosse
permetteva, permetːˈɛva, permetːˈeva
posta, pˈɔsta, pˈosta
potessi, potˈɛssɪ, potˈessɪ
potesse, potˈɛsse, potˈesse
raccoglie, rakːˈoʎe, rakːˈɔʎe
rappresentano, rapːrezˈentano, rapːrezˈɛntano
sapeva, sapˈɛva, sapˈeva
sapevo, sapˈɛvo, sapˈevo
sapevi, sapˈɛvɪ, sapˈevɪ
saresti, sarˌɛstɪ, sarˌestɪ
saremmo, sarˌɛmmo, sarˌemmo
sareste, sarˌɛste, sarˌeste
temevo, temˈɛvo, temˈevo
temeva, temˈɛva, temˈeva
venne, vˈɛnne, vˈenne
c'è, tʃe, tʃɛ
```

## General
```
quello, kwˈɛllo, kwˈello
quella, kwˌɛlla, kwˌella
quelle, kwˌɛlle, kwˌelle
questa, kwˌɛsta, kwˌesta
questo, kwˌɛsto, kwˌesto
queste, kwˌɛste, kwˌeste
questi, kwˌɛstɪ, kwˌestɪ
nella, nˌɛlla, nˌella
nello, nˌɛllo, nˌello
nelle, nˌɛlle, nˌelle
nei, nˌɛi, nˌei

loro, lˌɔro, lˌoro
incantesimi, inkantˈɛzimɪ, inkantˈezimɪ
chicchessia, kikːˈessia, kikːessˈia
lettera, lˈɛtːera, lˈetːera
professor, professˈɔr, professˈor
pareti, parˈɛtɪ, parˈetɪ
pochi, pˈokɪ, pˈɔkɪ
poche, pˈoke, pˈɔke
ancor, ankˈɔr, ankˈor
brefotrofio, brefotrˈofio, brefotrˈɔfio
centoventisette, tʃentoventizˈetːe, tʃentoventizˈɛtːe
corridoi, korɾidˈɔi, korɾidˈoi
curiosi, kʊriˈɔzɪ, kʊriˈozɪ
dimensiona, dimensjˈɔna, dimensjˈona
famosi, famˈɔzɪ, famˈozɪ
foglie, fˈoʎe, fˈɔʎe
gio, dʒˈɔ, dʒˈo
gorgonzola, ɡorɡontsˈɔla, ɡorɡondzˈɔla
interrotte, interɾˈɔtːe, interɾˈotːe
luoghi, lʊˈoɡɪ, lʊˈɔɡɪ
maggior, madʒːˈɔr, madʒːˈor
metri, mˈetrɪ, mˈɛtrɪ
nord-est, nˈɔrdˈest, nˈɔrdˈɛst
numerosi, nʊmerˈɔzɪ, nʊmerˈozɪ
occupano, ˈokːʊpano, ˈɔkːʊpano
opera, ˈopera, ˈɔpera
opere, ˈopere, ˈɔpere
po', pˈo, pˈɔ
pressoché, pressokˈe, prɛssokˈe
ricasoli, rikazˈɔlɪ, rikazˈolɪ
romane, rˌɔmˈane, rˌomˈane
torre, tˈɔrɾe, tˈorɾe
torri, tˈɔrɾɪ, tˈorɾɪ
```

## Numbers
Here in numbers the errors are when they are written in letters and not in digits, with the exception of 30 that is always wrong (it should have a closed e)
```
trenta, trˈɛnta, trˈenta
30, trˈɛnta, trˈenta
centotredici, tʃentotrˈɛditʃɪ, tʃɛntotrˈeditʃɪ
centonove, tʃentonˈove, tʃɛntonˈove
milleseicentouno, millezejtʃentoˈuno, millesejtʃɛntoˈuno
millesettecentouno, millezetːetʃentoˈuno, millesetːetʃɛntoˈuno
centosessanta, tʃentozessˈanta, tʃɛntosessˈanta
centosettanta, tʃentozetːˈanta, tʃɛntosetːˈanta
duemilaundici, dʊemilˈaʊnditʃɪ, dʊemilaˈʊnditʃɪ
```

## Foreign Names
Here I'm not 100% sure of the transcription, but it looks ok to me.
```
gargoyle, ɡarɡoˈile, ɡarɡˈɔil
voldemort, voldˈemort, vˈɔldemɔrt
Peeves, peˈɛves, pˈivs
Umbridge, ʊmbrˈiddʒe, ˈambriddʒ
Weasley, weˈazleɪ, wˈizleɪ
Ron, rˈon, rˈɔn
Wood, wˈɔod, wˈud
Percy, pˈɛrtʃɪ, pˈɛrsɪ
Roberts, rˈoberts, rˈɔberts
Azkaban, atskˈaban, ˈatskaban
Beauxbatons, beaʊksbˈatons, bobatˈon
isozaki, izotsˈakɪ, izodzˈakɪ
oberdan, obˈɛrdan, ˈoberdan
```

**Comment by Christianlm** [comment]
I apologize for the eternal delay, a PR on this issue will come soon.
Some further considerations:
It is preferable to check the phonetic transcription for a single word, 
cause  in continuous reading of an entire sentence eSpeak has different behaviors.
E.G. an open E changes to a different phoneme, for example a short unstressed (secondaryStress) open E.
This is to help the Italian prosody and intonation.
Regarding numbers written literally, I think it's an endless job. There are infinite combinations, we don't get out alive.
Thanks.
