### ISSUE TITLE
requesting zulu language for ESpeak.

### ISSUE THREAD

**Issue by Sergiawsxp** [espeak-ng/espeak-ng#1040]
Is difficult to find syntesizers of some languages. An example of that is the zulu language, a South African language. I'm not from South Africa, I just wanted to experiment with some of these languages, and zulu has very interesting sounds.
As I noticed, zulu phonemes are close to Swahili and Setswana languages, an example of that is the pronunciation of "hl" (both languages, zulu and setswana, pronounce it the same way). Another thing is how can be implemented the pronunciation of the "q", "x" and "c", these phonemes have strange sounds. And is also important to remember that some letters like t or p can have an aspiration (th, ph). Another thing, can't see how to create languages on Windows. So, if you implement that language, can you tell how to add it to a Windows Sapi5 ESpeak? Thanks for replying!
Here are instructions of the pronunciation of "c", "q", "x", etc.
https://www.youtube.com/watch?v=WHHGOYu6Fl0

**Comment by jaacoppi** [comment]
For adding a language, see docs/add_language.md.

For Windows, you'll also need to add the language to src/windows/data.vcxproj so the Visual Studio IDE will find it and compile it, and to src/windows/installer/Product.wxs so the installer is able to install it.

We get a lot of requests for different languages so it's unlikely someone who doesn't speak Zulu will have the time to implement the language. I suggest you read the documentation and try to do it yourself. You can make a copy of another language and start from there.
