### ISSUE TITLE
Japanese language not supported

### ISSUE THREAD

**Issue by glen-username** [espeak-ng/espeak-ng#1041]
To replicate:
1. select Language: Japanese
2. Insert any text in Japanese
3. Press "send"
4. Listen to output: "chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter chinese letter"

**Comment by valdisvi** [comment]
For Japanese only [Hiragana and Katakana is supported](https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages.md).
