### ISSUE TITLE
Compiling from the source fails

### ISSUE THREAD

**Issue by lingjzhu** [espeak-ng/espeak-ng#1042]
Hi there! I am trying to compile espeak-ng from the source because 1.50 is not available on Ubuntu 18.04.

I followed every step in the instruction yet compiling still failed when running the `make` command. 
The compilation stuck at the following message `cd dictsource && ESPEAK_DATA_PATH=/mnt/exp/espeak-ng ../src/espeak-ng --compile="af"` and never moved on. So the compilation could not complete. Does anyone have an idea about what is going on here? I really appreciate your help! Thank you. 

The full message is as follows.
```
cd . && /bin/bash ./config.status espeak-ng.pc
config.status: creating espeak-ng.pc
ESPEAK_DATA_PATH=/mnt/exp/espeak-ng src/espeak-ng --compile-intonations && \
	ESPEAK_DATA_PATH=/mnt/exp/espeak-ng src/espeak-ng --compile-phonemes && \
	touch phsource/phonemes.stamp
Compiled 30 intonation tunes: 0 errors.
Compiling phoneme data: /mnt/exp/espeak-ng/espeak-ng-data/../phsource/phonemes

Refs 4431,  Reused 3460
Compiled phonemes: 0 errors.
touch dictsource/af_extra
  EMOJI     dictsource/af_emoji
  DICT      espeak-ng-data/af_dict
rm -f espeak-ng-data/af_dict
cd dictsource && ESPEAK_DATA_PATH=/mnt/exp/espeak-ng ../src/espeak-ng --compile="af"
```

**Comment by valdisvi** [comment]
`af` is first language/voice in the list and compilation of voice data may break when compiling in multiple threads. Try to recompile cleanly with `make clean; make -B`.

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
