### ISSUE TITLE
testing my local copy before committing to my forc

### ISSUE THREAD

**Issue by king-dahmanus** [espeak-ng/espeak-ng#1047]
This is not ment to be an issue, but there's no forum or such for discussing these things I know of. But, I want to test the changes I made to the offline copy of my forc before committing it to the online version. How do I do that? Like what command should I use? I'm stuck. I switched to the dirrectory where my repo is but didn't know what the command is. Sorry, and thanks

**Comment by valdisvi** [comment]
To discuss issues, project uses [eSpeakNG mailing list](https://groups.io/g/espeak-ng). For customization look at [Building guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md) and [Adding or Improving a Language](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md). Links to more documentation are provided in [project home page](https://github.com/espeak-ng/espeak-ng#documentation)

**Comment by king-dahmanus** [comment]
Thanks Valdis. Could you please check the pull request I made?

**Comment by king-dahmanus** [comment]
Hello. I have asked them in the mailing list, but they didn't reply yet. So, I have a simpler way of putting this: can you please tell me of the way to run a speak NG from The source because I don't know how to compile it. Thanks, and hope this is better for you to understand. Thanks.

**Comment by valdisvi** [comment]
Review [Contribution Guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md), especially [step 3](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#user-content-step3) and [eSpeak NG online testing guide](https://odo.lv/EspeakGuide).

**Comment by king-dahmanus** [comment]
Thanks, but I don't know how to build the PC audio lib. I tried to download it from github, but it all it downloads is the source code. How can I get the the library needed for East peak to work? I really need to download the ready to use library instead of the source code. Please help me sort this issue out. Thanks. Regards

**Comment by king-dahmanus** [comment]
Sorry for the wrong typing, I am using voice recognition, that's why you see the errors in my typing. Please excuse me.

**Comment by valdisvi** [comment]
It is not accident that active contributors of espeak-ng are using Linux based systems as it is much easier. On Debian based systems you can install pcaudiolib with `sudo apt-get install libpcaudio0` and `sudo apt-get install libpcaudio-dev`.

**Comment by king-dahmanus** [comment]
Excuse me, but I am using windows. I know that it's easy for Linux users,
but I don't have access to a good computer for trying it. Sorry, but I'll
have to deal with windows for a large portion of my work. Thanks

**Comment by king-dahmanus** [comment]
I am just dying to get this thing working so I can build it and test it. But as you said, it is slightly more difficult for Windows users than the linux. I hope you understand.

**Comment by jaacoppi** [comment]
This is a Git issue. Closing.
