### ISSUE TITLE
Looking for the complete set of IPA phonemes that espeak-ng might output

### ISSUE THREAD

**Issue by jncasey** [espeak-ng/espeak-ng#1050]
I'm looking for documentation on every possible phoneme that espeak might generate and group together between the `_` phoneme separator when using the `--ipa` and `--sep="_"` flags. Ideally for all supported languages, but even just the subset for US english would be incredibly helpful. I'm hoping to eventually tokenize text processed with espeak by individual phonemes for use in a phonetic language model.  

This would include all the standard single characters, standard double-characters like `dʒ`, diphthongs and triphthongs like `aɪ` and `aɪə`, and anything else espeak treats as a single phoneme.

I'm no linguist, so apologies if this is basic information that everyone should know. But I've been looking around and haven't found a definitive list anywhere. 

I've pulled a lot from [this helpful documentation](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phonemes.md) and added in the standard English diphthongs for US, UK, and AU dialects. But when processing a subset of my corpus, I'm getting phonemes in the output that I was not expecting, like `ææ` or `nf`, as well as ones with diacritics like `nʲ` or a double long like `iːː`. And though the documentation shows a comprehensive list of diacritics, I'm not sure which diacritics can be combined with which base phonemes. 

Is there a complete set published anywhere? Or is my best bet to process a big corpus and keep track of the unique phonemes in the output?

**Comment by jaacoppi** [comment]
Start by checking the phoneme definitions in phsource/ph_english. That should be enough but I'm not sure.

**Comment by jncasey** [comment]
Thanks for the suggestion. I'm not sure I fully understand how those definition files work, but I do see the IPA definitions for diphthongs and other merges, which is very helpful. 

But I've tried processing a few gigabytes of text (mostly English) and extracting the unique phonemes that espeak puts out, and I'm getting some phonemes that I can't find in the definition files (e.g. `ɐɐ`, `daɪ`, `eɪdʒ`, `ələ`, `1`)

It's possible that my processing code is somehow merging separate phonemes, and I'm trying to track down the specific sections of text that are generating these out-of-standard-vocabulary phonemes. 

Assuming there's not an error in my code to identify the unique phonemes, it sounds like this brute force approach is maybe my best shot at getting a list of potential phonemes espeak can generate?

**Comment by jncasey** [comment]
Okay, it does seem to be an issue with phonemes getting merged. Not in my code, but by espeak itself. 

`echo "an oldie but goodie" | espeak-ng -q -x --ipa --sep="|"` returns
`ɐ|n ˈəʊ|l|d|i|| b|ˌʌ|t ɡ|ˈʊ|d|i` as expected.

but `echo "---an oldie but goodie" | espeak-ng -q -x --ipa --sep="|"` returns
`ɐ|nˈəʊ|l|d|i|| b|ˌʌ|t ɡ|ˈʊ|d|i`

with the erroneous merged phoneme `nˈəʊ`

I'll dig in some more and raise a separate issue if I can isolate the problem

**Comment by jaacoppi** [comment]
If you're parsing words instead of syllables it's probable that the output is multiple phonemes tied together instead of single phonemes.

Once you identify the problematic sections you can use the -X switch to see the rules used:
espeak-ng --ipa -X "testing"

From there you should be able to figure out why the phonemes are generated. Note that the rules are in Kirshenbaum, not IPA.

**Comment by jaacoppi** [comment]
Sorry, missed this message before writing my previous reply.

> but `echo "---an oldie but goodie" | espeak-ng -q -x --ipa --sep="|"` returns
> `ɐ|nˈəʊ|l|d|i|| b|ˌʌ|t ɡ|ˈʊ|d|i`
> 
> with the erroneous merged phoneme `nˈəʊ`

Looks like the "---" creates something. Sounds like a familiar issue, there might be something in the issue tracker.

**Comment by jncasey** [comment]
It seems there's some weirdness when there's an odd number of hyphens. I'll close this and open a more targeted bug report.
