### ISSUE TITLE
Concatination of short words in the IPA output

### ISSUE THREAD

**Issue by Illlin** [espeak-ng/espeak-ng#1051]
When running
`espeak-ng --ipa "In the test. Of the words. Not a thing"`
I get
`ɪnðə tˈɛst`
`ɒvðə wˈɜːdz`
`nˌɒtə θˈɪŋ`

Where "in the", "of the", and "not a", are concatenate into one word in the phonetics.

**Comment by jaacoppi** [comment]
This is intended behavior for pronunciation. It affects many word combinations. The rules are in dictsource/en_list, search for "(in the)" and so on.

I'm not a linguist so I'm not sure how the IPA should be produced in these cases.

Espeak-ng is primarily a speech syntherizer, not a phonemizer. There might be other tools better suited for producing IPA output.

**Comment by Illlin** [comment]
Okay, makes sense. I'll set up a custom dictionary with out them. And from what I have found eSpeak-ng is actually one of the best phonemizer I can find.

**Comment by WordKing911** [comment]
I have same issue.
The GPT give me the answer. you can replate ' ' with '|',then the output is rgiht.
for example:
espeak-ng -v en --ipa "Each|individual|in|the|group|contributed|their|own|unique|ideas|to|the|project."
ˈiːtʃ ˌɪndɪvˈɪdʒuːəl ɪn ðə ɡɹˈuːp kəntɹˈɪbjuːtɪd ðeəɹ ˈəʊn juːnˈiːk aɪdˈiəz tə ðə pɹˈɒdʒɛkt
