### ISSUE TITLE
fatal error: language "mb-fr4" is not supported by the espeak-mbrola backend

### ISSUE THREAD

**Issue by sravani40** [espeak-ng/espeak-ng#1055]
!echo "bonjour le monde" | phonemize -b espeak-mbrola -l mb-fr4 -p ' ' -w '/w '

giving me this error   "fatal error: language "mb-fr4" is not supported by the espeak-mbrola backend"

**Comment by jaacoppi** [comment]
You should contact the support for phonemize.

The syntax for espeak-ng is:
echo "bonjour le monde" | espeak-ng -v mb-fr4
