### ISSUE TITLE
Russian is broken 

### ISSUE THREAD

**Issue by alex19EP** [espeak-ng/espeak-ng#1067]
latest master.
`espeak-ng -v ru+max -s 300 "русский язык теперь не возможно использовать. цифры 346 сша и другие слова звучат очень странно. а также буквы ы ж т ь Ъ ж ш"`

please revert last commits.

**Comment by alex19EP** [comment]
I do not want to offend anyone, but it would be good to test such changes first.

**Comment by valdisvi** [comment]
Everyone has chance to be trusted first. Reverted with commit 86bc55c5c47cfdaf4632fa02194935697ce29491.

**Comment by alex19EP** [comment]
thanks.
