### ISSUE TITLE
can I build my own voice?

### ISSUE THREAD

**Issue by darkgirl** [espeak-ng/espeak-ng#1068]
Hi,

is there any way to add my own voice ?

**Comment by jaacoppi** [comment]
The short answer is no. Espeak-NG uses formant synthesis, not human speech samples. It will be very difficult to make a recognizable voice.

**Comment by king-dahmanus** [comment]
how about making editing tune statement files easier, I mean the issue that
joshknd1992 posted?  That could help make a more humanlike sounding voice,
then adding variants which try to reflect some specific voices

**Comment by valdisvi** [comment]
As pencil sketch will never be as realistic as high resolution photo, synthesized voices of eSpeak NG will never sound human enough. Please learn about [additive/formant synthesis](https://en.wikipedia.org/wiki/Speech_synthesis#Formant_synthesis) with particular examples for [eSpeak NG](https://en.wikipedia.org/wiki/ESpeak#Synthesis_method). As it was told, either look at [MBROLA](https://en.wikipedia.org/wiki/MBROLA) synthesizer or neural network based synthesizers e.g. [TensorFlow WaveNet](https://github.com/ibab/tensorflow-wavenet).

**Comment by king-dahmanus** [comment]
If so, then why is eloquence and deck talk sounding natural, while still
being formant based synthesizers.? Can he speak be improved to match these?

**Comment by king-dahmanus** [comment]
Espeak,*

**Comment by valdisvi** [comment]
As it was noted, eSpeak NG can be used as frontend for [Klatt](https://github.com/espeak-ng/klatt) engine as well. It uses [subtractive synthesis](https://en.wikipedia.org/wiki/Subtractive_synthesis), which has richer sound (more sound formants) therefore more human like. Voice parameters for this engine is supported for [eSpeak Edit](http://espeak.sourceforge.net/editor.html), but it is not documented, therefore its usage without good understanding of theoretical principles will be hard.

**Comment by king-dahmanus** [comment]
can you make a documentation for it so we can build more humanlike
voices/variants
