### ISSUE TITLE
[en_rules] Ligature ﬅ is st, not ft

### ISSUE THREAD

**Issue by agonzalezd** [espeak-ng/espeak-ng#1069]
https://github.com/espeak-ng/espeak-ng/blob/86bc55c5c47cfdaf4632fa02194935697ce29491/dictsource/en_rules#L53

Ligature ﬅ is st, not ft

https://en.wiktionary.org/wiki/%EF%AC%85

**Comment by jaacoppi** [comment]
Fixed in commit f78bb1bec524f5.
