### ISSUE TITLE
Question GUI

### ISSUE THREAD

**Issue by andresgarcia0313** [espeak-ng/espeak-ng#1070]
I hope to collaborate with the following suggestions
Please:
Add in the readme information on which gui or graphical clients are compatible.

How to configure the gui.

How to install different voices to mbrola for example those of loquendo among many others.

**Comment by jaacoppi** [comment]
Readme answers your questions. Espeak NG does not have a GUI. Documentation for mbrola is also mentioned there.

If you wish to use espeak NG with a screen reader, at least Orca and NVDA support it, but there are probably others. Do you think that should be added to the Readme?
