### ISSUE TITLE
src/libespeak-ng/ieee80.c has a non-free license

### ISSUE THREAD

**Issue by ulm** [espeak-ng/espeak-ng#1072]
Forwarding [Gentoo bug 832778](https://bugs.gentoo.org/832778):

The file `src/libespeak-ng/ieee80.c` has the following copyright and license notice:
```
Copyright (C) 1989-1991 Apple Computer, Inc.

All rights reserved.

Warranty Information
[...]

This code may be used and freely distributed as long as it includes
this copyright notice and the above warranty information.
```

This grants only the right to use and distribute the software, but it neither grants the right to modify it nor to distribute modified versions. This is not enough to qualify as a free software license.

The language used in `COPYING.IEEE` only says "The source code available from this page may be freely downloaded and used", so even the right to redistribute is missing. It is also doubtful if this license notice applies, because the copyright notice of the file itself says that copyright is by Apple Computer, Inc.

**Comment by Alessandro-Barbieri** [comment]
Both debian and fedora have it in the free section
see also https://www.spinics.net/linux/fedora/fedora-legal/msg02876.html

**Comment by ulm** [comment]
> Both debian and fedora have it in the free section see also https://www.spinics.net/linux/fedora/fedora-legal/msg02876.html

Quoting from the first reply in that thread:
> I'd take the license at face value (including the appearance of having been granted by Apple around 1991, where Turkowski evidently was employed at that time) and I'd then apply the principle we've used for similar informal licenses dating from around that time, that grants of mere permission to "use" should be understood to cover (among other things) modification, since there's a lot of general evidence that this is what licensors from that time period meant. So that seems okay.

I strongly disagree with this. The meaning of the words "use" and "modify" in the English language hasn't changed in the last 30 years. We don't know what the licensor's intentions were, so we must go with the wording which says use but not modify. Other licenses from the same time period (like the MIT and BSD licenses) clearly make the distinction.

There is also the precedent of the Pine license which said "modify or distribute", and the copyright holder insisted that distribution of modified versions (i.e. "modify and distribute") is not allowed by that. It is a much smaller difference in wording than what we have here.

**Comment by rhdunn** [comment]
From the README section:

**Comment by rhdunn** [comment]
If you can find/create a version of the function that has an acceptable license *and* passes the current tests, it will be merged. The function is used by espeak-ng to parse floats from the file when building the phoneme data. It was in espeakedit via the wxWidgets library, which has a different version of the function.

See the following https://lists.debian.org/debian-accessibility/2016/09/msg00123.html discussion regarding the original version that was not accepted by Debian, but the one currently in espeak-ng was -- thanks to @sthibaul for locating it. See also the Fedora packaging ticket (https://bugzilla.redhat.com/show_bug.cgi?id=1376900#c8).

**Comment by ulm** [comment]
I am working on it and I'll provide a patch.

**Comment by rhdunn** [comment]
Great, thanks.

**Comment by alex19EP** [comment]
I think this can be closed

**Comment by sthibaul** [comment]
this was fixed in the latest release, yes
