### ISSUE TITLE
Problem with "ll" in mbrola spanish voices

### ISSUE THREAD

**Issue by bellidoj** [espeak-ng/espeak-ng#1083]
Hi!

I've found some errors when speak-ng uses the mbrola spanish voices.

espeak-ng -v es "caballo" -x
kaB'al^o

That is the proper way to pronounce this word, but

espeak-ng -v mb-es1 "caballo" -x
kaB'al^o
mbrola: Warning: a-l^ unknown, replaced with _-_
mbrola: Warning: l^-o unknown, replaced with _-_

I suppose that there are some missing phoneme translations from speak-ng to mbrola, but I can't fix this myself because I don't understand how mbrola works internally and pretty much nothing about phonetic itself.

Thanks.

**Comment by hozosch** [comment]
This is a very easy fix. Something is wrong in the MBrola phoneme file for Spanish, but I unfortunately forgot which phoneme it was exactly. If no one else is willing to look into it, I'll create a pull request fixing this.

**Comment by hozosch** [comment]
Yes, there is no Entry for "l^" in the phoneme file for Spanish mBrola. I may create a pull request later.

**Comment by PanderMusubi** [comment]
Same problem here, looking forward to the PR. Thanks.

**Comment by PanderMusubi** [comment]
Would this also work for voices `mb-es1` and `mb-es2` as I see only `es`, `es3` and `es4`?

**Comment by hozosch** [comment]
Yes, some of those translation files, to translate from eSpeak to MBrola phonemes, are used for multiple voices. I'm pretty sure that covers anything, except for mexican and venezuelan, those are extra files.

**Comment by PanderMusubi** [comment]
Thanks. Hope your PR can go into https://github.com/espeak-ng/espeak-ng/issues/857 🤞

**Comment by PanderMusubi** [comment]
@hozosch can you make a PR for upstream? Thanks.

**Comment by hozosch** [comment]
Sorry, how do you mean?

**Comment by PanderMusubi** [comment]
You commit is in your personal fork?

**Comment by hozosch** [comment]
Well yes, but a PR is a request to include it in the base project, isn't it?

**Comment by PanderMusubi** [comment]
Yes, so it will be included in the upcomming release

**Comment by hozosch** [comment]
Right! So there's nothing more for me to do, is there? I hope you saw #1142 already?

**Comment by PanderMusubi** [comment]
Ah, 1142 takes care of it. Didn't saw that before. Thanks again for fixing this.
