### ISSUE TITLE
Adding Google voices

### ISSUE THREAD

**Issue by guest271314** [espeak-ng/espeak-ng#1090]
This Google Chrome extension includes voice data and metadata [US English Female Text-to-speech (by Google)](https://chrome.google.com/webstore/detail/us-english-female-text-to/pkidpnnapnfgjhfhkpmjpbckkbaodldb).

The voice files 
[US_English_Female_Google.zip](https://github.com/espeak-ng/espeak-ng/files/8224400/US_English_Female_Google.zip).

How do we go about incorporating the above voice into eSpeak Ng?

**Comment by king-dahmanus** [comment]
good one. Although I think that it maybe
extreeeeeeeeeeeeeeeeeeeeeeeeeeeeemely difficult to incorporate a voice like
that since it's probably hts, and hts is statistical parametric based,
which means it's a million times more complex than espeak's additive
formant synthesis.

**Comment by guest271314** [comment]
@king-dahmanus If I am not mistaken the speech synthesis engine which interacts with the voice files are included in the Native Client application in the extension; we just need to extract that code from `tts_service_x86_64.nexe` and incoprate that code into eSpeak NG?

**Comment by king-dahmanus** [comment]
god knows, I don't. I've only had some experience with the phonemes of
espeak, not the coding side of that

**Comment by alex19EP** [comment]
even if that's possible. this raises big questions about the legality of this action.

**Comment by guest271314** [comment]
@alex19EP How so? As far as I can tell no notice eplicitly says Google voices cannot be used outside of the Native Client application released at Chrome Web Store or PATTS  

```
wget https://chromium.googlesource.com/chromiumos/platform/assets/+archive/master/speech_synthesis/patts.tar.gz
```

There is also https://github.com/google/voice-builder, and https://github.com/google/voice-builder here on GitHub, both are Apache license.

**Comment by king-dahmanus** [comment]
Is there a difference between the first voice builder and the second voice
builder?
