### ISSUE TITLE
How to run espeak for kannada langugae

### ISSUE THREAD

**Issue by A-d-DASARE** [espeak-ng/espeak-ng#1096]
Can someone pls help me with detailed instructions on how to go about espeak Kannada. I tried compiling dictionary but it says no rules for Kannada. Whatever changes I try to make with voice.. I still get US accent. How to go about it. Detailed instruction is highly appreciated. Thank you!

**Comment by jaacoppi** [comment]
What have you tried so far? Post the exact commands here. With a default build, this works for me: 
espeak-ng -v kn "1, 2, 3"

**Comment by A-d-DASARE** [comment]
Hi, this is the wavefile I got by using default voice, the voice is
horrible.. How can I change the voice, does mbrola support an Indian
accent? how to do that? i found American accent mbrola voices.... but not
for indian voices.

 ***@***.***:~$ espeak-ng -v kn -w wave.wav -f txt.txt
***@***.***:~$ espeak-ng -p 180 -s 80 -v kn -w wave1.wav -f txt.txt
***@***.***:~$ espeak-ng -p 150 -g 15  -s 80 -v kn -w wave1.wav -f txt.txt
***@***.***:~$ espeak-ng -p 200 -s 80 -v kn -w wave2.wav -f txt.txt
***@***.***:~$ espeak-ng -v kn -p 200 -s 80 -v kn -w wave3.wav -f txt.txt
***@***.***:~$ espeak-ng -p 150 -s 80 -v kn -w wave4.wav -f txt.txt
***@***.***:~$ espeak-ng -p 150 -s 70 -v kn -w wave5.wav -f txt.txt
***@***.***:~$ espeak-ng -p 150 -s -v kn -w wave6.wav -f txt.txt
***@***.***:~$ espeak-ng -p 150 -g 20 -v kn -w wave7.wav -f txt.txt
***@***.***:~$ espeak-ng -p 100 -g 20 -v kn -w wave6.wav -f txt.txt

 i did all possible variation sound still looks horrible

Regards,
ASHWINI DASARE

**Comment by jaacoppi** [comment]
Read the documentation for improving the language.

Original issue is solved, closing.
