### ISSUE TITLE
Hyphen pronounced as half-space

### ISSUE THREAD

**Issue by parhamdoustdar** [espeak-ng/espeak-ng#114]
Here are the steps to reproduce:
1. Open the terminal, and type in `espeak-ng --punct -v ira/fa -`.

Expected result: I must hear "Katte fAsele" which indicates dash or hyphen in Persian.

Actual result: I instead hear `nimfAsele` which indicates half-space in Persian.

Here is the output of `espeak-ng --version`:

```
eSpeak text-to-speech: 1.48.15  16.Apr.15  Data at: /usr/share/espeak-data
```

**Comment by ValdisVitolins** [comment]
What should be pronunciation?
Is this line ok?
```
_-	katte_fAsele:
```

**Comment by parhamdoustdar** [comment]
I think the offending line is line 203 in the `fa_list` file, the line below this comment:

`//this code is recognized as (ZWNJ) U+200c (half space) at eSpeak 1.46.22 and later`

The correct pronunciation would be almost what you just wrote:

`_-  Xatte_fAsele:`

The reason I didn't just edit that line is that for some reason, this line (line #203 in the `fa_list` file) is supposed to match halfspace, and it's matching dashes instead. Isn't this a regression?

**Comment by ValdisVitolins** [comment]
Following rules work for me:
```
_-	Xatte_fAsele:
_–	n-dash
_—	m-dash
```
```
$ espeak-ng -x --punct -v ira/fa -
 X,atte_fAs'ele:
$ espeak-ng -x --punct -v ira/fa –
 'n-dash
$ espeak-ng -x --punct -v ira/fa —
 'm-dash
```
What should be actual pronunciation for n-dash and m-dash?

**Comment by parhamdoustdar** [comment]
Sorry, let me elaborate on what i just said.

If you change line 203 to `Xatte_fAsele:` as you just did, `-` will be read correctly. That's great.

However, the problem is this character: `‌`.

It is a character that is used in Farsi as a half-space, where there's a space between two words, but they are semantically related. If there's a way to match this character in the `fa_list` file, that should be used instead of `-`.

Does this make sense?

**Comment by ValdisVitolins** [comment]
So, I committed fix into my repo: https://github.com/ValdisVitolins/espeak-ng/commit/19b742f69003b2b645937eec9b26f0695970a452 Reece will merge this into his repository eventually.
But, as far as I investigated, espeak changes U+200c symbol to - somewhere inside itself, and fixing it could be much harder (I added lines into `fa_list` and `fa_rules` but they never succeeded.)

**Comment by parhamdoustdar** [comment]
So, now - and U+200C are pronounced the same, no matter what the 
pronunciation is set to?

**Comment by ValdisVitolins** [comment]
Yes, if `--punct` switch is added. If normal pronunciation is used, dash is spelled, but U+200c symbol is just silence.
E.g. file:
```
 ْإ‌ ْ.
 ْ-ؤ.
 ُؤ‌أإ.
```
is spelled in punctuation mode:
```
$ espeak-ng -x --punct -v ira/fa -f test.txt 
 s'Aken 'alefeh,amzez,iR X,atte_fAs'ele:_:_: s'Aken
 n'oqte:
 s'Aken X,atte_fAs'ele: X,atte_fAs'ele: v'Avh,amze:
 n'oqte:
 'o v'Avh,amze: X,atte_fAs'ele: X,atte_fAs'ele: 'a?e?
 n'oqte:
```
and in normal mode:
```
$ espeak-ng -x -v ira/fa -f test.txt 
Bad voice attribute: maintainer
Bad voice attribute: status
 'e? X,atte_fAs'ele: s'Aken
 s'Akenv'Avh,amze:
 'oo?'a?e?
```

**Comment by parhamdoustdar** [comment]
Ah, thank you.
