### ISSUE TITLE
converting all espeak varients to subtractive synthesis?

### ISSUE THREAD

**Issue by king-dahmanus** [espeak-ng/espeak-ng#1145]
since the klat implimentation, or rather the subtractive synthesis side of espeak makes the voices sound much more natural (in their timbre), is it possible to convert the rest of the varients to klat/ss? If yes, then would you guys who maintain and contribute to this thing be interested in adding a change like that, or at least approve it if someone ever pullrequests it? Thanks. I think this will allow us to use max, the males and other varients but sounding more natural in their timbre instead, edward 2 is a good example of a ballenced and cool klat voice, maybe the other varients could be recreated in that way. What do you think?

**Comment by FelipeZanabria** [comment]
This can be easily done without having to compile from source.
Locate the EspeakNG data/Voices/v folder.
Inside are all the variant files, which are plain text files.
What you need to do is open each one in text files like Windows Notepad and add the following line anywhere:
klatt 6
Then it must be saved.
I have created a variant similar to the Reed variant, which defaults to Eloquence.
This is the timbre of voice in Spanish, which sounds a little different from English.
Save the code below in a utf-8 file called Reed, with no extension.
language variant
name Reed
klatt 6
consonants 85 85
voicing 120
breath 35

pitch 85 135

formant 1 72 100 70 90
formant 2 83 100 75 170
formant 3 100 100 85 80
formant 4 100 100 100
formant 5 100 100 100

**Comment by animeshahilya** [comment]
Really happy to see the improvement. 
I wish we convert all voices like this for once, so all can benefit from it. 
We can do this in computer but on android this is not possible. 
That’s y this needs to be implemented in the source as well

**Comment by king-dahmanus** [comment]
yeah, someone has to edit them all locally, push them to their forks, pull request here, then the compilation to android can be done

**Comment by alex19EP** [comment]
> since the klat implimentation, or rather the subtractive synthesis side of espeak makes the voices sound much more natural (in their timbre)

this is a very subjective statement. I tested some preferred voices (like max) and I didn't like how they sounded at all.

> is it possible to convert the rest of the varients to klat/ss?\

As already mentioned above, this is indeed possible.

>  you guys who maintain and contribute to this thing be interested in adding a change like that, or at least approve it if someone ever pullrequests it?

my answer is definitely no.
