### ISSUE TITLE
Don't get any audio output when testing

### ISSUE THREAD

**Issue by marksev1** [espeak-ng/espeak-ng#116]
So, compiling went fine (I even tried explicitly setting pulseaudio one time when i was compiling), no error messages. But when testing, I get no output, when I copy-paste that command from the readme. It just goes into new line in the terminal (no error message). 

When I give --help at the end of that command it outputs its available options and stuff, so seems espeak-ng compiled fine, its just a problem of outputing or something??

How can I debug this? I also modified and added "This is a test" to that command so it would speak it, but it didn't. Running Ubuntu Mate 14.04 32-bit on my netbook.

**Comment by rhdunn** [comment]
From the configure output, did it detect pcaudiolib? You need that library to enable audio support in espeak-ng.

**Comment by marksev1** [comment]
Oh, I didn't install that since it says its optional :). I'm gonna try installing that and seeing what happens, do I need to recompile?

**Comment by marksev1** [comment]
Yup that was it. (the pcaudiolib). Thanks.
