### ISSUE TITLE
Android directory is missing Raw folder

### ISSUE THREAD

**Issue by ominfowave** [espeak-ng/espeak-ng#1161]
After cloning and running the Android project, I am getting this issue "Cannot resolve symbol 'raw'".
So the Raw directory is missing in the Android directory, is there any way to get those files?

**Comment by alex19EP** [comment]
yes you need to run ./configure and then `make android/res/raw/espeakdata_version`

**Comment by alex19EP** [comment]
sure. if you on linux you need to install all dependencies for espeak-ng building.
then in root of repository you should run ./autogen.sh ./configure and then make android/res/raw/espeakdata_version

**Comment by ominfowave** [comment]
Unfortunately, I'm not on the Linux system, is there any way for Windows?

**Comment by ominfowave** [comment]
> sure. if you on linux you need to install all dependencies for espeak-ng building. then in root of repository you should run ./autogen.sh ./configure and then make android/res/raw/espeakdata_version

Hi @alex19EP is there any way to do it on the Windows system? thanks.

**Comment by alex19EP** [comment]
@ominfowave when #960 will be merged you will need to make espeak-data files for example with visual-studio and then build android app.

**Comment by ominfowave** [comment]
> @ominfowave when #960 will be merged you will need to make espeak-data files for example with visual-studio and then build android app.

Hi @alex19EP I don't see that merge yet, is it possible to build it from your branch? thanks.

**Comment by alex19EP** [comment]
yes you can install github-cli and checkout my pr with it.

**Comment by ominfowave** [comment]
Hi @alex19EP any idea regarding the following issue, I cloned the code from your branch but the build is failing.

* Where:
Build file 'F:\Ominfowave\Demo\espeak-ng-android-improvements\android\build.gradle' line: 30

* What went wrong:
Execution failed for task ':checkData'.
> assert file("../espeak-ng-data/en_dict").exists()
         |                                 |
         |                                 false
         F:\Ominfowave\Demo\espeak-ng-android-improvements\espeak-ng-data\en_dict

**Comment by alex19EP** [comment]
you need to compile espeak-ng data you can use visual-studio for that.

**Comment by ominfowave** [comment]
> you need to compile espeak-ng data you can use visual-studio for that.

Which Visual studio framework is required to compile espeak-ng-data ? Is there any guid available?

**Comment by alex19EP** [comment]
> Is there any guid available?

https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#windows
