### ISSUE TITLE
-v is not working

### ISSUE THREAD

**Issue by helloguysw** [espeak-ng/espeak-ng#1180]
When I try to use -v to change the language, the default voice is used. Why is this?

**Comment by jaacoppi** [comment]
Should work:
$ espeak-ng -v en hello -x
h@l'oU
$ espeak-ng -v fi hello -x
h'ello
$ espeak-ng -v de hello -x
h'Elo:

**Comment by jaacoppi** [comment]
Closed until more information is received from original author.
