### ISSUE TITLE
Question about --ipa outputting language names e.g. (en) (fr)

### ISSUE THREAD

**Issue by fijipants** [espeak-ng/espeak-ng#1184]
Hi guys,

When I run IPA with `en-us` it comes out fine:

```bash
$ espeak-ng "2000 years later" --ipa -v en-us
tˈuː θˈaʊzənd jˈɪɹz lˈeɪɾɚ
```

But when I run it with `fr-fr` it has `(en)` and `(fr)` all over the place:

```bash
$ espeak-ng "2000 years later" --ipa -v fr-fr
dø mˈil (en)jˈiəz(fr) latˈe
# ------^^^^ ----^^^^
```

What am I supposed to do with this? Is there some way to get IPA output without this `(en)` `(fr)` stuff?

**Comment by jaacoppi** [comment]
(en) and (fr) mean that the rules change first to english and then back to french. The word "years" is translated with English rules for some reason. Use -x and -X to debug why this happens:

```
espeak-ng "years" -v fr```
Translate 'years'
 25	_) y (A  [_|j]
  1	y        [i]

  1	e        [@]
 22	ea       [_^_]
Translate 'years'
  1	y        [j]
 46	y (ear   [j]

 36	ea       [i:]
 57	ear      [i@3]
  1	e        [E]

 42	@) s (_NS1  [z]
 23	s (_N    [z]
  1	s        [s]
 22	s (_     [s]

Translate 'year'
  1	y        [j]
 46	y (ear   [j]

 36	ea       [i:]
 57	ear      [i@3]
  1	e        [E]

(en)j'i@3z(fr)
```


In this case the problem is here: ` 22	ea       [_^_]`
This roughly means that whenever an "ea" is encountered, switch to default language (English). We can test this with:
```
espeak-ng "mean clean team" -v fr -x
(en)m'i:n kl'i:n t'i:m(fr)

```

To fix this, change that line in dictsource/fr_rules. Note that there are almost two hundred other cases. docs/dictionary.md has documentation for the syntax of rules files.

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
