### ISSUE TITLE
F-Droid app cannot be updated as version code is the same

### ISSUE THREAD

**Issue by ArenaL5** [espeak-ng/espeak-ng#1185]
Continuation of #644. (I wasn't sure whether to comment on that or to open a new issue, as the actual issue is different this time.)

I've created a [new merge request at F-Droid's GitLab](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10975) in order to update the app there to [1.51, release version](https://github.com/espeak-ng/espeak-ng/releases/tag/1.51), and also to enable auto-updates. There's currently only one issue with that; both Android and F-Droid use the version code to know when there is an update, and the version code has been kept to `20` since then.

There are a couple of fixes that can be done to bypass this:

- Make another release with version code 21 and use that on both GitHub and F-Droid (probably the easiest, and the one that packager Licaon_Kter recommends).
- Raise the version code now, and use the most current commit for the F-Droid app (but the F-Droid app wouldn't match the release version on GitHub)
- Force the version code on the recipe, so that F-Droid's release matches GitHub's release (You wouldn't need to do anything. The human-readable version name would match, but the version code wouldn't. Not really an issue since users can't switch between GitHub and F-Droid release without uninstalling the app).
- Maybe other?

In all of the cases, the version code would need to be raised again for the next release.

I realize this is a lot of text for just a couple of bytes, but I want to ask what option do you prefer, or what option makes the most sense with your current development cycle.

**Comment by IzzySoft** [comment]
@rhdunn seeing this without a reply after 3 weeks, I hesitantly pull the "ping gun" and dare mentioning one of the team. Any chance to get this rolling, so we can update eSpeak at F-Droid?

**Comment by IzzySoft** [comment]
F-Droid still has the 1.51-dev from 4/2021 as when making the 1.51 release in 4/2022, `versionCode` was not increased. And while `build.gradle` allready says `1.52-dev`, `versionCode` [still is left on `20`](https://github.com/espeak-ng/espeak-ng/blob/master/android/build.gradle#L73). Maybe `versionCode` could be increased and a new tag created?

**Comment by alex19EP** [comment]
@sthibaul how about creating 1.51.1 with this change, if you agree i can prepare a pr.

**Comment by sthibaul** [comment]
I'm not a release manager at all :)

**Comment by IzzySoft** [comment]
You could maybe increase VC now to `22` (intentionally leaving a gap for 1.51, as the current VN has already advanced to 1.52-dev) to prevent the issue to repeat. That way, whenever the next tag is created, F-Droid would update properly. Whether and how to push out the 1.51 can then be dealt with separately.

One idea for the latter: create a branch from the commit marking 1.51, adding a single commit there increasing VC to `21`, and update the YAML at F-Droid manually to add that release. I could see to get the latter part done (disclosure: I'm one of the F-Droid maintainers).

**Comment by alex19EP** [comment]
@sthibaul I understand, but you have rights to the repository and you're quite active... so maybe we can do this together...

or @jaacoppi I think you did the last release.

**Comment by sthibaul** [comment]
My activity is rather a one-shot about sanitizers etc. triggered by a project from my students.

**Comment by alex19EP** [comment]
@sthibaul  ok thanks for clarifying.

then we have no choice but to wait for the maintainers to pay attention to this issue.

**Comment by valdisvi** [comment]
https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#user-content-step11

**Comment by alex19EP** [comment]
@valdisvi hmm. if this is an invitation to action, then I'm ready to take responsibility...

**Comment by alex19EP** [comment]
hello @IzzySoft I created 1.51.1 tag.

If you have any other problems just ask.
