### ISSUE TITLE
Add information on phoneme tests to add_language.md

### ISSUE THREAD

**Issue by codeofdusk** [espeak-ng/espeak-ng#1194]
As part of PR #1193, I ran into CI failures related to missing phoneme tests. Instructions on adding tests/documentation of their format should be added to the `add_language.md` file.

**Comment by jaacoppi** [comment]
Would this be enough?

### Adding tests

All languages require automated tests to make sure accidental changes 
in program code don't change how the languages sound. 

Tests are run with `make check`. It will print an error if a language
is missing tests.

Most tests are bash scripts in tests/ and follow the syntax:
<test name> <language code> <expected result> <input>

To add a test:

1. First add a test line with arbitrary expected result. 
Example line in tests/language-phonemes.test:
test_phwav fi this_should_fail "ma na Na pa ba ta da"

2. run `make check` to see expected and actual results:
testing fi
1c1
< this_should_fail
---
> 7541590a29e2392b827d9f1563e6579774fb15ea

3. change the expected result in the test:
test_phwav fi > 7541590a29e2392b827d9f1563e6579774fb15ea "ma na Na pa ba ta da"

**Comment by codeofdusk** [comment]
Mostly, but it'd also be nice to document how the test values are derived. Some sort of hash?

Otherwise, looks good to me!

**Comment by jaacoppi** [comment]
Yeah it's a hash. Tests use md5sum internally. I'll add that as well.
