### ISSUE TITLE
Automatic language switching is broken due to a commit

### ISSUE THREAD

**Issue by burakyuksek** [espeak-ng/espeak-ng#1200]
I have opened an issue regarding Automatic language switching no longer working correctly in NVDA, and they said it is broken in espeak due to this commit: https://github.com/espeak-ng/espeak-ng/commit/e91d0a58612a01954687d34c7417cf0fbd3cadaa
My primary language is Turkish, and when I read an English webpage it doesn't switch automatically.

**Comment by seanbudd** [comment]
We believe this is because "en" no longer maps to "en-gb". We are patching this in NVDA but we thought it was worth raising here.
