### ISSUE TITLE
[android] can not set target sdk to api32

### ISSUE THREAD

**Issue by MH140000** [espeak-ng/espeak-ng#1202]
hi. can not set target sdk to api32, after i set target to api 32 i got error about android manifest. please fix this.

**Comment by alex19EP** [comment]
hmm. maybe it's worth waiting for the developers to update the sdk version themselves... trust me in the android version of espeak there are much more serious problems than switching to a new api version.

**Comment by MH140000** [comment]
Because on Android 13 can not install 32bit apps, please update espeak for
android

**Comment by beqabeqa473** [comment]
I think this issue could be closed as completed
