### ISSUE TITLE
espeak intonation editor and sapi5 espeak ng

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#1220]
first, I am disappointed that there is still no easy to install sapi5 version of espeak-ng both 32bit and 64bit so it also works with windows narrator. Second, can you please make an intonation editor with edit boxes and a test espeak button to quickly change ESpeak's intonation style and play with new styles of speaking? I would like a way to quickly experiment with and change espeak's style of speech by quickly changing all numbers for intonation parameters, and the ability to increase and decrease the headsize of all the voices.

**Comment by alex19EP** [comment]
first, keep in mind that all espeak-ng developers are volunteers. and many don't use windows... so contribution would be welcome.

**Comment by joshknnd1982** [comment]
My programming ability only goes so far as to write some basic jaws scripts to make applications more accessible.
