### ISSUE TITLE
Break command at start of speech is not respected

### ISSUE THREAD

**Issue by seanbudd** [espeak-ng/espeak-ng#1232]
The `<break/>` SSML tag is not respected if it is at start of speech, and the `strength` attribute is not provided.
I believe this is an old issue that is still present in the latest eSpeak (1.51.1+)
For example:

- No pause: `espeak-ng -m "<break time='1000ms'>cat"`
- Pause: `espeak-ng -m "<break time='1000ms' strength='1'>cat"`
- Pause: `espeak-ng -m "cat<break time='1000ms'>cat"`

**Comment by djphoenix** [comment]
The root cause is here: https://github.com/espeak-ng/espeak-ng/blob/38384e4a67b17fdfb54fdf9a46b9917cadf84edf/src/libespeak-ng/translate.c#L1645-L1650

If pause comes a first that to be synced, it is removed explicitly.

@jaacoppi any ideas to workaround?
