### ISSUE TITLE
Tibetan support

### ISSUE THREAD

**Issue by shenzo1** [espeak-ng/espeak-ng#1234]
Hello,

This looks fantastic. Will Tibetan be supported? And if not what are the major obstacles to that being so?

Thank you

**Comment by valdisvi** [comment]
Look at [Contribution Guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md).

**Comment by Giovani93** [comment]
This idea is great, but are there some Tibetan speakers and users of Github? Those questions are inportant to create It.
