### ISSUE TITLE
Recognition of Chinese characters Error

### ISSUE THREAD

**Issue by yt09** [espeak-ng/espeak-ng#1236]
hi i am a beginner of espeak-ng。I build the environment in Windows10 with Visual Studio the espeak-ng version is 1.51 .I input  -v cmn "好" -X this command in debug model .like this
![微信截图_20220711165604](https://user-images.githubusercontent.com/16026634/178227216-f1879a31-5b96-49a6-8a0f-9f923fd84202.png)

but the result showing this when i running Program
![微信截图_20220711165749](https://user-images.githubusercontent.com/16026634/178227584-9be7f4ac-5555-441a-b264-502036d356e8.png)

it is not right Pronunciation “好”-hao in chinese。it sound very strange。what i miss set or config？i get raw code from git and i had setup wix had move the pcaudiolib in src fold. 

i use test website to test my example like this ：
![UseTest](https://user-images.githubusercontent.com/16026634/178234178-a0ee1bca-0157-4e93-bd3a-51e149a53834.png)
and it is error too. 

thank you very much to take time looking this problem

**Comment by yt09** [comment]
@eeejay @CMB @rhdunn @ragb

**Comment by hgneng** [comment]
This should be a bug in espeak-ng. "好“ is translated as "hao2" and pronounced as "hao two" in English.

see also:
#1028 #1163 #1044

**Comment by yt09** [comment]
Thanks you reply me！ I had set "cmn-latn-pinyin" to make it work.  I hope they can fixed it and the document more clear.
