### ISSUE TITLE
Pronunciation of ı and i sounds in Turkish

### ISSUE THREAD

**Issue by Qchristensen** [espeak-ng/espeak-ng#1241]
This was reported to me by an NVDA user and I've used Google Translate (original Turkish provided as well):

"Türkçede ı ve i seslerinin telaffuzları birbirinden farklıdır, bu yüzden şapkalı î telaffuzunun şapkalı i olarak seslendirilmesi daha iyi olur. Meselâ türkçede bir örnek vereyim: âlî paşa ismini örnek vereyim. Bunun doğrusu, âli paşa olarak telaffuz edilmesi lâzım. Şapkalı i harfini ı olarak seslendiriyor."

(Google translated to English):

"The pronunciations of ı and i sounds in Turkish are different from each other, so it would be better to pronounce hatli î as hatli i. For example, let me give an example in Turkish: Let me give the name Ali Pasha as an example. In fact, it should be pronounced as ali pasha. He pronounces the letter i with the hat as i."

Hopefully one of the Turkish translators is able to understand / confirm the issue?

In NVDA 2022.1 (the current stable version) we use eSpeak-NG 1.51-dev commit 7e5457f91e10

**Comment by Gurbuzguven** [comment]
Turkish speaker here, can confirm this issue. Circumflex i(î) in Turkish is pronounced as slightly longer sounding " i ", and not " ı ".

**Comment by Qchristensen** [comment]
More information from my Turkish user (again, in Turkish and translated via Google to English):

Bilindiği gibi, Düzeltme (Şapka) İşareti ( ^ ) ve Kullanıldığı Yerler vardır. Sorun şununla ilgili:
Nispet i'sinin kullanımı:
Espeak ng, nispet i'sini ı olarak seslendiriyor. Örnekler şunlar:
• (Türk) askeri ve askerî (okul),
• (İslam) dini ve dinî (bilgiler),
• (fizik) ilmi ve ilmî (tartışmalar).
Bu örneklerde ı olarak seslendirdiğini duyuyorsunuz. Nispet i'sinin de, i harfi ile seslendirilmesi gerekir.

ENGLISH:

As it is known, there are Correction (Hat) Sign ( ^ ) and Where It is Used. The problem is with:
Usage of the ratio i:
Espeak ng is pronouncing the ratio i as i. Examples are:
• (Turkish) military and military (school),
• (Islam) religion and religious (information),
• (physics) science and scientific (discussions).
In these examples, you hear it pronounced as I. The proportion i must also be pronounced with the letter i.

**Comment by Qchristensen** [comment]
Ah thank you! Do you know if that is in / scheduled to be in a particular eSpeak-NG build and I can push for us to update NVDA to it soon.

**Comment by Gurbuzguven** [comment]
My pleasure. Not in the mainstream yet, but i've created PR so i guess it will get accepted soon.

**Comment by Qchristensen** [comment]
Thank you!  My user said:

Merhaba, oluşturulan sorundaki söylenenleri takip ettim ve söylediğim sorun tamamen çözüldü. 

İlâve olarak bir şeyin daha eklenmesini isteyeceğim:
Türkçede, ince a, yani şapkalı a diye de bilinir, k harfinden sonra ince a yani şapkalı a geldiğinde espeak ng bunu seslendiremiyor. Sadece, Hakkâri ismini doğru seslendiriyor. Halbuki, kâğıt, kâtip, kâse, gibi kelimeleri düzgün seslendiremiyor. Yani k harfinden sonra ince a, yani şapkalı a geliyorsa k harfini incelterek seslendirmesi gerekiyor.

(ENGLISH TRANSLATION):

Hello, I followed what was said in the generated problem and the problem I said is completely resolved.

In addition, I would like to add one more thing:
In Turkish, it is also known as a thin a, that is, a capped a, after the letter k, a thin a, that is, a capped a, cannot be pronounced as espeak ng. He just pronounces the name Hakkari correctly. However, he cannot pronounce words such as paper, clerk, bowl properly. In other words, if thin a, that is, a capped a, comes after the letter k, it must be vocalized by thinning the letter k.

**Comment by Qchristensen** [comment]
Here's some more feedback from the user - this one doesn't work as well translated but again I'll include his original Turkish and what Google gave me in English below:

Merhaba, oluşturduğunuz soruna şu yorumu da eklerseniz çok sevinirim:
Oluşturduğunuz çözümü test ettim. Bu sefer de, bu uzatmayı, her yerde yapmaya başladı espeak ng. Yani, bunun yapıldığı yerler var, yapılmadığı yerler var. Meselâ uzatılmaması gereken yerler için örnek vereyim:
İSTİKLÂL MARŞI
Korkma, sönmez bu şafaklarda yüzen al sancak;
Sönmeden yurdumun üstünde tüten en son ocak.
O benim milletimin yıldızıdır, parlayacak;
O benimdir, o benim milletimindir ancak.
Çatma, kurban olayım çehreni ey nazlı hilâl!
Kahraman ırkıma bir gül… ne bu şiddet bu celâl?
Sana olmaz dökülen kanlarımız sonra helâl,
Hakkıdır, Hakk’a tapan, milletimin istiklâl.
Gördüğünüz gibi, bu sefer de, istiklaal, hilaal, celaal, helaal, diyerek, bunu bütün kelimeler için uygulamaya başladı.

Hello, I would be very happy if you add the following comment to the problem you have created:
I tested the solution you created. This time, it started doing this extension everywhere, espeak ng. I mean, there are places where this is done, there are places where it's not done. For example, let me give an example for places that should not be extended:
INDEPENDENCE ANTHEM
Do not be afraid, the red banner floating in these unquenchable dawns;
The last stove that is smoking on my country before it goes out.
He is the star of my nation, he will shine;
It is mine, it belongs to my nation.
Don't fall, let me be a victim, O coy crescent!
A rose to my heroic race… what is this violence, this majesty?
Our spilled blood then you will not lawful,
It is right, the one who worships God, the independence of my nation.
As you can see, this time, he started to apply this for all words, saying istiklaal, hilaal, celaal, helaal.

**Comment by haruncetinkaya306** [comment]
Merhaba Gürbüzgüven, ben sorunu anlatan kullanıcıyım. Mesele daha iyi anlaşılsın diye bizzat yazmak istedim. İkimiz de Türkçe dilini bildiğimizden daha iyi anlaşacağımızı düşünüyorum.
Sizin soruna çözüm olsun diye oluşturduğunuz sözlüğü test ettim. Bu sefer de daha başka bir sorun oluştu:
Bu uzatmayı, her yerde yapmaya başladı espeak ng. Yani, bunun yapıldığı yerler var, yapılmadığı yerler var. Meselâ uzatılmaması gereken yerler için örnek vereyim:
İSTİKLÂL MARŞI
Korkma, sönmez bu şafaklarda yüzen al sancak;
Sönmeden yurdumun üstünde tüten en son ocak.
O benim milletimin yıldızıdır, parlayacak;
O benimdir, o benim milletimindir ancak.
Çatma, kurban olayım çehreni ey nazlı hilâl!
Kahraman ırkıma bir gül… ne bu şiddet bu celâl?
Sana olmaz dökülen kanlarımız sonra helâl,
Hakkıdır, Hakk’a tapan, milletimin istiklâl.
Oluşturduğunuz sözlükle test ederseniz göreceksiniz ki; bu sefer de, istiklaal, hilaal, celaal, helaal, diyerek, bunu bütün kelimeler için uygulamaya başladı.
Nispet i'si için sadece normal i harfini yazarsanız, bir de şapkalı a harfini eskisi gibi yaparsanız her şey daha iyi olacaktır zannımca. Bir de, bağışlamak, kelimesini Espeak ng sanki ğ harfinden sonra iki ı varmış gibi seslendiriyor. Bu da düzeltilirse sevinirim. Teşekkürler...

**Comment by Qchristensen** [comment]
My user added the following information:

Merhaba, bahsettiğim sorunla ilgili çözüm alpha-26331,5a4512ef (2022.4.0.26331'de uygulanmış. Ama burada da küçük bir düzeltme iyi olur. Â ve î harflerini uzatmayarak, sadece a ve i harfleri olarak telaffuz etmeli.

Yoruma şunu ekleyebilirsiniz; nispet i'sini uzatmayarak ve şapkalı a harfini uzatmayarak okursa sorun tamamen çözülmüş olur. Nispet i harfini uzatmadan i olarak seslendirmesi gerekiyor espeak ng sentezleyicisinin.

(Translated below with Google translate):

Hello, the solution to the problem I mentioned was implemented in alpha-26331,5a4512ef (2022.4.0.26331. But a small correction would be nice here too. It should not prolong the letters Â and î, but pronounce them only as the letters a and i.

You can add the following to the comment; If he reads it by not extending the proportion i and not extending the letter a with the hat, the problem is completely solved. The espeak ng synthesizer needs to pronounce the letter i as i without prolonging it.
