### ISSUE TITLE
Phonemes for word "Aujourd'hui" seem incorrect (FR)

### ISSUE THREAD

**Issue by DrugRaja** [espeak-ng/espeak-ng#1269]
In French language, phonemes generated for word "Aujourd'hui" seem incorrect to me. 

Output I get is: " oʒuʁdyˈi ˈi "

Expected output: " oʒuʁdyˈi"

This error happens only for textmode espeakCHARS_WCHAR.

**Comment by sthibaul** [comment]
How do you get that output? With version 1.51, I get this:

```
$ espeak-ng -v fr -x "Aujourd'hui"    
oZurdy'i
```

**Comment by valdisvi** [comment]
It is IPA output, but still is not reproducible:
```    
espeak-ng -v fr -x --ipa "Aujourd'hui" 
oʒuʁdyˈi
```

**Comment by DrugRaja** [comment]
I get it with call to following function:

espeak_TextToPhonemes((const void**)ptrToString, espeakCHARS_WCHAR, espeakPHONEMES_IPA);

Version is 1.49.2 on Ubuntu 18.04

**Comment by sthibaul** [comment]
@DrugRaja 1.49.2 is much more than old, we cannot fix bugs in the past :)
