### ISSUE TITLE
Memory leak/Segmentation Fault when espeak is called with text string ending in double periods ".."

### ISSUE THREAD

**Issue by kallistisoft** [espeak-ng/espeak-ng#1277]
**Issue:**
Calling espeak with text ending in ".." causes a memory leak or segfault when trying to export to wav file with '-w' flag

**Reproduction Steps:**
Call espeak with: 'espeak ".."

**Observed Behavior:**
Evoking espeak with a string ending in ".." causes espeak to emit what appears to be a memory pointer violation

**Example of output:**
[https://voca.ro/1ky1vFSGvHAF](https://voca.ro/1ky1vFSGvHAF)

**Expected Behavior:**
Silent output

**System Specs:**
OS: Arch Linux x86_64
Kernel Release: 5.18.6-arch1-1
eSpeak Version: eSpeak NG text-to-speech: 1.51  Data at: /usr/share/espeak-ng-data

**Comment by valdisvi** [comment]
Cannot reproduce in development version neither on my computer nor in [online test site](https://odo.lv/Espeak?eslang=-ven-gb&speed=160&output=-w&debug=-x&text=..&formmethod=get) (which also produces wav files).

**Comment by sthibaul** [comment]
We already had the bug https://github.com/espeak-ng/espeak-ng/issues/1271 reporting it, that was fixed a week ago.

**Comment by kallistisoft** [comment]
I had tried searching previous issues with just the string ".." thinking that was specific enough, but apparently Github's search engine doesn't work that way...  

Thank you for your attention to this matter!
