### ISSUE TITLE
problems with question marks in Latin Spanish and the letter r when spelling in espeak ng.

### ISSUE THREAD

**Issue by gregodejesus** [espeak-ng/espeak-ng#1313]
Hey.
It turns out that I use the Latin Spanish language in espeak ng, but unlike Spanish spain, in Spanish spain if you intone the questions, which in Latin Spanish does not happen the same.
[spanish.zip](https://github.com/espeak-ng/espeak-ng/files/9438420/spanish.zip)
I would like this problem to be fixed since espeak 1.52 is in development.
Below I leave some examples.
also to say that the letter r when spelling character by character, I feel that it verbalizes it as l.
Greeting.

**Comment by jaacoppi** [comment]
Do you mean Spanish (Latin America), es-419? Configuration is in  espeak-ng-data/lang/roa/es-419.

See `docs/intonation.md` for an explanation of the `tunes` command.
See `docs/voices.md` for an explanation of the `intonation` command.

Can you test it yourself?

**Comment by gregodejesus** [comment]
correct, I already found the fault and fixed it. the intonation would be like this for the Latin Spanish questions:
tunes s6 c6 q6 e6
i would like that same code to be implemented in the espeak in:
espeak-ng-data/lang/roa/es-419.
