### ISSUE TITLE
Adding Mongolian language

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#1324]
Hello.
I have a new suggestion to You. Could You add Mongolian language? It'll be very great to have this language on Espeak.
I am not Mongolian speaker, but I would like to use It to read mongolian text.
Thank You.

**Comment by btseee** [comment]
Dear @Giovani93,

I have been contributing Mongolian language support to this project for the past year and continue to actively develop and improve it.

Mongolian is a complex language, and the implementation is still not perfect, but I hope it will be useful and help move the project forward.
