### ISSUE TITLE
French pronounciation problems

### ISSUE THREAD

**Issue by DataTriny** [espeak-ng/espeak-ng#133]
Hi, the French version of eSpeak NG fails to pronounce correctly very common things.
Here are two problems I encountered: "votre" and "vôtre" are pronounced exactly the same, "ui" is also not pronounced correctly.
Thanks in advance!

**Comment by Christianlm** [comment]
Hi, "votre" and "vôtre" is not pronuncied exactly in the same way by espeak-ng, "votre" is always unstressed.
However, I agree. Seems that espeak-ng don't pronunces correctly the french possessive pronouns 
"vôtre", "nôtre".

**Comment by ValdisVitolins** [comment]
I have made temporal changes. Does [this](http://odo.lv/Espeak?eslang=-vfr&speed=160&output=-w&debug=-X&text=Votre.+Vôtre.+Nôtre.) sounds better?

**Comment by ValdisVitolins** [comment]
espeak-ng now says:
```
espeak-ng -x -vfr "votre, vôtre, nôtre, cône."
 v'otr
 v'o:tr
 n'o:tr
 k'O~n
```
where **o** is shorter one, **o:** is longer one, but **O~** is nasal variant.

**Comment by ValdisVitolins** [comment]
... and `votre` is already set as unstressed word in `fr_list` file.

**Comment by cmrdt** [comment]
not fluent at french but 
don't think vowel length does that much(no diff) except for rare ɛ

[wiki: vowel length](https://en.wikipedia.org/wiki/Vowel_length)
[wiki:french](https://en.wikipedia.org/wiki/French_phonology#Length)

not sure about the wiki's accuracy, 
[votre](https://en.wiktionary.org/wiki/votre) is vɔtʁ `v'Otr`
[vôtre](https://en.wiktionary.org/wiki/v%C3%B4tre) is votʁ `v'otr`
