### ISSUE TITLE
Espeak ng türkçe dil desteğinde telaffuz düzeltmesi

### ISSUE THREAD

**Issue by haruncetinkaya306** [espeak-ng/espeak-ng#1337]
#Türkçe dilinde, espeak ng, bağışlamak, kelimesini ğ harfinden sonra iki ı harfi varmış gibi okuyor.

**Comment by jaacoppi** [comment]
What is the correct pronunciation?
The current rule is here: 
`dictsource/tr_listx:18:bağışlamak ba:@@Sla'mak`

You can experiment with other words using espeak-ng -x:

```
espeak-ng -v tr -x "Türkçe dilinde, espeak ng, bağışlamak, kelimesini ğ harfinden sonra iki ı harfi varmış gibi okuyor"
t'YRktSE dilInd'E
Espe'ak n,EJ'E
ba:@@Slam'ak
kelimesin'I jumuS'ak J'E haRfInd'&n sOnR'a ik'I '@ haRf'I vaRm'@S Jib'I ok'ujOR
```

**Comment by haruncetinkaya306** [comment]
Doğrusu, bağışlamak.

**Comment by haruncetinkaya306** [comment]
Yani şöyle anlatmam gerekiyor sanırım; (bağışlamak) yazdığımda, espeak ng sentezleyicisi, bunu, (bağıışlamak) şeklinde yazılmış gibi okuyor. Ğ harfinden sonra bir tane ı harfi yazılmasına rağmen, okurken, iki tane ı harfi varmış gibi tepki veriyor. Düzeltilebilirse, düzeltilecek olan şey, bu kelimeyi okurken, yazıldığı gibi tepki vermesidir.

**Comment by jaacoppi** [comment]
so the "i"  in bağışlamak should be short like in for example "bağışlama"?

What about "bağışlayın"? Should it be short as well?

**Comment by haruncetinkaya306** [comment]
Bu kelime, 10 harften meydana geliyor. Yani bağışlamak. Ama espeak ng, bunu, 11 harf ile yazılmış gibi, yani bağıışlamak, şeklinde telaffuz ediyor, yani okuyor. Yani, ğ harfinden sonra, iki tane ı harfi yazılmış gibi davranıyor.

**Comment by haruncetinkaya306** [comment]
Sorunuza ayrıca şöyle cevap verebilirim: Bu sorun sadece, bağışlamak, kelimesinde var. Meselâ bağışla, kelimesinde sorun yok. Bağışlamak, kelimesinde de, bağışlada olduğu gibi, ğ harfinden sonra 1 tane ı harfi varmış gibi okumalı evet!

**Comment by haruncetinkaya306** [comment]
Şunu merak ediyorum, bu sorunun çözümüne dair bir taahhüd olacak mı, yani sorun çözülebilecek mi?

**Comment by jaacoppi** [comment]
[This commit](https://github.com/espeak-ng/espeak-ng/commit/e5ae5b8557cb824cf253e00c67daec71418575c2) Changes words "bağışlamak" and "bağışlayın". Can you test it now?

**Comment by haruncetinkaya306** [comment]
Sözlüğü indirmem gerekiyor sanırım ama bunu nasıl yapacağımı bilemiyorum. Nasıl indirmem gerekiyor?

**Comment by haruncetinkaya306** [comment]
Alfa kanalında sözlüğü bulamadım. Bakmamı istediğiniz yerde de sözlüğü tek dosya halinde bulup indiremiyorum.

**Comment by jaacoppi** [comment]
Normally the best option is to use [https://odo.lv/Espeak](https://odo.lv/Espeak) but it is not updated yet.

On linux you can compile the dictionary to ../espeak-ng-data/tr_dict like this:
`cd dictsource &&  ESPEAK_DATA_PATH=`pwd`/.. LD_LIBRARY_PATH=../src:${LD_LIBRARY_PATH} ../src/espeak-ng --compile=tr`

I don't know how to do it in Windows. 
Here's the compiled tr_dict file: [tr.zip](https://github.com/espeak-ng/espeak-ng/files/9709182/tr.zip)

**Comment by haruncetinkaya306** [comment]
Bağışlamak, kelimesinin sorunu çözüldü. Bir de, bağışlayın, kelimesinde de aynı sorun var. Bunun için de bir düzeltme olabilir mi?

**Comment by haruncetinkaya306** [comment]
Bağışlayın kelimesinde sorun olduğunu taahhüt ettiğiniz sözlüğü test ederken fark ettim bu yüzden üzgünüm. Eğer bağışlayın kelimesinde de sorun olduğunu anlasaydım ikisini aynı anda söyleyebilirdim. Ne yazık ki bunu birkaç dakika önce fark ettim.

**Comment by haruncetinkaya306** [comment]
Bağışlayın, sözcüğü de düzeltilirse, o haliyle de sözlüğü zip halinde buraya yükleyebilir misiniz? Onu da test etmek isterim.

**Comment by jaacoppi** [comment]
Both words are already changed in the zip file.


Old version:
```
espeak-ng -v tr "bağışlamak bağışlayın" -x
ba:@@Slam'ak ba:@@Sl'aj@n

```
New version in the zip file:
```
espeak-ng -v tr "bağışlamak bağışlayın" -x
ba:@SLam'ak ba:@SLaj'@n

```

**Comment by haruncetinkaya306** [comment]
Sözlüğü ikinci kez test ettim bağışlamak kelimesi düzeltilmiş ama, bağışlayın, kelimesinin sorunu devam ediyor.

**Comment by haruncetinkaya306** [comment]
Bağışlayın, kelimesini tekrar kontrol ederseniz güzel olur.

**Comment by haruncetinkaya306** [comment]
Merhaba jaakoppi,  Bağışlayın, kelimesi düzeltilemediğinden, eğer bu konuda tekrar bir düzeltme yapılırsa, onu da zip dosyası halinde gönderirseniz alfa kanalına getirilmeden önce test edebilirim

**Comment by haruncetinkaya306** [comment]
Hi jaacoppi, the first word was fixed but the second word's problem could not be fixed. Can this word be corrected too?

**Comment by jaacoppi** [comment]
I have changed "bağışlayın".  It can be seen in the debug output. Unless you provide the correct Kirshenbaum notation (like "ba:@SLaj'@n") I cannot help any more.

> Old version:
> ```
> espeak-ng -v tr "bağışlamak bağışlayın" -x
> ba:@@Slam'ak ba:@@Sl'aj@n
> ```
> 
> New version in the zip file:
> ```
> espeak-ng -v tr "bağışlamak bağışlayın" -x
> ba:@SLam'ak ba:@SLaj'@n
> ```

**Comment by haruncetinkaya306** [comment]
I am sending two audio recordings that encode the word letter by letter. The first is spelled wrong, the second is spelled correctly.

**Comment by haruncetinkaya306** [comment]
Hatalı olan sözcük:
[4AF1.zip](https://github.com/espeak-ng/espeak-ng/files/9741079/4AF1.zip)

**Comment by haruncetinkaya306** [comment]
Bu da, doğru sözcük:
[4AF1.zip](https://github.com/espeak-ng/espeak-ng/files/9741083/4AF1.zip)

**Comment by haruncetinkaya306** [comment]
Bu sözcüklerin önce yanlış, sonra doğru okunuşlarını txt dosyaları ile de gönderiyorum. Umarım tüm bunlar yardımcı olabilir.

**Comment by haruncetinkaya306** [comment]
[wrong word.txt](https://github.com/espeak-ng/espeak-ng/files/9741163/wrong.word.txt)

**Comment by haruncetinkaya306** [comment]
[correct word.txt](https://github.com/espeak-ng/espeak-ng/files/9741170/correct.word.txt)

**Comment by jaacoppi** [comment]
Run espeak-ng with the dictionary I provided and with these options: `-v tr "bağışlamak bağışlayın" -X`

Paste the output here.

**Comment by haruncetinkaya306** [comment]
Sorry Jaacoppi, I didn't understand what to do. That's why I can't do what you said. I guess unfortunately there is nothing that can be done about this word. Actually, I thought of a final solution: In earlier versions, this word was pronounced correctly. Would it be helpful if I shared this dictionary here just for this word?

**Comment by jaacoppi** [comment]
@SeanTolstoyevski: Your commit [2fe8a189](https://github.com/espeak-ng/espeak-ng/commit/2fe8a1898f377cae0801bd32bb493faa22d51f12) Originally changed these words. Any ideas?

**Comment by haruncetinkaya306** [comment]
This text has been translated into english by google translate. The original is below:
Hi @SeanTolstoyevski, it seems you prepared the pronunciation of the words we spoke in issue #1337. I read your statement in the commit. I think you did something like this to indicate the letter Ğ. But in previous versions, the letter ğ could be heard. In my opinion, there was no need for you to go to such a solution. This time, he started to sound as if there were two ı letters after the letter ğ in his words forgive and forgive, espeak ng. Corrected the word forgive. But I could not explain that the word forgive should also be corrected and that the correct one should be after the letter ğ, because our languages are different. I think you know Turkish. So you should know what I mean. Forgive me, it would be nice if the wording was corrected as well.
Merhaba @SeanTolstoyevski, görünüşe göre sayı #1337'de konuştuğumuz kelimelerin telaffuzunu siz hazırladınız. Taahhütteki açıklamanızı okudum. Ğ harfinin belirtilmesi için böyle bir şey yaptınız sanırım. Ama önceki sürümlerde ğ harfi duyulabiliyordu. Bana kalırsa böyle bir çözüme gitmenize gerek yoktu. Bu kez de, bağışlamak ve bağışlayın, sözcüklerinde, ğ harfinden sonra, iki tane ı harfi varmış gibi seslendirmeye başladı espeak ng. Bağışlamak sözcüğü düzeltildi. Ama bağışlayın kelimesinin de düzeltilmesi gerektiğini ve doğrusunun ğ harfinden sonra bir tane ı harfi olması gerektiğini anlatamadım dillerimizin farklı olması sebebiyle. Sizin türkçe bildiğinizi sanıyorum. Bu yüzden ne demek istediğimi anlamış olmalısınız. Bağışlayın, kelimesi de düzeltilirse güzel olur.

**Comment by haruncetinkaya306** [comment]
@Gurbuzguven, do you have an opinion on what was said? I think you know Turkish too. Do you have a solution suggestion for this issue?

**Comment by SeanTolstoyevski** [comment]
@jaacoppi
> Your commit 2fe8a189 Originally changed these words. Any ideas?

Yes, it seems that I entered some notations wrong. I apologize.

I have some time after 1 day and after 2 days. I will take care of it.

**Comment by SeanTolstoyevski** [comment]
@haruncetinkaya306


[tr]

merhabalar,
öncelikle geç cevaplar için özür dilerim. mail'lere de dönemedim. şu sıra hayatım çok yoğun. iş dışında da kafam pek yerinde değil, onun için hiçbir şeyle ilgilenemedim.

espeak sözlükleri, farklı bir notasyonla yazılıyor. kendine ait kuralları var.
daha sonra bu sözlük, derlenerek espeak'ın okuyabileceği bir formata dönüştürülüyor.
maalesef bu işlemleri yapabilmek için temel düzeyde bir geliştirme tecrübeniz olmalı.
vakit bulursam, windows'ta espeak'ı basitçe derlemek için bir script yazmayı düşünüyorum ama dediğim gibi vaktim çok sıkışık.

**Comment by haruncetinkaya306** [comment]
[tr]
Merhaba @SeanTolstoyevski, sizi anlıyorum. Zaten @jaacoppi taahhüdünde belirttiği iki kelimeden birincisini düzeltti. Espeak onu doğru telaffuz edebiliyor. İkinci sözcüğü de düzelttiğini söylüyor. Ama ne yazık ki espeak ng ikinci sözcükte aynı tepkiyi vermeye devam ediyor. İngilizce diline hakimiyetim olsa @jaacoppi'ye bu durumu anlatabilirim. Ama çeviriyle anlatabildiğim kadar anlatabiliyorum. Yoksa size rahatsızlık vermek istemezdim, ben anlatabilsem @jaacoppi bu sözcüğü de düzeltebilecektir ama bu noktada ben yetersiz kalıyorum.

**Comment by haruncetinkaya306** [comment]
@SeanTolstoyevski Bir gelişme var mı bu düzeltme hakkında?

**Comment by SeanTolstoyevski** [comment]
@haruncetinkaya306 
[tr]
halen espeak'i windows'ta derleyemedim.


[en]
I still couldn't compile espeak on windows.

**Comment by haruncetinkaya306** [comment]
@SeanTolstoyevski
[tr]
Anlıyorum. Henüz düzeltme ile ilgilenemediniz sanırım. Düzeltmeyi yaptığınız zaman sözlüğü derlenmiş halde zip dosyası olarak paylaşırsanız güzel olur. Böylelikle test etme imkânı bulurum.

**Comment by haruncetinkaya306** [comment]
@SeanTolstoyevski
[tr]
Bu sayıda belirttiğim kelimeler konusunda bir gelişme oldu mu? Bunu şunun için soruyorum; biliyorsunuz yıl sonuna gelmek üzereyiz. NVDA 2022.4 sürümünden sonra yeni bir sürüm döngüsüne başlayacak. Bunun gelmesi zaman alabilir. Şuan 2022.4 beta kanalındayken, eğer yapılabiliyorsa düzeltme beta kanalına, eğer o da mümkün değilse yıl bitmeden halen alfa kanalı güncelleme alıyorken 2023.1 yapısına dahil edilse iyi olur.

**Comment by haruncetinkaya306** [comment]
Özür dilerim, sayı #875'teki konuşmayı şimdi gördüm. @jaacoppi'nin orada son yorumda paylaştığı sözlükte, söylediğim tüm hatalar çözülmüş. @jaacoppi'nin paylaştığı dosyayı bu sayıda oradan alarak ben de paylaşıyorum. Dosya bu haliyle sorunsuz hale getirilmiştir, artık bu dosya alfa yapısına ve eğer mümkün olabilirse beta yapısına dahil edilebilir. Tüm geliştiricilere ilgi ve yardımlarından dolayı teşekkür ederim...
@Qchristensen
@jaacoppi
@SeanTolstoyevski
[tr_dict.zip](https://github.com/espeak-ng/espeak-ng/files/9887827/tr_dict.zip)

**Comment by jaacoppi** [comment]
Those fixes have been in the master branch for some time. Closing issue.
