### ISSUE TITLE
Tracking environment-dependent tests behavior

### ISSUE THREAD

**Issue by djphoenix** [espeak-ng/espeak-ng#1368]
Following #1264, #1353.

Some of tests (found faulty on macOS) are disabled in commit 0f5a30f.

**UPD:** ssml/prosody test depends on libsonic

Tracking (re-enabled) tests behavior with some compilers:

- Debian 11 x86-64, clang-14.0.6-2: ✔️ passed
- Debian 11 x86-64, gcc-12.2.0-1: ✔️ passed
- Alpine x86-64 (docker), gcc-12.1.1_git20220630-r5: ❌ FAILED (language-phonemes/ltg, language-phonemes/lv)
- macOS 12.5.1 x86-64, apple-clang-1316.0.21.2.5: ❌ FAILED (language-phonemes/ltg, language-phonemes/lv)
- macOS 12.5.1, x86-64, gcc-12.2.0 (homebrew): ❌ FAILED (language-phonemes/ltg, language-phonemes/lv)

_// to be continued_

**Comment by sthibaul** [comment]
https://github.com/espeak-ng/espeak-ng/issues/1264#issuecomment-1200287097 is probably interesting:

« Seems like uppercase letters in phonemes are completely ignored... »

**Comment by djphoenix** [comment]
@sthibaul more interesting observations:

- ssml/prosody fails with gcc somewhere after v12.1.x
- lv/ltg fails... somewhere?

**Comment by djphoenix** [comment]
Seems like I've distinguished root cause for 'prosody' failure: compilation without libsonic. In alpine I haven't found it in package manager. In macOS it may be some faulty. When I disabled it in Debian configure (--without-sonic), it fails.

**Comment by djphoenix** [comment]
@alex19EP can you confirm your build (for PR #1353) was with libsonic or without? Debian 11 without libsonic gets exact your hash (32c9f870117bce5852fd53af93e967187fa8ca40).

**Comment by djphoenix** [comment]
> surrounding brackets indicate that letters are not written text but sequence of phoneme names.

Sure, I know. The root question is "why it fails" :)

**Comment by alex19EP** [comment]
> @alex19EP can you confirm your build (for PR #1353) was with libsonic or without? Debian 11 without libsonic gets exact your hash (32c9f870117bce5852fd53af93e967187fa8ca40).

yep. in Arch Linux I haven't package libsonic.

**Comment by djphoenix** [comment]
Yeah, in alpine-docker I've installed libsonic from source and prosody test passed. I will prepare PR to make macos test work with it too.

The remaining question... what wrong with phonemes.

**Comment by sthibaul** [comment]
> Seems like I've distinguished root cause for 'prosody' failure: compilation without libsonic. In alpine I haven't found it in package manager. In macOS it may be some faulty. When I disabled it in Debian configure (--without-sonic), it fails.

Ah, that makes sense, we could accept both hashes

**Comment by djphoenix** [comment]
> we could accept both hashes

I'm not so familiar with project test system, so not sure that I can patch test to "multihash" variant. But it is good point (and TODO).

**Comment by valdisvi** [comment]
If you will provide list of needed hashes, I may update test to accept more than one value.

**Comment by djphoenix** [comment]
`32c9f870117bce5852fd53af93e967187fa8ca40` without libsonic
`88fccb35536158f25f4ae44a03fb005fef95c99b` with

**Comment by valdisvi** [comment]
ok

**Comment by valdisvi** [comment]
Latvian or Latgalian? Probably need both.

**Comment by djphoenix** [comment]
> Latvian or Latgalian? Probably need both.

That for ssml <prosody> test. Phoneme tests are still a question.

**Comment by djphoenix** [comment]
Sorry, I have mixed a cases. It is good that one of them was easy and split-fixed.

**Comment by djphoenix** [comment]
Seems like generation for `ltg` is slightly differs between alpine (test-broken) and debian (test-pass).
Maybe we need to go deeper into wave generation. Overall file seems very similar, but, in fact, different.

![diff](https://user-images.githubusercontent.com/1833493/189884632-8c197acd-cff3-4769-aa75-bbc00575b11e.png)
![diff-zoom](https://user-images.githubusercontent.com/1833493/189884647-c307f95c-363a-43d1-b80e-752836517c3c.png)

**Comment by djphoenix** [comment]
So I think I am very near the key of problem for phonemes.

I started with an idea that, "if it only single languages, it should be something wrong with language definition".

So I have cleaned every setting from `ltg` files in Alpine and Debian, and hashes becomes the same (both wrong for test, but it doesn't matter).

Then I reverted settings step-by-step, and have the one that makes hash to differ.

And the winner is... "breath".
Searching for this line in the entire project gives me a meaning that `ltg` and `lv` are the single languages that have this option.

@valdisvi @sthibaul I need your expertise here, I have no idea how "breath" setting should work (ether in voice or language definition). But the key of the problem was found.

**Comment by djphoenix** [comment]
Also, it doesn't affect this case, but deep dive into project code gives me into method `Read8Numbers` (that called from code that  reads "breath" setting). It `memset`s a buffer to zeroes, but actually zeroing only 12 bytes, not entire buffer. Should we fix it?

```patch
diff --git a/src/libespeak-ng/voices.c b/src/libespeak-ng/voices.c
index 4627e92e..395dd1b4 100644
--- a/src/libespeak-ng/voices.c
+++ b/src/libespeak-ng/voices.c
@@ -476,7 +476,7 @@ static void PhonemeReplacement(char *p)
 static int Read8Numbers(char *data_in, int *data)
 {
        // Read 8 integer numbers
-       memset(data, 0, 8+sizeof(int));
+       memset(data, 0, 8*sizeof(int));
        return sscanf(data_in, "%d %d %d %d %d %d %d %d",
                      &data[0], &data[1], &data[2], &data[3], &data[4], &data[5], &data[6], &data[7]);
 }
```

**Comment by valdisvi** [comment]
My understanding is that [breath](https://github.com/espeak-ng/espeak-ng/blob/master/docs/voices.md#breath) adds (pseudo-random) fluctuations to formant to make it less like pipe (precisely harmonic) sound. Probably in different platforms this randomness starts differently.

**Comment by djphoenix** [comment]
The main observation here that `breath` was used only in voices, not langs. Until `ltg` and `lv`...

**Comment by djphoenix** [comment]
I can dive some deeper to understand **why** it actually differs for this case. [It should be simple](https://www.meme-arsenal.com/memes/17d708c0fddc8ccce2d014ad8f097516.jpg)...

**Comment by sthibaul** [comment]
> Also, it doesn't affect this case, but deep dive into project code takes me into method `Read8Numbers` (that called from code that reads "breath" setting). It `memset`s a buffer to zeroes, but actually zeroing only 12 bytes, not entire buffer. Should we fix it?
> 
> ```diff
> diff --git a/src/libespeak-ng/voices.c b/src/libespeak-ng/voices.c
> index 4627e92e..395dd1b4 100644
> --- a/src/libespeak-ng/voices.c
> +++ b/src/libespeak-ng/voices.c
> @@ -476,7 +476,7 @@ static void PhonemeReplacement(char *p)
>  static int Read8Numbers(char *data_in, int *data)
>  {
>         // Read 8 integer numbers
> -       memset(data, 0, 8+sizeof(int));
> +       memset(data, 0, 8*sizeof(int));

That looks completely right! I have also changed `int*` in https://github.com/espeak-ng/espeak-ng/pull/1375, letting that go through CI before pushing.

**Comment by sthibaul** [comment]
> My understanding is that [breath](https://github.com/espeak-ng/espeak-ng/blob/master/docs/voices.md#breath) adds (pseudo-random) fluctuations to formant to make it less like pipe (precisely harmonic) sound. Probably in different platforms this randomness starts differently.

AIUI, `rand()` is not guaranteed to return the same values on different OSes indeed... Perhaps try to replace the rand() calls with a dumb constant number, to see whether that makes the two cases identical.

**Comment by sthibaul** [comment]
Perhaps we can introduce an environment variable that disables the `breath` functionality, so that `make check` can set it to avoid the differing behavior, while keeping the functionality enabled for normal use?

**Comment by djphoenix** [comment]
@valdisvi as maintainer of these langs, correct me if I wrong. The breath attribute affects a pronouncing and specific for voice. In most voices it is specified. So it is useless for **lang** specification. What will be wrong if we remove attribute from `lv` and `ltg`?

**Comment by jaacoppi** [comment]
I agree. breath and breathw are voice attributes and should not be set in lang files. There's probably other similar cases as well. Removing the setting will probably break phoneme tests but that's easy to fix.

Affected languages:
% grep -lr breath espeak-ng-data/lang/
espeak-ng-data/lang/aav/vi-VN-x-south
espeak-ng-data/lang/aav/vi-VN-x-central
espeak-ng-data/lang/bat/lv
espeak-ng-data/lang/bat/ltg

In the long run, voices.c should be refactored to clearly separate voice and language settings.

**Comment by djphoenix** [comment]
> espeak-ng-data/lang/aav/vi-VN-x-south
> espeak-ng-data/lang/aav/vi-VN-x-central

For sure, these two are unaffected because breath options are commented out.

**Comment by sthibaul** [comment]
> I agree. breath and breathw are voice attributes and should not be set in lang files.

We can probably create a test that checks against that?

**Comment by djphoenix** [comment]
@jaacoppi for me, it would be great to have some technical format description (maybe something like DSL) that suitable for automatic parse and validate data files. Not only for “allowed options” but for “argument formatting” and “value ranges” too. But it is huge step and requires precise knowledge of all used data formats.

**Comment by jaacoppi** [comment]
> @jaacoppi for me, it would be great to have some technical format description (maybe something like DSL) that suitable for automatic parse and validate data files. Not only for “allowed options” but for “argument formatting” and “value ranges” too. But it is huge step and requires precise knowledge of all used data formats.

Sounds like a good idea. Generally speaking we have limited documented knowledge of existing functionality. This would be a great way for improving both the tests and the documentation.

My plan is to combine LoadConfig() with LoadVoice() in a way that any language / voice setting could be overwritten at runtime by reading espeak-ng-data/config. This would make it possible to write a test script that parses the DSL for any combination of input parameters and expected outputs. Does it sound good to you?

**Comment by djphoenix** [comment]
> Does it sound good to you?

I’m not sure. In general, it is bad idea to mix different entities (voices and langs i.e.) in same decoders. Also I plan to dive deep into the question about difference of phonemes that available only for certain langs (it is strange because phonemes are language-independent), and IPA mapping mismatches (and missed mappings at all).

**Comment by djphoenix** [comment]
Guys, my final proposal is to fix flaky tests by removing `breath` args from voices, close this issue and create separate one for discuss and track convenient method for data linting. @sthibaul  @jaacoppi @valdisvi ?

**Comment by JuhoHiltunen** [comment]
> Guys, my final proposal is to fix flaky tests by removing `breath` args from langs

Did I understand correctly, you want to remove breath from ltg and lv? I agree that this should be done.

**Comment by djphoenix** [comment]
> Did I understand correctly, you want to remove breath from ltg and lv?

Yes, as discussed before.
