### ISSUE TITLE
some strange problem with 32 digits

### ISSUE THREAD

**Issue by kirill-jjj** [espeak-ng/espeak-ng#1385]
when i write one and 31 zerow's and grater it reads like 3647, like this: 100000000000000000000000000000000

**Comment by beqabeqa473** [comment]
Looking at the code, it was done intentionally.
Specifically in commit #4412de57fd759430f8a38c8a50b86231c75a5242, there was introduced one more conditional check if length of digit is less or equals to 32.

I don't know why this change was made, but maybe @sthibaul would be able to answer to this question.

**Comment by valdisvi** [comment]
In not reproducible in [develoment version](https://odo.lv/Espeak?eslang=-ven-gb&speed=160&output=-w&debug=-X&text=100000000000000000000000000000000&formmethod=get).

**Comment by sthibaul** [comment]
> Yes, it is. didn't test in linux and with standalone app, but in nvda

But is your nvda using the latest espeak-ng master version, and not only the last released version 1.51.1?

**Comment by sthibaul** [comment]
Note that the "32" limitation is not something that I have invented with commit 4412de57fd759430f8a38c8a50b86231c75a5242. it is the point where the code in version 1.51.1 starts getting out-of-bound issues.

**Comment by kirill-jjj** [comment]
@sthibaul do you have any ideas how to fix this problem?

**Comment by sthibaul** [comment]
@kirill-jjj  Since I can't reproduce the issue, no I have no idea.
It'd be useful that you manage to reproduce the issue with an espeak-ng call

**Comment by kirill-jjj** [comment]
@sthibaul, it is silent in the espeak-ng command line, and this is also wrong, let it break the number, even if it breaks it incorrectly, it is better than silence, or 3647 in nvda, and also, the number 3647, which it says instead of breaking the number in nvda, can be misleading

**Comment by Danstiv** [comment]
@sthibaul, I reproduced this using the library.
[espeak_3647_test.zip](https://github.com/espeak-ng/espeak-ng/files/9792790/espeak_3647_test.zip)

**Comment by Danstiv** [comment]
An example with an English voice (in the previous comment, by mistake, there was an example with a Russian voice).
[espeak_3647_test.zip](https://github.com/espeak-ng/espeak-ng/files/9793133/espeak_3647_test.zip)

**Comment by kirill-jjj** [comment]
@sthibaul, danstiv reproduced the 3647 problem using espeak-ng library, by the way, nvda uses it, sorry for annoying you, but i think that is critical problem whitch must be fixed.
Sorry for my english
