### ISSUE TITLE
Türkçe dilinde, espeak ng sentezleyicisinde telaffuz hatası

### ISSUE THREAD

**Issue by haruncetinkaya306** [espeak-ng/espeak-ng#1412]
Espeak ng sentezleyicisinde, türkçe dilinde, bağışlayın, sözcüğünü telaffuz ederken ğ harfinden sonra 2 tane ı harfi varmış gibi okuyor. Bu konuda sayı #1337'de yorumlarım mevcut. Oraya da bakabilirsiniz. Bu kelimenin düzeltilemediğini orada yazdım.

**Comment by jaacoppi** [comment]
Duplicate of #1337. Let's keep the conversation in one place.
