### ISSUE TITLE
strange problem with numbers in Russian

### ISSUE THREAD

**Issue by kirill-jjj** [espeak-ng/espeak-ng#1420]
Hello, I would like more than 18 digits to be read correctly in Russian.
But when I write 1000000000000000000 and 2000000000000000000, with the max digits 32 directive enabled, it reads not odin kventilion and dva kventilionna, as it should be, but odna kventilion and dve kventiliona.
I would like to draw your attention to the fact that only thousands are declined this way, for example 1000, odna tisycha, 2000, dve tisychi, 21000, dvadtsat odna tisicha, 22000, dvadtsat dve tisichi and so on
sorry for my english

**Comment by sthibaul** [comment]
> when I write 1000000000000000000 and 2000000000000000000, with the max digits 32 directive enabled, it reads not odin kventilion and dva kventilionna, as it should be, but odna kventilion and dve kventiliona

I'm not actually getting either of those with `espeak -v ru` (which doesn't surprise me since I don't see rules for so many zeros in `dictsource/ru_list`). How do you reproduce it?

**Comment by kirill-jjj** [comment]
update espeak-ng to the latest master, I added them there.
and in file tr_languages.c
replace the line, coresponding to russian
	tr->langopts.max_digits = 18;
with
	tr->langopts.max_digits = 32;

**Comment by kirill-jjj** [comment]
pull requested, I meen

**Comment by kirill-jjj** [comment]
> > when I write 1000000000000000000 and 2000000000000000000, with the max digits 32 directive enabled, it reads not odin kventilion and dva kventilionna, as it should be, but odna kventilion and dve kventiliona
> 
> I'm not actually getting either of those with `espeak-ng -v ru` (which doesn't surprise me since I don't see rules for so many zeros in `dictsource/ru_list`). How do you reproduce it?
update espeak-ng to the latest master, I added them there.
and in file tr_languages.c
replace the line, coresponding to russian
	tr->langopts.max_digits = 18;
with
	tr->langopts.max_digits = 32;

sorry, I'm not used to pressing reply button

**Comment by kirill-jjj** [comment]
@sthibaul, update espeak to the latest master, I pull requestted them there, and in file tr_languages.c, change the line
	tr->langopts.max_digits = 18;

	tr->langopts.max_digits = 32;

**Comment by sthibaul** [comment]
@kirill-jjj I have no idea about this bug either, much even less so since it looks like a male/female question, which I have no idea how espeak manages it.

**Comment by kirill-jjj** [comment]
@sthibaul all I could understand was the problem in numbers.c, and there is an intersection somewhere, he just counts thousands and quintillions like thousands.

**Comment by sthibaul** [comment]
> all I could understand was the problem in numbers.c, and there is an intersection somewhere, he just counts thousands and quintillions like thousands.

? you wrote before this:

> it reads not odin kventilion and dva kventilionna, as it should be, but odna kventilion and dve kventiliona

So it means it's confusing 

```
_1      ojd;'in
_1f     odn'a
```

i.e. AIUI it's confused whether kventilion is male or female.

Really it's useless to ask specifically me about this, I have no idea how all that is managed in espeak-ng.

**Comment by a11cf0** [comment]
There's the following check in function LookupNum3 in numbers.c:
```
			if (ordinal & 0x20)
				x |= 0x20; // variant form of ordinal number
		} else if (tr->langopts.numbers2 & (1 << thousandplex)) // The *cause*
			x = 8; // use variant (feminine) for before thousands and millions
```
Since thousandplex for 1000000000000000000 equals 6, 1 << 6 == 64 (0x40) and NUM2_THOUSANDS_VAR1 is defined to be 0x00000040 we're bound to get a false positive here.
Languages which use NUM2_THOUSANDS_VAR2 will similarly fail starting at 1000000000000000000000, because NUM2_THOUSANDS_VAR2 is 0x00000080 (128).
