### ISSUE TITLE
Creating an Ukrainian language for Espeak NG

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#144]
Hello!
I have one question. I am not a programmer, but please, anybody, can You create an Ukrainian voice for Espeak?
Thanks alot.
Marco Oros

**Comment by ValdisVitolins** [comment]
General information, how to add language is described in [Adding or Improving a Language](/espeak-ng/espeak-ng/blob/master/docs/add_language.md).
Please note, what issues will you have and I'll try to improve documentation, that it is understandable for beginners. Also I can create initial files and configuration for you, but please note, that without your help, spelling will not be usable much.

**Comment by JRMeyer** [comment]
Hey Marco!

I have been working on adding the Kyrgyz language to eSpeak NG, and I decided to write a tutorial on how to add a new language in general: 

http://jrmeyer.github.io/tutorial/2016/07/03/How-to-Add-a-Language-to-Espeak-NG.html

I hope you find it useful for Українська мова ;) 

-josh

**Comment by Giovani93** [comment]
But, I haven't a linux. I don't know programming. This was only my idea 
and I don't know Ukrainian.
I would like to use ukrainian voice to my experiences.
I would like to explain You. There is another language 'Ruthenian or 
Rusin' in my country. It uses an Ukrainian alphabet. This language is 
ethnical and is used also in eastern parts of Slovakia, where I live. I 
am not Ruthenian, but I heard about another dialect of Ruthenian 
speaking in Vojvodina, which is roughly related to eastern slovak 
dialects. I use also Espeak to experiences with various languages.
Thank You!
Marco Oros

**Comment by ValdisVitolins** [comment]
JRMeyer, I've investigated your experience by adding Kyrgyz language and updated documentation.
https://github.com/ValdisVitolins/espeak-ng/commit/9f8dc78422aa07960fe54c9b672bf6503349526b
Is it more clear now?

**Comment by valdisvi** [comment]
@Giovani93, Ukrainian language is now supported in development version of eSpeak NG. You can test it [online](https://odo.lv/Espeak) and improve it yourself by following [contributor guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md).
