### ISSUE TITLE
Extended tracing of eSpeak NG rules (and other things)

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#146]
While dealing with eSpeak NG issues, only reliable method to trace rule compilation and execution is printing to output. Could another "trace" level be introduced?
E.g. currently I have to synchronize and ignore, while comparing differences, following statements:

```
#include <stdarg.h>
...
static int traceLogCount;
static int traceLevel = 4;

void trace(int level, const char * format, ...) {
    if (level <= traceLevel) {
        char pad[20] = {""};
        for (int i=0; i<level; i++)
          strcat(pad, "⏵");
        traceLogCount++;
        va_list args;
        va_start(args, format);
        printf("%s %d. ", pad, traceLogCount);
        vprintf(format, args);
        va_end(args);
    }
}

void tracefile(int level, char *memo, FILE *file) {
    if (level <= traceLevel) {
        trace(level, memo);
        //fflush(file);
        printf("«%s»\n", file->_IO_write_base);
        trace(level, "\n");
    }
}
...
trace(1, "espeak_ng_CompilePhonemeData\n");
...
trace(2, "i:%d\n", i);
...
```

If similar approach seems sane and reasonable, I could add such changes, which would make my synchronization much easier with upstream project.

**Comment by rhdunn** [comment]
Ideally, I don't want to litter the code with trace statements. The espeak codebase had something similar, but this made it harder to read and maintain the code. The problem I have with this is that typically what you need to trace varies depending on the problem you are debugging.
