### ISSUE TITLE
bad pronunciation of "unary"

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#148]
Hello,
From http://bugs.debian.org/830731 : 

“
espeak pronunces "unary" as:
[[Vn'A@r-i]]

I believe the correct pronunciation is:
[[j'un@ri]]
”

This happens with espeak-ng too.

**Comment by ValdisVitolins** [comment]
Fixed in commit: https://github.com/ValdisVitolins/espeak-ng/commit/dda8f25e4ca73a187f775efcf8219b4ff4fe60fb
