### ISSUE TITLE
EWMH, UCS, UTF, UUID acronyms

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#149]
Hello,

From http://bugs.debian.org/830730 : 

“
These acronyms are currently not pronounced correctly:
EWMH, UCS, UTF, UUID
”

A proposed patch was submitted:
[espeak-abbrev.diff.txt](https://github.com/espeak-ng/espeak-ng/files/466117/espeak-abbrev.diff.txt)

**Comment by ValdisVitolins** [comment]
Fixed in https://github.com/ValdisVitolins/espeak-ng/commit/fccae1c62f306a800198cadf2b690ec446e19d43
