### ISSUE TITLE
Voice "Alicia" is broken

### ISSUE THREAD

**Issue by djphoenix** [espeak-ng/espeak-ng#1494]
Something changed in core I think, because data file of Alicia was never changed since 2020.
With version from around Jul 31st, it sounds normally.
On current master, I (and users from espeak-ng/espeak-ng-ios-app#16) hear high pitched noise.
I'm not sure what was changed and when... Should we binary search within commits in that date range, or anyone (maybe @jaacoppi as most active committer) have an idea?

**Comment by jaacoppi** [comment]
Git bisect is the correct tool for this.

22ef8b260d435e7f633fe37174407605d8576997 is the first bad commit
commit 22ef8b260d435e7f633fe37174407605d8576997
Author: Yury Popov ***@***.***>
Date:   Sat Sep 17 02:09:52 2022 +0200

    Read8Numbers: Fix zeroing data

My guess is that this change to Read8Numbers is okay but one of the voice options using it has a bug.

**Comment by djphoenix** [comment]
The first thought was "oh gosh, that was me?" haha

OK, let's dig into it again...

**Comment by djphoenix** [comment]
Hm, looks like `breathw` in Alicia is 6-number, not 8...

**Comment by djphoenix** [comment]
And hell yes, when I add two remaining as "600 600" (see [voices.c#L289](https://github.com/espeak-ng/espeak-ng/blob/246f487814784117523dabe27be69f77bc51f2b1/src/libespeak-ng/voices.c#L289)) voice sounds cleanly. The interesting thing that a bug in Read8Numbers was to keep that numbers, and now we (OK, I) fix it...

**Comment by jaacoppi** [comment]
> The first thought was "oh gosh, that was me?" haha
Don't worry. We're dealing with audio so these things happen all the time. 

Can you think of a test to prevent this? Looks like a perfect use case for #1452 . Affects all options using breathw, probably everything using Read8Numbers().

can you check these as well:
```
$ grep -r breathw espeak-ng-data/voices/*
espeak-ng-data/voices/!v/sandro:breathw 255 255 60 180 160 255 255 255
espeak-ng-data/voices/!v/Demonic:breathw 255 255 60 180 160 255 255 255
espeak-ng-data/voices/!v/whisperf:breathw 150 150 200 200 400 400
espeak-ng-data/voices/!v/Alicia:breathw 150 150 200 200 400 400
espeak-ng-data/voices/!v/whisper:breathw 150 150 200 200 400 400
espeak-ng-data/voices/!v/f5:breathw 150 150 200 200 400 400 
```


>

**Comment by djphoenix** [comment]
`brewthw` is documented as "up to 8 numbers". So I'm not sure does we should force it to 8, or (in case of shorter) disable last resonators.

**Comment by djphoenix** [comment]
> can you check these as well

Seems like only Alicia have hearable noise. But I check it with iOS app now, will also check on CLI as open laptop

**Comment by djphoenix** [comment]
So, for other voices:

- `sandro` and `demonic` are properly configured (8 numbers)
- `whisper` and `whisperf` are normally handled because number of `breath` and `breathw` are equals (6 both)
- `f5` is unaffected (count of `breath` and `breathw` mismatches, but renders normally for some reason)
- `alicia` is broken

So my proposal to fulfill `f5` and `alicia` to defaults (600 600) to fix Alicia and avoid further bugs in `f5`
