### ISSUE TITLE
Audio output chunks not properly separated in single session

### ISSUE THREAD

**Issue by djphoenix** [espeak-ng/espeak-ng#1506]
Maybe some of buffers are not cleaned properly.

_Originally posted by @tspivey in https://github.com/espeak-ng/espeak-ng-ios-app/issues/7#issuecomment-1304433373_

This is easy to reproduce with just espeak-ng, running with espeak -m:

```
<speak><prosody rate="274.46155%"><break time="60ms" />            Untitled 8 <break time="60ms" />            window</prosody></speak>
<speak><prosody rate="274.46155%"><break time="1000ms" /> test</prosody></speak>
```

As soon as you hit enter on the second line, you'll hear a bit of audio at the beginning.

**Comment by sthibaul** [comment]
Perhaps create a test that runs `espeak-ng -m` on this example, and see what valgrind says about it? (unitialized memory, typically)

**Comment by djphoenix** [comment]
OK [let's see](https://github.com/djphoenix/espeak-ng/actions/runs/3405787317) what happens.

**Comment by djphoenix** [comment]
@sthibaul looks like... nothing. Tests are failed with hashes mismatch, but sanitisers are silent.

**Comment by djphoenix** [comment]
Let's look on [synthesized wave](https://user-images.githubusercontent.com/1833493/200193675-649a180c-f98a-40e3-bd91-4acbec5e8069.png) and [zoomed in](https://user-images.githubusercontent.com/1833493/200193692-340823e8-9e81-45d8-a3a6-508d6dac9bdb.png)...

Seems like that's not a dirty buffer, I have not found a copy of that signal.
So I think that this is some case of synthesisers that go sleep from previous phrase and awoken in bad state...

**Comment by djphoenix** [comment]
After some more investigations, I discovered that this behaviour appears only on `</speech><speech>` boundary. Separators like newlines, including timings, does not makes a sense. If I put both `<prosody>` in single `<speech>`, it works as expected.

**Comment by djphoenix** [comment]
Three dirty patches later, I think that I revealed a root cause.

[wavegen.c#L1299](https://github.com/espeak-ng/espeak-ng/blob/34fecbdd4f068feab21916fc0bc8f69b26b00397/src/libespeak-ng/wavegen.c#L1299) - WCMD_PAUSE emits some silence **without** flushing sonic stream, that done in [wavegen.c#L1403](https://github.com/espeak-ng/espeak-ng/blob/34fecbdd4f068feab21916fc0bc8f69b26b00397/src/libespeak-ng/wavegen.c#L1403).

Then, next time that libsonic been invoked, it emits an internal buffer as well...

**Comment by djphoenix** [comment]
Ah, even simpler, looks like speech rate resets to default and sonic SpeedUp is not invoked at all unless new high-speed prosody started.

**Comment by djphoenix** [comment]
Also interesting question: does `prosody rate` should affect length of `break`? With sonic SpeedUp, it does.
