### ISSUE TITLE
Compiling on Arch Linux

### ISSUE THREAD

**Issue by xyproto** [espeak-ng/espeak-ng#151]
Hi,

I'm trying to package espeak-ng 1.49.0 for Arch Linux.

When building, I get error messages like these:

```
Unknown phoneme table: 'en'
Can't read dictionary file: '/home/alexander/archpackages/community/espeak/trunk/src/espeak-ng/espeak-ng-data/en_dict'
```

Attaching PKGBUILD, error.log and output.log in a tarball.

[arch-espeak-ng-2016-09-12.tar.gz](https://github.com/espeak-ng/espeak-ng/files/467048/arch-espeak-ng-2016-09-12.tar.gz)

What am I missing?

Best regards,
Alexander F Rødseth

**Comment by ValdisVitolins** [comment]
I couldn't reproduce this on cleanly cloned repository on version 76e5224545d969adefe8661211e61b2f18a78be1.
I suspect, you have made some build on previous espeak-ng version and have created some folders with **root** user, which can't be created/modified with usual user permissions somewhere during build again.
Please check, your usual user is owner of full tree files and folders in the project.

**Comment by xyproto** [comment]
No, not running as root. Perhaps I have a too strict umask. Will also try building in a chroot.

**Comment by rhdunn** [comment]
If you are building the dictionary file for the first time, it cannot read that file. This is to be expected.

The actual error you have is:

    Error processing file '/home/alexander/archpackages/community/espeak/trunk/src/espeak-ng/espeak-ng-data/temp': No such file or directory.

__NOTE:__ Building the voice and language data does not work when using multiple make jobs. You need to run:

    make -j8 src/espeak-ng src/speak-ng
    make

This is documented in the README file.

**Comment by xyproto** [comment]
That does not solve the issue.

When building with:

    make -j8 src/espeak-ng src/espeak-ng
    make

I get:

```
Compiling: 'bn_extra'
	0 entries
Compiling: 'bn_rules'
	168 rules, 68 groups (67)

Error processing file '/build/espeak/src/espeak-ng/espeak-ng-data/temp': No such file or directory.
cd dictsource && ESPEAK_DATA_PATH=/build/espeak/src/espeak-ng LD_LIBRARY_PATH=../src: ../src/espeak-ng --compile=el && cd ..
	1528 entries
Compiling: 'af_extra'
	0 entries
make[1]: *** [Makefile:1896: espeak-ng-data/cs_dict] Error 1
make[1]: *** Waiting for unfinished jobs....
Compiling: 'af_rules'
	11153 entries
Compiling: 'da_extra'
	0 entries
Compiling: 'da_rules'
	5156 rules, 60 groups (0)

Can't read dictionary file: '/build/espeak/src/espeak-ng/espeak-ng-data/de_dict'
Using phonemetable: 'de'
Compiling: 'de_list'
	653 entries
Compiling: 'de_extra'
	0 entries
Compiling: 'de_rules'
Can't read dictionary file: '/build/espeak/src/espeak-ng/espeak-ng-data/el_dict'
Using phonemetable: 'el'
Compiling: 'el_list'
	379 entries
Compiling: 'el_extra'
	0 entries
Compiling: 'el_rules'
	182 rules, 27 groups (26)

Error processing file '/build/espeak/src/espeak-ng/espeak-ng-data/temp': No such file or directory.
make[1]: *** [Makefile:1908: espeak-ng-data/da_dict] Error 1
Error processing file '/build/espeak/src/espeak-ng/espeak-ng-data/temp': No such file or directory.
make[1]: *** [Makefile:1914: espeak-ng-data/de_dict] Error 1
/bin/sh: line 1:  6052 Segmentation fault      (core dumped) ESPEAK_DATA_PATH=/build/espeak/src/espeak-ng LD_LIBRARY_PATH=../src: ../src/espeak-ng --compile=af
make[1]: *** [Makefile:1848: espeak-ng-data/af_dict] Error 139
make[1]: Leaving directory '/build/espeak/src/espeak-ng'
make: *** [Makefile:502: all] Error 2

```

**Comment by ValdisVitolins** [comment]
When I got strange compilation errors, for me helped `make -B` as Reece suggested elsewhere.

**Comment by rhdunn** [comment]
I'm curious as to why it is saying `espeak-ng-data/temp` is not found. The segfault could be due to the phoneme data being incorrectly built from a previous parallel build, so `make -B` should help there.

**Comment by rhdunn** [comment]
The "Error processing file" message originates from a call to `create_file_error_context` from the failure to open that file.

**Comment by ValdisVitolins** [comment]
Probably you should also check, that there are no files created with **root** user, which you try to rewrite as regular user. (It has happened to me, when I did `sudo make` instead of `sudo make LIBDIR=/usr/lib/x86_64-linux-gnu install`)

**Comment by xyproto** [comment]
Will try the above suggestions, thanks.

I am building in a clean chroot so there should be no root/sudo/permission issues. Will try building on another machine too.

**Comment by fornwall** [comment]
@xyproto Could you check if you have the `MAKEFLAGS` environment variable set? I had set  `MAKEFLAGS=-j4` in ~/.profile which caused this build failure. Running `unset MAKEFLAGS` before building fixed the problem.

**Comment by xyproto** [comment]
Building with `make -j1` solved this issue.
