### ISSUE TITLE
Invalid SSML break duration in prosody

### ISSUE THREAD

**Issue by djphoenix** [espeak-ng/espeak-ng#1512]
See simple example:

```bash
function ssml_test() {
  echo $2 | espeak-ng -m -w$1.wav
}

ssml_test 50_1000ms '<speak><prosody rate="50%">Test<break time="1000ms"/>speech</prosody></speak>'
ssml_test 100_1000ms '<speak><prosody rate="100%">Test<break time="1000ms"/>speech</prosody></speak>'
ssml_test 200_1000ms '<speak><prosody rate="200%">Test<break time="1000ms"/>speech</prosody></speak>'
ssml_test 300_1000ms '<speak><prosody rate="300%">Test<break time="1000ms"/>speech</prosody></speak>'
```

Then real break time measured with markers in audio editor.

- For 50%, it is around 2800ms.
- For 100%, it is exactly one second (of course it is right even if prosody just omitted).
- For 200%, it is around 125ms.
- For 300%, it is around 135ms (it is most strange that faster speed has longer break).

I'm unsure how it should be fixed. Does it expected to be a constant time, or scale linearly with rate?

I have not found a reference should `<break>` time be modified when placed inside `<prosody>` with set `rate`.
But, even if yes or no, seems like it calculated wrong.

**UPD:**
I found a boundary when duration becomes invalid second time, and the winner is `libsonic` again:
- 257% (rate: 449) => 86ms
- 258% (rate: 451) => 160ms

**Comment by jaacoppi** [comment]
I think a brea time specified in ms should not change. Prosody affects rate of speech, not rate of breaks.

SSML code is messy. There are a few other bugs like this in the issue tracker. I don't remember the details any more.

Pause is also complicated. I think pause time is returned by ReadClause() so debugging that might help.

**Comment by beqabeqa473** [comment]
I also think that rate should not affect break time.

If author of text decided that break must be 1000 ms, it should be 1000 ms at any rate
