### ISSUE TITLE
Meaning of "async" espeak mode

### ISSUE THREAD

**Issue by djphoenix** [espeak-ng/espeak-ng#1518]
I mean `configure --with(out)-async` and following `USE_ASYNC` definition.

In all cases that I've found, Synthesize call followed with Synchronize. So asynchronous are not used really. It involves a bunch of code, including FIFO and separate thread. But as we all know, espeak is use a lot of global state variables, so multithreading cannot be used freely.

I propose to clean all pseudo-async stuff, replacing Synchronize with no-op and using synchronous audio output by default. It will simplify a core a lot and make further refactoring much easier.

**Comment by djphoenix** [comment]
But does it really rely on asynchronous? As I know, almost all modern audio APIs work async under the hood (pulseaudio on linux, CoreAudio on macos, oh I unsure about windows) - they have internal buffers that fulfills with no cost and plays as the audio driver becomes ready.

**Comment by sthibaul** [comment]
> But does it really rely on asynchronous?

Yes. For espeakup for instance, without that the user won't be able to interrupt the speech.

> they have internal buffers that fulfills with no cost and plays as the audio driver becomes ready

Yes, and so?
Also, the buffer will get full at some point, and then the audio functions will block.

**Comment by djphoenix** [comment]
> Yes, and so?

Oh, I'm really not trying to push or get rude, of course. Just really trying to understand an objections about async mode. Now I see that many clients use it, and have no much options to avoid or workaround.

However, I want to try to clean up the code to make it simple and easy to improve.

**Comment by sthibaul** [comment]
> > Yes, and so?
> 
> Oh, I'm really not trying to push or get rude, of

Sorry, I didn't mean that. I was just wondering how the buffering of audio APIs would help?
Actually it's even the converse: to get good indexing, one would rather *not* see the audio API buffer a lot. Or at least be able to tell what exactly went on the air (which apparently APIs don't often provide).
