### ISSUE TITLE
Language apparently not supported when using phonemizer

### ISSUE THREAD

**Issue by AlexSteveChungAlvarez** [espeak-ng/espeak-ng#1580]
I get this error when trying to call Quechua language from espeak:
`RuntimeError: language "qu" is not supported by the espeak backend`
But this language is included in my espeak:
`espeak-ng --voices
Pty Language       Age/Gender VoiceName          File                 Other Languages
 5  af              --/M      Afrikaans          gmw/af               
 5  am              --/M      Amharic            sem/am               
 5  an              --/M      Aragonese          roa/an               
 5  ar              --/M      Arabic             sem/ar               
 5  as              --/M      Assamese           inc/as               
 5  az              --/M      Azerbaijani        trk/az               
 5  ba              --/M      Bashkir            trk/ba               
 5  be              --/M      Belarusian         zle/be               
 5  bg              --/M      Bulgarian          zls/bg               
 5  bn              --/M      Bengali            inc/bn               
 5  bpy             --/M      Bishnupriya_Manipuri inc/bpy              
 5  bs              --/M      Bosnian            zls/bs               
 5  ca              --/M      Catalan            roa/ca               
 5  chr-US-Qaaa-x-west --/M      Cherokee_          iro/chr              
 5  cmn             --/M      Chinese_(Mandarin,_latin_as_English) sit/cmn              (zh-cmn 5)(zh 5)
 5  cmn-latn-pinyin --/M      Chinese_(Mandarin,_latin_as_Pinyin) sit/cmn-Latn-pinyin  (zh-cmn 5)(zh 5)
 5  cs              --/M      Czech              zlw/cs               
 5  cv              --/M      Chuvash            trk/cv               
 5  cy              --/M      Welsh              cel/cy               
 5  da              --/M      Danish             gmq/da               
 5  de              --/M      German             gmw/de               
 5  el              --/M      Greek              grk/el               
 5  en-029          --/M      English_(Caribbean) gmw/en-029           (en 10)
 2  en-gb           --/M      English_(Great_Britain) gmw/en               (en 2)
 5  en-gb-scotland  --/M      English_(Scotland) gmw/en-GB-scotland   (en 4)
 5  en-gb-x-gbclan  --/M      English_(Lancaster) gmw/en-GB-x-gbclan   (en-gb 3)(en 5)
 5  en-gb-x-gbcwmd  --/M      English_(West_Midlands) gmw/en-GB-x-gbcwmd   (en-gb 9)(en 9)
 5  en-gb-x-rp      --/M      English_(Received_Pronunciation) gmw/en-GB-x-rp       (en-gb 4)(en 5)
 2  en-us           --/M      English_(America)  gmw/en-US            (en 3)
 5  en-us-nyc       --/M      English_(America,_New_York_City) gmw/en-US-nyc        
 5  eo              --/M      Esperanto          art/eo               
 5  es              --/M      Spanish_(Spain)    roa/es               
 5  es-419          --/M      Spanish_(Latin_America) roa/es-419           (es-mx 6)(es 6)
 5  et              --/M      Estonian           urj/et               
 5  eu              --/M      Basque             eu                   
 5  fa              --/M      Persian            ira/fa               
 5  fa-latn         --/M      Persian_(Pinglish) ira/fa-Latn          
 5  fi              --/M      Finnish            urj/fi               
 5  fr-be           --/M      French_(Belgium)   roa/fr-BE            (fr 8)
 5  fr-ch           --/M      French_(Switzerland) roa/fr-CH            (fr 8)
 5  fr-fr           --/M      French_(France)    roa/fr               (fr 5)
 5  ga              --/M      Gaelic_(Irish)     cel/ga               
 5  gd              --/M      Gaelic_(Scottish)  cel/gd               
 5  gn              --/M      Guarani            sai/gn               
 5  grc             --/M      Greek_(Ancient)    grk/grc              
 5  gu              --/M      Gujarati           inc/gu               
 5  hak             --/M      Hakka_Chinese      sit/hak              
 5  haw             --/M      Hawaiian           map/haw              
 5  he              --/M      Hebrew             sem/he               
 5  hi              --/M      Hindi              inc/hi               
 5  hr              --/M      Croatian           zls/hr               (hbs 5)
 5  ht              --/M      Haitian_Creole     roa/ht               
 5  hu              --/M      Hungarian          urj/hu               
 5  hy              --/M      Armenian_(East_Armenia) ine/hy               (hy-arevela 5)
 5  hyw             --/M      Armenian_(West_Armenia) ine/hyw              (hy-arevmda 5)(hy 8)
 5  ia              --/M      Interlingua        art/ia               
 5  id              --/M      Indonesian         poz/id               
 5  io              --/M      Ido                art/io               
 5  is              --/M      Icelandic          gmq/is               
 5  it              --/M      Italian            roa/it               
 5  ja              --/M      Japanese           jpx/ja               
 5  jbo             --/M      Lojban             art/jbo              
 5  ka              --/M      Georgian           ccs/ka               
 5  kk              --/M      Kazakh             trk/kk               
 5  kl              --/M      Greenlandic        esx/kl               
 5  kn              --/M      Kannada            dra/kn               
 5  ko              --/M      Korean             ko                   
 5  kok             --/M      Konkani            inc/kok              
 5  ku              --/M      Kurdish            ira/ku               
 5  ky              --/M      Kyrgyz             trk/ky               
 5  la              --/M      Latin              itc/la               
 5  lb              --/M      Luxembourgish      gmw/lb               
 5  lfn             --/M      Lingua_Franca_Nova art/lfn              
 5  lt              --/M      Lithuanian         bat/lt               
 5  ltg             --/M      Latgalian          bat/ltg              
 5  lv              --/M      Latvian            bat/lv               
 5  mi              --/M      Māori             poz/mi               
 5  mk              --/M      Macedonian         zls/mk               
 5  ml              --/M      Malayalam          dra/ml               
 5  mr              --/M      Marathi            inc/mr               
 5  ms              --/M      Malay              poz/ms               
 5  mt              --/M      Maltese            sem/mt               
 5  my              --/M      Myanmar_(Burmese)  sit/my               
 5  nb              --/M      Norwegian_Bokmål  gmq/nb               (no 5)
 5  nci             --/M      Nahuatl_(Classical) azc/nci              
 5  ne              --/M      Nepali             inc/ne               
 5  nl              --/M      Dutch              gmw/nl               
 5  nog             --/M      Nogai              trk/nog              
 5  om              --/M      Oromo              cus/om               
 5  or              --/M      Oriya              inc/or               
 5  pa              --/M      Punjabi            inc/pa               
 5  pap             --/M      Papiamento         roa/pap              
 5  piqd            --/M      Klingon            art/piqd             
 5  pl              --/M      Polish             zlw/pl               
 5  pt              --/M      Portuguese_(Portugal) roa/pt               (pt-pt 5)
 5  pt-br           --/M      Portuguese_(Brazil) roa/pt-BR            (pt 6)
 5  py              --/M      Pyash              art/py               
 5  qdb             --/M      Lang_Belta         art/qdb              
 5  qu              --/M      Quechua            qu                   
 5  quc             --/M      K'iche'            myn/quc              
 5  qya             --/M      Quenya             art/qya              
 5  ro              --/M      Romanian           roa/ro               
 5  ru              --/M      Russian            zle/ru               
 2  ru-lv           --/M      Russian_(Latvia)   zle/ru-LV            
 5  sd              --/M      Sindhi             inc/sd               
 5  shn             --/M      Shan_(Tai_Yai)     tai/shn              
 5  si              --/M      Sinhala            inc/si               
 5  sjn             --/M      Sindarin           art/sjn              
 5  sk              --/M      Slovak             zlw/sk               
 5  sl              --/M      Slovenian          zls/sl               
 5  smj             --/M      Lule_Saami         urj/smj              
 5  sq              --/M      Albanian           ine/sq               
 5  sr              --/M      Serbian            zls/sr               
 5  sv              --/M      Swedish            gmq/sv               
 5  sw              --/M      Swahili            bnt/sw               
 5  ta              --/M      Tamil              dra/ta               
 5  te              --/M      Telugu             dra/te               
 5  th              --/M      Thai               tai/th               
 5  tk              --/M      Turkmen            trk/tk               
 5  tn              --/M      Setswana           bnt/tn               
 5  tr              --/M      Turkish            trk/tr               
 5  tt              --/M      Tatar              trk/tt               
 5  ug              --/M      Uyghur             trk/ug               
 5  uk              --/M      Ukrainian          zle/uk               
 5  ur              --/M      Urdu               inc/ur               
 5  uz              --/M      Uzbek              trk/uz               
 5  vi              --/M      Vietnamese_(Northern) aav/vi               
 5  vi-vn-x-central --/M      Vietnamese_(Central) aav/vi-VN-x-central  
 5  vi-vn-x-south   --/M      Vietnamese_(Southern) aav/vi-VN-x-south    
 5  yue             --/M      Chinese_(Cantonese) sit/yue              (zh-yue 5)(zh 8)
 5  yue             --/M      Chinese_(Cantonese,_latin_as_Jyutping) sit/yue-Latn-jyutping (zh-yue 5)(zh 8)`
I don't know what to do, it works in another computer, but now I only have access to this one and it doesn't work. Building v1.51(latest) was tricky on both computers.

**Comment by jaacoppi** [comment]
> `RuntimeError: language "qu" is not supported by the espeak backend`

This is not an espeak-ng error. What software are you using? How are you trying to run espeak-ng? My guess is the software you're using has a different version of espeak or espeak-ng installed.

Here's how to check that the language works in espeak-ng:

 $ espeak-ng --version
eSpeak NG text-to-speech: 1.51.1  Data at: /usr/share/espeak-ng-data

$ espeak-ng -v qu "1 2 3"  -x
h'uk 'iskaj k'imsa

**Comment by jaacoppi** [comment]
> Yes, it works in espeak-ng, I am trying to train on this model: https://github.com/DigitalPhonetics/IMS-Toucan

Have you tried other languages? If all languages fail there's probably a configuration error with the data directory (/usr/share/espeak-ng-data in my previous example).

**Comment by AlexSteveChungAlvarez** [comment]
RuntimeError: language "en-us" is not supported by the espeak backend you are right, even with English fails! How can I fix this?

**Comment by jaacoppi** [comment]
Since espeak-ng works but the other project doesn't I guess you're better off asking them how they've configured it.

**Comment by AlexSteveChungAlvarez** [comment]
The other project works in my laptop (just tried setting all up last night) and in another computer (which I can't use everyday), only in this PC it doesn't, it had another version of espeak-ng installed previously which I deleted because it didn't let the 1.51 be recognised...Any ideas? 
Maybe I removed something I didn't have to, so when I reinstall, it doesn't gets installed (it happened already with the espeak-ng-data directory located in /usr/local/share, I deleted it by accident and it didn't appear there again when reinstalling espeak-ng 1.51, so I had to move manually the directory from source)...Or maybe I have to make something manually in the installation of espeak because of that problematic previous version...I can't use my laptop since it has another problem related to memory....

**Comment by GoArsenal** [comment]
Have you solved the problem? 

> The other project works in my laptop (just tried setting all up last night) and in another computer (which I can't use everyday), only in this PC it doesn't, it had another version of espeak-ng installed previously which I deleted because it didn't let the 1.51 be recognised...Any ideas? Maybe I removed something I didn't have to, so when I reinstall, it doesn't gets installed (it happened already with the espeak-ng-data directory located in /usr/local/share, I deleted it by accident and it didn't appear there again when reinstalling espeak-ng 1.51, so I had to move manually the directory from source)...Or maybe I have to make something manually in the installation of espeak because of that problematic previous version...I can't use my laptop since it has another problem related to memory....

**Comment by AlexSteveChungAlvarez** [comment]
No, I didn't. I uninstalled my Ubuntu and installed Windows11 instead. It's working well now with that OS. I never figured out what was happening with the Ubuntu I had...

**Comment by zaherweb** [comment]
I fixed this problem by just installing Espeak 
from this link https://espeak.sourceforge.net/download.html
