### ISSUE TITLE
some variants created by me

### ISSUE THREAD

**Issue by gregodejesus** [espeak-ng/espeak-ng#1581]
Hello. I leave the updates of the variants. Some improvements were made in the voices. Added the doctordennys variant 4, this is the last update of the variants. I leave them at your disposal.
Update. from the folder.
[all.eSpeak.variants.zip](https://github.com/espeak-ng/espeak-ng/files/10332209/all.eSpeak.variants.zip)

**Comment by gregodejesus** [comment]
Hello, I leave this pack of variants. I modified some parameters to add more natural. Some variants created by me, and some NVDA defaults.
[voices.zip](https://github.com/espeak-ng/espeak-ng/files/10202639/voices.zip)
this is the last update so that after they don't go into confutions.
Bye.

**Comment by Turkrosoft** [comment]
Uh, I'd love that the archive contain only the voices modified or made by you. By the way, the variants are awesome and should be added to official releases. You know, some are already modified versions of my variants, so it'd be great if both your and my variants were included. One thing is, I would make a second variant for Sonya with higher pitch and inflection values as found in the attached archive. I also made a second variant of Sandy to make it better resemble ETI Eloquence Sandy's pitch/inflection. You might also want it to replace variant 1.
[Second variants for Sandy and Sonya.zip](https://github.com/espeak-ng/espeak-ng/files/10272666/Second.variants.for.Sandy.and.Sonya.zip)

**Comment by Turkrosoft** [comment]
So here's an archive with all the necessary renaming and editing needed to let the original non-klatt versions of my variants and the modified klatt versions coexist, as well as the other variants you've made and my modified versions, along with one more variant (evil) that I made a while ago.
[New variants by Turkrosoft and gregodejesus.zip](https://github.com/espeak-ng/espeak-ng/files/10272812/New.variants.by.Turkrosoft.and.gregodejesus.zip)

**Comment by Turkrosoft** [comment]
And here's yet another variant that I've just made by modifying kit1
[kit5.zip](https://github.com/espeak-ng/espeak-ng/files/10273202/kit5.zip)
.

**Comment by Turkrosoft** [comment]
Here is the whole !v folder with new variants made today.
[All variants.zip](https://github.com/espeak-ng/espeak-ng/files/10280081/All.variants.zip)

**Comment by alex19EP** [comment]
just FYI. you need to create pull request to make this new voices available in espeak-ng's next release.

**Comment by Turkrosoft** [comment]
Thanks for the explanation… I have still been working on improving the variants and adding new ones. Also, it’s always better to let everyone test anything new before trying to incorporate it into an official release.

Thanks,

Enes


Windows için Posta ile gönderildi

Kimden: Alexander Epaneshnikov
Gönderilme: 22 Aralık 2022 Perşembe 16:09
Kime: espeak-ng/espeak-ng
Bilgi: Turkrosoft; Comment
Konu: Re: [espeak-ng/espeak-ng] some variants created by me (Issue #1581)

just FYI. you need to create pull request to make this new voices available in espeak-ng's next release.

**Comment by gregodejesus** [comment]
Great. The folder with all the variants is in order, it would be good for these voices to be added to the upcoming e Speak ng releases. Here the edward variant with some improvements, this variant was originally made with klatt 5, but I replaced klatt 5 by klatt 6 making it similar to klatt 5 but with good quality, the last format 4 value I dropped it to 15, sounds pretty good. Thus we would have edward with a noticeable and intelligible quality, and edward 2, the same as always. I leave the code available to anyone who wants it. In updates it would be all

language variant
name Edward
klatt 6
voicing 100
consonants 70 80

formant 1 92 100 130
formant 2 103 100 80
formant 3 103 100 70
formant 4 114 100 15

**Comment by gregodejesus** [comment]
I want to thank turkrosoft for seeing the variants in order and also for aver included mine and some other new ones created by turkrosoft. Also to say that if these variants were added in future versions of speak, if it were to be specified, it would be a great breakthrough, since in NVDA the variants that match by default like the max variant sound metal and noisy, making for the ear they sound upset and There are people who cannot continue using e Speak for the same. Thanks to the arrival of the Speech Player klatt 6 and its variants do not pass this. They sound a lot more pleasant in the ear and more intelligible. Greetings from chili.

**Comment by gregodejesus** [comment]
well here I leave all the variants available, (a second folder) All variants 2 or 3 are klatt variants.

**Comment by alex19EP** [comment]
I plan to make new release by the end of the year. if you want this new voices to be included please make a pull request.

if you don't know how to do that look at [github docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests)

**Comment by gregodejesus** [comment]
> perfect alex 19, this would be a great speak cabinet, then I hope the release of speak with the changes for NVDA and for android. then I hope the release of speak with the changes for NVDA and for android. To say this would be the last update of the voices

**Comment by gregodejesus** [comment]
I left three new variants available. eddy, I tried to make it the most intelligible to the ear. Edith, it's the eddy counterpart and finally, jose.
