### ISSUE TITLE
How can I build a Persian dictionary for CMUsphinx?

### ISSUE THREAD

**Issue by rezaee** [espeak-ng/espeak-ng#160]
Hi
At first, I want to know is there any Persian dictionary with it's pronunciation to using with CMUsphinx to build Persian language model?
If there isn't, how can I build one? I want to build a simple command-control like system with pocketsphinx at first, and extend it to a complete speech system later.
I'm following this tutorial and I want a Persian dictionary for that: http://cmusphinx.sourceforge.net/wiki/tutorialdict

Thank you in Advanced!

**Comment by rhdunn** [comment]
This is not the CMUsphinx project. Also, espeak-ng does not support the CMUsphinx language models, so that will not work either.

**Comment by rezaee** [comment]
Thanks rhdunn
How can I find all of the Farsi phonetics?
I mean for example 
 'alef ا
 b'e: ب
 ?p'e: پ
 t'e: ت
 s'e: ث

All of these, where can I find them?

**Comment by drTonyRobinson** [comment]
Wikipedia is almost always the best place to start for any phoneme set https://en.m.wikipedia.org/wiki/Persian_phonology

Tony

________________________________
