### ISSUE TITLE
I may not differentiate between the letter r and l in Spanish

### ISSUE THREAD

**Issue by gregodejesus** [espeak-ng/espeak-ng#1612]
Hello. I explain my problem to you that when I am spelling a word, the letter r in Spanish the eSpeak pronounces it as ere, and there are times that I have to put the synthesizer slow to be able to differentiate it, being that in Spanish do not miss this, the letter r is deviated to pronounce the fonema of the speak (if it is lyrics) as erre, and not as a single letter, as it currently does. There are ways to edit this phonema, if so what are the steps I should follow?
Thank you very much, I would like to improve this, since I am not the only person who complains about thisinconvenience with e Speak, I have a friend who also has the same

**Comment by jaacoppi** [comment]
You can debug the pronunciation rules with -X like this:
```
$ espeak-ng -v es -X "r"
Found: 'r' [Ere]  
'E**e
```

Then checkout the list of rules in dictsource/es_list and es_rules. This one can be found on line 287 in es_list like this:
```
$ grep -n r dictsource/es_list
287:r	ERRe

Edit that line and recompile. Documentation can be found in docs/. Start with building.md and dictionary.md

```

**Comment by rmcpantoja** [comment]
@gregodejesus Hi! Just a few commits back in the main repository is a fix for that. Now the letter r is pronounced as "eRRe" and not "eRe", and it will be a nice improvement to Spanish when the espeak-ng version is officially released. It may be information from the pull request I made [here](https://github.com/espeak-ng/espeak-ng/pull/1517). In the meantime, use the new es_dict file from this repository in the master branch, and paste it into the espeak-ng-data folder of some project; for example, it may be the same espeak-ng compiled for NVDA.

**Comment by gregodejesus** [comment]
> Hello. I can't find the new file is dictat to download

**Comment by rmcpantoja** [comment]
@gregodejesus Try this: https://github.com/rmcpantoja/espeak-ng/releases/download/1.51.1/es_dict

**Comment by gregodejesus** [comment]
Thank you very much. I downloaded it.
Now that improvements are being made in the pronunciation both in latinamerica spanish and spanish, I am trying to make improvements in the score com, the code would be like that.
tunes s6 c5 q6 e6
I write this here. Now I have a problem. It turns out that when I'm reading a text and when there's a parenthesis, it's going on long and doesn't respect the score, that is, it doesn't pause. Any way to fix this?
