### ISSUE TITLE
How to get source index using TextToPhonemes()

### ISSUE THREAD

**Issue by arcln** [espeak-ng/espeak-ng#1614]
Hi,

I am using `TextToPhonemes()` to translate text into IPA.
I would like to be able to match the input string with the output IPA.

For example, given the english word "syllable" which translates to "sɪləbəl".
I would like to know which IPA phoneme code is associated with which input character.
I am thinking about an output like : `s[s] y[ɪ] ll[l] a[ə] b[b] le[əl]`.

I know this is not implemented, but I am willing to develop this feature for a personal project.
I've tried digging into the codebase but it seems there is a LOT of complexity and it doesn't seem easy to implement.

My questions are: How hard would it be ? Is there a generic function I can hook into or do I need to put pieces of code everywhere in the translation journey ? Can someone point me into the right direction ? Would you accept a PR for this feature ?

Have a nice day

**Comment by jaacoppi** [comment]
It's a bit tricky because the rules system looks at the complete sentence instead of single letters.

You can start expereimenting with --sep and -X like this:
```
$ espeak-ng -x syllable --sep="|" --ipa=2
sˈɪləbə͡l
$ espeak-ng -x syllable --sep="|" --ipa
s|ˈɪ|l|ə|b|əl
$ espeak-ng -x syllable --sep="|"
s|'I|l|@|b|@L
```
Looks like there's a bug that causes the separator to not work with ipa=2.

After that, you can see which rules affect the outcome:

```
Translate 'syllable'
  1	s        [s]

 20	C) y     [I]
  1	y        [j]
 20	y (C     [I]
 33	y (CC    [I]
 26	_s) y    [I]
 23	XC) y    [aI]
 24	_C) y    [aI]

  1	l        [l]
 20	l (C     [l]
 43	y) ll    [l]

118	&) able (_S4eiv  [@b@L]
 78	able     [eIb@L]
  1	a        [a]

Translate 'syll'
  1	s        [s]

 20	C) y     [I]
  1	y        [j]
 20	y (C     [I]
 33	y (CC    [I]
 26	_s) y    [I]
 23	XC) y    [aI]
 24	_C) y    [aI]

  1	l        [l]
 20	l (C     [l]
 43	y) ll    [l]

s|'I|l|@|b|@L
```

**Comment by arcln** [comment]
Thank you very much, that solved my problem.
