### ISSUE TITLE
[French] cerf should be pronounced sεʁ  and not sεʁf

### ISSUE THREAD

**Issue by Shallowmallow** [espeak-ng/espeak-ng#163]
The most common pronunciation for 'cerf'  is sεʁ
(  sεʁf exists but it is a regionalism)
which helps to distinguish from the word 'serf' pronounced sεʁf

**Comment by ValdisVitolins** [comment]
I could fix this, but I have some questions:
1. Is this word flexible?
1. Shouldn't final f actually be pronounced as quiet __h__ (e.g. `espeak-ng -vfr "[[s'Erh.]]"` (maybe more quiet as espeak says it).

**Comment by ValdisVitolins** [comment]
I used words from LibreOffice spellcheck dictionary and Google Translate as example to check that 
```
cerf.
entre-nerf.
nerf.
serf.
```
are spelled more or less appropriately.

**Comment by Shallowmallow** [comment]
Sorry I didn't answer you.
2. Can it be described as common rule for similar set of words?  
Yes. In nerf you don't pronounce the "f".
 (serf is the exception where you pronounce the "f")
But, for words  that are shorts for other words, like "perf"  for performance you pronounce  the "f".

so, cerf and nerf, you don't pronounce te "f"
in perf and serf , you do.
I cannot thing of other words that end with "erf"

3 Shouldn't final f actually be pronounced as quiet h (e.g. espeak-ng -vfr "[[s'Erh.]]"
I'm unable to tell you

**Comment by ValdisVitolins** [comment]
Yes, "silent h" at the end was unnecessary. Now espeauk-ng says:
```
espeak-ng -x -vfr "Cerf, entre-nerf, ner, serf."
 s'Er
 A~trn'Er
 n'Er
 s'Er
```
where r is (meant to be) [ʁ](https://en.wikipedia.org/wiki/Voiced_uvular_fricative).

**Comment by valdisvi** [comment]
Look also at [comments in mailing list](https://groups.io/g/espeak-ng/topic/4462798#490)
