### ISSUE TITLE
System restart occurs, "your data may be corrupt"

### ISSUE THREAD

**Issue by Noitarud** [espeak-ng/espeak-ng#1630]
I plugged the headphones in to listen to something and an application that had speaking running caused the speaking to begin. I then started VLC to listen to music assuming eSpeak  would stop because apps normally cut each other off. However both ran together, and I thought it was funny being able to listen to two things together for the first time. After maybe 30s the system shuts down (shows Lenovo logo, it is a TB-X505F), Android 10 begins to start and am given the "Android recovery" screen. I tell it to "try again". It starts. I tell the speaking app to speak again and (maybe) 10s later the same occurs. I have not done it a third time.

**Comment by Noitarud** [comment]
Has not happened since.

**Comment by jaacoppi** [comment]
Let's reopen if this can be duplicated.

**Comment by Noitarud** [comment]
It did do it again but this time was using [https://github.com/AndBible/and-bible](➤Bible Reader) v4.0.651 and was looking at the android dropdown notification list (since this app was updating notification text to what was presently being read) when it happened. Maybe 30s elapsed.

Model:  Lenovo TB-X505F
Android:  10 (API 29)
Security Patch:  2021-07-05
Build:  TB-X505F_S001142_210804_ROW
Kernel:  4.9.205-perf+
WebView Provider:  com.google.android.webview
WebView Version:  94.0.4606.61
System Available Memory:  450.42 MiB
System Total Memory:  1,864.02 MiB

**Comment by Noitarud** [comment]
I tried again some times more, it did it again after I plugged in my OTG cable + Ethernet adaptor. Again not a reliable trigger.

**Comment by Noitarud** [comment]
@jaacoppi would you like to test it with that Bible program? Maybe it does not like being constantly loaded with phrases (assumed action). Give it a minute.

**Comment by jaacoppi** [comment]
Sorry, I don't have time to test this. I don't know if the problem is in espeak-ng or somewhere else.
