### ISSUE TITLE
Link to Mbrola Windows Download Doesn't Work

### ISSUE THREAD

**Issue by GameDungeon** [espeak-ng/espeak-ng#1632]
Currently, the [documentation ](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md#windows-installation) links to this http://www.tcts.fpms.ac.be/synthesis/mbrola/bin/pcwin/MbrolaTools35.exe in the Mbrola install page. This link does not work for me.

**Comment by jaacoppi** [comment]
Closing as duplicate.
