### ISSUE TITLE
espeak ng stops working in android OS

### ISSUE THREAD

**Issue by haruncetinkaya306** [espeak-ng/espeak-ng#1639]
Espeak ng synthesizer stops working in Android 8.1.0.

**Comment by qkqsb** [comment]
@haruncetinkaya306 More information is needed. What specifically doesn't work? How did you test this? Where did you install the app from? Etc.

**Comment by joshknnd1982** [comment]
I also don't see new variants like Reed, and Mike2. Please update android espeak ng to the latest version.

**Comment by haruncetinkaya306** [comment]
@qkqsb I downloaded the application from the Playstore. I use it without problems when the screen is on, but after turning off the screen, after 5-10 minutes have passed, when I turn on the screen again, I see that it has returned to the previous installed synthesizer.

**Comment by alex19EP** [comment]
hello @haruncetinkaya306 there is no official espeak-ng app in google play yet.

can you try apk from hour release section on github?

**Comment by haruncetinkaya306** [comment]
@alex19EP
Sorry, I thought github was developing the application that is on playstore, I downloaded it from github and started testing it.

**Comment by haruncetinkaya306** [comment]
I am having the same problem here.

**Comment by alex19EP** [comment]
hmm. we need more info. what your phone model and android version?

**Comment by haruncetinkaya306** [comment]
@alex19EP
Samsung SM-A 260 F, Android 8.1.0.

**Comment by alex19EP** [comment]
o it's not a very powerful phone. there is a memory leak in espeak-ng on android, maybe it's because of this. also you can try to disable battery optimization for espeak-ng in your phone settings.
