### ISSUE TITLE
Voicing Delay After Dot-Separated Sentences for Turkish

### ISSUE THREAD

**Issue by SeanTolstoyevski** [espeak-ng/espeak-ng#1648]
Hi all community,

Currently, in Espeak Turkish, if there is a period/dot sign after a sentence and the new sentence starts with a space (space, newline), it reads by combining two sentences.
**note 1**: it happens when the sentence after this point starts with a lowercase letter.

example 1[tr]:
eve gidiyorum. iki ekmek aldım.

espeak output like:
eve gidiyorum iki ekmek aldım.

Expected / wanted:
eve gidiyorum (few ms delay) iki ekmek aldım.

like:
Eve gidiyorum. İki ekmek aldım.

Is this possible of implementation for Turkish language rule?

**Comment by SeanTolstoyevski** [comment]
No need for sapi5. this also exists when using command-line.

**Comment by joshknnd1982** [comment]
But without sapi5 support, how can I use espeak ng with Jim Kitchen’s audio games?

**Comment by alex19EP** [comment]
@joshknnd1982 please don't spam with unrelated comments.

**Comment by jaacoppi** [comment]
> **note 1**: it happens when the sentence after this point starts with a lowercase letter.
> 
> Is this possible of implementation for Turkish language rule?

It's default for all languages. After a dot (or other sentence ending punctuation like ! or ?), a new sentence starts with an upper case letter. 

See lowercaseSentence in docs/voices.md.


Examples:
$ espeak-ng -x "hello. new sentence"
***@***.***'oU nj'u: ***@***.***

$ espeak-ng -x "hello. New sentence"
***@***.***'oU
nj'u: ***@***.***

$ espeak-ng -x -v tr "eve gidiyorum. iki ekmek aldım."
ev'E Jid'ijo*Um ik'I Ekm'Ek ***@***.***

$ espeak-ng -x -v tr "eve gidiyorum. Iki ekmek aldım."
ev'E Jid'ijo*Um
@k'I Ekm'Ek ***@***.***

-- 
Juho Hiltunen

**Comment by SeanTolstoyevski** [comment]
hi @jaacoppi ,

I see.

I'm closing this

Many thanks for your explanations.
