### ISSUE TITLE
espeak ng crashing on android

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#1659]
espeak ng is crashing frequently on my samsung galaxy a14. the android logs are attached.
[logs.zip](https://github.com/espeak-ng/espeak-ng/files/10786431/logs.zip)

**Comment by alex19EP** [comment]
please provide the following information:

* android version
* espeak-ng app version
* where the app was downloaded from.

**Comment by joshknnd1982** [comment]
I can provide my exact androoid logs. 
[logs.zip](https://github.com/espeak-ng/espeak-ng/files/10818188/logs.zip)

**Comment by joshknnd1982** [comment]
sorry I meant android logs

**Comment by alex19EP** [comment]
thank you for the logs but please answer my previous questions.

**Comment by joshknnd1982** [comment]
android version: 13. espeak ng app version: 1.5 2.0.1. the app was customised by Ken Perry in his free time. he sent it to me in a private email because I wanted those extra variants like espeak ng Glenn, bobby, betty, baby, and so on, on my android phone and so he customised it for me and others wanting those variants.

**Comment by aryanchoudharypro** [comment]
I also want to try it

**Comment by aryanchoudharypro** [comment]
How can I get those extra variants you mentioned

**Comment by joshknnd1982** [comment]
You can get the extra variants from this file. or and from this APK by installing it on your android phone. 
[espeaknewvariants.zip](https://github.com/espeak-ng/espeak-ng/files/10833679/espeaknewvariants.zip)

**Comment by joshknnd1982** [comment]
and here is the new android APK. though it has some crashing issues here and there that Ken Perry has not been able to figure out yet. 
https://drive.google.com/file/d/1-9HPB3wuMCPfOnrLFuxqn3cLGOzca4Zl/view?usp=sharing

**Comment by aryanchoudharypro** [comment]
It will be awesome if these changes can be added to the official e speak
reportery

**Comment by joshknnd1982** [comment]
espeak ng is still crashing on android, and the new variants still don't work in Ken's espeak apk file. here once more are the new variants I want in the android espeak ng version. also the bug where espeak randomly switches languages needs fixed. thanks. variants zip file attached to this comment. 
[espeaknewvariants.zip](https://github.com/espeak-ng/espeak-ng/files/10910113/espeaknewvariants.zip)

**Comment by joshknnd1982** [comment]
is anyone still monitoring this issue? Has anyone found out why espeak ng is crashing on android and do you have a fix for it? And can you please update the APK to the latest espeak ng and include the new variants?

**Comment by beqabeqa473** [comment]
Hello.

Please try espeak from the latest codebase withot modifications and in case of crashes provide adb logcat output here

**Comment by alex19EP** [comment]
https://cloud.alex19ep.me/s/Mcjka3GH6NdNwjq

**Comment by joshknnd1982** [comment]
So far no crashes. It is working good. Also, keeping in mind that I am unfamiliar with android development and I can only do some very basic Jaws scripting... Would it be possible for you to talk me through customising that espeak APK with the new variants from this attached zip file? These new variants make espeak sound much better. Most are based on klatt6 or nv speech player included in espeak ng. 
[espeaknewvariants.zip](https://github.com/espeak-ng/espeak-ng/files/10944780/espeaknewvariants.zip)

**Comment by joshknnd1982** [comment]
all I know is that I would need android studio for windows.

**Comment by alex19EP** [comment]
> So far no crashes. It is working good.

expected that.

> Would it be possible for you to talk me through customising that espeak APK with the new variants from this attached zip file?

sorry no time for that.

> These new variants make espeak sound much better. Most are based on klatt6 or nv speech player included in espeak ng.

those who made these voices should make a pr to the repository.

**Comment by joshknnd1982** [comment]
I helped make the voices. So how do I make a pr?

**Comment by alex19EP** [comment]
read github documentation.
