### ISSUE TITLE
Fails to build on big-endian architectures

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#166]
Hello,

On big-endian architectures, one gets:
Unsupported spectral file format.

It indeed seems spect.c does not care about endianness.
The attached patch fixes this.
[big-endian.txt](https://github.com/espeak-ng/espeak-ng/files/579603/big-endian.txt)

Samuel

**Comment by rhdunn** [comment]
I have applied this patch, thanks.

Does this mean that the espeak-ng data now works in an architecture independent way (meaning it does not need to be stored in /lib)?

**Comment by sthibaul** [comment]
No, this patch is only about the spectral data. Notably, phondata, phonindex, and phontab are still endian-specific.

BTW, it seems like the code producing _phtrans files puts random bytes at the end of the file, and the code producing the phondata file puts random values throughout.  I'm attaching here a patch to fix this. It actually seems to be fixing a real bug: see the "peak" loop, it is using "ix" as index inside klatt_ap and klatt_bp, instead of "peak".

[reproducible.txt](https://github.com/espeak-ng/espeak-ng/files/588148/reproducible.txt)
