### ISSUE TITLE
Error trying to build latest stable release (espeak-ng 1.51)

### ISSUE THREAD

**Issue by vanfanel** [espeak-ng/espeak-ng#1665]
Hi there,

I'm trying to build latest stable espeak-ng version on Debian 11 Stable, but I get this:
```

src/libespeak-ng/compiledata.c:38:10: fatal error: dictionary.h: No such file or directory
   38 | #include "dictionary.h"               // for strncpy0
      |          ^~~~~~~~~~~~~~
```

I have tried to configure for a minimal build like this:
```

./configure --without-extdict-ru --without-extdict-cmn --without-extdict-yue --without-gradle\
--without-mbrola --without-klatt --without-sonic --without-speechplayer
```

...But the errors persist and I don't know where "dictionary.h" should come from...

Any help would be welcome, thanks!

**Comment by jaacoppi** [comment]
It's in src/libespeak-ng/dictionary.h. Do you have the file?

**Comment by vanfanel** [comment]
@jaacoppi The file seems to be absent on the release sources, but it's available on the git sources, which build fine. Closing this, thanks!
