### ISSUE TITLE
endian.h missing on Windows

### ISSUE THREAD

**Issue by michaelDCurran** [espeak-ng/espeak-ng#167]
Recently, spect.c has started including endian.h. This does not exist on Windows, thus we can no longer compile eSpeak for the NVDA project.
Broke in commit 832058167513670fa9fe23e640ece643751b125b

**Comment by rhdunn** [comment]
I have added a compatibility shim for `endian.h` from https://gist.github.com/panzi/6856583, but have not tested it on Windows yet.

**Comment by michaelDCurran** [comment]
endian.h now requires sys/param.h, which also does not exist on Windows.
Oddly though, the inclusion of that file is specific to the checking of 
```
__WINDOWS__
```

However, that define comes from gcc/mingw, MSVC never sets it. But, higher up in endian.h it is explicitly set if other more common Windows defines are set.

I think the person who wrote this endian.h may have only tested on mingw or gcc cross-building for Windows.

I am assuming the msvc project included with eSpeak would be also broken at this stage...
(NVDA has its own build system).

**Comment by rhdunn** [comment]
This has now been fixed.
