### ISSUE TITLE
new pull request for espeak ng variants

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#1676]
Can someone make a pull request with the new espeak variants? this is a lot more complicated than uploading to google drive. thanks. I mean a lot more! I don't understand what to do and git is an invalid command in command prompt on windows11. so it just is not working for me.

**Comment by joshknnd1982** [comment]
I looked on youtube for how to fork repositories and stuff but the videos are of sighted people doing stuff and i can't see the output and there is no screen reader feedback because I am blind. please help!! Is there an audio only podcast that goes over how to do this with a screen reader? I know that if I put the variant files in the right place in my NVDA screen reader folder and restart it, they work.

**Comment by joshknnd1982** [comment]
ok so I asked on some email lists if someone could remote into my machine and show me how to use a screen reader to make a pull request. and do the forks and stuff like that. I asked both for Jaws and NVDA. if nobody gets back to me maybe freedom scientific tech support can walk me through making a pull request using jaws remote. I can't believe I have to call freedom scientific jaws tech support and do remote access just to make a pull request!! this is rediculous but if its what I have to do to get the new variants into espeak ng then I guess its what I have to do...

**Comment by joshknnd1982** [comment]
if anyone on here can use NVDA remote or jaws tandom to show me how to do this that would be helpful thanks.

**Comment by joshknnd1982** [comment]
oh also can you record jaws tandom remote or NVDA remote sessions into mp3 somehow? then I could have a copy of it in case I need to refer back to it to make a new pull request on github? this is the only way I can think of to learn how to make a pull request. If nobody on here is willling to help out with this then I am calling freedom scientific tech support since I am a jaws customer. Maybe freedom scientific can help me with this espeak ng pull request.

**Comment by jaacoppi** [comment]
See #1649 and #1677. This issue is request for help on using git and github.

Closing as a duplicate.
