### ISSUE TITLE
Spanish: the letter r seems too long

### ISSUE THREAD

**Issue by sukiletxe** [espeak-ng/espeak-ng#1699]
From the testing page, pronunciation for `r erre` is different between both. Specifically, the letter is composed of two consonant sounds (`RR`), instead of using the single one (`R2`). I don't know if this sound is also used for word lists, but I certainly prefer the short `r2` one.

**Comment by sukiletxe** [comment]
Ah, you're right. Is NVDA using this older version?

**Comment by rmcpantoja** [comment]
@sukiletxe Yes, NVDA is using a commit prior to the spanish fixes that have been made. Note that this was recently merged, and it is likely that they will update espeak-ng to the latest NVDA alpha releases.

**Comment by sukiletxe** [comment]
OK, thanks! Closing.
