### ISSUE TITLE
MISTAKE IN THE Turkish LANGUAGE

### ISSUE THREAD

**Issue by haruncetinkaya306** [espeak-ng/espeak-ng#1702]
For NVDA, it is more accurate if espeak ng reads the thin letter a (a) written after the letter g in the Turkish language on the synthesizer without thinning the letter G. Since there are many rules about fine letters in the Turkish language, espeak ng cannot apply all of them.

**Comment by jaacoppi** [comment]
Please give example words. What words are wrong? Are some words correct?

**Comment by jaacoppi** [comment]
Please give an example of two words that are working correctly and two words that is wrong. It is much easier for non-turkish speakers to help you if you do that.
