### ISSUE TITLE
monotonous speech by default when used as a lib?

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#171]
Hello,

As reported on http://bugs.debian.org/848008 , switching brltty to espeak-ng (without source code change) makes the speech very monotonous, which makes it unusable for some work usage. I'm afraid that if it's not fixed soon I'll have to revert to espeak in Debian.

Samuel

**Comment by sthibaul** [comment]
Oops, sorry, I meant http://bugs.debian.org/848016

**Comment by rhdunn** [comment]
This is likely fixed by https://github.com/espeak-ng/espeak-ng/pull/170. I'll keep this bug open until this has been verified.

I'll create a new 1.49.1 release in the next few days with this fix in it.

**Comment by sthibaul** [comment]
Ah, I didn't get notified of the comment edition, so I received by mail only the original comment, now seeing the new one :)

You can run it on the linux text console, for instance:

brltty -s es -b no -p alsa

and it should be speaking everything that gets printed (and it's indeed monotonous on my box too).

**Comment by sthibaul** [comment]
Hello,

I believe I found what the issue is. You can try easily by building brltty from brltty.com, patching Programs/spktest.c the following way:

-  if (!sayString(spk, string, 0)) return 0;
+  if (!sayString(spk, string, SAY_OPT_MUTE_FIRST)) return 0;

then

./configure --with-speech-driver=es && make
cd Programs ; make spktest
./spktest -t "hello, this is a test" es

The speaking will be monotonous. Running with ltrace notably shows:

27451 espeak_Initialize(0, 0, 0, 0 <no return ...>
...
27451 espeak_SetParameter(1, 265, 0, 185 <unfinished ...>
27451 espeak_Cancel(0x7ffd488f7270, 0x5593fc0aa0c0, 0, 0x5593fc0aeb94 <unfinished ...>
27451 espeak_Synth(0x5593fccfae60, 22, 0, 1 <unfinished ...>

i.e. espeak_Cancel is called before any call to espeak_Synth. It happens that espeak_ng_Cancel indeed calls SetParameter with the saved parameters without having checked that they have been saved at all at least once, and thus bogusly sets all parameters to 0!

Even if it looks odd, calling espeak_Cancel before espeak_Synth is not a crazy thing to do and it does work with espeak. The following patch fixes the issue here.

[monotonous.txt](https://github.com/espeak-ng/espeak-ng/files/697511/monotonous.txt)

**Comment by sthibaul** [comment]
Ergl, of course github mangled it all... I of course meant to replace the first quoted code line with the second quoted line.

**Comment by rhdunn** [comment]
Thanks for the bug fix. I'm not sure why this worked in espeak, though.

**Comment by sthibaul** [comment]
Reece H. Dunn, on Tue 10 Jan 2017 23:39:41 -0800, wrote:
> Thanks for the bug fix. I'm not sure why this worked in espeak, though.

Perhaps espeak was putting the default values in the saved parameters at
startup?

Samuel

**Comment by sthibaul** [comment]
Samuel Thibault, on Wed 11 Jan 2017 09:56:53 +0100, wrote:
> Reece H. Dunn, on Tue 10 Jan 2017 23:39:41 -0800, wrote:
> > Thanks for the bug fix. I'm not sure why this worked in espeak, though.
> 
> Perhaps espeak was putting the default values in the saved parameters at
> startup?

Yes, it does so in espeak_Initialize.

for(param=0; param<N_SPEECH_PARAM; param++)
	param_stack[0].parameter[param] = saved_parameters[param] = param_defaults[param];

Perhaps it'd be better to rather fix the issue that way?

Samuel

**Comment by rhdunn** [comment]
That for loop is now in espeak_ng_Initialize (in speech.c, line 354). That code is called from the espeak_Initialize compatibility method (in espeak_lib.c, line 55).

**Comment by sthibaul** [comment]
Reece H. Dunn, on Wed 11 Jan 2017 13:22:09 -0800, wrote:
> That for loop is now in espeak_ng_Initialize (in speech.c, line 354).

But the version in espeak-ng does not set saved_parameters, only
param_stack[0].parameter

Samuel

**Comment by rhdunn** [comment]
Ah, you are correct! Thanks for taking the time to investigate this. I have pushed a proper fix now.

**Comment by rhdunn** [comment]
__NOTE:__ This was because the `initialize` function in eSpeak has a similar loop (does not set the `saved_parameters`). When merging/simplifying the logic, I thought those it was identical to the one in `espeak_Initialize` as the logic was duplicated.
