### ISSUE TITLE
Parse into formatted input/output

### ISSUE THREAD

**Issue by cmrdt** [espeak-ng/espeak-ng#174]
to help readability (custom ASCII phonetic multi-glyph symbols hard to read)
color-coding syntax highlighting to assist readability &debugging

maybe making the RGB color a function of

- if vowel of the language-specific formant f1,f2,f3.. coordinates)
- if consonant based on location

- https://en.wikipedia.org/wiki/Template:IPA_chart/table_vowels
- espeak\phsource\vowelcharts
- https://en.wikipedia.org/wiki/Consonant#Features
the complex entries could easily be put into coordinates

maybe https://en.wikipedia.org/wiki/YUV or https://en.wikipedia.org/wiki/Lab_color_space

maybe also support for IPA input with https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#Diacritics_and_prosodic_notation (more/less round, voiced, central)

- https://en.wikipedia.org/wiki/Vowel#Height
(height related to f1) , (backness related to f2)

**Comment by rhdunn** [comment]
Duplicate: issue #193.
