### ISSUE TITLE
Add support for Arabic

### ISSUE THREAD

**Issue by rhdunn** [espeak-ng/espeak-ng#176]
There is Arabic support in https://github.com/linuxscout/espeak-ng. This needs cleaning up to:

1.  Simplify the history to not include small changes with non-descriptive commit messages.
2.  Not add the Arabic MBROLA voice binary files to the espeak-ng repository.

**Comment by ValdisVitolins** [comment]
Reece, I'd like to fix this issue, but I wonder what exactly I should do.

In latest espeak-ng there is much longer list of phonemes
in [/phsource/ph_arabic](/espeak-ng/espeak-ng/blob/master/phsource/ph_arabic) than in my previous fork merged from [linuxscout](https://github.com/linuxscout/espeak-ng)

It only lacks rule files: .../dictsource/ar_extra, ar_list, ar_listx, ar_rules.

So, what is source for current `ph_arabic` file, is it reliable, and can I use it (and extend, if necessary) to use (with, probably adjusted) rule files from linuxscout repository?

**Comment by rhdunn** [comment]
The `ph_arabic` file was added by Jonathan for the 1.48.05 release. I'm looking at this issue -- the `ph_arabic` file is different, and there are files that need to be added (while other files need to be ignored).

**Comment by rhdunn** [comment]
I have incorporated this into espeak-ng. The things I have not incorporated are:

1.  The additional `ar-fm`, `ar_moh` and `ar_mustafa` voices. These are voice variants. I want to change the way languages (voices) and voices (voice variants) are handled in espeak-ng to better model voices and languages.

2.  The arabic MBROLA data. The source of the phoneme translation tables do not exist and will need to be recreated.

This still needs work. See https://github.com/espeak-ng/espeak-ng/issues/186.
