### ISSUE TITLE
espeak on ARM systems

### ISSUE THREAD

**Issue by graduatemazada** [espeak-ng/espeak-ng#1777]
i wonder if anybody has sucessfully built espeak-ng on ARM system

**Comment by alex19EP** [comment]
yes. on Android, linux arm and even apple m1+ hardware.

**Comment by graduatemazada** [comment]
i used UltraEdit try to make the obeject document(.o)，and get the lib document，but it sent the error，i wonder if it is the Compiler Environment matters，because i have successfully compile on linux but failed on ARM ，i would appreciate if u could give me a hand.
