### ISSUE TITLE
Error: The specified espeak-ng voice does not exist.

### ISSUE THREAD

**Issue by testtest954** [espeak-ng/espeak-ng#1782]
when i try a filipino language it shows up
Error: The specified espeak-ng voice does not exist.
need help?

**Comment by jaacoppi** [comment]
Espeak-ng doesn't support filipino.

**Comment by testtest954** [comment]
there is when you look in wikipedia https://en.wikipedia.org/wiki/ESpeak#Languages

**Comment by jaacoppi** [comment]
That Wikipedia list is very inaccurate. Most of the languages listed there are not supported.
