### ISSUE TITLE
Microsoft Visual C++ VC6.0 

### ISSUE THREAD

**Issue by graduatemazada** [espeak-ng/espeak-ng#1797]
how to generate phontab .phonindex. phondata. intonations

**Comment by jaacoppi** [comment]
Closing this as duplicate of #1790 and #1791 .

Data files are generated with the espeak-ng --compile commands:
espeak-ng --compile
espeak-ng --compile-intonations
espeak-ng --compile-phonemes

You can check src/windows/data.vcxproj to see how the commands are run.
