### ISSUE TITLE
Undefined reference to rpl_malloc

### ISSUE THREAD

**Issue by midaszhou** [espeak-ng/espeak-ng#180]
Just cross compile espeak-ng for Openwrt,  Errors arise at final make stage :
 
 
![image](https://cloud.githubusercontent.com/assets/20430007/21589236/c6731266-d12a-11e6-94e2-063db0d56817.png)

**Comment by midaszhou** [comment]
I've deleted lines of "#undef malloc"  and  "#undef realloc" in config.h.in before,  otherwise  it would cause "undefined reference to rpl_malloc"  error during making.   Dose that matter ?

**Comment by rhdunn** [comment]
The build process uses the built espeak-ng program to build the dictionary and phoneme data. You could do the following:

1.  Build the program locally to build the dictionary and voice data (`make`).
2.  Build the espeak-ng and speak-ng programs with the library using cross compilation (`make -B src/speak-ng src/espeak-ng`).

The "undefined reference to rpl_malloc" error is an issue with the `configure.ac` script.

**Comment by midaszhou** [comment]
Thanks a lot!  It works!
For the 2nd step,  I deleted  'AC_FUNC_MALLOC'  and 'AC_FUNC_REALLOC' in configure.ac, 
then run  autogen.sh and  bulid.sh again.
I edited  build.sh for cross compilation like this:
#!/bin/sh
./configure  --build=i386-linux \
--host=mipsel-openwrt-linux \
--target=mips-linux \

finially run make as  (   make  -B src/speak-ng src/espeak-ng ).
Its tricky and exiting!
![image](https://cloud.githubusercontent.com/assets/20430007/21960507/ea5051c2-db29-11e6-87bb-b239125813e5.png)
