### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [espeak-ng/espeak-ng#1810]
Hello,
Is it possible to change this to a more permissive license (such as MIT/ISC/BSD)? Many libraries depend on this project, and this requires all upstream libraries to use GPLv3.
Thanks in advance!

**Comment by fakerybakery** [comment]
Ok, that makes sense. Thanks

**Comment by amakropoulos** [comment]
hi, thanks for this great library!
is there any way to reach the author?
this is quite blocking for the adoption of the library as well as libraries depending on it e.g. Piper.
there is no alternative as far as I know for the C world
