### ISSUE TITLE
Config.h error during build (android)

### ISSUE THREAD

**Issue by captnc** [espeak-ng/espeak-ng#185]
Hi, 
i try to build espeak-ng for android :
export ANDROID_HOME=...
./autogen.sh
./configure --with-gradle=...
make apk-release

but i have this error : 
cd android && ndk-build
make[1] : on entre dans le répertoire « /home/mr_pou/Travail/Espeak/espeak-master/android »
[mips] Compile        : ttsespeak <= compiledata.c
jni/../../src/libespeak-ng/compiledata.c:20:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
...

Thx

**Comment by rhdunn** [comment]
I have now fixed this issue. Thanks for reporting it.

Note that while the Android code on the master branch builds, I still have the following things to do:

1.  Test the built APK file.
2.  Re-add support for handling Unicode characters.

**Comment by captnc** [comment]
Thanks a lot, i will try today

**Comment by captnc** [comment]
Hi, 
thanks for this fix: build is ok.
Unfortunately, espeak crash ("unfortunately, espeak has stopped") when i launch it or when i change the tts engine to espeak one.
I have a samsung A6 10.1 (SM-T580) with android 6.0.1
