### ISSUE TITLE
Missing phonemes in Japanese

### ISSUE THREAD

**Issue by SchweitzerGAO** [espeak-ng/espeak-ng#1854]
I am trying to train a Japanese TTS model using [piper](https://github.com/rhasspy/piper) with espeak-ng as a phonemizer backend, I encountered this when I am processing the dataset. Is there any solutions?

![image](https://github.com/espeak-ng/espeak-ng/assets/64410968/ddb23171-0e07-42be-a77b-19ccc155adb4)

I am on Ubuntu 22.04 and I installed espeak-ng by `apt-get install espeak-ng`

**Comment by rhdunn** [comment]
The piper command is generating those messages, not espeak-ng -- https://github.com/rhasspy/piper/blob/2fa4c2c13933c1f6b8d87e34d12788ca8e6d073b/src/python/piper_train/preprocess.py#L255.

In the ph_japanese espeak file, it has the following ipa transcriptions:
1. `u` -> ɯᵝ
2. `e` -> e̞
3. `o` -> o̞
4. `a` -> ä
5. etc.

It looks like piper does not recongize/handle some or all of the espeak IPA transcriptions for Japanese properly. See https://en.wikipedia.org/wiki/Japanese_phonology#Vowels.

**Comment by SchweitzerGAO** [comment]
Sure I will turn to piper

**Comment by masterwang22327** [comment]
@rhdunn hi，he changed espeak-ng to epeak in this issue in the final.https://github.com/rhasspy/piper/issues/344#issuecomment-1890844487
i also download espeak-1.48.04-source.zip but not found ja_dict in espeak,do you know how he changed  the file and solve this issue.look for  your reply.
