### ISSUE TITLE
some Phonemes are combined and output when the input text contains phrase 'in the'

### ISSUE THREAD

**Issue by matt90luo** [espeak-ng/espeak-ng#1859]
I execute the command: echo "I am  in the night" | espeak-ng --ipa --sep='|' -q
I found the output is: aɪ|ɐ|m ɪ|n|ð|ə n|ˈaɪ|t

Does someone know why the phrase "in the ninght" is parsed as "ɪ|n|ð|ə n|ˈaɪ|t"? It is supposed to be "ɪ|n ð|ə n|ˈaɪ|t"

espeak-ng version info:
eSpeak NG text-to-speech: 1.50  Data at: /usr/lib/x86_64-linux-gnu/espeak-ng-data

**Comment by jaacoppi** [comment]
Because of the "multiple words" feature explained in docs/dictionary.md. "In the" is parsed as a single word.

$ grep -n "(in the)\|(of the)" dictsource/en_list 
5246:(of the)         ***@***.***		$nounf
5276:(in the)         ***@***.***

**Comment by matt90luo** [comment]
> Because of the "multiple words" feature explained in docs/dictionary.md. "In the" is parsed as a single word. $ grep -n "(in the)\|(of the)" dictsource/en_list 5246:(of the) ***@***.*** $nounf 5276:(in the) ***@***.***

1
