### ISSUE TITLE
ipa output: option for “ə + ˞”  rather than  ɚ

### ISSUE THREAD

**Issue by cmrdt** [espeak-ng/espeak-ng#189]
therefore could also do & blends with
ɑ˞ c˞

also if could allow for fuzzy phomeme input (user friendly) see:
![wb2](https://cloud.githubusercontent.com/assets/24411108/21827929/c78da1d4-d75b-11e6-8e72-29154d1fff64.png)

**Comment by rhdunn** [comment]
Using the combined ɚ character is perfectly valid, just like using the combined a + umlaut character.

espeak-ng uses broad phoneme transcriptions for input specific to each language, just like the SPRs referenced in that link to the watson TTS docs, using an ASCII representation.
