### ISSUE TITLE
Adding Amazigh/Berber language

### ISSUE THREAD

**Issue by abdelhaqueidali** [espeak-ng/espeak-ng#1902]
We would like you to work on adding Amazigh language, also known as berber. This language is spoken in North Africa. The writing system it uses is its own script which is called Tifinagh, also Latin script is used.
We would like Moroccan Amazigh, which is officially using Tifinagh as the main script to write it. Script is not a matter since it is just about changing one from tifinagh to latin.
I do not have experience in developing programs, but I can help with choosing the appropriate phonemes that are needed to be used. I can help with basic rules too for better reading.
Tifinagh consists of 33 main letters which has 4 vowels, a shwa and 3 letters that represent (a, u, i) but the alphabet can be expanded to more than 55 letters with two more vowels.
Here is the full list with IPA :
 _ⴰ a short æ
_ⴱ b
_ⴲ b fricative. Like spanish v, pronouncing letter b but sounds like v, air flow passes while keeping it voiced so it does not turn into p.
_ⴳ g
_ⴴ g fricative (letter g while airflow passes)
_ⴵ dʒ
_ⴶ dʒ
_ⴷ d
_ⴸ ð
_ⴹ dˁ thick d
_ⴺ ðˁ thick ð
_ⴻ ə
_ⴼ f
_ⴽ k
_ⴾ k
_ⴿ k fricative
_ⵀ h
_ⵁ h
_ⵂ h
_ⵃ ħ like arabic haa
_ⵄ ʕ like arabic ain
_ⵅ x
_ⵆ x
_ⵇ q
_ⵈ q
_ⵉ i short ɪ
_ⵊ ʒ
_ⵋ ʒ
_ⵌ ʒ
_ⵍ l (letter L)
_ⵎ m
_ⵏ n
_ⵐ gn
_ⵑ ng
_ⵒ p
_ⵓ u short u
_ⵔ r
_ⵕ rʕ thick r
_ⵖ ɣ
_ⵗ ɣ
_ⵘ ɣ
_ⵙ s
_ⵚ sˁ thick s
_ⵛ ʃ
_ⵜ t
_ⵝ θ
_ⵞ tʃ
_ⵟ tˁ thick t
_ⵠ v
_ⵡ w
_ⵢ j
_ⵣ z
_ⵤ z
_ⵥ zˁ
ⵦ e like french é
ⵧ o like english ɔ
_ⵯ  ʷ
Main letters that can use ⵯ
_ⴽⵯ kʷ
_ⴿⵯ kʷ fricative
_ⴳⵯ gʷ
_ⴴⵯ gʷ fricative
_ⵇⵯ qʷ
_ⵖⵯ ɣʷ
_ⵅⵯ xʷ

Letter ⴰ changes from a (short æ) to ɑ when it is after thsese letters
ⵥⴰ
ⵕⴰ
ⵟⴰ
ⵚⴰ
ⴹⴰ

Letter ⵓ changes from short u to o when after these letters
ⵥⵓ
ⵕⵓ
ⵟⵓ
ⵚⵓ
ⴹⵓ
ⵖⵓ
ⵅⵓ
ⵇⵓ

These letters can be treated differently from word to another for this change, but words that do not follow this rule can be added to the dictionary to be pronounced differently than this rule.

The good thing about Amazigh is that it is read as it is written except for some rules like when a word ends with a vowel and another starts with another vowel, certain letters are being used in the transition depend on the vowels.
Word ends with ⴰ or ⵓ or ⵉ + word starts with ⴰ it becomes --vowel ⵢⴰ--
Word ends with ⴰ or ⵓ or ⵉ + word starts with ⵉ it becomes --vowel ⵢⵉ--
Word ends with ⴰ or ⵓ or ⵉ + word starts with ⵓ it becomes --vowel ⵡⵓ--
By covering all these letters most amazigh varients can be spoken with it.
I hope you work on it, there is almost no text to speech service for this language, I would be happy to help in anyway. I tried modifying arabic files to get Amazigh since it has most letters that Amazigh has but I do not know how to deal with non-ipa symbols that are used in it and how they are pronounced by espeak. I am also not sure how to try the modified file with espeak to see the result if I do not find how to so in the internet. 
I am not sure if i have used the appropriate phonemes symbols since I could not test them with espeak to see how each one sounds. What i said might not be complete but it is something can be begin with, improvements can be done latter for better results.
Than you.

**Comment by jaacoppi** [comment]
Requests for new supported languages are collected in #1396 . Closing this.
