### ISSUE TITLE
espeak klatt voices

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#191]
Could the klatt voices please be improved? Please add the nv-speech-player-voices such as edward as an espeak standard voice. Note klatt phonemes for other languages such as French need improvement.

**Comment by rhdunn** [comment]
Duplicate: issue #181

**Comment by rhdunn** [comment]
__NOTE:__ The edward implementation is in C++ and is not compatible with the espeak/espeak-ng architecture.
