### ISSUE TITLE
espeak sapi5

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#192]
Please make espeak sapi5 installable with an installer wizard for windows. Perhaps the installer could have two tree views with checkboxes. one tree view for variants you want installed and registered as sapi5 voices, and another tree view to select any and all available languages including dialects, with the requirement that at least one language and at least one voice variant has to be installed for the installation to continue.

**Comment by rhdunn** [comment]
Duplicate: issue #7.
