### ISSUE TITLE
syntax colored IPA output

### ISSUE THREAD

**Issue by cmrdt** [espeak-ng/espeak-ng#193]
maybe using 
```
i	y		3d96e2	157bc6
ɨ	ʉ		a575e1	8a58c6
ɯ	u		da35e1	bd09c6
				
ɪ	ʏ		8189cf	666eb4
ɪ̈	ʊ̈		a579cf	8a5db4
ɯ̽	ʊ		c263cf	a645b4
				
e	ø		489abe	267fa3
ɘ	ɵ		a57bbd	8b60a2
ɤ	o		d94dbc	bb2ca1
				
e̞	ø̞		519ba5	31808b
ə	ɵ̞		a77ea6	8c638b
ɤ̞	o̞		d955a2	bb3687
				
ɛ	œ		5b9c8d	3c8171
ɜ	ɞ		a9818b	8e6670
ʌ	ɔ		da5a88	bc3c6d
				
æ			689c64	4c8148
ɐ	ɞ̞		ad8267	92674c
				
a	ɶ		769b32	5b8010
ä	ɒ̈		b38230	976710
ɑ	ɒ		de602e	c0410e
```
![2017-01-10 16_27_40-espeak speech synthesizer s](https://cloud.githubusercontent.com/assets/24411108/21835599/466cd0e4-d78c-11e6-8606-0e234693b064.png)

![espeak](https://cloud.githubusercontent.com/assets/24411108/21830052/3965b72c-d768-11e6-94c4-bc79996c98ba.png)

**Comment by rhdunn** [comment]
I don't see the benefit of this. If you want to do this, you could create a script to do it for you.
