### ISSUE TITLE
Please add Mongolian language

### ISSUE THREAD

**Issue by garawaa** [espeak-ng/espeak-ng#1935]
Please add Mongolian language

**Comment by jaacoppi** [comment]
Closing as a duplicate of #1324 and #1396 .

**Comment by btseee** [comment]
Dear @garawaa,

I have been contributing Mongolian language support to this project for the past year and continue to actively develop and improve it.

Mongolian is a complex language, and the implementation is still not perfect, but I hope it will be useful and help move the project forward.
