### ISSUE TITLE
Different non-Latin diacritized consonants are wrongly considered as one doubled

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#195]
if following rule `a (C% u`, then it passes also for '**aņš**a'.
As workaround one can use character group (e.g. `.L01 ņ` and `.L02 š`) and `... (L01%` `... (L02%` rules instead.

**Comment by rhdunn** [comment]
The better approach would be to fix the logic in espeak-ng when processing `C%` rules.

**Comment by ValdisVitolins** [comment]
Agree, but I want to highlight known caveats.

**Comment by ValdisVitolins** [comment]
Actually... I got idea how to fix it.

**Comment by ValdisVitolins** [comment]
It was hard weekend, but I managed to fix this.

**Comment by rhdunn** [comment]
Thanks for the fix.
