### ISSUE TITLE
Linking failure with libucd

### ISSUE THREAD

**Issue by WilliamTambellini** [espeak-ng/espeak-ng#1972]
Just a linking failure with libucd.a:
```
...
[ 21%] Building C object src/libespeak-ng/CMakeFiles/espeak-ng.dir/espeak_api.c.o
[ 22%] Linking C shared library libespeak-ng.so
/usr/bin/ld: ../ucd-tools/libucd.a(categories.c.o): relocation R_X86_64_PC32 against symbol `ucd_lookup_category' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
which makes sens: you build ucd as a static lib to be embedded within a dyn lib (libespeak.so).
The clean fix is just to add:
set_property(TARGET ucd PROPERTY POSITION_INDEPENDENT_CODE ON)
in
https://github.com/espeak-ng/espeak-ng/blob/master/src/ucd-tools/CMakeLists.txt
Would you like me to prepare a PullReq to do so?

**Comment by alex19EP** [comment]
hello. yes pr would be welcome. but I can't reproduce this issue at all on my system. can you provide more info how to do that?

**Comment by WilliamTambellini** [comment]
Fixed. Tks.
