### ISSUE TITLE
Rebrand the espeak program to espeak-ng.

### ISSUE THREAD

**Issue by rhdunn** [espeak-ng/espeak-ng#2]
The program, library, environment variables, etc. should reflect the project being `espeak-ng`. This will help differentiate it from the upstream `espeak` project, should Jonathan continue to make releases to it, allowing both to run on a system. It also helps to avoid confusion.

**Comment by ValdisVitolins** [comment]
I'd better prefer "drop-in replacement" as for MySQL and MariaDB.
That means package/project name is different, but executables/configuration files have the same name. (It already has quite many different back-end files.)

**Comment by rhdunn** [comment]
The plan is to retain API compatibility of the C API in libespeak-ng and the command line in espeak-ng and speak-ng with the espeak equivalents.

The "drop-in replacement" can then be done by creating symbolic links, either manually or by the `update-alternatives` command on Linux (Debian?). For example:

    ln -s espeak-ng espeak
    ln -s libespeak-ng.so libespeak.so

**Comment by ValdisVitolins** [comment]
It should be good on Unix-like systems. Don't know about Windows though.
