### ISSUE TITLE
make clean ; make  doesn't work.

### ISSUE THREAD

**Issue by vrdhn** [espeak-ng/espeak-ng#201]
Hi
 I'm  unacquainted with autotools . I noticed that running `make clean` followed by `make` doesn't build,
and generates the following messages:

>   : espeak-ng $ make src/libespeak-ng.la
>   CCLD     src/libespeak-ng.la
> gcc: error: src/libespeak-ng/.libs/src_libespeak_ng_la-compiledata.o: No such file or directory
> gcc: error: src/libespeak-ng/.libs/src_libespeak_ng_la-compiledict.o: No such file or directory
> gcc: error: src/libespeak-ng/.libs/src_libespeak_ng_la-compilembrola.o: No such file or directory
>  ..... several more ....

In the generated Makefile, the dependencies are generated without the '/.libs' portion;
Fixing this, or updating the `make clean ` target to clean more exhaustively would help immensely.
For now, the workaround is `git clean -dxf` !

**Comment by ValdisVitolins** [comment]
`make clean` doesn't work for me also, but I can always build with:
```
./autogen.sh
./configure --prefix=/usr
make -B
```
... except when I got [problems with libraries](https://groups.io/g/espeak-ng/message/182) on `sudo make LIBDIR=/usr/lib/x86_64-linux-gnu install` and I had to do before that:
```
sudo rm /usr/lib/libespeak* /usr/local/lib/libespeak* /usr/local/lib/lt-espeak-ng*
sudo rm -fr /usr/include/espeak* /usr/share/espeak-ng-data
sudo ldconfig -v
```
But I agree, that "something fishy" is happening during builds.

**Comment by vrdhn** [comment]
Found that updating clean-local target to remove .o/.lo files from src/llibespeak-ng worked:

```
diff --git a/Makefile.am b/Makefile.am
index 1fb36583..82202bd0 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -55,6 +55,7 @@ install-exec-hook:
 
 clean-local:
 	cd src && rm -f *.o *~ && cd ..
 +	cd src/libespeak-ng/ && rm -f *.o *.lo && cd ../..
 	cd android && $(GRADLE) clean
```

**Comment by ValdisVitolins** [comment]
I applied this fix to my branch.
