### ISSUE TITLE
Number processing broken at least for slovak and czech 

### ISSUE THREAD

**Issue by pvagner** [espeak-ng/espeak-ng#2109]
Dear @sthibaul 
Since bf8d06c4784f6af05a46dd30e1cf5da06614e78b speaking numbers occupying more than 4 digits is broken.
I can use this command to trigger unexpected behaviour
```
espeak -v sk 12345
```

Actual: Pronouncing the number is cut off. The more digits the earlier the cut takes place. For example with the 5 digit number first 3 numbers are handled.

Expected: the number should be handled and spoken to the end.

Thanks for the latest improvements.

Greetings

Peter

**Comment by sthibaul** [comment]
It's actually fe53b1b29dddb4a4a73ce62b53a3cd2fa988cea8 that brings the break. I'll revert it for now.

**Comment by sthibaul** [comment]
(and we will see which fuzzing crashes show up again)

**Comment by sthibaul** [comment]
Fixed by a3c87bd

**Comment by pvagner** [comment]
Thank you verry much, it's working fine over here.
