### ISSUE TITLE
stdin inputs larger than 1000 bytes cause heap corruption

### ISSUE THREAD

**Issue by ChliHug** [espeak-ng/espeak-ng#212]
The code in [src/espeak-ng.c](https://github.com/espeak-ng/espeak-ng/blob/e372d8434897ed6995da49873ef75782ace8459c/src/espeak-ng.c#L701) which loads the data from stdin reallocates the buffer every 1000 bytes but never actually uses the pointer returned by realloc. If there are more than 1000 bytes coming from stdin, the code will write to an invalid pointer causing heap corruption and access violations.

The attached patch adds the needed pointer assignment. It also changes the type of the `max` variable to size_t and adds an overflow check. Overflowing the int after 2 GiB of data from stdin causes undesirable behavior. This check needs the SIZE_MAX macro from stdint.h, but I think this isn't a problem since this project already requires C99. (Is that correct?)

[espeak-ng_fix_heap_corruption_for_large_stdin_inputs.diff](https://github.com/espeak-ng/espeak-ng/files/746615/espeak-ng_fix_heap_corruption_for_large_stdin_inputs.txt)

**Comment by rhdunn** [comment]
Thanks for the patch.
