### ISSUE TITLE
Marathi problem

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#230]
Hi!
I notice a big mistake in Marathi. For example, if is written s (halanta) r, It says 'shalantr'. But It must says 'sr'. Please, could You fix this problem?
Thanks alot!
Marco Oros

**Comment by ValdisVitolins** [comment]
Marco, can you run sample text in command line with Marathi sample text and show actual and necessary output? E.g.:
```
espeak-ng -x -vmr "त्याचे"
t:j'a:ce:
```
but should be `....` (if you don't know precise phoneme writing syntax, just describe what should be changed).

**Comment by Giovani93** [comment]
I am sorry, I use Espeak on NVDA on Windows.

**Comment by valdisvi** [comment]
Can you provide word (in original writing) where problem was found?
So far I understand is that _somewhere_ **..tr** is said instead of  **..sr**, but that is not precise enough to fix it.

**Comment by Giovani93** [comment]
OK, for example word namaskar नमस्कार is pronounced, like 
(namashalantkar) not (namaskar).

**Comment by valdisvi** [comment]
Hm...
development version of eSpeakNG says: [namskar](http://odo.lv/Espeak?eslang=-vmr&speed=160&output=-w&debug=-x&text=%E0%A4%A8%E0%A4%AE%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A4%BE%E0%A4%B0)

**Comment by Giovani93** [comment]
I'll checked It at NVDA.
Maybe, this is problem of NVDA, but I am not shure. Or, this is fixed. I 
don't know really.

**Comment by rhdunn** [comment]
The Marathi voice was updated in espeak-ng on 25th Jan 2017, which likely fixed this problem. NVDA are likely using an older version without those changes.

**Comment by Giovani93** [comment]
Current NVDA also countains Arabic and Japan voice. So It means, that is 
maybe use new version of Espeak.

**Comment by Giovani93** [comment]
Yes, this version of Espeak NG is from 10th january. OK, I'll maybe 
contact the developers.
Or, the best way is also on this, what what fate will bring me, as I say 
sometimes.
Marco

**Comment by valdisvi** [comment]
Giovani,
I have rechecked how eSpeakNG says for example, "[नमस्कार](http://odo.lv/Espeak?eslang=-vmr&speed=160&output=-w&debug=-x&text=%E0%A4%A8%E0%A4%AE%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A4%BE%E0%A4%B0&formmethod=get)" and I believe this issue if fixed (at least, in development).
If you think, issue still exists, please, reopen it with additional information.
