### ISSUE TITLE
म and व sound absolutely same in Marathi?

### ISSUE THREAD

**Issue by MaheshVelankar** [espeak-ng/espeak-ng#231]
म and व sound absolutely same in Marathi.

Please check these words to confirm

मदन = God of love
वदन = face or mouth

If you listen to the sound file produced, there is hardly any difference between म and व.
This is not correct and needs to be fixed.
(May be same problem will be seen in Hindi too...........I have not checked though.)

Please see how and where this should be fixed.

**Comment by valdisvi** [comment]
Sounds are similar, but different.
Marathi doesn't have its own definition of v sound, it relies on `ph_hindi_base`, where `v` is described as
```
...
// approximant, not fricative
base1/v#
...
```
which has more nasal sound, thus similar to `m`.
Solutions are:

1. change this generally used phoneme from `v#` to `v` which is fricative with more distinct sound,
1. overriding `v` phoneme only in Marathi language,
1. adding more language rules in Marathi to distinguish between aproximant `v#` and fricative `v` sounds.

**Comment by valdisvi** [comment]
I decided to implement 2nd option (redefining v sound for Marathi language). Currently you can test it [here](http://odo.lv/Espeak?language=en&eslang=-vmr). If fix is not correct, please, reopen issue.
