### ISSUE TITLE
Handle all letters in ligatures

### ISSUE THREAD

**Issue by sukiletxe** [espeak-ng/espeak-ng#232]
Currently, things like Kaedmon, Caesar, soeur (French), oeuf (French), if written using ligatures, are pronounced as if the second letter was missing (i. e. Casar, Kadmon).

**Comment by valdisvi** [comment]
More proper way would be replacing ligatures with two letters (see issue #199), but currently as workaround I added [ separate pronunciation rules](https://github.com/valdisvi/espeak-ng/commit/5b0b2cd3360b67efdc6b3714fc1c5716cc6cf399) for  `æ` an `œ` ligatures.

**Comment by rhdunn** [comment]
Using replacement rules to handle this works for me.
