### ISSUE TITLE
Unsupported on XP, (espeakng.exe is not a Valid Win32 Aplication)

### ISSUE THREAD

**Issue by afarlie** [espeak-ng/espeak-ng#239]
Recently aimed to test the new version,
However the binary listed for download, is not recognised by Windows XP SP 3. 

This is not a major concern as XP is end of life in any event.

I will in the absence of confirmation that the listed download is  "bad" build, assume that NG now needs Windows 8 or higher, and that I'm stuck using the last version of the original E-Speak (which still supports XP) if someone can advise which version that is.

**Comment by rhdunn** [comment]
The Windows binaries are built for Windows 8 or later, and I have tested them on Windows 10.
