### ISSUE TITLE
make clean now requires gradle

### ISSUE THREAD

**Issue by pettarin** [espeak-ng/espeak-ng#244]
With the current head a72199f7144722f606f934248e0e7dfab5009691 , ``make clean`` requires ``gradle``, which I am not sure it is appropriate (since maybe some users are not interested in compiling the Android version and/or in getting tons of stuff from maven).

**Comment by pettarin** [comment]
Detail: the relevant line is https://github.com/espeak-ng/espeak-ng/blob/master/Makefile.am#L62

**Comment by rhdunn** [comment]
I have pushed a fix for this issue. Thanks for the bug report.

**Comment by pettarin** [comment]
Thank you!
