### ISSUE TITLE
some words in NVDA are starting to speak incorrectly since the last espeak NG update for it

### ISSUE THREAD

**Issue by derekriemer** [espeak-ng/espeak-ng#250]
Hi:

NVDA is currently incubating https://github.com/nvaccess/nvda/pull/7115 which is causing some words to break in english US.
Here are a list I have compiled. 
compiled compressional condolence current continue 

The issue is that the c at the beginning of the words is way to short, so it kind of sounds like the second vowel is simply being shortened. I am not sure how to explain this without telling someone the pronunciation I expect.
as this will affect NVDA, cc @jcsteh @MichaelDCurran

**Comment by derekriemer** [comment]
open might be one too, but I bet this is a different phoneme. It sounds like a person who got hit in the mouth and has a fat lip when espeak-ng says the p in open (The p is muted and sort of has a v embedded in the p).

**Comment by rhdunn** [comment]
I have pushed an update to espeak-ng that should fix this issue. I have included a test to help identify regressions like this in the future. Can you test these changes to verify that they fix the issues you have described here.

**Comment by valdisvi** [comment]
Derek, I have updated test site [http://odo.lv/Espeak](http://odo.lv/Espeak), you can test it and (I believe close) this issue.

**Comment by derekriemer** [comment]
I can't select en-us from the website so I can't test my dialect, but it seems better. Hold on until after dinner tonight, and I'll build master with NVDA and test it.

**Comment by derekriemer** [comment]
I'll reopen if this remains an issue.

**Comment by valdisvi** [comment]
Derek, I've added most widely used English dialects to the list.
(In other specific cases, you can use GET method in form, to show generated URL parameters, which then can be changed and submitted in browser's address bar by hand).
