### ISSUE TITLE
Tracking other parallel espeak developments ?

### ISSUE THREAD

**Issue by cmrdt** [espeak-ng/espeak-ng#251]
found 

- https://github.com/jticket1024/espeak-en-us

others?

**Comment by rhdunn** [comment]
I'm already keeping track of other espeak projects. There does not need to be an issue for this.

I am aware of espeak-en-us. That project cannot be incorporated as is, as it tends to create American English specific pronunciations, but I do incorporate several fixes from that project into espeak-ng.
