### ISSUE TITLE
Espeak + Mbrola + Javascript 

### ISSUE THREAD

**Issue by isteven** [espeak-ng/espeak-ng#252]
Hi,

Is there a doc / example on how to use espeak + mbrola with Javascript?

I set up espeak and mbrola on my machine (Win 7 64 bit). They work nicely using the command line (example: espeak -v mb-id1 "Halo").

However, i'm not sure how to do it using Javascript in the browser. I tried fiddling around, but all I got was the same synthetic voice.

Also, how do I know if the mbrola languages are installed properly? For example, will it be displayed on the language list in the demo page? (https://www.readbeyond.it/espeakng/)

Any help would be appreciated. Thanks.

**Comment by rhdunn** [comment]
The mbrola voice synthesis is handled by a separate mbrola binary where the source code is not provided. As such, it is not possible to use the mbrola voices from JavaScript. Longer term I want to add support for additional synthetic voices, but this requires architectural changes.
