### ISSUE TITLE
a significant problem in Farsi language fa* files.

### ISSUE THREAD

**Issue by shadyar** [espeak-ng/espeak-ng#253]
@rhdunn 

Hello 
I am Shadyar Khodayari the developer of Farsi language of espeak.
in all previous commits of e-Speak-NG, for  Farsi language, there are three language files fa fa-en-us fa-pin (fa-pin is the same fa-latin in the latest commit in this path
espeak-ng / espeak-ng-data / lang / ira / .

fa-en-us reads english texts with American accent. the grate number of Persian speakers learn English with American accent and would like to hear text with the same accent.
1. but fa-en-us in the Latest commit has been omitted. please restore it.
2. the name of fa in the Latest commit has been changed to "Persian", it was in all previous commits "Persian+English u.k" please restore this name.

Regards

**Comment by rhdunn** [comment]
The selection of the accent of English to use is independent of the selection of Farsi/Persian, and would equally apply to other languages that don't use the Latin script (e.g. Bulgarian). That is the reason for these changes.

I do intend to provide the ability to select the language/accent for a particular script in addition to the primary language, as detailed in https://github.com/espeak-ng/espeak-ng/issues/216. This would allow things like:

1.  `-v fa,en` -- Farsi with the default English accent;
2.  `-v fa,en-GB-x-rp` -- Farsi with a Received Pronunciation British English accent;
3.  `-v fa,en-US` -- Farsi with an American English accent.

None of the other non-Latin script languages use "+English u.k.", so the Farsi/Persian language will not use that extension either.

**Comment by shadyar** [comment]
@rhdunn 

it seams a good idea, just how about eg. NVDA user? (as you know, e-Speak-NG is integrated in this project)
I do not have any imagine, I would appreciate, if you could explain;which how do the Persian speakers will select English accent in NVDA project?
I should notify them, in time, because I publish a news-letter for users of e-Speak in Persian, the majority of them use NVDA.
