### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#256]
Hi!
There is mistake in the documentation, but I am not shure.
What Manipuri language is developed?
Manipuri, as a Maythili, or Manipuri, as Bengali dialect?
If, this is Bengali (Bangla) dialect, this language is belong to Indo-arian group, not Sino-tibetan.
Please, could You look at documentation and edit It?
Thank You!
Marco Oros

**Comment by valdisvi** [comment]
Isn't this duplicate of issue #238?

**Comment by Giovani93** [comment]
I am sorry, Yes, It is. This is about Meitei, or Bishnupriyamanipuri 
language, as I noticed.
  But, please, edit this documentation. I think on languages mentioned 
ain readme file and there is mistake, as I have mentioned.
Thank You!

**Comment by rhdunn** [comment]
I have updated `docs/languages.md` to correct the `bpy` (Bishnupriya Manipuri) language in that list. I missed updating this when fixing https://github.com/espeak-ng/espeak-ng/issues/238. Are there any other references that I am missing?

**Comment by Giovani93** [comment]
Yes, there are.
For example, every Slavic language is South slavic.
So, South slavic languages are:
Slovene, Croatian, Serbian, Macedonian, Bosnian, Montenegrin and Bulgarian.
East slavic are:
Belarusian, Ukrainian, Russian and Rusin (or Ruthenian).
West slavic are:
Czech, Slovak, Polish, Sorbian (lower and upper), Kashubian and Silesian.
I mean on mistake in documentation.
Thank You!
Marco

**Comment by rhdunn** [comment]
Thanks. I have now corrected the documentation for `cs`, `pl`, `ru` and `sk` so they are now classified as East/West Slavic languages correctly.

**Comment by Giovani93** [comment]
Thank You alot.
I'll look also to the codes, if there are for those languages too.
