### ISSUE TITLE
More description needed, about choosing English accent in other projects that integrate eSpeakNG

### ISSUE THREAD

**Issue by shadyar** [espeak-ng/espeak-ng#258]
@rhdunn 
#253 
it seams a good idea, just how about eg. NVDA user? (as you know, e-Speak-NG is integrated in this project)
I do not have any imagine, I would appreciate, if you could explain;which how do the Persian speakers will select English accent in NVDA project?
I should notify them, in time, because I publish a news-letter for users of e-Speak in Persian, the majority of them use NVDA.

**Comment by rhdunn** [comment]
This is a duplicate of https://github.com/espeak-ng/espeak-ng/issues/216, like https://github.com/espeak-ng/espeak-ng/issues/253 was.
