### ISSUE TITLE
regression in georgian language

### ISSUE THREAD

**Issue by beqabeqa473** [espeak-ng/espeak-ng#262]
hello reece.

in latest espeak update which is used in nvda georgian voice is broken, specifically letters are spelled when reading.

**Comment by beqabeqa473** [comment]
only english letters are speeled.

**Comment by rhdunn** [comment]
Hi beqa, I have identified the source of the regression and created a fix for the problem. I have also added a test case for this behaviour to prevent this regression happening again.
