### ISSUE TITLE
segfault in libespeak-ng when attempting to synthesize without selecting a voice

### ISSUE THREAD

**Issue by CMB** [espeak-ng/espeak-ng#267]
The following little program previously ran fine with espeak-1.48.04.
It segfaults with espeak-ng.

#include <string.h>
#include <espeak/speak_lib.h>
int main(void) {
	const char *text = "Hello!";
	int synth_flags = espeakCHARS_AUTO | espeakPHONEMES | espeakENDPAUSE;
	size_t size = strlen(text);
	espeak_Initialize(AUDIO_OUTPUT_PLAYBACK,0,NULL,0);
	espeak_Synth(text,size+1,0,POS_CHARACTER,0,synth_flags,NULL,NULL);
	espeak_Synchronize();
	return 0;
}

The segfault happens at line 406 of src/libespeak-ng/speech.c,
which reads:

	status = text_decoder_decode_string_multibyte(p_decoder, text, translator->encoding, flags);

translator is NULL, so it is a NULL pointer dereference.

**Comment by rhdunn** [comment]
Thanks for the bug report. I have pushed a fix for the problem and a few other related issues as well.
