### ISSUE TITLE
Turksih pronunciation with letter w

### ISSUE THREAD

**Issue by burakyuksek** [espeak-ng/espeak-ng#274]
Some time ago I requested that w should be pronounced as çift v. Can you make it so it can be pronounced as dabılyu instead? I am very sorry for the trouble I have caused. Thanks.

**Comment by valdisvi** [comment]
For Latvian I decided to use "Latvianized" pronunciation `d'ubve:_:` (as shortened one from proper `d'ubu>ltve:` which is too long for www etc.). Why you have decided to use pronunciation in English?

**Comment by burakyuksek** [comment]
Because the letter w is pronounced as dabılyu

**Comment by valdisvi** [comment]
Is [this](http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-x&text=w&formmethod=get) ok?

**Comment by burakyuksek** [comment]
Can't it be made so it pronounces it as dabılyu, exactly as I typed? Because it sounds most proper that way.

**Comment by valdisvi** [comment]
Sorry, I didn't look up that `ı` is pronounced as `@` ([schwa](https://en.wikipedia.org/wiki/Schwa)). It it OK [now](http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-x&text=w&formmethod=get)?

**Comment by burakyuksek** [comment]
If you can make it pronounce the letter y the way it originally does in Turkish, it will be better.

**Comment by valdisvi** [comment]
How is it now?

**Comment by burakyuksek** [comment]
It works. Thank you.

**Comment by valdisvi** [comment]
Good!
I made pull request to merge this into mainstream.
