### ISSUE TITLE
Add phonemes/IPA output to the emscripten js library

### ISSUE THREAD

**Issue by BenTalagan** [espeak-ng/espeak-ng#289]
Hello all,

One really nice feature would be imho to be able to retrieve phonemes for a synthesis thanks to the js library (in fact I am more specifically interested by the IPA output).

Is it hard to do ? It seems to me that everything is available since espeak_TextToPhonemes is exposed through the API right ? So it should just be converted to an asynchronous method belonging to the js worker then (by extending the existing glue) ?

Thanks!

**Comment by BenTalagan** [comment]
Ok, I'm trying to add this feature by myself and make a Pull Request. I just need a piece of advice on this. It's kind of working, I'm using the `espeak_SetPhonemeTrace` function from the API, plus the virtual file system from emscripten to write the result and get it to and from a file. This is more or less the heart of the feature, really simple) :

```
    espeak_SetPhonemeTrace(phoneme_conf, f_phonemes_out);
    espeak_Synth(aText, 0, 0, POS_CHARACTER, 0, 0, NULL, NULL);
    espeak_SetPhonemeTrace(phoneme_conf, NULL);
```

My question concerns the architecture of the demo ; currently, I am doing this by adding the feature as an asynchronous method to the espeakNG worker (like it's done for the rest of the demo). The problem that arrises is that I'm using the same instance of the worker to call both the synthesize (audio) & the synthesize_ipa (text) methods, the one created by : 

```
 tts = new eSpeakNG('js/espeakng.worker.js',...)
```

I'm not totally sure about what happens under the hood of the demo, but it seems to me that if this instance is shared, a text synthesis and an audio synthesis both running at the same time may interfere, right (i.e. it's not a good idea to turn on and off the phoneme trace while an audio synthesis is currently running) ? Should I create a second eSpeakNG instance dedicated to IPA synthesis?

Thanks!

**Comment by BenTalagan** [comment]
Ok, found the answer to my question : tasks executed from the worker seem to be queued in the message queue of the worker and executed one by one. 

But since each command may change the configuration of espeak, each command should prepare its own configuration carefully and do some cleanup at the end (this wasn't my case for the synthesis output, and the IPA output was enabling console output without disabling it).

I have written a PR : #292 for this feature.

**Comment by rhdunn** [comment]
I have merged the PR.

Thanks for implementing this feature.

**Comment by BenTalagan** [comment]
Awesome. Thanks, Reece!
