### ISSUE TITLE
Pronunciation of 'reputedly' is broken in current master for various english langs

### ISSUE THREAD

**Issue by BenTalagan** [espeak-ng/espeak-ng#294]
Hi all, in the current master, the pronunciation of the word 'reputedly' is broken : 

```
$ espeak-ng --ipa "reputedly" -v "en-gb"
ɹɪpˈʊtɪdli
```
whereas (with espeak 1.48.03  04.Mar.14)

````
$ espeak --ipa "reputedly" -v "en-gb"
 ɹɪpjˈuːtɪdlɪ
````

It seems quite recent, 1.49.1 does not have the problem.

**Comment by BenTalagan** [comment]
(Seems solved by commit 01919cd48a566cdf34347784b2e74554b376e900 ? , right ? 😌  )

**Comment by valdisvi** [comment]
Yes

**Comment by BenTalagan** [comment]
Awesome, thanks!
