### ISSUE TITLE
New espeak variant: Pablo

### ISSUE THREAD

**Issue by ehollig** [espeak-ng/espeak-ng#298]
Forwarding this on from https://github.com/nvaccess/nvda/issues/2704.
[pablo.zip](https://github.com/espeak-ng/espeak-ng/files/1205355/pablo.zip)

**Comment by bdorer** [comment]
@valdisvi would you include new variants? It would be really nice to have variants included in to NVDA in Linux for example. Would you accept a pull request?

**Comment by valdisvi** [comment]
This is already included in espeak-ng as [pablo](https://github.com/espeak-ng/espeak-ng/blob/master/espeak-ng-data/voices/!v/pablo) voice.
