### ISSUE TITLE
Loading voice !v/Annie crashes

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#299]
Hello,

The original test case was this: espeakup was given "" as voice parameter, leading to

    memset(&voice_select, 0, sizeof(voice_select));
    voice_select.languages = voice;
    rc = espeak_SetVoiceByProperties(&voice_select);

which ends up loading "!v/Annie", I guess because it's the last voice or something like that. This eventually leads to a crash here:

    				langopts->intonation_group = option_tone_flags & 0xff;

Here,  langopts is NULL because nothing has made it non-NULL before, thus the crash.

**Comment by rhdunn** [comment]
Hi,

Thanks for the detailed bug report. I could reproduce the issue by loading `!v/Annie` directly, but not via `espeak_SetVoiceByProperties`, with the latest code. I have fixed that crash in commit 16bea7fd0faa75e51e95d9f7aafa6d411019025d, as well as the other places that were referencing `langopts`.
