### ISSUE TITLE
mkdictlist is missed

### ISSUE THREAD

**Issue by linuxscout** [espeak-ng/espeak-ng#30]
The mkdictlist file is missed, I want to use it to add new voices for arabic

**Comment by rhdunn** [comment]
All `mkdictlist` was doing was editing the `Makefile.am` file -- you can add your language files directly to the makefile. Look for `af_dict` and `ph_afrikaans` for where to edit the file.

**Comment by linuxscout** [comment]
you must update the readme.md, #adding-new-voices

**Comment by rhdunn** [comment]
I will do, thanks.
