### ISSUE TITLE
making bg dictionary Segmentation fault

### ISSUE THREAD

**Issue by davidweenink** [espeak-ng/espeak-ng#318]
On my Linux Ububuntu 16.04 system I recently get a segmentation fault:
$ make dictionaries
  DICT      espeak-ng-data/bg_dict
/bin/bash: line 1:  1893 Segmentation fault      (core dumped) ESPEAK_DATA_PATH=/home/david/projects/espeak-ng LD_LIBRARY_PATH=../src: ../src/espeak-ng --compile=`echo espeak-ng-data/bg_dict | sed -e 's,espeak-ng-data/,,g' -e 's,_dict,,g'`
Makefile:2596: recipe for target 'espeak-ng-data/bg_dict' failed
make: *** [espeak-ng-data/bg_dict] Error 139

This occurs only for bg, making other dictionaries like is ok.
$ make fi
  DICT      espeak-ng-data/fi_dict
Using phonemetable: 'fi'
Compiling: 'fi_list'
        336 entries
Compiling: 'fi_emoji'
        1568 entries
Compiling: 'fi_extra'
        0 entries
Compiling: 'fi_rules'
        130 rules, 29 groups (0)

This error  was very recently introduced (< 3 weeks ago)

**Comment by rhdunn** [comment]
I cannot reproduce this locally. The espeak program will try to load the old version of the dictionary when compiling the new one. I made changes on 2017-07-26 to fix writing and reading the emoji dictionary entries, which will affect reading existing dictionary files written using the old, broken code.

Is this with a clean build? Can you use git bisect to identify the problem commit?

Does `rm -f espeak-ng-data/bg_dict && make bg` work?

**Comment by davidweenink** [comment]
Thank you for the tip.
Removing the old dictionaries first salved my problem.

Greetings,

david


On donderdag 19 oktober 2017 07:01:17 CEST Reece H. Dunn wrote:
> I cannot reproduce this locally. The espeak program will try to load the old
> version of the dictionary when compiling the new one. I made changes on
> 2017-07-26 to fix writing and reading the emoji dictionary entries, which
> will affect reading existing dictionary files written using the old, broken
> code.
> 
> Is this with a clean build? Can you use git bisect to identify the problem
> commit?
> 
> Does `rm -f espeak-ng-data/bg_dict && make bg` work?


-- 
David Weenink
Phonetic Sciences, University of Amsterdam
Spuistraat 134, room 6.33
1012 VB Amsterdam, The Netherlands
http://www.fon.hum.uva.nl/david
