### ISSUE TITLE
Mac OS X install

### ISSUE THREAD

**Issue by cainesap** [espeak-ng/espeak-ng#320]
Firstly, thanks for maintaining this great resource!

Second is my question, apologies if this is basic, but can anyone tell me what the 'LIBDIR' value should be for Mac OS X?

`sudo make LIBDIR=/usr/lib/x86_64-linux-gnu install`

**Comment by cainesap** [comment]
Resolved this:
```
sudo make LIBDIR=/usr/local/lib install
```

**Comment by SearaChen** [comment]
@cainesap  I had some what of a similar issue with you, I am wondering before you put sudo make LIBDIR=/usr/local/lib install   , what command did you put for  " ./configure --build=... --host=... --target=... "  ?  like what did you use in place of the ... for the option of build, host and target? 

Thank you so much!

**Comment by cainesap** [comment]
hi @SearaChen this was my config command. I didn't specify build, host, target --
```
./configure --exec-prefix=/usr/local/ --datarootdir=/usr/ --sysconfdir=/usr/local --sharedstatedir=/usr/local --localstatedir=/usr/local --includedir=/usr/local --with-extdict-ru --with-extdict-zh --with-extdict-zhy
```

**Comment by twerkmeister** [comment]
good stuff @cainesap! this helped a lot, I just need to adjust the datarootdir to /usr/local aswell

```
./configure --exec-prefix=/usr/local/ --datarootdir=/usr/local --sysconfdir=/usr/local --sharedstatedir=/usr/local --localstatedir=/usr/local --includedir=/usr/local --with-extdict-ru --with-extdict-zh --with-extdict-zhy
```
 
```
sudo make LIBDIR=/usr/local/lib install
```
