### ISSUE TITLE
Wrong stress on multisyllable English words

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#326]
When listening espeak, I have found several words, which (in my foreign opinion) has wrong stress on words, when they are in sentences.
E.g. single word "important" has stress on second syllable but on first syllable in some sentences:

```
espeak-ng -x -ven "Important."
 Imp'o@t@nt

espeak-ng -x -ven "This is important."
 DIs Iz Imp'o@t@nt
```
... sounds OK to me.

But in some sentences:
```
espeak-ng -ven -x "Something important."
  s'VmTIN 'Impo@t@nt

espeak-ng -ven -x "This is something important."
 DIs Iz s'VmTIN 'Impo@t@nt
```
Note that in these sentences "important" is spelled as ```'Impo@t@nt``` with stress on first syllable.

Is this OK?
("Important" is not the only word, but it is hard to catch them and reliably reproduce.)

**Comment by valdisvi** [comment]
It is actually regression. I used bisect, and the first bad commit is 119c200e00a46248bbaa149e8d0c3b1f19f86135

**Comment by valdisvi** [comment]
Unfortunately there are still cases when spelling of (now Latvian sentences) is wrong.

**Comment by valdisvi** [comment]
Failing sentence for Latvian:
```
espeak-ng -vlv -x "Neviena no Eiropas valstīm nekad nav pārgājusi no universālās (no visparējiem nodokļiem finansētas) sistēmas uz obligātās apdrošināšanas sistēmu Beigas."
```
Is:
```
 nev'ie:na no`_ 'eiRo:pas v'a>lsti:m nek,ad nav p'a:Rga:jusi no`_ 'univERsa::la:s_:_: no` visp'aRe:jiem n'uoduok}l^iem f'inansE:tas_:_: s'iste:mas uz 'obliga:ta:s 'apdRuoSina:Sanas s'iste: b'eigas
```
Should be:
```
 nev'ie:na no`_ 'eiRo:pas v'a>lsti:m nek,ad nav p'a:Rga:jusi no`_ 'univERsa::la:s_:_: no` visp'aRe:jiem n'uoduok}l^iem f'inansE:tas_:_: s'iste:mas uz 'obliga:ta:s 'apdRuoSina:Sanas s'iste:mas b'eigas
```

**Comment by rhdunn** [comment]
I have reverted the commit you identified in the bisect (thanks for locating the source of the issue), which also fixed the failing Latvian sentence. I have added these cases to the phoneme output test, and limited the change to just fix the line affecting emojis.
