### ISSUE TITLE
Digit 7 spelled wrong in Myanmar language

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#335]
When single digit **7** is passed for espeak-ng in Myanmar language, it is spelled wrongly:

```
espeak-ng -X -vmy "7"
Replace: 7   200D 1F466] 
Translate '200D'
Found: '_2' [n'i:]  
Found: '_0' [tonj'a:]  
Found: '_0' [tonj'a:]  
Translate '1F466]'
Found: '_1' [t'i:]  
 n'i:tonj'a:_!tonj'a:
```
where `n'i:tonj'a:_!tonj'a:` comes from spelling of unexpected translation to **200**.

It should be spelled in following way instead:

```
espeak-ng -X -vmy "7"
Translate '7'
Found: '_7' [kon'i]  
 kon'i
```
similarly to other digits, for example **6**:

```
espeak-ng -X -vmy "6"
Translate '6'
Found: '_6' [tSa:]  
 tS'a:
```

**Comment by rhdunn** [comment]
Fixed in issue #332.
