### ISSUE TITLE
Why my espeak-ng program doesn't say anything?

### ISSUE THREAD

**Issue by ghost** [espeak-ng/espeak-ng#337]
I want to pass a string to espeak-ng and it reads my string by sound!

I searched and found this program and did a little modification to change it to English from Italian(under the commented lines), but didn't work:

```
#include <string.h>
#include <malloc.h>
#include <espeak-ng/speak_lib.h>



espeak_POSITION_TYPE position_type;
espeak_AUDIO_OUTPUT output;
char *path=NULL;
int Buflength = 500, Options=0;
void* user_data;
t_espeak_callback *SynthCallback;
espeak_PARAMETER Parm;



//char Voice[] = {"lt+klatt2"};
 char Voice[] = {"English"};

char text[30] = {"this is a english test"};
unsigned int Size,position=0, end_position=0, flags=espeakCHARS_AUTO, *unique_identifier;




int main(int argc, char* argv[] ) 
{
    output = AUDIO_OUTPUT_PLAYBACK;
    int I, Run = 1, L;    
    espeak_Initialize(output, Buflength, path, Options ); 
    espeak_SetVoiceByName(Voice);
    //const char *langNativeString = "lt"; //Default to US English
    const char *langNativeString = "en"; //Default to US English
    espeak_VOICE voice;
    memset(&voice, 0, sizeof(espeak_VOICE)); // Zero out the voice first
    voice.languages = langNativeString;
    //voice.name = "klatt";
    voice.name = "US";
    voice.variant = 2;
    voice.gender = 1;
    espeak_SetVoiceByProperties(&voice);
    Size = strlen(text)+1;    
    printf("Saying  '%s'",text);
    espeak_Synth( text, Size, position, position_type, end_position, flags,
    unique_identifier, user_data );
    espeak_Synchronize( );
    printf("\n:Done\n"); 
    return 0;
}
```

It compiles without errors and makes speaks as executable file but when I try ./speaks the result is:

```
Saying  'this is a english test'
:Done
```

Without voice!

**Comment by rhdunn** [comment]
The `path` parameter of `espeak_Initialize` needs to point to the `espeak-ng-data` directory, or its parent directory. Alternatively, you can set the `ESPEAK_DATA_PATH` environment variable to point to that directory.

You only need to call one of `espeak_SetVoiceByName` or `espeak_SetVoiceByProperties`.

The methods will usually provide a return code to indicate success or failure, so you can use that to report errors. NOTE: The `espeak_ng_` variants of the APIs provide more specific details of what went wrong; the error context is to provide information like file path parameters to the error code formatting APIs.

The `src/espeak-ng.c` file is the source to `espeak-ng` and provides an example of using the `espeak-ng` specific APIs.

**Comment by roboticslover** [comment]
Hi rhdunn,
Thanks for help, may you tell me how to set ESPEAK_DATA_PATH environment variable?
I know it's in `/usr/local/share/espeak-ng-data'

**Comment by roboticslover** [comment]
I tried to add this line to `etc/environment' but didn't work:  `ESPEAK_DATA_PATH=/usr/local/share/espeak-ng-data`

**Comment by valdisvi** [comment]
You can try to look at and customize [espeak-ng.c](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.c) file.

**Comment by valdisvi** [comment]
Related issue #317

**Comment by valdisvi** [comment]
I  spend quite much time to get parameters right to compile your example.
But after compiling with `gcc test.c -lespeak-ng -o test` I got it working immediately.

Probably you don't have `espeak-data` folder or it is in wrong place. If you use Debian packaging guidelines (as well as [eSpeakNG insructions](https://github.com/espeak-ng/espeak-ng/#installing)), actual folder is `/usr/lib/x86_64-linux-gnu/espeak-data`, or it could also be `/usr/share/espeak-ng-data` (and if you use installed version of espeak-ng, one of them could be symbolic link as well as links  named `espeak-data`.
`/usr/local/share/espeak-ng-data` could be used if you build and install it as local application.

**Comment by RomanVia** [comment]
Hi,

I use the code of roboticslover and it's been 2 days since I can not solve the following errors : 

```
error LNK2019: unresolved external symbol __imp_espeak_Initialize refereed in function "public: void __cdecl AMyActor :: TestESpeak (void)" (? TestESpeak @ AMyActor @@ QEAAXXZ)
error LNK2019: unresolved external symbol __imp_espeak_Synth refereed in function "public: void __cdecl AMyActor :: TestESpeak (void)" (? TestESpeak @ AMyActor @@ QEAAXXZ)
error LNK2019: unresolved external symbol __imp_espeak_SetVoiceByProperties referenced in function "public: void __cdecl AMyActor :: TestESpeak (void)" (? TestESpeak @ AMyActor @@ QEAAXXZ)
error LNK2019: unresolved external symbol __imp_espeak_Synchronize refereed in function "public: void __cdecl AMyActor :: TestESpeak (void)" (? TestESpeak @ AMyActor @@ QEAAXXZ)
```

I have the impression that this comes from the inclusion of the bookstore but I have this line : 
`#include "espeak-ng/espeak-ng/speak_lib.h"`

Ps : I use Visual Studio as IDE for my project with unreal engine

**Comment by valdisvi** [comment]
I've found on Ubuntu (i.e. Lubuntu 16.04, if it matters), that, if `espeak-ng` is compiled and installed without [pcaudiolib](https://github.com/espeak-ng/pcaudiolib) compiled and installed before, then calling it simply
```
espeak-ng hello
```
doesn't produce any sound.
Then usual workaround with sending data standard output and piping it to `aplay` (Lubuntu) or `paplay` (Ubuntu) works:
```
espeak-ng hello --stdout|aplay
```
But, when `pcaudiolib` is compiled and installed and espeak-ng is reconfigured, recompiled and reinstalled again, simple call works properly.

I wonder, should we add such note in [README](README.md#building)?

**Comment by valdisvi** [comment]
I have created more detailed guides for usage and error solutions [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/guide.md).

**Comment by Dumisanik** [comment]
In my case, I had to disable PortAudio and opt for PulseAudio in Ubuntu 18. Then audio worked. I made this change in the Makefile when building [speak version 1.48](http://sourceforge.net/projects/espeak/files/espeak/espeak-1.48/espeak-1.48.04-source.zip)

```
#AUDIO = portaudio
AUDIO = pulseaudio
```

**Comment by jaacoppi** [comment]
> In my case, I had to disable PortAudio and opt for PulseAudio in Ubuntu 18 then audio worked. I made this change in the Makefile when building [speak version 1.48](http://sourceforge.net/projects/espeak/files/espeak/espeak-1.48/espeak-1.48.04-source.zip)

That is a very old version of espeak. This project is espeak-ng. Try our latest version and see if it builds correctly. It should, but Pulseaudio is not a dependency anymore so you can't switch to it anyways.
