### ISSUE TITLE
Hardcoded rpath in executable

### ISSUE THREAD

**Issue by luigino** [espeak-ng/espeak-ng#342]
Packaging for openSUSE linux.
When passing the --disable-static switch, speak-ng ends up with a hardcoded rpath that rpm doesn't like.

```
ERROR: RPATH "/home/abuild/rpmbuild/BUILD/espeak-ng-1.49.3dev.ge6590cad/src/.libs" on /home/abuild/rpmbuild/BUILDROOT/espeak-ng-1.49.3dev.ge6590cad-0.x86_64/usr/bin/speak-ng is not allowed
```
--disable-rpath is seemingly ignored.

**Comment by jaacoppi** [comment]
Please post the exact commands and configuration used to reproduce this error.

**Comment by rhdunn** [comment]
The build is generating a local `libtool` script. The configure.ac file does not have a `--disable-rpath` option. It should be added and follow the OpenSUSE guide for patching rpath from the local libtool script:

```
# See https://old-en.opensuse.org/openSUSE:Packaging_Guidelines#Removing_Rpath
sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool
```

References:
1. https://wiki.debian.org/RpathIssue
1. https://old-en.opensuse.org/openSUSE:Packaging_Guidelines#Beware_of_Rpath
