### ISSUE TITLE
Big bug in Mandarin Chinese

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#346]
Hi!
I have tested the new Espeak and I have found some bug. Characters in Mandarin Chinese are pronounced, like letter and some kind of number. For example in character for gong luo, character is pronounced as luo yi. I don't know, why.
Please, could You fix It?
Thank You.

**Comment by valdisvi** [comment]
This is already fixed issue #338 in development version espeak-ng.
