### ISSUE TITLE
Bug around Chinese Mandarin in Espeak has been discovered

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#348]
Hi!
I have discovered bug in Mandarin Chinese of Espeak. Here is copy of My e-mail sent to one mailing list.
OK, bug is discovered, I think It is misstake of Espeak NG. 
There are two voices classified, as Mandarin Chinese. One is incorrect and countains bugs. Two voices labelled, as Mandarin Chinese in direction with chinese voices. 
Please, could You look to this folder and fix the bug?
Thank You.
Marco

**Comment by Giovani93** [comment]
Please, test It in this page, there are two Chinese mandarin Espeak and this is not very good for NVDA.
http://odo.lv/Espeak?language=en

**Comment by rhdunn** [comment]
There is only one instance of each Chinese voice listed by espeak-ng, and via its API:

    $ src/espeak-ng --voices | grep Chinese
     5  cmn             --/M      Chinese_(Mandarin) sit/cmn              (zh-cmn 5)(zh 5)
     5  yue             --/M      Chinese_(Cantonese) sit/yue              (zh-yue 5)(zh 8)

Therefore, this is a bug in the odo.lv page and NVDA.

**Comment by rhdunn** [comment]
NOTE: If they are not removing the previous voice files when copying over the new ones, they may have added duplicate voice entries from changes to the layout of that directory in previous versions of espeak-ng, including the move from the `voices` directory to the `lang` directory. In that case, the MBROLA voices and the voice variants are listed in the `voices` directory, while the languages are in the lang` directory.

**Comment by valdisvi** [comment]
I fixed list of languages on the test page.
I don't know about NVDA, but invoking espeak-ng in command line,  `cmn` or `zh-cmn`, and `yue` or `zh-yue` work as synonyms for voice parameters:
```
$ espeak-ng -x -vcmn "铁人麝香：从特斯拉到太空探索"
 th'iE21_| z.'@35n_| s.'o-51_| S;'iA55N_|
 tsh'ong35_| th'@51_| s'i[55_| l'A55_| t'Au51_| th'ai51_| kh'ong55_| th'a51n_| s'uo214_|

$ espeak-ng -x -vzh-cmn "铁人麝香：从特斯拉到太空探索"
 th'iE21_| z.'@35n_| s.'o-51_| S;'iA55N_|
 tsh'ong35_| th'@51_| s'i[55_| l'A55_| t'Au51_| th'ai51_| kh'ong55_| th'a51n_| s'uo214_|

$ espeak-ng -x -vyue "铁人麝香：从特斯拉到太空探索"
 t'i3t_| j'a4n_| s'e6_| h'oeng1_|
 c'ung4_| d'a6k_| s'i1_| l'aai1_| d'ou3_| t'aai3_| h'ung1_| t'aa3m_| s'o3k_|

$ espeak-ng -x -vzh-yue "铁人麝香：从特斯拉到太空探索"
 t'i3t_| j'a4n_| s'e6_| h'oeng1_|
 c'ung4_| d'a6k_| s'i1_| l'aai1_| d'ou3_| t'aai3_| h'ung1_| t'aa3m_| s'o3k_|
```
