### ISSUE TITLE
Bad Pronunciation in French ɔ̃

### ISSUE THREAD

**Issue by Shallowmallow** [espeak-ng/espeak-ng#350]
In words with ɔ̃
like ronron tonton ponton maison million pont ion donc maison section rayon
maison mɛzˈɔ̃ we hear maiso
It seems we hear it correctly when it is followed by a vowel
like "pont et demi"

**Comment by Shallowmallow** [comment]
Okay . I was able to do to a O~ sound with espeak edit . I have just one tiny problem. I can  save ( and load them ) my files from espeakedit. But I cannot see them in the explorer on in command administrato mode ( windows 8). So I cannot post it.
I could always take a screenshot of my frames ....

**Comment by valdisvi** [comment]
By listening samples of [The sounds [ɔ̃], [ɑ̃] and [ɛ̃] - Phonetics](http://parlons-francais.tv5monde.com/Webdocs-to-learn-French/Memos/Phonetique/p-285-lg1-Les-sons--et-.htm) I made provided phoneme with wider frequency window (i.e. less resonant) around 4th formant of 3520Hz.
Before you adjust/create new phonemes I recommend to analyze recorded samples with Audacity's (frequency spectrogram view)[https://manual.audacityteam.org/man/spectrogram_view.html]. After that you can simply transform Audacity's view of 'horizontal-time/vertical spectrum' into eSpeakEdit's 'vertical-time/horizontal-spectrum' frames.

**Comment by Shallowmallow** [comment]
Thanks. It is understandable at least , which is the most important :). I'll try to do what you've said and see if I can improve it.

**Comment by valdisvi** [comment]
Karl provided better definition. I think now it is more or less ok. As usual, you can check it [online](https://odo.lv/Espeak).
