### ISSUE TITLE
Bad pronunciation in French "qua"

### ISSUE THREAD

**Issue by Shallowmallow** [espeak-ng/espeak-ng#355]
Words starting with "qua" are often badly pronounced.
There are two pronunciation of qua in French  "kwa " and "ka" ( I don't know which is more common)
quatorze quadrant, quadriceps, quantité  all use the "kw" sound instead of the "k" sound
(quantitté which is an incorrect work actually have the correct "k" sound)

**Comment by jaacoppi** [comment]
Please see the code:
https://github.com/espeak-ng/espeak-ng/blob/a61a0e6523a0ae981ee7a6fe736912beeb48d895/dictsource/fr_rules#L1104-L1119

Which cases should be kwa, and which ka? The syntax is in https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#pronunciation-rules

**Comment by Shallowmallow** [comment]
Thanks I'll make few tests . It seems it's missing some cases.

**Comment by Shallowmallow** [comment]
Thanks
 What I found was good.

        q          k        // coq
     _) qu' (AP3   k
     _) qua (d     kwa       // quadrature
     _) qua (tA    kwa       // quaternaire
 _   _) quan (tA kA~ // quantique, quantité, quantifié
     _) qua(to  ka//quatorze
     _) qua (drill ka        // quadriller
    _a) qua        kwa       // aquarium
    _a) qu (if     ku        // aquifère
    _A) qui (dist  kyi      // équidistant
    _A) qui (lat   kyi      // équilatéral
    _C) qua        kwa       // squale square
    _A) qua        kwa       // équateur
    dé) qua        kwa       // adequate
    _) qua (r ka// quarantain
        qu         k         // quatre
     _) que (_     k@        // que
     n) q (_       k         // cinq
     n) q (_mill                // cinq mille
     n) q (_cent_                // cinq cent

+ adding the words and quartet
quarto kwarto
quartet kwartEt

**Comment by valdisvi** [comment]
For GitHub markdown syntax look at [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) particularly for [code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code}

**Comment by valdisvi** [comment]
I sorted rules and did [some formatting](https://github.com/valdisvi/espeak-ng/blob/99cbb4f03b44857d7e94f7a8737ca6383fa78da6/dictsource/fr_rules#L1104)
