### ISSUE TITLE
System error in espeak-ng.exe of espeak-ng-x64.msi

### ISSUE THREAD

**Issue by smtsh** [espeak-ng/espeak-ng#357]
I have windows 7 ultimate with service pack 1 installed. 
I installed latest version of espeak-ng-x64.msi but I get error at lunching of espeak-ng.exe!
A dialog box entitled "espeak-ng.exe - System error" apeared that say: The program can't start because XAudio2_8.dll is missing from your computer. Try reinstalling the program to fix this problem.
Although I reinstalled program again but XAudio2_8.dll missing error remained!

**Comment by rhdunn** [comment]
Duplicate of https://github.com/espeak-ng/espeak-ng/issues/209.
