### ISSUE TITLE
Problems in Greek language

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#359]
There is a problem in Greek language. Somebody removed another letters of politonic Greek from Espeak. Those letters are not speak.
Please, could You look on this problem?
Thank You.
Marco

**Comment by valdisvi** [comment]
It is not problem of eSpeakNG (development version).
[Here are rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/el_rules#L19) and [here is demo](https://odo.lv/Espeak?eslang=-vel&speed=160&output=-w&debug=-x&text=%CE%A0%CE%AC%CF%84%CE%B5%CF%81+%E1%BC%A1%CE%BC%E1%BF%B6%CE%BD+%E1%BD%81+%E1%BC%90%CE%BD+%CF%84%CE%BF%E1%BF%96%CF%82+%CE%BF%E1%BD%90%CF%81%CE%B1%CE%BD%CE%BF%E1%BF%96%CF%82%C2%B7+%E1%BC%81%CE%B3%CE%B9%CE%B1%CF%83%CE%B8%CE%AE%CF%84%CF%89+%CF%84%E1%BD%B8+%E1%BD%84%CE%BD%CE%BF%CE%BC%CE%AC+%CF%83%CE%BF%CF%85%C2%B7%0D%0A%E1%BC%90%CE%BB%CE%B8%CE%AD%CF%84%CF%89+%E1%BC%A1+%CE%B2%CE%B1%CF%83%CE%B9%CE%BB%CE%B5%CE%AF%CE%B1+%CF%83%CE%BF%CF%85%C2%B7&formmethod=get).
