### ISSUE TITLE
speech.h should not hardcode platform-specific defines

### ISSUE THREAD

**Issue by michaelDCurran** [espeak-ng/espeak-ng#36]
Currently at master 36be9ac src/libespeak-ng/speech.h line 41: PLATFORM_POSIX is a hardcoded define.
  This makes it impossible to compile on non-posix platforms such as Windows, even by providing contrary PLATFORM_* defines via compiler commandlines.
Perhaps it is a work in progress to move the code across to some kind of configure.h.in or equivalent, but for now this is completely breaking compilation of libespeak-ng on Windows for NVDA. 

Note that commenting this line out, addressing the fclose bug in LoadSpectSeq, handling NULL log FILE arguments in compilePhonemeData and compileIntonations, and addressing the phsource directory check in compilePhonemeData2, libespeak-ng is being successfully compiled and used by NVDA.

**Comment by rhdunn** [comment]
This applies to the other platform-specific defines in `speech.h` (e.g. `USE_NANOSLEEP`).

The configure script generates a `config.h` file for supported definitions, so that should be used for platform configurations. A Windows-specific `config.h` file should be created in `src/windows`.

**Comment by michaelDCurran** [comment]
Unless I'm missing something, config.h is not yet referenced by any 
source files, and would probably be a bit of work to do so.

Therefore for now, would it be at least possible if PLATFORM_POSIX could 
stop being defined in speech.h, and instead be passed in as a define in 
compiler commands (i.e. change Makefile.am)?
I know that this may sound hackish, but this is the *only* issue 
stopping NVDA Windows builds, that requires a direct change to a source 
file. The others, such as !access, or strings.h can all be worked around 
via our build system with more defines or extra include directories etc.

By all means config.h should eventually be used. But in the short term, 
it would be nice if there was not code that forceably broke a particular 
platform (even if unintentional).

As far as other defines in speech.h go: nothing is breaking NVDA Windows 
builds, so they obviously just don't apply in our particular scenario I 
guess.

On 17/12/2015 11:19 PM, Reece Dunn wrote:
>
> This applies to the other platform-specific defines in |speech.h| 
> (e.g. |USE_NANOSLEEP|).
>
> The configure script generates a |config.h| file for supported 
> definitions, so that should be used for platform configurations. A 
> Windows-specific |config.h| file should be created in |src/windows|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/espeak-ng/espeak-ng/issues/36#issuecomment-165451557>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by rhdunn** [comment]
I have incorporated the defines from the Windows speech.h file under a `_WIN32 || _WIN64` check. Thus, on Windows builds `PLATFORM_WINDOWS` should be defined and on non-Windows builds `PLATFORM_POSIX` should be defined.

This should fix the issues you are having at the moment. In the longer term, I can figure out how best to support the platform differences in a more consistent way.
