### ISSUE TITLE
can't split the syllables accurately & show the tone number

### ISSUE THREAD

**Issue by Yoxem** [espeak-ng/espeak-ng#361]
I've tried to add Hakka Chinese (using https://en.wikipedia.org/wiki/Pha%CC%8Dk-fa-s%E1%B9%B3 phak-fa-su as the Romanizing system). I finally create/modified the related files (as the attachments [hak-related.zip](https://github.com/espeak-ng/espeak-ng/files/1592575/hak-related.zip)).
However, I can't make the splitting of the syllables accurately.
for example:
as I added "iu iu" and "3 3" in hak_rules, "hiúng" should be converted to hiuN3 or hiu3N (I'm not clear). but It gives:
$ espeak -x -X "hiúng" -v hak
Translate 'hi'
  1	h        [h]

  1	i        [i]

Translate 'u'
  1	u        [u]

Translate 'ng'
  1	n        [n]
 22	ng       [N]

 h'i 'u N

and the tone number can't be shown as in Mandarin Chinese, eg（兄 xiong1

）:
espeak -x -X "兄" -v cmn

Replace: 兄   xiong1 
Translate 'xiong1'
  1	x        [S;]

  1	i        [i]
 68	io (DngK [y]

  1	n        [n]
 42	ng (K    [N]

 22	1        [55]

 S;'y55N_|
how could I solve it?

**Comment by valdisvi** [comment]
I have added all files in [my project](https://github.com/valdisvi/espeak-ng/commit/75e42d687083451e19493ce3511195dc7c90eb8f) with few modifications which you can test [online](https://odo.lv/Espeak) Missing part were settings in [tr_languages.c](https://github.com/valdisvi/espeak-ng/blob/master/src/libespeak-ng/tr_languages.c#L802) as currently all language settings can't  be set in language configuration file. Please review it (and compare e.g. with Chinese) if some other advanced settings are necessary.
