### ISSUE TITLE
How to make tone sandhi works like Mandarin Chinese.

### ISSUE THREAD

**Issue by Yoxem** [espeak-ng/espeak-ng#364]
Like lots of Sinitic languages (aka Chinese Vernaculars), There's rules of tone sandhi in Hakka Chinese.
The tone of a 1st-tone (yinping 陰平) syllable that is in front of another 1st-tone or 4th-tone (yinqu 陰去) or 6th-tone (yangru 陽入) should be changed to the 2nd-tone. For example, "Kâ-chû" (Ka1-chu1, lit. California) should be pronounced as "Ka2chu1" (k'a2ts'u1). but the result is as below (with the version in my repo: https://github.com/Yoxem/espeak-ng):
$espeak -v hak "Kâ-chû" -x -X # Ka1-chu1
```
Translate 'ka1'
  1	k        [k]

  1	a        [a]

 22	1        [1]

Translate 'chu1'
 22	ch       [ts]

  1	u        [u]

 22	1        [1]

 k'a1ts'u1

```
However, the tone sandhi of Mandarin (the tone of tone-214 syllable in front of another tone-214 tone is changed to tone-35) works. eg 雨傘 (yu214 san214 -> yu35 san214):
```
espeak -v zh "雨傘" -x -X
Replace: 雨   yu3 
Translate 'yu3'
 22	y (u     []
 36	y (uK    [;]
  1	y        [j]

  1	u        [u]
 27	L01) u   [y]

 22	3        [214]

Replace: 傘   san3 
Translate 'san3'
  1	s        [s]

 44	a (DnK   [a]
  1	a        [A]

  1	n        [n]

 22	3        [214]

 ;'y35_| s'a214n_| #'y214 is changed to 'y35 automatically

```
Even though the tone sandhi rule is not defined in zh_list or zh_rules, the tone-sandhi rule works. How do I implement this kind of tone sandhi rule to Hakka Chinese?

**Comment by jaacoppi** [comment]
The code is here:
https://github.com/espeak-ng/espeak-ng/blob/314e9f2e36800c1fde62e32db8da2bc050022cee/src/libespeak-ng/intonation.c#L849-L860

It looks like you can simply add a check for hakka there so it works exactly like mandarin. Do you want to push the commit yourself?

**Comment by Yoxem** [comment]
the code may be like:

````
......
		if (p->synthflags & SFLAG_SYLLABLE) {
			tone_ph = p->tone_ph;
			tph = phoneme_tab[tone_ph];
		// hakka
			if (tr->translator_name == L('h','a','k')){
                            if (prev_p->tone_ph == PhonemeCode2('1')){
                                    if (p->tone_ph = PhonemeCode2('1')|| p->tone_ph = PhonemeCode2('4')|| p->tone_ph = PhonemeCode2('6')){
                                              prev_p->tone_ph == PhonemeCode2('2')
                                   }
                            }
			}
			// Mandarin
			if (tr->translator_name == L('z', 'h')) {
				if (tone_ph == 0) {
					if (pause || tone_promoted) {
						tone_ph = PhonemeCode2('5', '5'); // no previous vowel, use tone 1
						tone_promoted = 1;
	.....
````
but I don't know how it actually works, please help me modify the code. Thank you a lot.

**Comment by jaacoppi** [comment]
You are using the tone numbers in PhonemeCode2(). That is wrong. The phoneme codes for mandarin chinese are found here:
https://github.com/espeak-ng/espeak-ng/blob/314e9f2e36800c1fde62e32db8da2bc050022cee/dictsource/zh_rules#L294-L300.

As you can see, tone 1 is actually PhonemeCode2('5', '5') and tone 2 is PhonemeCode2('3', '5').

If you want to make Hakka sandhi for the tones 1 and 2 sound exactly like mandarin, the best way to do is to use the same code:
Change the line
https://github.com/espeak-ng/espeak-ng/blob/314e9f2e36800c1fde62e32db8da2bc050022cee/src/libespeak-ng/intonation.c#L849

to
			if (tr->translator_name == L('z', 'h') || tr->translator_name == L('h', 'a', 'k')) {

and see if that works. Intonation.c is a big file so it can be that I am wrong and the real reason for mandarin sandhi is elsewhere in the file.

**Comment by jaacoppi** [comment]
(I just deleted my previous post from 30 minutes ago because it was full of mistakes).

I think my first code sample was the wrong place to look. For example, the code for the 雨傘 (yu214 san214 -> yu35 san214) is here:
https://github.com/espeak-ng/espeak-ng/blob/314e9f2e36800c1fde62e32db8da2bc050022cee/src/libespeak-ng/intonation.c#L869-L871

Something like this should work for your conversion of Kâ-chû:
```
if (tr->translator_name == L('h', 'a', 'k') {
    if (prevw_tph->mnemonic == FIRST_TONE)
 	    if (tph->mnemonic == FIRST_TONE || tph->mnemonic == FOURTH_TONE)
               prev_p->tone_ph = PhonemeCode2(SECOND_TONE);
}
```

I don't know what the correct numbers for TONES are. The tone numbers used for mandarin are not 1,2,3,4 but instead can be found here:
https://github.com/espeak-ng/espeak-ng/blob/314e9f2e36800c1fde62e32db8da2bc050022cee/dictsource/zh_rules#L294-L300

I am not sure why those numbers are used and if Hakka should use the same tone numbers or something else. Also, I don't know how to convert them to hex values, but looking at intonation.c it seems that 0x3131 equals 11 (tone 5) and so on.

**Comment by Yoxem** [comment]
Ok, I've modified the code, see: https://github.com/valdisvi/espeak-ng/pull/2/files

It seems to work. 
```
$ espeak -v hak "Sîn-chûng Thièn-hang ôn-lo̍k" -x -X
Translate 'si1n'
  1	s        [s]
 22	s (i     [S;]

  1	i        [i]

 22	1        [1]

  1	n        [n]

Translate 'chu1ng'
 22	ch       [ts]

  1	u        [u]
 85	u1ng (_  [uN1]

Translate 'thie2n'
  1	t        [t]
 22	th       [th]

  1	i        [i]
 63	ie2 (L02 [ie2]

  1	n        [n]

Translate 'hang'
  1	h        [h]

  1	a        [a]
 21	a (L02   [a4]

  1	n        [n]
 22	ng       [N]

Translate 'o1n'
  1	o        [o]
 64	o1n (_   [on1]

Translate 'lo̍k'
  1	l        [l]

  1	o        [o]
 42	o̍ (L01 [o6]

  1	k        [k]

 S;'i2nts'u1N th'ie2nh'a4N 'o2nl'o6k

```

**Comment by jaacoppi** [comment]
This is merged in https://github.com/espeak-ng/espeak-ng/commit/e8fbe6a5affe3cd9064d234a4dca0bc4bdca4a65. The issue can be closed.
