### ISSUE TITLE
Is it possible to substitute espeak-ng for espeak as default module of speech-dispatcher?

### ISSUE THREAD

**Issue by guest271314** [espeak-ng/espeak-ng#365]
Is it possible to substitute espeak-ng for espeak as default module of [`speech-dispatcher`](https://devel.freebsoft.org/speechd)? If the above is possible, can we set the `m` option as default for all calls to `espeak-ng` during unix socket connections to browsers?

**Comment by jaacoppi** [comment]
As far as I know the API of espeak and espeak-ng  are 100% compatible, so yes you can. A [quick search ](https://github.com/brailcom/speechd/search?utf8=%E2%9C%93&q=espeak-ng&type=) implies that espeak-ng is already supported by speech-dispatcher so setting it default is a trivial task.

I think this issue can be closed here and a new one opened at speech-dispatcher  if needed.

**Comment by guest271314** [comment]
@jaacoppi Already opened and closed an issue at speech-dispatcher https://github.com/brailcom/speechd/issues/1.

How to achieve the second question?
