### ISSUE TITLE
How to make a rule that "tur" at the end of a word is stressed?

### ISSUE THREAD

**Issue by hozosch** [espeak-ng/espeak-ng#375]
As far as I know, there isn't a rule to tell espeak that "Tur" is stressed at the end of a word. I could only make a rule that would stress it practically everywhere, but I would like to have an option that tells espeak to stress the "U" in "tur" if it is the last 3 characters in a string.

**Comment by jaacoppi** [comment]
See https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md

There is symbol  to add secondary stress: ","
There is a way to handle cases at end of word: "(_"
Combine these two and you'll have:

```
.group t
        tur (_        ,tur
```

I think this issue can be closed.
