### ISSUE TITLE
Documentation: unused reference to Place of Articulation phontab.md

### ISSUE THREAD

**Issue by jaacoppi** [espeak-ng/espeak-ng#386]
Place of articulation  is mentioned in contents of phontab.md:

https://github.com/espeak-ng/espeak-ng/blob/16dffab873845a839eb47d8b2db82578aaa8944d/docs/phontab.md#L8

However, the actual documentation is missing and #place-of-articulation leads nowhere.

**Comment by jaacoppi** [comment]
Place of articulation is already fully documented in phonemes.md. Reference to it should be removed in phontab.md.

**Comment by rhdunn** [comment]
That is correct. I have pushed a commit that fixes this.
