### ISSUE TITLE
SSML <prosody> element rate attribute applies previous <prosody> element rate attribute

### ISSUE THREAD

**Issue by guest271314** [espeak-ng/espeak-ng#401]
Given SSML 

`<prosody rate="default">I am now  speaking at default speed. </prosody>`

when passed as argument to `espeak-ng` with `-m` option without adjacent `<prosody>` element which has a `rate` set to a different value the expected result is output as audio.

When a `<prosody>` element is followed by a `<prosody>` element which has a different `rate` set, the former rate is applied to the latter `<prosody>` element.

````
$ espeak-ng -m '<break time="1s"> <prosody rate="x-fast">I am now  speaking at fast speed. </prosody> <break time="1s"/> <!-- "x-fast" `rate` is applied where `"default"` should be applied --> <prosody rate="default">I am now  speaking at default speed. </prosody><break time="1s"/><prosody rate="slow"> I am now speaking at slow speed. </prosody>'
````

Version: eSpeak NG text-to-speech: 1.49.3-dev

**Comment by jaacoppi** [comment]
https://github.com/espeak-ng/espeak-ng/blob/f096ca7bb572f8d107a142afbaa3ad6b5ef7400c/src/libespeak-ng/readclause.c#L719

This evaluates to false when changing from non-default value to default value.  A quick and dirty fix would be to skip the evaluation and simply use `value = new_parameters[param]` instead. That would probably be a waste of cpu resources. The real problem is probably somewhere else.

**Comment by jaacoppi** [comment]
This seems to work fine: 
`<break time="1s"> <prosody rate="x-fast">I am now speaking fast speed</prosody> <break time="1s"/> <!-- "x-fast" `rate` is applied where `"default"` should be applied --> <prosody rate="default">I am now speaking default speed</prosody><break time="1s"/><prosody rate="slow">I am now speaking slow speed</prosody>`

Somehow the  ".  " at the end of sentence causes problems for handling  `outbuf`. Perhaps this is a null termination issue and not an SSML issue?

**Comment by guest271314** [comment]
The "." character appears to be the issue. Why?

**Comment by jaacoppi** [comment]
The embedded command to switch back to default speed is inserted at the end of each sentence. For some reason, espeak-ng stops reading the sentence after the '.' so the embedded command is never run.

Most likely this has something to do with `terminator` or the parts with `c =  '  ' `  in readclause.c or transtate.c

**Comment by jaacoppi** [comment]
I'm pretty sure I found it:

This part sets `end_clause_after_tag`:
https://github.com/espeak-ng/espeak-ng/blob/f096ca7bb572f8d107a142afbaa3ad6b5ef7400c/src/libespeak-ng/readclause.c#L2018-L2022

This part deletes everything after the . in the sentence when `end_clause_after_tag` is set:
https://github.com/espeak-ng/espeak-ng/blob/f096ca7bb572f8d107a142afbaa3ad6b5ef7400c/src/libespeak-ng/readclause.c#L1714-L1718

The embedded command to return to default rate is never ran. I'll see if I can come up with a fix.
