### ISSUE TITLE
I can not understand this part of the tutorial(Building Android)

### ISSUE THREAD

**Issue by rezaee** [espeak-ng/espeak-ng#409]
```
Building with Gradle
Set the location of the Android SDK:

$ export ANDROID_HOME=<path-to-the-android-sdk>
Build the project:

$ ./autogen.sh
$ ./configure --with-gradle=<path-to-gradle>
$ make apk-release
This will create an android/build/outputs/apk/espeak-release-unsigned.apk file.
```

I can't understand it tries to build what? Also what if I use Windows and Android Studio?

**Comment by jaacoppi** [comment]
It seems  you can use Gradle with Android Studio on Windows. See the source subdirectory android for necessary files.

Further reading:

configure and make:
[](https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install)

Makefile:
[](https://www.cprogramming.com/tutorial/makefiles.html)

Gradle:
[](https://gradle.org/)

**Comment by rhdunn** [comment]
The `espeak-release-unsigned.apk` file is an Android package for the espeak project on Android. That command builds everything needed by the package. Specifically:
1.  It builds espeak-ng locally (using the local gcc or clang compiler) as this is needed to build the language dictionaries and voice files;
2.  Builds the dictionaries and voice files;
3.  Creates a zip with the dictionaries and voice files that the Android package installs onto the Android device;
4.  Builds the espeak library using the Android NDK (native development kit);
5.  Builds the Java code and creates the Android package using gradle.

Android Studio will only handle the last step.

The automated build above is designed to use POSIX platforms such as Linux. You could try something like cygwin or msys2. Alternatively, you could handle steps 1 and 2 using the espeak-ng Windows build. You will then need to create the zip file manually for step 3, call `ndk-build` directly for step 4, then either use gradle directly or Android Studio for step 5.

I don't plan on making it easier to build the Android package on Windows.
