### ISSUE TITLE
espeak-ng and portaudio and pcaudiolib ?

### ISSUE THREAD

**Issue by fredvs** [espeak-ng/espeak-ng#413]
Hello.

In doc there is :  

> Dependencies: Optionally, you need pcaudiolib.

and a few later: 

> Option | Audio Interfaces | Default
>--with-portaudio | PortAudio | yes

So it seems that Portaudio is used by default in configure.
Maybe I am wrong but, AFAIK, Portaudio and pcaudiolib do the same audio task.

Then the question is: how to use espeak-ng with portaudio only ?
I did try to use espeak-ng without pcaudiolib installed but it did not work.

Thanks.

**Comment by fredvs** [comment]
Oooooops, sorry, I just see now that doc is talking about

**Comment by fredvs** [comment]
Sorry, I did a wrong touch.
The first message is the good one.

**Comment by fredvs** [comment]
Re-hello.

After check in configure script, there no --with-portaudio flag.
Could it be that README.md is obsolete because portaudio is not used any more with espeak-ng ?

(in CHANGELOG.md: ### 1.49.0 - 2016-09-10 *  Removed the local portaudio header files.)

Fre;D

**Comment by rhdunn** [comment]
That is correct, that section of the documentation is out of date. Thanks for the bug report.
