### ISSUE TITLE
$text mangles or removes words

### ISSUE THREAD

**Issue by sukiletxe** [espeak-ng/espeak-ng#421]
I am using NVDA 2018.1 with eSpeak NG at commit 3ed34d3a74eb69cedcdfa98dbedef4359279d352 . I don't know if this is a Espeak NG issue or an NVDA issue.

Espeak NG behaves incorrectly when it finds a word which includes the $text flag.

For example, read this word by word (CTRL + Right arrow and CTRL + Left arrow, multiple times), setting the synthesiser's language to English:

boogey début lasagne protegé Bogotá

With the Spanish voice this is much more noticeable (read this with the Spanish voice):

voice DPTO. SR. DRA. English Excmo. Izq. kg. Pte. UD.

**Comment by rhdunn** [comment]
This looks like a bug I fixed a few days ago (see commit eaa08a2bc34e3cfc5b5e4e2dd94ba998792b2026). You will either need to get NVDA to update to the latest development version of eSpeak NG, or build it youself.
