### ISSUE TITLE
Add configure option for clang sanitizer

### ISSUE THREAD

**Issue by brawer** [espeak-ng/espeak-ng#423]
It would be great if the autoconf setup could allow `./configure --with-sanitize=address` (or undefined, memory, etc. If passed, this would add `-fsanitize=address` to the C flags, and it would link the binaries with clang++ passing the same flag again.

I’m currently blocked on https://github.com/espeak-ng/espeak-ng/issues/407 because the sanitizers fail upon `make check`. The detected issues seem real; very much worth fixing. To reproduce and fix these error reports, it would help if the autoconf file took a command-line flag with the requested sanitizer.

**Comment by rhdunn** [comment]
I have documented how to configure the `-fsanitize` flags -- passing it via `CFLAGS` and `LDFLAGS` options when running configure. I don't want to add custom autoconf support for this, as none of the other compiler flags (e.g. hardening flags) are enabled that way. See also https://fuzzing-project.org/tutorial-cflags.html.

If you need to automate it, it is easy to create a shell script to pass the appropriate flags. It also does not cause confusion when more sanitize options are added to gcc or clang that are not documented in the configure message.
