### ISSUE TITLE
release package is in wrong format

### ISSUE THREAD

**Issue by hgneng** [espeak-ng/espeak-ng#434]
The actual format of release package below is "tar" not "tar.gz". Running `tar zxvf` to exact the package on Linux will complain errors. (But it runs normally on Mac.) The package is about 12M after gzip not 36M.

https://github.com/espeak-ng/espeak-ng/releases espeak-ng-1.49.2.tar.gz

**Comment by polyzen** [comment]
Confirmed with `file`: `espeak-ng-1.49.2.tar.gz: POSIX tar archive (GNU)`.

**Comment by ndarilek** [comment]
Would be great to see a fix for this. I'm trying to create Flatpak packages with this as a dependency, and it's frustrating that I can't point to an actual tar.gz that flatpak-builder can actually download and compile.

Thanks.

**Comment by ryandesign** [comment]
The espeak-ng 1.50 source was correctly released as a gzip-compressed tarball, so let us assume that the developers will issue subsequent releases correctly as well. I suggest this issue be closed.

**Comment by baarkerlounger** [comment]
@ndarilek were you able to use `espeak-ng` as a flatpak dependency?

**Comment by ndarilek** [comment]
I don't recall, sorry. I was trying to flatpak Orca and ran into 
something else that blocked me.
