### ISSUE TITLE
Slurring of words and phrases

### ISSUE THREAD

**Issue by Trix-Maiden** [espeak-ng/espeak-ng#436]
I've mentioned this on mailing lists before, but I'll do so again here. I checked the issues from recent months and this hadn't come up.

A number of words and phrases have been unnaturally slurred in the version of Espeak ng packaged with the NVDA screen-reader since December. These include the phrases "for the" and "for a", and words such as "they're and our", twenty, nineteen, ninety, percent, fantasy and probably some others I can't think of right now. This makes these words and these ones alone sound slower than all the rest of the text around them, which is distracting and inaccurate.

Am I explaining this right? Has this been fixed and I just didn't see the issue yet? I went back to before December in open and closed Issues to make sure... All I know is the pronunciations of these words and phrases were fine in previous versions of the synthesiser.

**Comment by rhdunn** [comment]
I have identified and fixed the issue with twenty, fantasy, etc. Thanks for taking the time to provide examples of the issue.

The problem caused the vowel before the 'n' to be longer than it should be. This made the words slower than normal, and made them sound slurred.

For the "for the" and "for a" words, those are pronounced the same as they were in espeak, so I don't know if they have been fixed or if it is a different issue (e.g. a change in NVDA's Edward speechplayer voice).
