### ISSUE TITLE
More Mispronunciations I have discovered

### ISSUE THREAD

**Issue by Trix-Maiden** [espeak-ng/espeak-ng#440]
The first one is a Harry Potter term, but was previously rendered correctly. Apparated sounds like "Appareted", rather than "ApperAted". I do not mean there should be any stress on the capitalised syllable, but that the "ated" part should be clearly heard, as it was in previous versions.

The second I have discovered is the name "Ursula". The second syllable should not be stressed. No syllables in this name are stressed more than the others.

I'm sorry, I can't do the fiddly symbols marking stressed syllables and how they are stressed, as others can. I can only do my best to explain what I'm hearing.

**Comment by rhdunn** [comment]
Thanks, I have applied fixes for these words. It is fine to say which syllable should be stressed, like you did with Ursula.
