### ISSUE TITLE
Velarisation in Espeak NG is too pronounced

### ISSUE THREAD

**Issue by Trix-Maiden** [espeak-ng/espeak-ng#443]
I've brought this up before as well, but I want to do so again here, in less abrasive language.

The current way Espeak ng processes velarisation puts too much emphasis on it. Any word ending with an "N" that precedes one starting with a hard "g" or "c" sounds as if there is an extra "g" at the end of it before the next word begins. "Ing case", "wung game" "cang get", etc.

The last time I brought up this issue, I was told this is how these words sound when spoken by humans, but I would disagree. Not to say this doesn't happen, but it isn't lingered over the way it is in the current release of Espeak ng. In previous versions, the transitions between these words sounded natural enough to my ears, and this version over-emphasises the velarisation to the point of it being unnatural.

(Note: I do not type "one" like that, but I had to alter spellings to simulate the pronunciation issue as clearly as possible to another blind person.)

**Comment by rhdunn** [comment]
Fine. I've disabled velarisation between words.

I personally prefer the change I made, and Wikipedia [1] supports both between words (it will likely depend on how fast the person is speaking and accent variation).

[1] https://en.wikipedia.org/wiki/English_phonology -- "This effect can even occur across syllable or word boundaries, particularly in stressed syllables".
