### ISSUE TITLE
please can you add haitian creole language

### ISSUE THREAD

**Issue by weatherchann** [espeak-ng/espeak-ng#452]

**Comment by weatherchann** [comment]
please can you add haitian creole language

**Comment by valdisvi** [comment]
We can add support for Haitian Creole, but without active involvement of native speaker, produced speech will be very low quality.
If you wish to commit your effort for improvements, I can provide initial configuration files first approximation for spelling. After that, if you will not be able to [build eSpeak NG yourself](https://github.com/espeak-ng/espeak-ng#building-1), you will need to test it [on-line](https://odo.lv/Espeak) and provide changes for [pronunciation rules](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md).

**Comment by weatherchann** [comment]
how can I do

**Comment by weatherchann** [comment]
@valdisvi  how can I do to adding  Haitian Creole,

**Comment by valdisvi** [comment]
It is described [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md). But, if it seems too complicated, I can create initial configuration for you.

**Comment by weatherchann** [comment]
@valdisvi    please can you add haitian creole language in android and ios

**Comment by weatherchann** [comment]
@valdisvi here is pronunciation rules mp3 audio link
https://drive.google.com/file/d/1GL2szwdq-ak0IeE3z-JAYKVUXb1ju-39/view?usp=sharing

**Comment by valdisvi** [comment]
I have prepared configuration files for initial support of the Haitian Creole language. You can test it online [here](https://odo.lv/Espeak). Note, that now you can even edit config files and compile espeak-ng online, as it is described [here](https://odo.lv/EspeakGuide).
