### ISSUE TITLE
still overlapping speech with espeak-ng

### ISSUE THREAD

**Issue by lilmike** [espeak-ng/espeak-ng#463]
Hi,
I tried upgrading to espeak-ng on a speakup system. Upon restarting espeakup, I noticed that speech would overlap for maybe 0.1-0.25 seconds when doing something to interrupt (like moving to a new line with review). I tried with orca and speech-dispatcher, and all worked fine -- in fact it was much more responsive than regular espeak. I then tried with fenrir using the generic driver and the command espeak-ng [options]... That was quite sluggish as well. For reference (if you don't already know) the way fenrir's generic driver works is it forks a command (in this case espeak-ng) to read the text, and if it needs to interrupt speech it kills the command.
Any help is appreciated.
I also installed pcaudiolib from git, and it didn't fix it. I also installed espeak-ng from git.
-Michael.

**Comment by rhdunn** [comment]
When using orca and speech-dispatcher are you using espeak-ng?

There was discussion on the debian accessibility mailing list a while ago investigating this. See https://lists.debian.org/debian-accessibility/2017/01/msg00043.html and the associated thread.

**Comment by alex19EP** [comment]
can not confirm this on current espeak-ng and espeakup

**Comment by alex19EP** [comment]
I think this can be closed.

**Comment by sthibaul** [comment]
I believe that was fixed indeed
