### ISSUE TITLE
Māori missing from 1.49.2?

### ISSUE THREAD

**Issue by Porges** [espeak-ng/espeak-ng#469]
[The release notes](https://github.com/espeak-ng/espeak-ng/releases/tag/1.49.2) for 1.49.2 indicate that Māori is meant to be included, but it isn't installed by the MSI.

Am I meant to obtain it separately?

**Comment by valdisvi** [comment]
Māori is included in development version of espeak-ng since beginning of 2017. Also, it is available in [online test page](https://odo.lv/Espeak?language=en). But I don't know anything about Windows packages.

**Comment by douglasbagnall** [comment]
@Porges: the Māori rules could certainly do with improvement, if you have the time.
