### ISSUE TITLE
Punctuation not spoken correctly when using Orca and Speech Dispatcher

### ISSUE THREAD

**Issue by am-dxer** [espeak-ng/espeak-ng#477]
When using espeak-ng with orca and having punctuation set to all, the less than and greater than symbols (< and >) are not spoken. This is a regression from espeak where these are spoken correctly.

**Comment by am-dxer** [comment]
This is when reading by line or when using say all etc. If reading by character, these are spoken.

**Comment by jaacoppi** [comment]
https://github.com/espeak-ng/espeak-ng/blob/888bb71bbf305ff884522b81f4cef026b7412229/src/libespeak-ng/readclause.c#L1012



For some reason `iswpunct()` fails with '<' and '>'. Removing that check would fix this but the real reason might be somewhere else.

**Comment by rhdunn** [comment]
Interesting...

The espeak-ng code is using the Unicode data to perform case conversion and character class checks, via the `ucd-tools` code (in this case, in `src/ucd-tools/src/ctype.c`). This is to support platforms that don't have wide-character support (Android), have broken support (Windows), or lag behind the latest Unicode version (older operating systems).

That project has test programs `printcdata` (using the C API) and `printucddata` (using the Unicode data). The following prints the character, it's Unicode general category, and the result from `ispunct` on my Debian testing machine:

    $ echo ".<>" | tests/printucddata --stdin --format="%pc\t%c %ip\n"
    .	Po 1
    <	Sm 0
    >	Sm 0
    \n	Cc 0
    $ echo ".<>" | tests/printcdata --stdin --format="%pc\t%c %ip\n"
    .	Po 1
    <	Sm 1
    >	Sm 1
    \n	Cc 0

The reference for [`ispunct`](http://en.cppreference.com/w/cpp/string/byte/ispunct) states that `!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~` are classified as punctuation. I'll need to check against all Unicode values using a Unicode enabled locale.

**Comment by valdisvi** [comment]
That could be related by introduced `<` with specific meaning to decrease the score in the rule:
https://github.com/espeak-ng/espeak-ng/commit/252c894e59d7b21f33234a3b55122e468288f1a0

**Comment by rhdunn** [comment]
@valdisvi It is a bug in the ucd-tools code.

**Comment by valdisvi** [comment]
Yes, traced debug shows:

```
espeak-ng -X --punct "<"
Translate '<'
Found: '_<' [lEsDan] 
```

**Comment by rhdunn** [comment]
I've pushed a fix for this issue, so `iswpunct` is now calculated correctly.

**Comment by rhdunn** [comment]
Thanks for the bug report.
