### ISSUE TITLE
All checks have failed when adding new language

### ISSUE THREAD

**Issue by ronaldaug** [espeak-ng/espeak-ng#487]
First of all, thanks for building amazing tts engine.

I am very new to espeak-ng.
I just followed along with [this](http://espeak.sourceforge.net/add_language.html) and trying to add Shan language here. I think something is missing in my sources.

And when I pull request, all checks have failed (The Travis CI build failed).

Please guide me what to do first before I submit a new language here.
Thanks in advance.

**Comment by rhdunn** [comment]
The issues are to do with bad (unrecognised) phonemes when building the sgan dictionary.

I have fixed some of the issues, but have added a comment on the pull request about the others.
