### ISSUE TITLE
phoneme definition to make usually voiced consonants voiceless if the next phoneme is a consonant

### ISSUE THREAD

**Issue by hozosch** [espeak-ng/espeak-ng#492]
As far as I can see, there isn't such a feature stated in the issue title. I would be glad if this feature can be added, because in German that would be very useful.

**Comment by valdisvi** [comment]
It is not well documented, but there are some options to regulate this in [tr_languages.c](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/tr_languages.c) file. Particularly for German, look at the line:
[`tr->langopts.param[LOPT_REGRESSIVE_VOICING] = 0x100;`](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/tr_languages.c#L606) which should be changed to something else. 
Possible values can be looked for other languages, but code, which handles it is in
[phonemelist.c `MakePhonemeList()` function](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/phonemelist.c#L187).

**Comment by bdorer** [comment]
@hozosch did this information help you? If yes, this issue could be closed.

**Comment by hozosch** [comment]
Well I suppose it can be closed. This doesn't really bother me anymore and it's too difficult to do things like this in the source code. I don't know what to change and don't have the tools to compile Espeak-NG

**Comment by valdisvi** [comment]
@hozosch, it will not look very clean and short, but you can make switch from voiced to voiceless consonant with rules in `ph_german` file. E.g. it is already done to [to switch b to p if following is l2](https://github.com/espeak-ng/espeak-ng/blob/1fb68ffffea45bb1c182fdc27a4a436c69b937e5/phsource/ph_german#L407):

```
...
phoneme b
  vcd blb stp
  voicingswitch p
  IF nextPh(l2) THEN
    ChangePhoneme(p)
  ENDIF
...
```
You need to add similar [condition statements](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phontab.md#conditional-statements) for other phonemes and phonemes which may follow them.

**Comment by hozosch** [comment]
This sounds more like something I can do, but what I mean is this: if there is a break defined, words ending in a voiced consonant are not unvoiced, like they should be. Can this be fixed somehow?

**Comment by valdisvi** [comment]
Yes, there is option `IF nextPh(isPause) ...`.

**Comment by hozosch** [comment]
Will this affect $brk as well?

**Comment by valdisvi** [comment]
Rules in `ph_...` file are applied when text is already converted to the chain of phonemes to be synthesized, therefore, I think, "pause" in that stage is actually any silence between phonemes (sounds).
