### ISSUE TITLE
Typo in the ESpeak Emoji Dictionary

### ISSUE THREAD

**Issue by Mohamed00** [espeak-ng/espeak-ng#511]
Using eSpeak NG version 1.49.3 dev with the latest next snapshot of NVDA, I noticed an issue. The entry for the "🤣" emoji is pronounced as "rolling on the the floor laughing".

**Comment by jaacoppi** [comment]
Confirmed. This is not specific to this emoji, but instead affects all words that are grouped together in list files: (of the), (on the) and so on. See the emoji for "sign of the horns" for example. Probably happens with other languages as well.


-X produces (truncated, only the most relevant parts shown):
```
Replace:     rolling on the floor laughing
Translate 'rolling'
  1     r        [r]

 78     r) oll   [oUl]
  1     o        [0]
  4     X) o     [0#]

117     @) ing (_+S3evd  [IN]
  1     i        [I]

Translate 'roll'
  1     r        [r]

 78     r) oll   [oUl]
  1     o        [0]
  4     X) o     [0#]

Found: 'on the
' [O2nD@2]
Found: 'the' [D@2]   $nounf $only
Unpronouncable? 'floor'
 39     _) f (L01Y [f]
Translate 'floor'
```

**Comment by jaacoppi** [comment]
FLAG_SKIPWORDS and dictionary_skipwords seem to be checked when there's "(of the)" or similar words grouped together. For some reason after handling the two combined words the second word is still handled on its own instead of skipping it.

**Comment by rhdunn** [comment]
See TranslateWord in translate.c line 1157. That is where I added support for translating emoji. Specifically, lines 1197-1199 skip to the next word of the emoji. This only skips one word (the word that has been translated), so should be wrapped in a loop checking for `*word_out` and the skip count (setting the skip count to 1 by default).

NOTE: I am not sure how FLAG_SKIPWORDS works (i.e. how espeak knows how many words to skip).

**Comment by jaacoppi** [comment]
This would fix the issue and pass make check:

```
diff --git a/src/libespeak-ng/translate.c b/src/libespeak-ng/translate.c
index cb4ba94..4dc013b 100644
--- a/src/libespeak-ng/translate.c
+++ b/src/libespeak-ng/translate.c
@@ -1194,9 +1194,11 @@ int TranslateWord(Translator *tr, char *word_start, WORD_TAB *wtab, char *word_o
                        available -= n;
                        phonemes += n;
 
-                       // skip to the next word in a multi-word replacement
-                       while (!isspace(*word_out)) ++word_out;
-                       while (isspace(*word_out))  ++word_out;
+                       // skip to the next word in a multi-word replacement. Always skip at least one word.
+                       for (dictionary_skipwords = dictionary_skipwords + 1; dictionary_skipwords > 0; dictionary_skipwords--) {
+                               while (!isspace(*word_out)) ++word_out;
+                               while (isspace(*word_out))  ++word_out;
+                               }
                }
 
                // If the list file contains a text replacement to another

```

I'm also not sure how skipwords works, but it works. Should we use the existing int dictionary_skipwords like in the patch above, or write a new logic?

**Comment by rhdunn** [comment]
Thanks for the investigation. Looking at where dictionary_skipwords gets set (in dictionary.c), that looks correct.

Some minor comments on the code:
1.  `dictionary_skipwords = dictionary_skipwords + 1` can be replaced by `++dictionary_skipwords`.
1.  The `}` at the end of the for loop has an extra indent.

Can you create a PR for this? Thanks.
