### ISSUE TITLE
please can you add K'iche' language

### ISSUE THREAD

**Issue by salami5** [espeak-ng/espeak-ng#515]
@rhdunn  please can you add K'iche' language

**Comment by kflskflfkslfkskflskf** [comment]
https://en.wikipedia.org/wiki/K%27iche%27_language

**Comment by valdisvi** [comment]
From wikipedia article I understand, there are several dialects, which, particularly influences spelling of vowels. It is not clear, what is alphabet and writing system in general, is, e.g. how vowels are written (**a**, **ä** or **aa**) and how some consonants are written (**t'**, **k'**, **q'** with single quote **'** or accent **`** or something else).
Can you provide more details about writing and pronunciation and particular dialect?

**Comment by salami5** [comment]
there is phonemes K'iche Language 

/a/ | /ə/ | a | ä | a
-- | -- | -- | -- | --
/aː/ | /a/ | aa | a
/e/ | /e/ | e | ë | e
/eː/ | ee | e
/i/ | /i/ | i | ï | i
/iː/ | ii | i
/o/ | /o/ | o | ö | o
/oː/ | oo | o
/u/ | /u/ | u | ü | u
/uː/ | uu | u

**Comment by salami5** [comment]
I am not a programmer

**Comment by salami5** [comment]
hi how can I do that

**Comment by salami5** [comment]
@valdisvi K'iche' language  flite tts is old  i want eSpeak NG  K'iche' language new support  please can you add K'iche' language

**Comment by salami5** [comment]
please can you add K'iche' language
