### ISSUE TITLE
Broken pronunciations in the bulgarian language of eSpeak-NG 1.49.3-dev

### ISSUE THREAD

**Issue by k-kolev1985** [espeak-ng/espeak-ng#518]
Hello eSpeak-NG developers and maintainers,

I'm using the so called "alpha" snapshots of the NVDA screen reader.

Recently, the version of eSpeak used in it was updated from 1.49.1 to 1.49.3-dev. After the update, the bulgarian language in eSpeak-NG started sounding wrong. It started mispronouncing a lot of words. Now those mispronounced words sound like they are spoken by a russian voice and not a bulgarian one, even though the eSpeak language is set to "Bulgarian" and not "Russian".

Sorry that I can't give you more technical details on the problem, but I'm not a specialist or an expert in regards to speech synthesis or linguistics.

Anyway, if you need more information from me in regards to the issue, feel free to ask and I'll try to provided if I can.

Thanks much in advance!

**Comment by valdisvi** [comment]
In development version of espeak-ng structure of compiled configuration (*.dic) gradually changes, thus reading older files with newer executable may produce unexpected results. Please ensure you use executable compatible with language configuration files.

**Comment by k-kolev1985** [comment]
@valdisvi are you referring to me in your answer or the eSpeak-NG developers? Because if it is me, I don't have the slightest clue what are you talking about in regards to usage of executables in this case. I'm just a tester of NVDA and that is how I've noticed the regression in the bulgarian language of eSpeak. And I don't have the skills or knowledge to do the required fix myself. That is why I'm reporting it here, so it can be fixed by the eSpeak-NG developers.

Sorry if I've misunderstood you.

**Comment by michaelDCurran** [comment]
I believe this point is irrelevant as we always compile eSpeak and 
dictionaries from a fresh checkout. No pre-existing dictionary files are 
used.

Assuming I can hear the difference, I'll try and bisect the problem in 
the next day or so.

**Comment by valdisvi** [comment]
Can you check, if it works properly in [online testing page](https://odo.lv/Espeak)? If not, can you provide some example text where it is wrong?

**Comment by michaelDCurran** [comment]
For reference, the espeak-ng commit we are including in NVDA is e7e59f9.

**Comment by valdisvi** [comment]
The same commit currently is the last one on [testing page](https://odo.lv/Espeak).

**Comment by k-kolev1985** [comment]
It is the same in the online testing page. Here is the example that I've used in there:

NVDA се покрива от общото право на обществено ползване ГНУ версия 2 (GNU General 
Public License version 2 - GNU GPL version 2).Вие сте свободни да споделяте или 
променяте този софтуер по всякакъв начин дотолкова, доколкото той върви със същия 
лиценз, и да направите изходния код достъпен за всеки, който го иска. Това важи както 
за оригиналното, така и за модифицираните копия на този софтуер, заедно с всякакви 
вторични работи.

I think the main problem (if not the only one) is with the cyrillic letter "е", which now sounds more like "ие" than a eal "е". and only when reading complete words with it. When reading the "е" character alone, it is pronounced OK.

**Comment by beqabeqa473** [comment]
the main problem here is that people are touching languages which they
don't speak and braking what was working before.
the same thing was with russian language in which rules were broken,
consonants were wrongly speaking and so on.

2018-07-19 14:53 GMT+04:00, Kostadin Kolev <notifications@github.com>:
> It is the same in the online testing page. Here is the example that I've
> used in there:
>
> NVDA се покрива от общото право на обществено ползване ГНУ версия 2 (GNU
> General
> Public License version 2 - GNU GPL version 2).Вие сте свободни да споделяте
> или
> променяте този софтуер по всякакъв начин дотолкова, доколкото той върви със
> същия
> лиценз, и да направите изходния код достъпен за всеки, който го иска. Това
> важи както
> за оригиналното, така и за модифицираните копия на този софтуер, заедно с
> всякакви
> вторични работи.
>
> I think the main problem (if not the only one) is with the cyrillic letter
> "е", which now sounds more like "ие" than a eal "е". and only when reading
> complete words with it. When reading the "е" character alone, it is
> pronounced OK.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/518#issuecomment-406236655


-- 
with best regards beqa

**Comment by valdisvi** [comment]
Settings for Bulgarian are not changed for quite a while. Below is commit information for configuration files:

**espeak-ng-data/lang/zls/bg**
Author: Reece H. Dunn <msclrhd@gmail.com>
Date:   Thu Dec 21 21:58:46 2017 +0000

    Revert "Move most stress rule definitions from tr_languages.c to language files"
    
    This reverts commit 0f5520452227f2c6de25b1f4cd87ca35fac67fb5.
    
    This breaks using voice files like mb-de5-en. It could also use
    named values for the stress rules (e.g. 'first-syllable').

**phsource/ph_bulgarian**
commit 9ef1f2eec6352e0f7a7449baeb0491fea25a8b94
Author: Reece H. Dunn <msclrhd@gmail.com>
Date:   Mon Jan 30 20:16:47 2017 +0000

    Use base1 as the base phonemetable, not 'base'.
    
    This is a step in the transition to using a common IPA-based
    phoneme table for the pronunciations. It allows the base phonemes
    to import the IPA versions during this transition phase.

**dictsource/bg_list**
commit 790c151a4d3c0b47c7d30e09e826f52f98d46eca
Merge: b51fe6f 42028ac
Author: Reece H. Dunn <msclrhd@gmail.com>
Date:   Sun Mar 17 00:51:22 2013 +0000

    Merge branch 'upstream' into development
    
    Conflicts:
        dictsource/dict_phonemes
        phsource/compile_report
        phsource/vnasal/a#_n2
        phsource/vnasal/o_n4

**dictsource/bg_rules**
Author: Reece Dunn <msclrhd@gmail.com>
Date:   Sat Sep 17 16:31:41 2011 +0100

    1.45.44 -- from the espeak and espeakedit zip file sources

There are some not so old changes in **ph_russian** file ([look at change history here](https://github.com/espeak-ng/espeak-ng/commits/master/phsource/ph_russian)), which may affect pronunciation of Bulgarian, if it relays on definition of some Russian phoneme.

**Comment by rhdunn** [comment]
@beqabeqa473 The Bulgarian language has not changed from the last eSpeak changes, with the exception of the addition of emoji, so it is not due to people editing the Bulgarian language. You have added the same or similar comments to other issues that were not caused by people modifying the language, but due to something else. I would appreciate it if you did not add unconstructive comments. Thanks.

**Comment by rhdunn** [comment]
There is a difference between 1.49.2 and 1.49.3~e7e59f99d3. For example, from the example text Kostadin gave, one difference I see is:
```
- i: da n,aprav'ite ,isxodn'ija k'ot dost'@pen zafs'eki:
+ i: da n,aprav'ite ,isxodn'ija k'ot dost'@p;en zafs;'eki:
```

Specifically -- `p`, `s`, etc. are being incorrectly palatalized.

I am performing a bisection now to locate which commit is causing this bug.

**Comment by rhdunn** [comment]
The problem is in `SetCyrillicLetters` -- It was extended to support additional iotated vowels for Russian support (commit c53141ff1218d1a948304f3b8369684f3b361fce), which inadvertently affected other Cyrillic languages. I am working on a fix now.

**Comment by rhdunn** [comment]
I have pushed a fix for this issue. I now don't get the difference between 1.49.2 and 1.49.3~32ab396e (the current commit on the master branch).

**Comment by valdisvi** [comment]
Thanks, Reece, for rapid fix (and sorry for introduced bug).
@k-kolev1985, I have set up fixed version on the test site, you can check it there, and close an issue, if now spelling is ok.

**Comment by rhdunn** [comment]
Don't worry about it. Bugs and regressions happen, especially when the code is confusing like this. I've hopefully made the code less confusing.

**Comment by k-kolev1985** [comment]
I've checked in the online testing page and now the pronunciations sound OK. Thanks for the quick reaction and fix! :-)
