### ISSUE TITLE
Regression: espeak-ng 5d295bd is incorrectly slowed

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#52]
Tested on commit [5d295bd] (https://github.com/espeak-ng/espeak-ng/commit/5d295bdd30822fc9f01c928f361521d08f5d15f6)
Listen http://odo.lv/ftp/temp/broken.wav.mp3
It looks like lengthening phoneme **:** is _much_ too long for all vowels. 
Last good pronunciation is for commit [5bbc0d3](https://github.com/espeak-ng/espeak-ng/commit/5bbc0d37435867ffb9e10db8cef06afe0cdd830f)

**Comment by rhdunn** [comment]
I am not able to reproduce this issue on my current setup using:

    ESPEAK_DATA_PATH=`pwd` src/espeak-ng hello
    ESPEAK_DATA_PATH=`pwd` src/espeak-ng "It looks like the last good commit was 30 minutes ago."

Do you get the distortions with the default English voice using single words as well? Do you have any espeak parameters set?

**Comment by ValdisVitolins** [comment]
Because I test pronunciation rules for Latvian, I usually run it with parameters `espeak-ng -vlv -x "bla bla bla"` or `espeak-ng -vlv -X "bla bla bla"`.
But it talks with the same pronunciation problems with your lines too...

**Comment by rhdunn** [comment]
I hsve reverted 14a2fb39cf89c8e5561f833f961d8330059daaae, which should resolve the issue you are observing.
