### ISSUE TITLE
Create spelling tests to all languages

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#521]
To check for regressions due to implementation changes, all languages should have tested for spelling.
Phrases can be get from http://clagnut.com/blog/2380/ or similar, which are used for font testing.

**Comment by valdisvi** [comment]
Before issue #520 I'll start with this issue and will test it on some older version. If somebody has specific commit to be used, add it comments.

**Comment by rhdunn** [comment]
I agree with having spelling (and phoneme) tests for all languages -- that is what I want `language-pronunciation.test` (and `language-phonemes.test`) to be. NOTE: I have updated the language-pronunciation.test file for the languages in #520, and have added a language-replace.test file for testing `.replace` rules (currently only Bosnian, Croatian, English, and Serbian are tested).

**Comment by valdisvi** [comment]
Reece, I have added tests in tests/translate.test

**Comment by valdisvi** [comment]
I have created tests for most of the languages. Remaining part is documented in issue #529.
