### ISSUE TITLE
Tests: spelling differs for Russian with or without extended dictionary

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#527]
Test pangram for Russian "Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства." is spelled differently with or without extended dictionary, because extended dictionary changes stress thus affects spelling of stressed/unstressed **о**'s.
Without extended dictionary:
```
Syr'okVja E#l;ikt@-r;if;'ikVtsyja 'juZnyx gub;'ern;ij d'Ast m'oS;nyj tVltS;'ok pVdj'8mu s;ilsk'ovV xVz;'Ajstva#
```
(wrong stress for `электрификация` as `E#l;ikt@-r;if;'ikVtsyja` and `сельского` as `s;ilsk'ovV`).
With extended dictionary:
```
Syr'okVja E#l;ikt@-r;if;ik'Atsyja 'juZnyx gub;'ern;ij d'Ast m'oS;nyj tVltS;'ok pVdj'8mu s;'elskVvV xVz;'Ajstva#
```
(proper stress, spelling of **о**'s is changed accordingly to `E#l;ikt@-r;if;ik'Atsyja` and `s;'elskVvV`).
We can change test phrase to some silly word, which is not included in extended dictionary, or, (probably better) would be additional logic for unit tests.

What do you think?

**Comment by valdisvi** [comment]
One of options is to use explicit [stress mark](https://ru.wikipedia.org/wiki/%D0%97%D0%BD%D0%B0%D0%BA_%D1%83%D0%B4%D0%B0%D1%80%D0%B5%D0%BD%D0%B8%D1%8F), with additional spelling rules.

**Comment by rhdunn** [comment]
Two simple options:
1.  Add the words/stresses needed for the Russian pangrams to the main list, so it does not matter whether or not the extended list is used.
1.  Add an extra parameter to test_phonemes that provides an alternative transcription (maybe via a new test_phonemes_alt function).

I personally prefer (1), as it is not adding a huge amount of extra rules, and keeps the results consistent.

**Comment by valdisvi** [comment]
I added these two words in ru_list with a comment.
