### ISSUE TITLE
crashing with using georgian language

### ISSUE THREAD

**Issue by beqabeqa473** [espeak-ng/espeak-ng#534]
hello.

espeak-ng is crashing when using georgian voice with this string
,,,, 🚺🚺😍😎😎😎

maybe you can eliminate these type of crashes.

thanks.

**Comment by jaacoppi** [comment]
Latest git version doesn't crash for me. Could you
1) Attach a text file with a string that crashes
2) Tell where the crash is supposed to happen

**Comment by rhdunn** [comment]
I also don't see the crash in either 1.49.2, or the current 1.49.3 dev version:

    $ ESPEAK_DATA_PATH=`pwd` src/espeak-ng -xv ka 🚺🚺😍😎😎😎
     k#'alebisk#'alebism'omQim,arem'omQim,arem'omQim,arem'omQim,are

1. Which version of espeak are you using?
1. Which platform (Linux, Windows, etc.)?
1. Is this with NVDA? If so, which version of NVDA?
1. Is this with Android (custom espeak-ng build)? If so, which version of Android?

**Comment by zstanecic** [comment]
Hi to all, i can reproduce the crash with latest NVDA alpha and beta versions.
(windows)

**Comment by beqabeqa473** [comment]
hi.

i am using it on windows with latest nvda alpha build.


2018-08-06 22:26 GMT+04:00, zstanecic <notifications@github.com>:
> Hi to all, i can reproduce the crash with latest NVDA alpha and beta
> versions.
> (windows)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/534#issuecomment-410805422


-- 
with best regards beqa
