### ISSUE TITLE
Documentation: specify allowed number range of rule groups

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#54]
In [Text to Phoneme Translation] (/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#user-content-rule-groups) it is said that rule groups can be from **01** to **25** but in [dictsource](/espeak-ng/espeak-ng/tree/master/dictsource) **..\_rules** files group numbers are up to **38**.
Please update documentation to what is actually allowed range.

**Comment by rhdunn** [comment]
I have updated this to 94, per the `compile_lettergroup` behaviour in `compiledict.c` (line 1257).
