### ISSUE TITLE
Pronunciation in Portuguese-Brazillian

### ISSUE THREAD

**Issue by Qchristensen** [espeak-ng/espeak-ng#557]
I've had several NVDA users who use Portuguese (Brazillian) advise that there are pronunciation issues in eSpeak NG 1.49.3dev commit 910f4c2 (used in NVDA 2018.3.x), which weren't present in eSpeak NG 1.49.2 (used in earlier NVDA versions).

What they have advised is:
Words such as "Galxy" and "Maxy" and any other words ending in XY are being pronounced incorrectly.

Also a change in the pronunciation of the peak in words started by "sy" and "any", which used to read ok.

I gave them a try build of NVDA today which we compiled with the latest eSpeak NG build in order to fix the Russian pronunciation issues.  They confirmed that the issues with Portuguese Brazillian are still present in this build.

**Comment by rhdunn** [comment]
Thanks for the bug report.

I have run a git bisect and identified 6042eb8d1ebef0632f65b74e34f836e5c91e52fc as the cause of this issue. I have reverted the commit, so those words should be pronounced correctly now.
