### ISSUE TITLE
Regression: build 32655d doesn't speak

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#56]
When [32655d](https://github.com/espeak-ng/espeak-ng/commit/32655d264ddc522eb006f5bf0ad9751cad21fec5) build is compiled and installed it makes just few beeps and clicks and halts.
(Built on Ubuntu 14.04.3 LTS, kernel x86_64 3.13.0-74-lowlatency).

**Comment by rhdunn** [comment]
I have identified the various regressions from my end (tested with the portaudio 19 API). These should fix the issue you are experiencing.

**Comment by ValdisVitolins** [comment]
I can confirm that commit a8eb65 is ok.
