### ISSUE TITLE
please can you add Quechua language

### ISSUE THREAD

**Issue by salami5** [espeak-ng/espeak-ng#561]
https://en.wikipedia.org/wiki/Quechuan_languages

**Comment by salami5** [comment]
please can you add Quechua language

**Comment by salami5** [comment]
@valdisvi Adding a language by miself is kinda complecated, since I don't know those languages and I need to help them.

**Comment by salami5** [comment]
@valdisvi   don't blame me if I'm not following those rules.

**Comment by luiscarlos2000** [comment]
I've already said it Salám.

**Comment by salami5** [comment]
@valdisvi please can you create the Quechua language please  in soon as possible

**Comment by valdisvi** [comment]
@salami5 , I have added initial support for Quechua language. You can test it [online](https://odo.lv/Espeak) and improve it yourself by following [contributor guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md).
