### ISSUE TITLE
mbrola issues

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#566]
Running espeak-ng against mbrola 3.02b (as available on https://github.com/valdisvi/MBROLA ) gives:

    $ espeak-ng -v mb-es1 "Hola mundo" 
    mbrola: Warning: d-o/ unkown, replaced with _-_
    mbrola: Warning: o/-_ unkown, replaced with _-_

and the synthesis stops before the end.

**Comment by valdisvi** [comment]
It seems outdated version of espeak-ng with missing [honeme mappings](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/mbrola/es). Development version [runs fine](https://odo.lv/Espeak?githuburl=&eslang=-vmb-es1&output=-w&debug=-x&text=Hola+mundo&formmethod=get).

**Comment by sthibaul** [comment]
Hello, a release of espeak-ng would probably be nice to have these fixes available to the masses :)

**Comment by valdisvi** [comment]
With [1.50](https://github.com/espeak-ng/espeak-ng/releases/tag/1.50) this is fixed.

**Comment by itsupera** [comment]
I'm having a similar issue with the mb/mb-jp1 model:
```
$ espeak-ng -v mb/mb-jp1 "[[j i k o r i k a i]]"
mbrola: Warning: o-r unkown, replaced with _-_
mbrola: Warning: r-i unkown, replaced with _-_
```
I'm using espeak-ng 1.50 and MBROLA 3.02b
