### ISSUE TITLE
Cantonese doesn't work

### ISSUE THREAD

**Issue by abbr** [espeak-ng/espeak-ng#567]
Hi,
I am a native speaker of both mandarin chinese and cantonese. I verified mandarin chinese works but cantonese doesn't. I have tried inputting utf-8 simplified chinese, traditional chinese, and jgutping. None works. For example

```
espeak-ng 测试 -v yue
espeak-ng 測試 -v yue
espeak-ng ngat6gam1wai4zi2 -v yue  // jgutping of 迄今为止 as defined in dictsource/extra/zhy_list
```
they are either pronounced into *letter letter* or unrecognizable english/number combo.

**Comment by valdisvi** [comment]
Abbr, can you describe what you (incorrectly?) did before?
https://twitter.com/WiteWulf/status/1011324712545325056

**Comment by abbr** [comment]
I recompiled with `--with-extdict-zhy`.
It would be better if 5000 or so common characters from zhy_list is compiled by default - same way as zh_list.

**Comment by valdisvi** [comment]
Thanks!
Can produce such list?
