### ISSUE TITLE
Speak engine SQ <albanian>

### ISSUE THREAD

**Issue by marioallaa** [espeak-ng/espeak-ng#571]
###  Albanian Language
Hey guys!

I've been using Espeak-ng because I could't find another speak engine in Albanian <sq> , I couldn't change the default language but I started using it with command line, I wanted to ask if there is a way to do the same thing in android, and what can I do to change the sound of the voice because it doesn't sound that good?
I wanted to ask if I can implement voice changers, for example id want it to use my voice can I do that? 
If yes How?

**Comment by valdisvi** [comment]
I don't know how version installed from Google play works, but if you install it from source code, then language is set according to the interface language on phone (e.g. for me it is Latvian).
