### ISSUE TITLE
Adding Hebrew language to Espeak

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#582]
Hello.
In Espeak, there is support for reading Hebrew letters, but there is not any support for Hebrew language.
Maybe there are some people, who speaks Hebrew and they are programmers. I am not Hebrew native speaker, but I use Espeak to learn new languages. I have Espeak NG in NVDA and ofcourse, I use Espeak not only in My native language Slovak, but also in another languages to good understanding this language, for example English, or Spanish ETC.
So please, could You add Hebrew language to Espeak?
Thank You.
best regards
Marco Oros

**Comment by jaacoppi** [comment]
Available since version 1.51. Closing ticket.
