### ISSUE TITLE
long text with repeating pattern produces rogue phoneme output

### ISSUE THREAD

**Issue by ultrasound1372** [espeak-ng/espeak-ng#585]
I have come across a rather strange bug brought to me by a user on twitter. I use assistive technology, namely NVDA, and use it daily to read things such as twitter. I normally use a different synthesizer, however in this tweet a friend of mine quoted saying it makes eSpeak make hilarious noises. Naturally I had to switch. The output is completely different than what you would expect from such a string. The text will be pasted below, with a recording of a different synthesizer that I use reading the same text and producing output that is more typical for the English language rules. It is worth noting that previous versions of eSpeak, before the NG rebranding, are not subject to this bug.
``
Bananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananan
``

[ETI rogue banana string.zip](https://github.com/espeak-ng/espeak-ng/files/2869616/ETI.rogue.banana.string.zip)

**Comment by valdisvi** [comment]
Provided record in definitely not from the English language. You can test, listen and download proper sample from [online test page](https://odo.lv/Espeak?language=en&eslang=-ven-gb&speed=160&output=-w&debug=-x&text=Bananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananananananaananan&formmethod=get).

**Comment by ultrasound1372** [comment]
Ah, yes the testing page isn't subject to that it seems, as long as no line wrapping is being honored. I'll open this with NVDA then, maybe the commit they're on is a little outdated and subject to this bug. According to their change log they are on commit 919f3240cbb of espeak NG.
