### ISSUE TITLE
Maybe src/espeak-ng.1.html should be added to version control?

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#59]
Even though generated files in general are not included in version control, adding `src/espeak-ng.1.html` (and/or `src/speak-ng.1.html`?) would allow to use it in references from other documents.

**Comment by rhdunn** [comment]
The references should be handled in the same way the markdown references are handled -- reference them as:

    ... the [espeak-ng](../src/espeak-ng.1.ronn) command ...

This is already handled in the markdown to HTML build rules (for the links to the ronn files in README.md), so that does not need to be modified.

**Comment by ValdisVitolins** [comment]
If these files are not in version control, links will work only on locally compiled project. But, if they are included, relative links on github will also work.

**Comment by rhdunn** [comment]
The markdown files reference the ronn files, so the links on GitHub will work (see the examples in the README.md file) -- it will show the source as GitHub does not currently have a native renderer for ronn files. The correct thing on the GitHub side is for GitHub to have native rendering of ronn files like it does for markdown.
