### ISSUE TITLE
Question about languages using non-latin alphabet

### ISSUE THREAD

**Issue by burakyuksek** [espeak-ng/espeak-ng#594]
Hello,
Those languages that don't use latin alphabet usually speak English when they encounter a latin character. Is there any way to change this so I can work more comfortably between my language and the non-latin one?
Thanks.

**Comment by valdisvi** [comment]
You can add [language rule](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#special-characters-in-phoneme-string), to switch to different language when Latin character is found. For example, here are rules for Latvian to [switch to Russian for Cyrillic letters](https://github.com/espeak-ng/espeak-ng/blob/c38cb18de3793c98ed7abbef66a522865eafe3b9/dictsource/lv_rules#L1742). Similarly, you can choose switching to your preferred language for Latin letters.

**Comment by burakyuksek** [comment]
Hello,
how do I edit that dictionary file?
