### ISSUE TITLE
--ipa option values reversed vs. original espeak

### ISSUE THREAD

**Issue by dmgolubovsky** [espeak-ng/espeak-ng#598]
In the original espeak value 3 of the --ipa option caused IPA phonemes separated by underscore:

espeak --ipa=3 -q "hello"
 h_ə_l_ˈəʊ

In espeak-ng exactly same happens with the value 1:

espeak-ng --ipa=1 -q "hello"
h_ə_l_ˈəʊ

Any reason for such reversal? I have some use for this option to find rhyming words within arbitrary text (sounds weird, but usable in songwriting).

If I submit a pull request to restore the original semantics of the --ipa option, will there be any objections?

Thanks

**Comment by Punkroku** [comment]
what does espeak-ng --help say for the -ipa argument?
espeak says: --ipa      Write phonemes to stdout using International Phonetic Alphabet
	         --ipa=1 Use ties, --ipa=2 Use ZWJ, --ipa=3 Separate with _

**Comment by Punkroku** [comment]
Side topic do you know anything about lip syncing cartoons with papagayo? The phenome outs would be useful for this and I am interested in this topic for vibrochat.com

**Comment by valdisvi** [comment]
@dmgolubovsky that looks like bug that should be fixed. You can prepare pull request for that.

**Comment by dmgolubovsky** [comment]
Sorry for long silence, was away working on other projects. I was about to submit a patch, but did some research. Looks like the desired effect can be made with 

espeak-ng --ipa --sep=_  -q "hello"
h_ə_l_ˈəʊ

which makes this bug report irrelevant - so I am closing it now.
Thanks
