### ISSUE TITLE
How Can i choose language?

### ISSUE THREAD

**Issue by ghost** [espeak-ng/espeak-ng#600]
the multilanguage is not choosen?

**Comment by valdisvi** [comment]
eSpeak NG can be called as a [library](https://en.wikipedia.org/wiki/Library_(computing)) from other programs or executed as [CLI](https://en.wikipedia.org/wiki/Command-line_interface) application for which command prompt window is needed.
Simple test is something like:
```
espeak-ng -ven "Hello world"
```

**Comment by crensyhanilas** [comment]
a thanks! will close this issue.

**Comment by valdisvi** [comment]
Using `-v` switch, e.g. `-ven` uses English. Full list of available languages is provided by `espeak-ng --voices`. See more with `espeak-ng --help` and/or [CLI documentation](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.1.ronn).

**Comment by crensyhanilas** [comment]
not working

**Comment by Punkroku** [comment]
try this espea-ng --voices to see list of voices and try to put the 2letters like so

espeak-ng -v pl "THIS IS TRYING TO TALK IN POLISH BRATERSKA"
