### ISSUE TITLE
Difference between espeak-ng and speak-ng?

### ISSUE THREAD

**Issue by delthas** [espeak-ng/espeak-ng#618]
Hello,

What's the difference between espeak-ng and speak-ng?

Thanks.

**Comment by valdisvi** [comment]
[speak-ng](https://github.com/espeak-ng/espeak-ng/blob/master/src/speak-ng.c) seems just wrapper (probably for backward compatibility) of [espeak-ng](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.c).
