### ISSUE TITLE
Pronunciation of "binghamton" in English

### ISSUE THREAD

**Issue by codeofdusk** [espeak-ng/espeak-ng#620]
In English, the city name Binghamton should be pronounced /ˈbɪŋəmtən/, per [Wikipedia](https://en.wikipedia.org/wiki/Binghamton,_New_York). Thanks in advance!

**Comment by valdisvi** [comment]
Also by British people?

**Comment by codeofdusk** [comment]
> Also by British people?

Yes: see, for example, the pronunciation of "Wokingham" in England.
