### ISSUE TITLE
Pronunciation of "Dengler"

### ISSUE THREAD

**Issue by codeofdusk** [espeak-ng/espeak-ng#622]
The e in "Dengler" should be pronounced as a short e, like in "pet", rather than a short i. Thanks.

**Comment by valdisvi** [comment]
Any reliable source?

**Comment by codeofdusk** [comment]
> Any reliable source?

It's my name...

**Comment by valdisvi** [comment]
Safe way would be for you to customize your espeak-ng. In espeak-ng project create file `dictsource/en_extra` and add following line to it:
```
dengler d'ENgl3 $capital
```
Then recompile entire project with command `make -B` in the espeak-ng folder or recompile only English language:
```
cd your-place/espeak-ng/dictsource/
../src/espeak-ng --compile=en
```
where **your-place** is actual place of the espeak-ng project.

**Comment by codeofdusk** [comment]
@valdisvi Yes, but the name is *never* pronounced in the way that Espeak-ng does.
