### ISSUE TITLE
Words ending with a "e" in German are pronounced wrong

### ISSUE THREAD

**Issue by The1Freeman** [espeak-ng/espeak-ng#623]
eSpeak-NG has a problem with the German language, in which it pronounces words that end with a "e" too short.

The "e" is supposed to be longer, comparing the sentence "Eine wohl mächtige Waffe." in eSpeak-NG and Google Translate (and any native speaking German), shows that eSpeak-NG is wrong in this case.

**Comment by bdorer** [comment]
Hi, which version of eSpeak are you using?
At the moment I'm not able to reproduce. i'm using latest nvda master 
with eSpeak 1.49.3dev
For Developers NVDA master now uses commit espeak-ng/espeak-ng@67324cc

**Comment by The1Freeman** [comment]
[The latest development version using the web version of eSpeak](https://odo.lv/Espeak).

**Comment by hozosch** [comment]
This was my mistake, and I rectified it in pull request 624. I thought
it sounds natural to me, and I'm a native German, but then, that may
vary from person to person. In fact, I like it also with the longer word
ending better (please confirm if this is ok for you), but I definitely
don't like it as long as that before another consonant like n or l. In
the attached file you can hear my change.

Sincerelly,

Karl

Am 03.07.2019 um 15:33 schrieb Gordon Freeman:

**Comment by The1Freeman** [comment]
There's nothing attached... looks like I'll have to compile the change myself on my end, will get back to you as soon as I tested it

**Comment by hozosch** [comment]
Better than before, that's nice. But it sounds as though it still could
be made even better. What do you suggest, if this is so?

Am 03.07.2019 um 18:09 schrieb Gordon Freeman:

**Comment by The1Freeman** [comment]
It could be made better, though I don't know how or what I can suggest to improve it (and to add, the german voice needs a ton of improvement to be at least on par with other voice synthesizers).

**Comment by The1Freeman** [comment]
Just tested the development version on the test website, and can confirm that it's fixed there too!

Thanks for responding so quick and for the quick fix yesterday too.
