### ISSUE TITLE
Add Kabyle language

### ISSUE THREAD

**Issue by mozillakab** [espeak-ng/espeak-ng#626]
I'd like add Kabyle but the doc seems too hard to understand. I installed the Windows release and I didn't find the files supposed to be edited in the right paths.

**Comment by valdisvi** [comment]
In my biased opinion (I can easily build espeak-ng in Linux, but can't do it in Windows), Windows is not good fit to contribute to open source projects in general and to espeak-ng project particularly.
I suggest to set up VirtualBox in Windows, then create Ubuntu Linux in virtual machine, and then go through setup shown in [home page of the project](https://github.com/espeak-ng/espeak-ng#linux-mac-bsd).

**Comment by mozillakab** [comment]
I already have Ubuntu on an other workstation. I'll try to follow the guide to build the kab TTS. 
I'm also trying to work on a model using Mozilla's TTS project.
Thanks for help.
