### ISSUE TITLE
new voices for sapi5 ESpeak

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#629]
Could you please make a custom version of the sapi5 version of ESpeak which will load and use the decTalk and softVoice (dll files) abandonware voices? Attached is a zip file with the needed dll files and some python code. If these could be added on as additional sapi5 ESpeak voices please? thanks. 
[espeakNewVoices.zip](https://github.com/espeak-ng/espeak-ng/files/3398715/espeakNewVoices.zip)

**Comment by bdorer** [comment]
@joshknnd1982 where do theese files come from? Is there any license information? I think this is important to know.
