### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by behroozafrooz** [espeak-ng/espeak-ng#632]
Due to the fact that the latest version of this software has been released for a long time, it's evident that its updating is necessary.

**Comment by gholamim6** [comment]
hello dear developers.
i'm impatiently wating for the new update of ESpeak For Windows and Android.
as i said in Issue 630.
https://github.com/espeak-ng/espeak-ng/issues/630
thanks before.

**Comment by ryandesign** [comment]
This issue was filed in July 2019. A new release was made in December 2019. Therefore this issue should be closed. #857 already exists to track the next release after that.
