### ISSUE TITLE
the ability to read .epub files to .wav?

### ISSUE THREAD

**Issue by mhussaincov** [espeak-ng/espeak-ng#639]
hi there,
would it be possable to have it so espeak-ng is able to read .epub files?
when I type for example espeak-ng -f "test.epub" it does not read the contence of the file.
it just says pk.
using latest espeak-ng
the file in question does not have any protection on it.
I have attached it if you wish to try for yourself.
thanks,
Majid Hussain
[Accidents Happen.zip](https://github.com/espeak-ng/espeak-ng/files/3457331/Accidents.Happen.zip)

**Comment by valdisvi** [comment]
I would do something like this:
```
book="your-epub-file.epub"
ebook-convert "${book}" "${book%.*}.txt"
espeak-ng -ven -f "${book%.*}.txt" -w "${book%.*}.wav"
```
then listen produced wav file.

**Comment by jaacoppi** [comment]
Conversion from epub to .txt is very simple and needs not be included in espeak-NG. Closing as out-of-scope.
