### ISSUE TITLE
the possibility of increesing the wpm of espeak-ng past 390 wpm?

### ISSUE THREAD

**Issue by mhussaincov** [espeak-ng/espeak-ng#640]
hi there,
i'm running arch linux with latest espeak-ng from the archlinux repos.
would it be possible to hav the wpm increesed from 390 wpm?
to say 600 wpm?
currently when I output audio to a wav file the limit I believe is 390 wpm and was curious if it could be increesed?
thanks,
Majid Hussain

**Comment by valdisvi** [comment]
To speed up speech more than it is supported directly, eSpeak NG uses [sonic](https://github.com/espeak-ng/sonic) library. In [on-line test site](https://odo.lv/Espeak) you can choose up to 1000WPM (or pass your own speed parameters in URL).
To use sonic library, eSpeak NG should be compiled and built with this library included (and I don't know how it is compiled for Arch). See more at [building on Linux, Mac, BSD](https://github.com/espeak-ng/espeak-ng#linux-mac-bsd).
