### ISSUE TITLE
F-Droid (Request for packaging) - For info

### ISSUE THREAD

**Issue by hotlittlewhitedog** [espeak-ng/espeak-ng#644]
Yop Guys, 

Thanks a lot for your dev, I've created a RFP in F-Droid... 

https://gitlab.com/fdroid/rfp/issues/1066

**Comment by ArenaL5** [comment]
Hello there. I'm trying to speed up the inclusion in F-Droid (there hasn't been much progress in that request).

I created a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7136) with a build recipe, and a maintainer has already replied. They're asking now for a one-sentence summary and a description.

Both used to be provided in the merge request ([as you can see here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7136/diffs)) but they're following now a different approach: they'd like to add them directly to this repo, following either [Fastlane's](https://gitlab.com/snippets/1895688) or [Triple-T's](https://gitlab.com/snippets/1901490) format. This way, it's easier to update the icon, to add translations, changelogs, screenshots...

I can help you with translating them to Spanish from Spain, if you'd like.

There are also a couple of details that aren't absolutely necessary, but would simplify the recipe:
- Replacing `gradle:3.2.1` with `gradle:3.4.0` in [`android/build.gradle`](https://github.com/espeak-ng/espeak-ng/blob/master/android/build.gradle) (F-Droid servers auto-detect the version of Gradle they use, and the build doesn't work with `gradle:3.2.1`.
- Removing the three extraneous characters at the beginning of [`dictsource/fa_list`](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/fa_list) (it's no visible in the link, but that file starts with three U+0003 END OF TEXT characters, so the servers mistake it for a binary file.

**Comment by ArenaL5** [comment]
[Espeak-NG is finally published on F-Droid.](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7136) For the moment, it has to be uploaded manually, but updates can be done quickly.
