### ISSUE TITLE
error: bad file descriptor.

### ISSUE THREAD

**Issue by lilmike** [espeak-ng/espeak-ng#645]
When running espeak-ng from git (latest master as of right now, packaged with espeak-ng-git package in AUR arch linux), I get the following errors:

error: No such file or directory
error: Bad file descriptor

I have strace output in case it helps.

[error.txt](https://github.com/espeak-ng/espeak-ng/files/3507373/error.txt)

-Michael.

**Comment by valdisvi** [comment]
Can you fix that latest now MBROLA is working for now?
I fixed one found regression in it:
https://github.com/valdisvi/MBROLA/commit/3b77613e8675a09106d13e4b06aefaffdabf79ec

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
