### ISSUE TITLE
Suggestions: Wanted Learning ToMake Your own voice Tutorial 

### ISSUE THREAD

**Issue by Punkroku** [espeak-ng/espeak-ng#646]
Suggestions: Wanted Learning ToMake Your own voice Tutorial or data on how mbrola works or what ever engine is used in voices.

Also I wanted someone to look at papagayos broken software. Last I used it it would not output all the voice shapes and I had to manually lip sync but it was faster that hand lip syncing.

I wanted to see if espeak -ipa 
or espeak -x  output could be mapped to img files like the .dat file that papagayo creates.

I think I need to learn how to create a dictionary to change the phenomes to lips. I think I can do this easy using the sed -e 's/TEXTTOFIND/REPLACE/g;s/REGEXPR2/_replacementText_/g' program.

**Comment by Punkroku** [comment]
Also I create a shortlink for google translate jp 2 en at tiny.cc/jp2en it would be cool to use that right click selected text and send to espeak.. I saw a program somewhere on the web about this.

**Comment by valdisvi** [comment]
Short guide to create MBROLA voice is described in this project:
[https://github.com/numediart/MBROLATOR](https://github.com/numediart/MBROLATOR).

**Comment by Punkroku** [comment]
Thank you I also saw something in the DOCS folder describing integrating MBROLA and the voices naming convention

**Comment by valdisvi** [comment]
eSpeak NG integration with MBROLA is described in [mbrola.md](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md).

**Comment by valdisvi** [comment]
@Punkroku first I mistook you as some not very logically writing user, but looking at https://github.com/game-icons/icons/issues/588 issue looks you are just some troll/robot/spammer.
