### ISSUE TITLE
Missing contributing guidelines

### ISSUE THREAD

**Issue by The1Freeman** [espeak-ng/espeak-ng#647]
Currently, it is unclear on how anyone who's new to this project or anyone who wants to contribute fixes to certain words to properly edit the required files as desired, as though I was unable to find proper documentation about how a _rule file works and how to properly edit a _list file.

It would be great if there was a way of properly knowing how to submit feedback and the accompanying fixes (aside from using the issues to which the online dev version points to) as is missing a proper issues & pull request template, as well as a code of conduct to properly contribute to this project.

**Comment by valdisvi** [comment]
Initial version of contribution guidelines is provided [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md). Other documents, such as [README](https://github.com/valdisvi/espeak-ng/blob/master/README.md) is updated accordingly.
