### ISSUE TITLE
Dutch language improvements

### ISSUE THREAD

**Issue by leonardder** [espeak-ng/espeak-ng#65]
Although some improvements in the Dutch language have been included in the original espeak in 2012 and 2013, Dutch is still far from ideal. Things which have to be improved:
- The [r] phoneme, which is a trilled rhotic yet, but doesn't sound as it should. Furthermore, in Dutch, we have several accepted phonemes for words with 'r'.
- The [Q] phoneme in words with 'g' really doesn't sound as it should either
- [v] is used for words with 'v', which makes 'v' sound like [w]. It is not possible to distinguish 'van' from 'wan', for example
- Pronunciation of several English and French words which have been incorporated into the Dutch language

In [this](https://github.com/leonardder/espeak-ng/tree/dutch_ch/g_changes) branch, i started work on ch/g. Only thing I did so far is renaming the [x2] phoneme to [x], making words with [x] use the [x2] phoneme in Afrikaans. Please let me know whether this is desired behavior, or whether I should change nl-rules and nl-list to have [x2] instead, thereby abandoning [x].

**Comment by ValdisVitolins** [comment]
I believe you can name phonemes in any way which is consistent between phonemes and language rules.
But for better order you should follow IPA naming and consider that master [phonemes](/espeak-ng/espeak-ng/blob/master/phsource/phonemes) file will be overridden if you will use the same phoneme name in your chosen language.

**Comment by ValdisVitolins** [comment]
Leonard, I have cherry-picked your commit 0d56071. Keep up the good work!
