### ISSUE TITLE
the  Chinese  pronunciation  is wrong 

### ISSUE THREAD

**Issue by tears510** [espeak-ng/espeak-ng#664]
the  Chinese  voice  pronunciation  is wrong ,  zh_dist.

**Comment by nmstoker** [comment]
This doesn't really give enough detail for anyone to help you. Could you elaborate?

**Comment by YangtseSu** [comment]
It sounds more like noise.
I can't hear any Chinese words.

**Comment by valdisvi** [comment]
Please provide following information:
1. example of text, which demonstrates error and allows reproducing it;
2. explanation, why produced spelling is wrong and how it should be corrected.

Look for more details at [Simple steps for your feedback](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#simple-steps-for-your-feedback).

**Comment by hozosch** [comment]
And which voice do you mean? Cantonese or mandarin?

**Comment by YangtseSu** [comment]
Only cmn.
1. example text : "大"  [dà]
2.It should be https://fanyi.baidu.com/#zh/en/%E5%A4%A7
(click the speaker)

But it sounds like "大4" [dà sì],https://fanyi.baidu.com/#zh/en/%E5%A4%A74
Espeak-ng pronounced the four tones as 1234. 

https://en.wikipedia.org/wiki/Chinese_language#Tones

**Comment by hozosch** [comment]
Ah I see. This should be already  fixed in espeak 1.49.3 dev. You can test it [here](http://odo.lv/Espeak)

**Comment by tomcumming** [comment]
@hozosch will this get built and published as a `.deb` or something equivalent?

**Comment by hozosch** [comment]
Simon Ei geldinger has provided builds that he compiled out of the latest commits. I unfortunately don't have the mail anymore though, so someone else, maybe even the author himself, has to provide the link here.

**Comment by jaacoppi** [comment]
Should this be closed?

**Comment by valdisvi** [comment]
We could decide to close issue when it is fixed in code, but some of authors may consider issue resolved only when they got it fixed on their computer. Therefore policy in [contributor guideline](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#simple-steps-for-your-feedback) is that author closes it when it is resolved.
But, we can decide to do it differently.
