### ISSUE TITLE
Reverse-engineering espeak-ng for STT

### ISSUE THREAD

**Issue by guest271314** [espeak-ng/espeak-ng#669]
`espeak-ng` can produce `.wav` files using `--stdout`. 

What is the relative difficulty of reverse-engineering `espeak-ng` to take input as `.wav` file produced by `espeak-ng` to analyze the audio and output plain text?

**Comment by materia-cccp** [comment]
reversing function is not reverse engineering its a whole nother task

**Comment by guest271314** [comment]
@materia-cccp The concept is simple. Since `espeak-ng` is currently capable if mapping text to audio and given the audio output is the same or similar when the same input text and voice is used it should be possible to adjust the existing code to map the audio that will be produced by input text to output text.
