### ISSUE TITLE
Tool for testing espeak-ng

### ISSUE THREAD

**Issue by poeeain** [espeak-ng/espeak-ng#680]
I'm using Mac (Mojave) and trying to install espeak-ng with brew. But it doesn't sound anything. (Maybe I don't know how to properly install it) 
And I try to use espeak-ng from my phone, I found an app "eSpeak NG" on google playstore but the last updated was since August.
Again, I try to use **espeakng.js** [here](https://github.com/espeak-ng/espeak-ng/tree/master/emscripten) for web based, but this seems outdate too. 
Is there any tool or place I can test espeak-ng sound? Thanks in advance.

**Comment by valdisvi** [comment]
[https://odo.lv/Espeak](https://odo.lv/Espeak).

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
