### ISSUE TITLE
1.50 tarball contains symlinks instead of copies of autostuff files

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#683]
In the 1.50 tarball (https://github.com/espeak-ng/espeak-ng/releases/download/1.50/espeak-ng-1.50.tgz), the INSTALL, compile, config.guess, config.sub, depcomp, install-sh ltmain.sh, and missing files are only symlinks to /usr/share/{automake-1.15,libtool}.  They are thus completely useless on a system which does not exactly have these installed.

**Comment by sthibaul** [comment]
The tarball even contains config.log, Makefile, etc. These are not really supposed to be included in an upstream tarball. The make dist target of automake should be used instead to produce the release tarballs.

**Comment by valdisvi** [comment]
I assumed all building artefacts are removed with `make clean` command. 
@sthibaul, can you list all unneeded items and then could update [Makefile.am](https://github.com/espeak-ng/espeak-ng/blob/master/Makefile.am#L63).
Then I assume, proper project configuration for distribution could be get by:
```
make clean
make dist
```
commands.

**Comment by sthibaul** [comment]
Not all artefacts are removed with `make clean`, only the actual compilation artefacts. Configuration artefacts are removed with `make distclean`

Concerning the symlinks, that's because autogen.sh invokes `libtoolize` & `automake` manually without passing `--copy`. https://github.com/espeak-ng/espeak-ng/pull/687 adds the proper option. I'd recommend just using `autoreconf` instead which does everything needed automatically and as appropriate.

**Comment by sthibaul** [comment]
To make a dist tarball, one only needs to run `./configure && make dist`, there is no need to `make somethingclean`, since `make dist` just picks up the files mentioned in all `Makefile.am`, it does not look at existing files. That allows to even make a proper dist out of a very dirty checkout.

**Comment by sthibaul** [comment]
Running a `make distcheck` after that is a good way to catch missing files.

**Comment by sthibaul** [comment]
(which can be added to `noinst_HEADERS` for instance)

**Comment by valdisvi** [comment]
Tried `./configure && make dist` with pull request #687 applied,
`make distcheck` showed:
```
...
  CC       src/ucd-tools/src/src_libespeak_ng_la-case.lo
../../src/ucd-tools/src/case.c:25:21: fatal error: ucd/ucd.h: No such file or directory
compilation terminated.
Makefile:1494: recipe for target 'src/ucd-tools/src/src_libespeak_ng_la-case.lo' failed
make[2]: *** [src/ucd-tools/src/src_libespeak_ng_la-case.lo] Error 1
make[2]: Leaving directory '/home/valdis/code/espeak-ng/espeak-ng-1.51-dev/_build/sub'
Makefile:678: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/valdis/code/espeak-ng/espeak-ng-1.51-dev/_build/sub'
Makefile:2132: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
```
Any ideas?

**Comment by sthibaul** [comment]
Like I said, this probably needs to be added to `noinst_HEADERS` so that `make dist` knows it has to put it in the tarbal..

**Comment by valdisvi** [comment]
Can you provide example/pull request where it should be added?

**Comment by sthibaul** [comment]
https://github.com/espeak-ng/espeak-ng/pull/688

I however see that espeak-ng can't be built from source. You need to add proper support for that as well, i.e. so that

    mkdir build && cd build && ../configure && make 

works. Here, probably add a `-I$(srcdir)/src/ucd-tools/include` to CPPFLAGS

**Comment by rhdunn** [comment]
I have updated `AM_CFLAGS` to use `srcdir` when referencing the `ucd-tools` include path. That fixes the error with the `ucd/ucd.h` file not being found.

There are two groups of errors:
1.  errors from building in a different build directory;
2.  errors from building from a `make dist` generated tarball.

**Comment by sthibaul** [comment]
This is fixed in the latest release tarball
