### ISSUE TITLE
inform that --stdin flag reads multi-line text and then speaks it after 

### ISSUE THREAD

**Issue by sthibaul** [espeak-ng/espeak-ng#686]
From http://bugs.debian.org/946029:

“There's two ways to have espeak read from stdin:
- running it with no arguments, which makes it speak every line; and
- running it with the --stdin flag, which makes it read a text file (viz. multi-line text) from stdin until the EOF, and then speak it all at once.

I found out the difference between the two because, I wanted to pipe edbrowse, an interactive program, to espeak to make it speak out every new line of output -so I read the manpage of espeak for flags to use stdin, since some other programs in Debian require a flag.

I figured out after a while to not use that flag but, it'd be nice if the manpage added a sentence or two in the description for the --stdin flag mentioning this different behaviour from no-argument espeak.”

**Comment by valdisvi** [comment]
Actually it was told already, but less explicitly. I hope fix in 541cd90 make it more clear.
