### ISSUE TITLE
Speaking '1,,2' in German only says 'eins'.

### ISSUE THREAD

**Issue by rhdunn** [espeak-ng/espeak-ng#69]
The following is spoken given the input `1,,2`:

```
$src/espeak-ng -vde -x "1,,2"
_'aIns
$src/espeak-ng -ven -x "1,,2"
w'0n t'u:
```

The German output should be:

```
_'aIns tsv'aI
```

Source: https://github.com/nvaccess/nvda/issues/4956

**Comment by domasofan** [comment]
Hi,

yes can confirm that in espeak 1.48.15 using nvda as well.
interesting.



Am 10.01.2016 um 10:11 schrieb Reece H. Dunn:
> The following is spoken given the input `1,,2`:
>
>      $src/espeak-ng -vde -x "1,,2"
>      _'aIns
>      $src/espeak-ng -ven -x "1,,2"
>      w'0n t'u:
>
> The German output should be:
>
>      _'aIns tsv'aI
>
> Source: https://github.com/nvaccess/nvda/issues/4956
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/69
>

-- 
Simon Eigeldinger
Follow me on Twitter: http://www.twitter.com/domasofan/
E-Mail: simon.eigeldinger@vol.at
MSN: simon_eigeldinger@hotmail.com
ICQ: 121823966
Jabber: domasofan@andrelouis.com

---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by rhdunn** [comment]
I have tracked this down to `TranslateClause` in `translate.c` lines 2627-2631. In English, the code is executing the `space_inserted = 1;` branch. In German it is taking the else branch (setting `decimal_sep_count = 1;`).

**Comment by ValdisVitolins** [comment]
The same problem for such is for Latvian also.
`espeak-ng -vlv -x "1,,2"` says:
```
v'iens
```
But I think it should not be just `v'iens d'ivi`, but `v'iens k'omats_ komats_ d'ivi` (one comma comma two) because it should be considered as a number, not text sentence.

**Comment by ValdisVitolins** [comment]
I'm working on this and (hopefully) will provide patch tomorrow.
