### ISSUE TITLE
Differences between bashkir and tatar?

### ISSUE THREAD

**Issue by hozosch** [espeak-ng/espeak-ng#691]
Hi,
I noticed that the numbers in these two languages I mentioned are exactly the same, so is there a difference there? I don't see a point in adding the same language twice with different names.

**Comment by valdisvi** [comment]
They are related, but completely different languages used in different regions of Russian Federation:
- [Tatar](https://en.wikipedia.org/wiki/Tatar_language) in [Tatarstan](https://en.wikipedia.org/wiki/Tatarstan),
- [Bashkir](https://en.wikipedia.org/wiki/Bashkir_language) in [Bashkortostan](https://en.wikipedia.org/wiki/Bashkortostan).

For both of them I created initial configuration as a starting point for interested contributors, looking at [https://www.101languages.net/](https://www.101languages.net/). It may be, I did something wrong, but potential contributors have not tried to give any contribution/feedback yet.
