### ISSUE TITLE
Crash when folder has accented character

### ISSUE THREAD

**Issue by Qchristensen** [espeak-ng/espeak-ng#692]
(Template copied from NVDA issue template - filed as NVDA issue 10607 https://github.com/nvaccess/nvda/issues/10607)

### Steps to reproduce:

1. Start NVDA 2019.3 beta 1.
2. Create a portable copy.
3. When asked where to create the portable copy, specify a folder name which includes a character such as é, ç, ş, ğ.
4. Start the portable version.
5. Open NVDA's synthesizer dialog (NVDA+control+g)
6. Press HOME or use the arrow keys to select the "eSpeak NG" synthesizer.
7. Press ENTER.

### Actual behavior:

At the last step, NVDA immediately stops running (visually, the icon stays in the system tray until you mouse over it, that's simply an artifact of Windows not cleaning up properly - NVDA is not running by this point).

The very last entry in my NVDA log at Debug level is:

IO - inputCore.InputManager.executeGesture (13:03:39.817) - winInputHook (17464):
Input: kb(desktop):enter

(Registering the ENTER key being pressed to activate the OK button, set the synthesizer and close the synthesizer dialog.)

### Expected behavior:

Synthesizer should switch to eSpeak NG and NVDA should continue working normally.

#### NVDA installed/portable/running from source:
Portable, and setup in a folder which includes an accented character such as é, ç, ş, ğ

#### NVDA version:

2019.3 beta 1 (which uses eSpeak NG 1.51-dev, commit ca65812ac6019926f2fbd7f12c92d7edd3701e0c).

#### Windows version:

Windows 10 Version: 
18362.388

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2019.2.1 works fine in this situation.

**Comment by jaacoppi** [comment]
NVDA has closed this. Should we?

**Comment by rhdunn** [comment]
Thanks. Resolving as fixed.

**Comment by lukaszgo1** [comment]
Why exactly have you closed this? The solution employed in NVDA is merely an work around that is if eSpeak files are placed in a path with accented character eSpeak cannot be used and NVDA falls back to the another synthesizer assuming that any other engine is available.
