### ISSUE TITLE
Espeak ENG speech-dispatcher driver produces electric noise sounds while using it with Pulseaudio sound server

### ISSUE THREAD

**Issue by JanuszChmiel** [espeak-ng/espeak-ng#697]
Dear specialists,
Does somebodyof you know how to setup Pulseaudio sound server and how to setup Speech-dispatcher Espeak eng driver configuration file, so it will finally stop to produce electric noise while speaking? Those noises are louder when user have swap file enabled.
I have got so far while I have thought that The most sad think is, that if Espeak app is being used to produce speech output, no noise present. But when Speech-dispatcher is being used, there are issues.

Thank you very much for yours tips.

**Comment by alexarnaud** [comment]
There is already an issue reported against Speech Dispatcher: https://github.com/brailcom/speechd/issues/198

**Comment by sthibaul** [comment]
Yes and it was fixed,  it was a buffering issue with pulse audio,  now fixed,  please retry
