### ISSUE TITLE
Build fails with gcc10 and -fno-common

### ISSUE THREAD

**Issue by lgbaldoni** [espeak-ng/espeak-ng#699]
espeak-ng 1.50 on openSUSE Tumbleweed, see [log snippet](https://github.com/espeak-ng/espeak-ng/files/4039699/espeak-ng-1.50_gcc10.txt).

**Comment by rhdunn** [comment]
Thanks for the report. This also occurs with gcc 8 using `CFLAGS=flto-4 ./configure`.

I have modified the definitions so they match.

**Comment by lgbaldoni** [comment]
I applied https://github.com/espeak-ng/espeak-ng/commit/5feff569cc8b6d5817f04d9c65a0bd736f82d67d to 1.50, but it's [still failing](https://github.com/espeak-ng/espeak-ng/files/4042198/espeak-ng-1.50_gcc10_log2.txt).

**Comment by rhdunn** [comment]
I can't reproduce that issue locally. It looks like LTO is treating the `samplerate` in libespeak-ng the same as the one in espeak-ng. Does the following fix the issue?:

```
diff --git a/src/espeak-ng.c b/src/espeak-ng.c
index 10b8a887..3a7838cf 100644
--- a/src/espeak-ng.c
+++ b/src/espeak-ng.c
@@ -117,7 +117,7 @@ static const char *help_text =
     "--load     Load voice from a file in current directory by name.\n"
     "-h, --help Show this help.\n";
 
-int samplerate;
+static int samplerate;
 bool quiet = false;
 unsigned int samples_total = 0;
 unsigned int samples_split = 0;
```

If so, I will commit that change.

**Comment by lgbaldoni** [comment]
I can confirm the patch above fixes the build with gcc10.
