### ISSUE TITLE
In French: bad pronunciation of the word "aujourd'hui"

### ISSUE THREAD

**Issue by alexarnaud** [espeak-ng/espeak-ng#701]
Hello,

Environment:
- Debian 10 "Buster"
- Speech Dispatcher 0.9 and master
- Espeak NG 1.49 and master
- In French FR default voice
 
Espeak NG no longer pronounces the following sentence correctly:
> Aujourd'hui nous mangeons des crêpes.

If I remove the "'" the sentence is correctly pronounced so the sentence is:
> Aujourdhui nous mangeons des crêpes.

Let me know if I could help.

Best regards.

**Comment by alexarnaud** [comment]
Note that with espeak the pronunciation was good.

**Comment by valdisvi** [comment]
This cannot be reproduced in eSpeak NG [online testing site](https://odo.lv/Espeak?language=en&eslang=-vfr-fr&speed=160&output=-w&debug=-x&text=Aujourd%27hui+nous+mangeons+des+cr%C3%AApes.%0D%0AAujourdhui+nous+mangeons+des+cr%C3%AApes.&formmethod=get), therefore it probably comes from how speech dispatcher calls eSpeak NG, or how `espeak-ng` executable or `libespeak.so` library is called, or how they use language data files (then bug comes from broken packaging/installation).
Note that recently was released new version of eSpeak NG [1.50](https://github.com/espeak-ng/espeak-ng/releases/tag/1.50). Debian packages of which are available [here](https://packages.debian.org/search?keywords=espeak-ng).

**Comment by alexarnaud** [comment]
That's right. I don't confirm this with your online test.

@sthibaul Any idea what is causing this?

**Comment by alexarnaud** [comment]
I don't obtain the same result with:
> espeak-ng -v fr-fr "aujourd'hui c'est mardi."
(this is correct)

and 
> spd-say "aujourd'hui c'est mardi."
(this is not correct)

**Comment by sthibaul** [comment]
I'm not hearing any difference with my current setup, what is incorrect in the pronounciation?

@alexarnaud  could you perhaps catch the debug log from `/run/user/$uid/speech-dispatcher/log/espeak-ng.lgo` so we can know for sure what speech-dispatcher actually sends to espeak-ng?

**Comment by alexarnaud** [comment]
@sthibaul This happens with SSML only with this command:

> spd-say -x "<speak><mark name="0:11"/>aujourd'hui <mark name="12:17"/>c'est <mark name="18:27"/>vendredi.</speak>"

**Comment by alexarnaud** [comment]
Oops Github drops SSML stuff, you could find the command there:
https://framabin.org/p/?11312a2fa63307c1#SqnruarkMZ/FswPYKbAy+J6VMT26zITycYCFw6GfK00=

**Comment by rhdunn** [comment]
The command (from the framabin link) is:

    spd-say -x "<speak><mark name="0:11"/>aujourd'hui <mark name="12:17"/>c'est <mark name="18:27"/>vendredi.</speak>"

NOTE: If you indent the command with 4 spaces it treats the text as code and does not do any processing on it.

**Comment by alexarnaud** [comment]
I'm reproducing the issue without using Speech Dispatcher directly with:
`    espeak-ng -v fr-fr -m "<speak><mark name="0:11"/>aujourd'hui <mark name="12:17"/>c'est <mark name="18:27"/>vendredi.</speak>"`

**Comment by sthibaul** [comment]
Oh, are you actually talking about the prosody? I do hear a difference there when removing the marks indeed. Perhaps you should post here the wave result with the -w option, so we are sure we are hearing the same thing

**Comment by alexarnaud** [comment]
OK, I don't reproduce the issue with espeak-ng 1.50+dfsg-5 on Debian Testing. Could it be possible to have espeak-ng in backports ?

**Comment by sthibaul** [comment]
Ah. Indeed it makes sense to backport it, I have now uploaded it, we'll just have to wait for it to be accepted.
