### ISSUE TITLE
 In French: bad pronunciation of the letter "ô"

### ISSUE THREAD

**Issue by alexarnaud** [espeak-ng/espeak-ng#702]
Hello,

Environment:
- Debian 10 "Buster"
- Speech Dispatcher 0.9 and master
- Espeak NG 1.49 and master
- In French FR default voice

Espeak NG no longer pronounces the following words correctly:
- Plutôt
- Bientôt

If I remove the "^" the words are correctly pronounced so the word are:
- Plutot
- Bientot

The pronunciation was good with the old espeak.

Let me know if I could help.

Best regards.

**Comment by valdisvi** [comment]
This cannot be reproduced in eSpeak NG [online testing site](https://odo.lv/Espeak?language=en&eslang=-vfr-fr&speed=160&output=-w&debug=-x&text=Plut%C3%B4t.%0D%0ABient%C3%B4t.%0D%0A&formmethod=get). Look also at https://github.com/espeak-ng/espeak-ng/issues/701#issuecomment-578950939.

**Comment by alexarnaud** [comment]
I hear a difference between "bientôt" and "bientot". It should be both pronounce as "bientot". 
[Check there.](https://odo.lv/Espeak?githuburl=&eslang=-vfr-fr&speed=160&output=-w&debug=-x&text=Plut%C3%B4t.+Plutot.%0D%0ABient%C3%B4t.+Bientot.&formmethod=get)

**Comment by alexarnaud** [comment]
@valdisvi Could we expect to have a fix for this one ?

**Comment by alexarnaud** [comment]
I don't see specific pronunciation of "ô" in ./data/annotationsEspeak.

Is there another way to modify pronunciation of a letter ?

**Comment by DataTriny** [comment]
Hello,
I encountered a similar issue with the word "dépôt".
Here is how it is currently translated: dep'O~
And here is how it should be translated: dep'o

I would also like to help fixing this and others that I have found, but I can't get my head around the rule/list files...
Thanks.

**Comment by valdisvi** [comment]
There is specific rule [line 1063 in fr_rules file](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/fr_rules#L1063) to spell **..ôt** as `..O~` in difference of **..ot** which is spelled as `..o` [line 949](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/fr_rules#L949).
Solutions may be:
1. Removing that rule (then will be spelled as `..o:`, coming from default pronunciation of **ô** in [line 1062](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/fr_rules#L1062).
2. Changing existing rule to `ô) t_ o` to spell **..ôt** as `o`.
3. Changing existing rule to `r) ô (t_` for **..rôt**. Or should it be even more specific?

**Comment by alexarnaud** [comment]
@sthibaul Do you know if there is a word where "ô" is pronounced differently than a simple "o"?

IMHO, ô should be announced like "o" as indicated on [the French wikipedia page of the letter "ô"](https://fr.wikipedia.org/wiki/%C3%94).

**Comment by alexarnaud** [comment]
There is the word "fantôme" as [describe here](https://fr.wikipedia.org/wiki/Accent_circonflexe_en_fran%C3%A7ais#Modification_du_timbre_des_voyelles).

**Comment by DataTriny** [comment]
For me, the two later rules in the ô group are wrong because neither "rôt" nor "cône" are pronounced correctly.
Therefore I would suggest removing them.

**Comment by sthibaul** [comment]
@alexarnaud : I would say that "^" precisely makes o always be pronounced like a simple "o" (and not like in "grotte")

**Comment by valdisvi** [comment]
Should I leave just single rule e.g. `ô o:` (long **o**), or `ô o` (short **o**) for **ô**?

**Comment by alexarnaud** [comment]
The right one is long o, yes.

**Comment by alexarnaud** [comment]
After thinking more, I'm not so sure. Can we hear the difference?

**Comment by valdisvi** [comment]
I made [these changes](https://github.com/valdisvi/espeak-ng/commit/8b41079a1b49e5505af7f57f2147b731a280bb7b). Is [this](https://odo.lv/Espeak?&eslang=-vfr-fr&output=-w&debug=-X&text=Plut%C3%B4t%2C+Bient%C3%B4t%2C+fant%C3%B4me%2C+r%C3%B4t%2C+c%C3%B4ne.&formmethod=get) ok?

**Comment by alexarnaud** [comment]
It's perfect :). Many thanks.
