### ISSUE TITLE
--voices option doesn't show mbrola voices 

### ISSUE THREAD

**Issue by hadware** [espeak-ng/espeak-ng#705]
It only show them when the language is specified (eg : `espeak --voices=it`).

**Comment by DidierSpaier** [comment]
Try: espeak-ng --voices=mbrola

**Comment by valdisvi** [comment]
Look for command line parameters [here](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.1.ronn).
With f38ec9d commit you can also look on _all_ voices and variants with parameter `espeak-ng --voices=all`.
