### ISSUE TITLE
pronunciation error with abbreviations followed by "'s"

### ISSUE THREAD

**Issue by kara-louise** [espeak-ng/espeak-ng#706]
Using any of the English voices, abbreviations followed by "'s" such as IBM's or MIT's are read as though the 's is not there.
To clarify, "IBM's mainframes" is read as "IBM mainframes". This only occurs if the abbreviation is in uppercase.
I'm using version 1.49.3 dev which is included with NVDA as of version 2019.2.1.

**Comment by rhdunn** [comment]
Thanks for the bug report. This is also happening with the current version.

**Comment by jaacoppi** [comment]
Fixed in master, please close this ticket.
