### ISSUE TITLE
Where can the android apk be obtained?

### ISSUE THREAD

**Issue by gothmog123** [espeak-ng/espeak-ng#708]
Sorry if I am missing something.

**Comment by valdisvi** [comment]
There are several builds provided in Google Play. Most recent one is probably: [eSpeak NG - with emoticons support](https://play.google.com/store/apps/details?id=com.redzoc.ramees.tts.espeak).

**Comment by sparagi** [comment]
There are also [two packages available on F-Droid](https://search.f-droid.org/?q=espeak&lang=en).  eSpeak is much more recent than eSpeak TTS.

Since this question has been answered, would someone with permission be willing to close this issue?

**Comment by valdisvi** [comment]
Development build of eSpeak NG can be download from [here](https://odo.lv/ftp/tools/espeak-release-signed.apk).

**Comment by valdisvi** [comment]
> Since this question has been answered, would someone with permission be willing to close this issue?

Maintainers of project are not janitors, therefore decision to close issue [we leave as responsibility of its opener](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#simple-steps-for-your-feedback) (5. step).
