### ISSUE TITLE
Questions: Update via GITHUB and Read PDF

### ISSUE THREAD

**Issue by PauloBoaventura** [espeak-ng/espeak-ng#712]
Hello I have some doubts I tried to search ...
It may be my ignorance ...
It is better to ask than to be absent from knowledge.

I actually have two doubts:

1 - How can I update if I already have it installed on my Debian. What is the exact command to update via Git Hub.

2 - How can I make it Read PDF.
I saw that it was possible but I couldn't get it to work.

Thanks in advance!

**Comment by The1Freeman** [comment]
github only provides you with the source code, which you'll have to compile on your own

**Comment by valdisvi** [comment]
General contribution guidelines are provided [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md). You may be more interested in [steps for your contribution](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#steps-for-your-contribution) part.

**Comment by AustinFoss** [comment]
Hello, I know this is closed but just want to leave a little extra for anyone else who finds this.

I believe the correct cli tool to recommend is `pdftotext` as it is included in Debian's standard repos, likely other linux distros, and there appears to be a windows build available. Mac OSX appears to have options but is more complicated.

`pdf2txt` seems to be an older out of date proprietary binary, as well as another independent project by the same name built with scala.

Poppler seems like the more widely used and available option.
