### ISSUE TITLE
Wrong pronunciation of "gif"

### ISSUE THREAD

**Issue by The1Freeman** [espeak-ng/espeak-ng#714]
eSpeak-NG mispronounces gif as "jif", which is incorrect as [every word that starts with a G, then a vowel, then an F, should be pronounced with a hard G. ](http://howtoreallypronouncegif.com/)

**Comment by valdisvi** [comment]
Should it be pronunciated as [`g'if` or `g'If`](https://odo.lv/Espeak?eslang=-ven-gb&output=-w&debug=-x&text=%5B%5Bg%27if%5D%5D.%0D%0A%5B%5Bg%27If%5D%5D.&formmethod=get)?

**Comment by The1Freeman** [comment]
I can barely notice any difference between the two, quite frankly, but `g'If` seems good.

**Comment by valdisvi** [comment]
Then this [should do](https://github.com/valdisvi/espeak-ng/commit/8aff8ada0832c7075d2460042d2bd5df26c13261).

**Comment by The1Freeman** [comment]
It does! Thank you!
