### ISSUE TITLE
Need better error messages if MBROLA engine or voice files are missing

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#715]
Some users are confused: https://bugs.launchpad.net/ubuntu/+source/espeak-ng/+bug/1863981

**Comment by DidierSpaier** [comment]
Maybe remove mb-ir2 from espeak-ng as AFAIK this voice is nowhere to be found.

**Comment by valdisvi** [comment]
Reference to this voice in development version ir removed two years ago: cdb837b430bf14788e084708850a0fa1de987e69 and stable version 1.50 (e.g. for [Debian](https://packages.debian.org/sid/espeak-ng) or [Ubuntu](https://launchpad.net/ubuntu/+source/espeak-ng/1.50+dfsg-6)) doesn't have it.

**Comment by DidierSpaier** [comment]
I looked in espeak instead of espeak-ng, sorry for the noide
