### ISSUE TITLE
Does this codecs compatible with espeakNG ?

### ISSUE THREAD

**Issue by Nokia808** [espeak-ng/espeak-ng#724]
Hi. I'm on Fedora Linux 30 X64 bit Cinnamon edition. On Fedora Linux the default TTS is espeakNG & it is the only one that existing on my system & no other program.

There is a codec in GNOME software center for espeak - see screenshot bellow:

![espeak-codecs](https://user-images.githubusercontent.com/25375330/77997562-27f88400-731f-11ea-9c98-65a4cd4387c8.png)

My question is that: is this codecs compatible with espeakNG also or not & being only usable with old espeak program ?

Thanks.

**Comment by The1Freeman** [comment]
I would test it out and see what happens, it's sort of pointless by asking this question without having it tested yourself.

I'd test it, and if it doesn't work, open a issue with detailed descriptions and logs when possible.

**Comment by valdisvi** [comment]
eSpeak NG is designed as drop-in replacement for eSpeak. Therefore it should work.

**Comment by guest271314** [comment]
It is not clear what the plugin does. 

`espeak-ng` outputs audio encoded as `audio/wav`. 

Does the plugin pipe default audio output from `espeak` and/or `espeak-ng` through a native application to output a different, user-selected audio codec?

If that is the case an intermediary application is not necessary, for example, to convert default `audio/wav` output stream to `audio/ogg;codecs=opus` (`audio/x-opus+ogg`)

`$ espeak-ng --stdout 'test' | opusenc - -`

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
