### ISSUE TITLE
Initial support for Hebrew language

### ISSUE THREAD

**Issue by boracasli98** [espeak-ng/espeak-ng#732]
the file "he" needs to go to /espeak-ng-data/lang/sem/
the file "he_dict" needs to go to /espeak-ng-data/
the file "ph_hebrew" needs to go to /phsource/
the others need to go to /dictsource/

[Hebrew eSpeak.zip](https://github.com/espeak-ng/espeak-ng/files/4483448/Hebrew.eSpeak.zip)
Edit: updated file

**Comment by boracasli98** [comment]
I'm not a native or even fluent Hebrew speaker, but native Hebrew speakers are all welcome to improve this.

**Comment by valdisvi** [comment]
Thanks for contribution!
It is added in project with [slight modificatons](https://github.com/valdisvi/espeak-ng/commit/4573cea94e9751b18e60cb894f77998587139048).
Most important, there is no need to redefine all phonemes without changes from `base1` table. You just need to [describe, which table you extend](https://github.com/valdisvi/espeak-ng/commit/4573cea94e9751b18e60cb894f77998587139048#diff-92efab87cd16a3a3440987daa88b40cf) in `phonemes` file.
I did simple test with text from wikipedia, and it still doesn't find pronunciation for letters:
```
 espeak-ng -x -vhe "הַבֵּן שֶׁלּוֹ הוּא אַבָּא שֶׁלָּהּ"
```
I think, there should be settings in `tr_languages.c` file, similarly to [Arabic](https://github.com/espeak-ng/espeak-ng/blob/f5b3734a465277750ad70aad35182de0725122e4/src/libespeak-ng/tr_languages.c#L510).
