### ISSUE TITLE
[Help Needed] Is there any docs for implementing a custom language?

### ISSUE THREAD

**Issue by purringChaos** [espeak-ng/espeak-ng#733]
The only sounds needed are 
```
m
p
n
t
r
ɹ
ɾ
j
x
χ
ʁ
ʀ
ʔ
h
t͡s
e
a
i
o
s
```

In IPA.
What would the best way to create a language for espeak for this be?

**Comment by valdisvi** [comment]
Look at [Adding or Improving a Language](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md).

**Comment by nmstoker** [comment]
@purringChaos as this answers you question, you ought to close the issue now.

If you run into further problems once you've read those docs then look for similar issues and if none cover your issue then raise another one :slightly_smiling_face:
