### ISSUE TITLE
Update for Turkish

### ISSUE THREAD

**Issue by boracasli98** [espeak-ng/espeak-ng#734]
I updated the Turkish list file and also added a listx file and migrated the words to the latter.

[espeak tr.zip](https://github.com/espeak-ng/espeak-ng/files/4484454/espeak.tr.zip)

**Comment by boracasli98** [comment]
And yes, I'm a native speaker.

**Comment by valdisvi** [comment]
Thanks for your contribution!
It is [added in project](https://github.com/valdisvi/espeak-ng/commit/1764ec647f19258a19665e227c6d15850139963c).
