### ISSUE TITLE
I'm using espeak to generate pronunciations, for a list of words sometimes there will be no space in between two of them

### ISSUE THREAD

**Issue by RuABraun** [espeak-ng/espeak-ng#739]
I'm calling espeak-ng with `-v en-us -f fin -q -x  --ipa=1 --phonout=fout`. And most of the time I can have a list of words and the file, and I'll get pronunciations separated by a space.

However for some words the space is missing, so for two words I have one pronunciation, and I don't know how to split them up.

One example is the words "there are", which results in a sequence phones with no space inbetween.

Is there something one can do to make sure there always is a space?

**Comment by valdisvi** [comment]
It is because in [pronunciation rules](https://github.com/espeak-ng/espeak-ng/blob/1764ec647f19258a19665e227c6d15850139963c/dictsource/en_list#L5612), where only secondary stress is put without word boundary.

**Comment by RuABraun** [comment]
Repeating my question: 

> Is there something one can do to make sure there always is a space?

**Comment by guest271314** [comment]
You can set `-m` option, use SSML for input with `<break>` between "there " and "are", e.g., in _fin_ 

`<speak>there <break time="125ms">are</speak>` 

which outputs

```

 ð_ˈɛɹ
 ˈɑːɹ
```
to _fout_ for the given command.

**Comment by guest271314** [comment]
To replace all space characters in _fin_ with SSML `<break>` elements

`sed -i "s/ /<break time=\"125ms\">/g" fin`

for inut "there are more ways than one to skin a cat" output is

```
 ð_ˈɛɹ
 ɑːɹ
 m_ˈoːɹ
 w_ˈeɪ_z
 ð_ɐ_n
 w_ˈʌ_n
 t_uː
 s_k_ˈɪ_n
 ˈeɪ
 k_ˈæ_t

```

**Comment by guest271314** [comment]
Check your work https://itinerarium.github.io/phoneme-synthesis/

**Comment by RuABraun** [comment]
Thank you @guest271314 !
