### ISSUE TITLE
Cracks when voicing multi-line text

### ISSUE THREAD

**Issue by SeanTolstoyevski** [espeak-ng/espeak-ng#742]
Hi espeak's developers,

This problem was first created in NVDA.

The problem is thought to be in Espeak.

Please check.

Here is the issue: https://github.com/nvaccess/nvda/issues/11061

**Comment by guest271314** [comment]
Can you record the output and post here?

**Comment by SeanTolstoyevski** [comment]
I don't know how I can do it.

But I will record sound.

**Comment by guest271314** [comment]
You can either save the file as WAV 

`$ espeak-ng -w output.wav 'test'` 

or at Firefox, record the output using `MediaRecorder`, see https://github.com/web-platform-tests/wpt/issues/23084#issuecomment-616151476, then save the file in a `.zip` archive then upload here within a comment.

**Comment by SeanTolstoyevski** [comment]
[espeak-test.zip](https://github.com/espeak-ng/espeak-ng/files/4571193/espeak-test.zip)
this is txt file. Test file

Hi,

There is a difference. Espeak pauses between lines.

NVDA does not pause in this type of text. it reads it as a plain sentence.

I did not see any problem when I tested Espeak.

By the way, this happens when the rate of sound is too high.
So this problem does not occur at normal rate.

If there is a parameter I can remove the pauses between lines, I would like to try again. I read `--help` but couldn't find it.
The command line parameters I use are:

`espeak-ng.exe -f espeak-test.txt -w output.wav -s 450 -g 0`

If the problem is not in Espeak, we will continue to topic this issue in NVDA.
As a note: I can say that there are more sound cracks in Turkish.
I can not decide because I am unable to create the same environment at the moment.

**Comment by guest271314** [comment]
The `.zip` file only contains plain text not audio output as a `wav` file. 

Does NVDA support SSML input?

**Comment by SeanTolstoyevski** [comment]
I did not add the wav file because I could not create the problem in NVDA in Espeak.
I don't know what is SSML.
With which parameter can I remove the pause between lines?

Also, when you test it with this file, you will see that it is okay.
To be sure, I need to remove the pause between lines, because NVDA does not pause between lines.

**Comment by guest271314** [comment]
> I don't know what is SSML.

See https://www.w3.org/TR/2010/REC-speech-synthesis11-20100907/. For example essentially an opposite requirement to what is described at this issue https://github.com/espeak-ng/espeak-ng/issues/739.

> With which parameter can I remove the pause between lines?

> To be sure, I need to remove the pause between lines, because NVDA does not pause between lines.

Have not thus far located any `espeak-ng` option to substitute multiple space characters and/or newline characters for single space character. 

--

Potential workarounds:

Am not able to test at a *indows OS. 

At *nix using `gedit` https://wiki.gnome.org/Apps/Gedit Find and Replace with a Regular expression can be used to replace `\s+` with ` `.

![Screenshot_2020-05-03_20-43-39](https://user-images.githubusercontent.com/4174848/80925446-4a971600-8d7f-11ea-8d55-170e7acbc2ec.png)


A local HTML file can also be used to replace `\s+` with a single space character.

```
<!doctype html>

<html>
  <head>
  </head>

  <body>
    <input type="file">
    <script>
      const input = document.querySelector('input[type=file]');
      input.onchange = e => {
        const {files:[file]} = e.target;
        const reader = new FileReader;
        reader.onload = _ => {
          const text = reader.result.replace(/\s+/g, ' ');
          window.open(`data:application/octet-stream,${encodeURIComponent(text)}`);
        }
        reader.readAsText(file);
      }
    </script>
  </body>
</html>
```

results  in a file downloaded to local filesystem with `\s+` replaced with single space character ` `.

<pre>
"test 123 Test one test two Table of content Part 1 : a night part 2 : african part 3 : the end world 
</pre>

**Comment by SeanTolstoyevski** [comment]
No no, this is not what I want to do.

I can delete the lines myself.

I need a parameter for Espeak to ignore the lines.

But still thank you.

**Comment by SeanTolstoyevski** [comment]
This issue seems to have been resolved somehow, so I'm closing  issue. thanks.
