### ISSUE TITLE
Initial support for Turkmen language.

### ISSUE THREAD

**Issue by boracasli98** [espeak-ng/espeak-ng#761]
[tk.zip](https://github.com/espeak-ng/espeak-ng/files/4684087/tk.zip)
These are the files for the initial support of the Turkmen language on eSpeak-NG.
(Again, I'm not a native speaker of this, and also included a listx file because of the long vowels which are not shown in the literary language)

**Comment by valdisvi** [comment]
@boracasli98, `phonemes` file is missing in archive. On which phoneme table you are basing phonemes for Turkmen? I can't figure it out. Can you just write what should be written in **??**
```
phonemetable tk ??
include ph_turkmen
```
in comments?

**Comment by valdisvi** [comment]
.. I think it is based on Turkish (at least it works).

**Comment by valdisvi** [comment]
Merged into project with commit 3d88d7e.

**Comment by boracasli98** [comment]
[Turkmen.zip](https://github.com/espeak-ng/espeak-ng/files/4691816/Turkmen.zip)
After a lot of work, I've made some improvements to the Turkmen language, including the phonemes.

**Comment by valdisvi** [comment]
Changes from second zip file are put into with commit 7cc25ab.

**Comment by boracasli98** [comment]
[espeak-ng-turkmen.zip](https://github.com/espeak-ng/espeak-ng/files/4870721/espeak-ng-turkmen.zip)
This is the updated version of the Turkmen synthesizer, but I've got a problem: When I want espeak-ng to pronounce "köçelerden", it pronounces it "köçölördän" instead of "köçölördön". I still haven't found where the problem is after minutes of trying to figure it out.

**Comment by valdisvi** [comment]
Updates from archive are put into project with commit 53c59f4.
Some notes:
1. You don't need to include `tk_dict` file that is generated automatically.
2. In `phonemes` file there were changes regarding to other languages. I took only changes for Turkmen, to rebase Turkmen phonemes from Turkish to base2:
`phonemetable tk base2`
`include ph_turkmen`
4. Each character for rule add weight for it. Therefore for long rules like
`L04CL04CCiC) i	Y`
you may need to decrease weight with [<](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#special-characters-only-in-post) sign.
3. Line `.C b ç d f g h j k l m n ň p r s ş t w ý z ž` in `tk_rules` file doesn't make compilation error, but actually is ignored, and you still use standard set of consonants. Characters with diacritic marks inherit properties of normal Latin characters, so usually you don't need to change them. If you really need to change definition of consonants, you have to change them in [tr_languages.c](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#redefinition-of-charater-groups) file. E.g. [here it is changed for Arabic](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/tr_languages.c#L376).
