### ISSUE TITLE
Nogai

### ISSUE THREAD

**Issue by boracasli98** [espeak-ng/espeak-ng#764]
[nog.zip](https://github.com/espeak-ng/espeak-ng/files/4688698/nog.zip)

Today's first one. Nogai is a Turkic language.

Edit: File updated.

Uses the Kazakh phonemes file.

**Comment by BenTalagan** [comment]
Hi @boracasli98, I see you've opened multiple issues for various languages recently with zip files. What's the reason for not creating a pull request? Is it that you're not familiar with git and the pull request system ?

**Comment by boracasli98** [comment]
I'm kind of not familiar with the pull request system. Sorry for the inconvenience.

**Comment by BenTalagan** [comment]
Ok, no worries. Are you familiar with `git` ? If so, it should be easy for you to learn how to use the pull request system. If you're not familiar with `git`, you'll probably need some reading and/or some assistance.

**Comment by boracasli98** [comment]
> Ok, no worries. Are you familiar with `git` ? If so, it should be easy for you to learn how to use the pull request system. If you're not familiar with `git`, you'll probably need some reading and/or some assistance.

I'm not familiar with git at all. I used it only to clone the repository onto my computer.

**Comment by BenTalagan** [comment]
Ok, thanks for the answer which gives a clearer context :) Imho the easiest way would still be for you to learn how to use `git`. That would allow you to continue to contribute in the feature, and make corrections easily. 

The general view is that you fork the main repository (from github UI) ; this gives you your own repository on github, which you can pull with `git`. You then integrate your changes in your local copy, you `git` commit them, you `git` push them back to github, and then you can create a pull request from the github UI. It's not that complicated but it's easy to get lost in all the features of `git`. @rhdunn and @valdisvi , what's your policy and advice on that kind of cases?

@boracasli98 : do you plan to create more languages and dialects in the following days?

**Comment by rhdunn** [comment]
We've handled people providing files directly in the past without requiring the use of git, so adding them to issues is fine.

**Comment by valdisvi** [comment]
Merged into project with commit 3a7cc32.
