### ISSUE TITLE
How do you make phonemes?

### ISSUE THREAD

**Issue by petcome** [espeak-ng/espeak-ng#766]
Hello, How do you make phonemes? the phonemes in chinese are not accurate at present, so I want to record and make phonemes again

**Comment by valdisvi** [comment]
I hope [that answers your question](https://github.com/espeak-ng/espeak-ng/blob/master/docs/phontab.md#customization-of-sound-source-files).

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
