### ISSUE TITLE
Pronunciation of Hawaiʻi

### ISSUE THREAD

**Issue by Qchristensen** [espeak-ng/espeak-ng#773]
NV Access received a comment from a user that eSpeak-NG mispronounces the traditional spelling of Hawaii which uses the backward apostrophe (called okina; hex code is 02BB) like so:  Hawaiʻi.  The okina is actually part of the Hawaiian alphabet along with the macron (the horizontal line atop Hawaiian vowels when the word calls for it).

They advised the correct pronunciation of the okina as basically a glottal stop in the pronunciation, nothing more.  At the moment NVDA reads Hawaiʻi as "Ha-wa-02BB-eye" with eSpeak-NG.

In writing this, I just saw https://github.com/espeak-ng/espeak-ng/issues/578 so maybe this has been fixed & we need to update our build of eSpeak-NG?  Perhaps @valdisvi or @ian4uh could confirm?

**Comment by valdisvi** [comment]
This problem doesn't exist in development version of eSpeak NG. You can check it [here](https://odo.lv/Espeak?language=en&eslang=-vhaw&output=-w&debug=-x&text=Hawai%CA%BBi&formmethod=get) and you can update your build of eSpeak NG.

**Comment by rhdunn** [comment]
Specifically, it works in the current version when the user specifies the Hawaiian language. Specifying English, it is spelled out as it does not recognise the word and English cannot currently handle the okina (`ʻ`). Is this issue referring to the English pronunciation?

**Comment by Qchristensen** [comment]
I believe this is using English language pronunciation, yes.

**Comment by valdisvi** [comment]
Simple fix particularly for English would be another rule in `.replace` group:
```
ʻ     '
```
But then it would cause problems for every other language.
More general solution would be to make such replacement for every language.

**Comment by valdisvi** [comment]
As we don't know, how long it will take to fix it properly, for now [I fixed with proposed workaround](https://github.com/valdisvi/espeak-ng/commit/1fb68ffffea45bb1c182fdc27a4a436c69b937e5) with replace rule, which works only for English.
