### ISSUE TITLE
Add new voices to the synthesizer.

### ISSUE THREAD

**Issue by comunicationVoices** [espeak-ng/espeak-ng#783]
Hello guys
I have ### made new voices for espeak ng and I would like you to include them in the synthesizer please, and in advance, thanks in advance.
[NewVoices.zip](https://github.com/espeak-ng/espeak-ng/files/4865401/NewVoices.zip)

**Comment by valdisvi** [comment]
Thanks for contribution!
Your voices are added to the project with commit b06f524.
