### ISSUE TITLE
Please can I build Espeak-ng from Alpine Linux?

### ISSUE THREAD

**Issue by JanuszChmiel** [espeak-ng/espeak-ng#797]
Dear specialists,
Can I build Espeak-ng from Alpine Linux? Or will I face many complex issues?
AlpineLinux is based on Busybox. As A result, build.sh script do not work. Line which contain copy exit1 or similar command do not work. So I Am thinkink. If simply replace copy with cp will not cause other scripting interpreting issues. Alpine Linux is light veight distro. Its official repository contain Espeak, but it do not even transfer sound data by using Libpulse or other libraryes. So if user type 0
echo "export PULSE_SERVER=\"127.0.0.1\"" >> ~/.bashrc

type exit and will login to Alpine again, Espeak do not send sound.
I Am working with Android Termux and Alpine, because it is new distro and I would like to bring Orca, Mate and Espeak-ng and speech-dispatcher. FOrtunately, Pulseaudio 13.0 is present in The repository. Many Mate packages are also available. Including Xorg. I AM only thinking if I have some chance to build The programs as espeak-ng or speech-dispatcher. 

Thank you very much for yours help.

**Comment by jaacoppi** [comment]
Just try to build it and see if you get any error messages. If you do, report them here.

**Comment by JanuszChmiel** [comment]
Autogen.sh fails to work thanks to copy word on one line.
It would be exciting adventure to build Espeak-ng for Alpine Linux. But if
Busybox Bash shell syntax differs too much from build scripts those scripts
would had to be recoded.
I will writ exact error code.

**Comment by JanuszChmiel** [comment]
localhost:/home/espeak-ng# ./autogen.sh

 ./autogen.sh: line 16: --copy: not found
My goal is to use Espeak-ng which will send audio data by using TCP socket
to Pulseaudio sound server which run on Termux and uses Opensles protocol to
send sound packets to some Android module, which play sound.

**Comment by jaacoppi** [comment]
See https://github.com/espeak-ng/espeak-ng/blob/master/autogen.sh

It seems Alpine is missing `libtoolize`. Autogen.sh should provide a proper error message about it instead of just failing.

**Comment by JanuszChmiel** [comment]
Unfortunately, libtoolize is really not available in Alpine Linux
repositoryes. And copy command really do not work because Alpine is based on
Busybox.
So as I see, there is complex and long way to build Espeak-ng and other
similar apps.
Because I think, that building libtoolize from this non standard Linux
distribution will be not easy.

**Comment by JanuszChmiel** [comment]
Alpine contain Espeak which is build without support to stream audio by
using sockets. So I Am triing to build Espeak-ng
I will try to debate with ALpine Linux devs but I think, that some tools are
not used thanks to its security issues so those tools do not met The Alpine
Linux securirty standards.
So very probably, Speech-dispatcher or Espeak-ng will not work or it will be
issues to build it.

**Comment by JanuszChmiel** [comment]
I have a good news. libtoolize exists for ALpine like libtool so I will have
some chances to build.

**Comment by JanuszChmiel** [comment]
Oh. There is complex problem. Espeak-ng have been build successfully except
some errors related to distronary files copy. But Espeak-ng can not send
audio data to Pulseaudio socket. I have installed libao, pulseaudio but it
did not help.
It is very interesting which libraryes Alpine lack so sound do not work.
I would had to run build in PUlseaudio and reconfigure it so it will use
simple protocol and may be, that in this case, Espeak-ng would work, but
this setup is slow and memory issues are presented on Android Termux and
Proot in this case.

**Comment by JanuszChmiel** [comment]
To allow sound support in Termux, Android and Proot, it is necessary to install alsa-plugins-pulse. In this case, Espeak or Espeak-ng will work reliably.
