### ISSUE TITLE
Undefined reference to sonicCreateStream

### ISSUE THREAD

**Issue by zywek123** [espeak-ng/espeak-ng#799]
Hello. When i'm trying to build espeak-ng 1.50 from git, i receive this error
/usr/bin/ld: /home/zywek/git/espeak-ng/src/libespeak-ng/wavegen.c:1380: undefined reference to `sonicCreateStream'
collect2: error: ld returned 1 exit status
I found that when i want to increate speed to bigger value than 600 wpm i have to have libsonic installed.
But When i compile it from git i don't have this functions mentioned abowe.
Is it possible to download a working version of library on arch linux?

**Comment by jaacoppi** [comment]
Compiling works for me on Arch linux. libsonic-git  package installs sonic.h in /usr/include, it provides sonicCreateStream.

**Comment by zywek123** [comment]
@jaacoppi it doesn't work for me. I've installed libsonic-git from aur and trying to compile espeak 1.50 from github and undefined reference to sonicCreateStream

**Comment by beqabeqa473** [comment]
I think issue could be closed if issue is fixed.
Anyway, issue is not at espeak side

**Comment by jaacoppi** [comment]
This is about version 1.50 anyway. Let's open a new ticket if this is still an issue in HEAD.
