### ISSUE TITLE
Broken import of multi-word terms from extra dictionary!?

### ISSUE THREAD

**Issue by repodiac** [espeak-ng/espeak-ng#817]
Hi,

when working on a German loan word dictionary (https://github.com/espeak-ng/espeak-ng/issues/814), to be imported as `de_extra` into espeak-ng, I figured that often/always(?) terms with **more than one word** are either rejected or -- **worse** - imported but somewhat crippled.

An example: Importing the term `common sense` as entry `,kOm@n'sEns` into the German `de_extra` dictionary results in `S'ense z'Enz@`
```
$ espeak-ng -v German "Common Sense" -x
S'ense z'Enz@
```
Is this as expected -- then: why? and how can I provide for a proper import? -- or is this likely a bug?
Thanks for any help!

**Comment by valdisvi** [comment]
Are you sure you have imported entry [according to the rules](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#multiple-words)?
It should look like:
```
(common sense) ,kOm@n'||sEns
```
because otherwise second word `sense` is assumed to be pronunciation and everything else after that is ignored.

**Comment by repodiac** [comment]
Oh great - thank you for the quick response! I'll look into it...

**Comment by repodiac** [comment]
Ok, I just checked out your suggestion: It works **only**, if I use **lower-case** so that the term is `(common sense)` !?! I first tried `(Common Sense)` which resulted in `k'Omo:n z'Enz@` -- in literally pronounced German but not the correct English pronounciation!

Did I miss something or is only lowercase allowed with imports? Does this make sense overall, I mean you loose information on being substantive for a word for instance in German.

**Comment by valdisvi** [comment]
Input words should be lowercase. If you want to mark that word should start or be entire in uppercase, you mark it with additional [flags](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#flags) like `$capital` or `$allcaps`.

**Comment by repodiac** [comment]
Okay, thanks again. I close the issue then
