### ISSUE TITLE
How I can add default Microsoft voice on Raspbian?

### ISSUE THREAD

**Issue by MartinsMaker** [espeak-ng/espeak-ng#821]
Good morning/evening I'm developing a simple vocal assistant and I'm using raspberry pi.
I'd like to use the default windows 10 Italian voice called "Elsa".
my idea was to export all the data of the voice on raspberry, but I can't find the folder with the voices data on the raspberry?
Does someone know where it is?

**Comment by rhdunn** [comment]
eSpeak/eSpeak-ng do not support the Windows 10 voices. Those are implemented by Microsoft in their own TTS engine, and the voice data is proprietary to Microsoft.
