### ISSUE TITLE
where I can download free voices for espeak?

### ISSUE THREAD

**Issue by MartinsMaker** [espeak-ng/espeak-ng#822]
Good evening.
Does someone know where I can download some free voices for espeak ?

**Comment by valdisvi** [comment]
Native voices (synthesized by eSpeak NG itself) are included in package of espeak-ng, which may also use few voices from [Klatt engine](https://github.com/rhdunn/klatt) as [voice variant](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.1.ronn). You may also use also [MBROLA engine](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md) with [its voices](https://github.com/numediart/MBROLA-voices).
