### ISSUE TITLE
Problem with Android

### ISSUE THREAD

**Issue by Rati2019** [espeak-ng/espeak-ng#826]
We have downloaded espeak-ng files for Android from https://github.com/espeak-ng/espeak-ng, but we miss files: 1) espeakdata
2) espeakdata_version. Could you please help us to resolve the issue?

**Comment by rhdunn** [comment]
You need to run the `make espeakdata` target in the makefile in the top-level project directory (not the android directory) which generates those files. There are `apk-release` and `apk-debug` helper targets in that makefile that build the jni library, espeak-ng, the espeak data, and the apk.
