### ISSUE TITLE
no pree build apk for espeak ng

### ISSUE THREAD

**Issue by animeshahilya** [espeak-ng/espeak-ng#828]
we should have a pree build android apk file for any one, who wants to install and test. in that way more feedback can come and the more the feadback, the more potential improovements.

**Comment by valdisvi** [comment]
Here it is: https://odo.lv/ftp/tools/espeak-release-signed.apk

**Comment by animeshahilya** [comment]
i  may be wrong, but we don't have any thing from espeak ng in this app.

**Comment by valdisvi** [comment]
To enable eSpeak, you need to:
1.  go into the Android Text-to-Speech settings UI;
2. enable eSpeak TTS in the Engines section;
3. select eSpeak TTS as the default engine;
4. use the Listen to an example option to check if everything is working.

**Comment by animeshahilya** [comment]
thanks i got it sir
