### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by SGamrekelashvili** [espeak-ng/espeak-ng#829]
I am getting error while make -f Makefile.am.
`makefile.am:67: *** missing separator.  Stop.`

**Comment by valdisvi** [comment]
Input for `make` command is `Makefile` file.
You create it from `Makefile.am` with [automake tools](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#building-1) (first `Makefile.in` and then `Makefile`).

**Comment by ryandesign** [comment]
This issue should be closed.
