### ISSUE TITLE
Please release a new maintenance release of pcaudiolib if possible.

### ISSUE THREAD

**Issue by joey-commits** [espeak-ng/espeak-ng#835]
Hi,
I am reporting this here because issues seem to be disabled in the pcaudiolib repo. Some distros are wary of diverging from upstream and there are several alsa issues fixed in pcaudiolib that are causing problems for espeakup users. Let me know if there is any help needed before the release can be made. Thank you.

**Comment by joey-commits** [comment]
By diverging from upstream I mean including patches or unreleased git versions etc that diverge from upstream stable.

**Comment by valdisvi** [comment]
I don't know where packagers of all distributions take their source, but for development of eSpeak NG we use [https://github.com/espeak-ng/pcaudiolib/](https://github.com/espeak-ng/pcaudiolib/) and, as far as I know, @sthibaul uses it to package pcaudiolib for Debian. Best way would be to provide  fixes/patches as [pull requests](https://github.com/espeak-ng/pcaudiolib/pulls) to that project.

**Comment by joey-commits** [comment]
Github is where distros get there source from what I understand. What I mean is that the last release was 1.1 in 2016. Some distros especially those that are rolling are reluctant to take a github pull from a snapshot in time and would rather take an actual release. I am just wondering if you could cut a 1.2 release on github with the latest changes.

**Comment by ryandesign** [comment]
pcaudiolib 1.2 was released July 30 and re-released today, August 18, so this issue should be closed, and future issues about pcaudiolib should be filed at https://github.com/espeak-ng/pcaudiolib/issues.
