### ISSUE TITLE
Arabic Long Vowels are Mispronounced

### ISSUE THREAD

**Issue by Turkrosoft** [espeak-ng/espeak-ng#842]
Many of the Arabic letters are mispronounced when spelled individually. A list of examples are as follows:
ر>raa
ل>laam
ص>saad
In all of the cases, the two a's are voiced as two separate letters rather than a long aa sound making up one long sound.

**Comment by Turkrosoft** [comment]
I lack the knowledge to properly explain the following, but I will try my best.
Certain letters should be distinguished from others. Letters like sad, ra or qaf, for instance, will make the long aa (alef) following them sound different from an alef that comes after, for example, seen or kaf. Just wanted to ask that this be taken into account.
To produce the sound for the first set of letters, you may refer to the phoneme used for UK English to pronounce such words as "car", or the individual pronunciation of the letter "o" in Uzbek, which is similar to how "au" is pronounced in US English. As for the second group of letters, you may refer to "ə (schwa)" in Azerbaijan or its equivalent in Finnish.

**Comment by valdisvi** [comment]
Pronunciation of mentioned examples comes from [ar_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/ar_list) file e.g. [taa?](https://github.com/espeak-ng/espeak-ng/blob/7df533b7b7192b592360764cd8cfd91a91371087/dictsource/ar_list#L35).
Probably in most of cases with doubled vowels, they actually should be rewritten with lengthening mark. E.g. instead of `aa` should be `a:`. If you confirm that it is correct, I can fix all these lines.

**Comment by Turkrosoft** [comment]
Yes, I suppose you're right.

**Comment by valdisvi** [comment]
What about words, where two, little bit different sounds of **a** (`a` and `A`) are used e.g. [Aajn](https://github.com/espeak-ng/espeak-ng/blob/7df533b7b7192b592360764cd8cfd91a91371087/dictsource/ar_list#L103) or [?arbaAah](https://github.com/espeak-ng/espeak-ng/blob/7df533b7b7192b592360764cd8cfd91a91371087/dictsource/ar_list#L140)? Should I leave them as is?

**Comment by jasondiab** [comment]
Hello @Turkrosoft, how did you get the Arabic to work? I've been having some trouble as addressed in issue #891 
Would really appreciate your input.

**Comment by hozosch** [comment]
He's using it as part of NVDA, a screen reader, which comes with ESpeak NG as its default speech synthesizer, and with that, all languages are operational.
