### ISSUE TITLE
mbrolator doesn't works on ubuntu

### ISSUE THREAD

**Issue by kcgaurab110** [espeak-ng/espeak-ng#846]
I am trying to follow the steps to create your own voice using mbrolator but somehow mbrolator part is not working in my pc why is that kinds of issues are comming?

**Comment by 0x5066** [comment]
posting logs would be helpful (as well as steps to reproduce what went wrong), as others otherwise cant figure out what is going on

**Comment by valdisvi** [comment]
Proper place to report this issue would be [MBROLATOR](https://github.com/numediart/MBROLATOR) project. And first thing you need to check is that your [MBROLATOR works properly in 64-bit environment](https://github.com/numediart/MBROLATOR/issues/1).
