### ISSUE TITLE
Some French diacritics are explicitly spelled out

### ISSUE THREAD

**Issue by CorentinJ** [espeak-ng/espeak-ng#854]
Hello, I found that French characters that have diacritics will be explicitly spelled out if they are at the end of a sentence.

This is fine:
```
>> espeak-ng "Je vais" -q -x -v fr-fr
Z@- v'E
```

This spells out "a accent grave":
```
>> espeak-ng "Je vais à" -q -x -v fr-fr
Z@- v'Ez2 ,a_|aksA~gr'av_|
```

This is fine:
```
>> espeak-ng "Je vais à la mer" -q -x -v fr-fr
Z@- v'Ez2 a la- m'Er
```

**Comment by valdisvi** [comment]
I think, similar problem was with `ô` at the end of sentence also, which is fixed with commit 9e9c0a04.

**Comment by CorentinJ** [comment]
Yes I had found the same problem with `ô` indeed.

Should we only worry about letters which can be words? The issue also persists with other diacritics such as `é, è, ê, â, ...`, but I suppose they won't pop up as single character words in sentences.

**Comment by valdisvi** [comment]
If letter can be also word, it should be noted with `_` prefix in xx_list file. For other possible problematic letters look at [fr_list](https://github.com/espeak-ng/espeak-ng/blob/9e9c0a042b23d1b0ecd9871b5b60d56e9aeeca2f/dictsource/fr_list#L37) file.
