### ISSUE TITLE
Cross compiling not work

### ISSUE THREAD

**Issue by leobbb** [espeak-ng/espeak-ng#856]
Hi, 
I want to build espeak-ng dynamic library for RK platform, but it seems not work.
build: x86_64-linux-gnu, host: aarch64-linux-gnu

I use command  
CC=gcc  ./configure  --host=aarch64-linux-gnu
make -B src/espeak-ng src/speak-ng

Build system had done and no error was reported. But, i found the type of espeak-ng library not changed.
readelf -h src/.libs/libespeak-ng.so.1.1.51
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64

Please tell me how to make it work? 
Thank you for your help.

**Comment by jaacoppi** [comment]
Cross compiling works for me. Are you able to cross compile other software on your machine - Are you sure this is a problem with espeak-ng or is it a problem in your build system?

The most common problem is that your system is missing the cross compiler. Make sure aarch64-linux-gnu-gcc is installed.

**Comment by leobbb** [comment]
> Cross compiling works for me. Are you able to cross compile other software on your machine - Are you sure this is a problem with espeak-ng or is it a problem in your build system?
> 
> The most common problem is that your system is missing the cross compiler. Make sure aarch64-linux-gnu-gcc is installed.

 Thank you for replying.
You are right, I am not install aarch64-linux-gnu-gcc. Now, this problem had done.

The command i used in bottom.
`mkdir $HOME/build_out

export PATH=$HOME/build_tool/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin:$PATH
CC=aarch64-linux-gnu-gcc  CXX=aarch64-linux-gnu-c++   ./configure --host=aarch64-linux-gnu  prefix=$HOME/build_out  --with-extdict-zh=yes --with-extdict-zhy=yes

make -B src/espeak-ng src/speak-ng`

**Comment by yiluzhuimeng** [comment]
> Hi, I suffer the similar problem.
> 
> Cross compiling is successful. But make install failed!
> 
> ESPEAK_DATA_PATH=/home/ai/Workspace/espeak-ng src/espeak-ng --compile-intonations && ESPEAK_DATA_PATH=/home/ai/Workspace//espeak-ng src/espeak-ng --compile-phonemes && touch phsource/phonemes.stamp src/espeak-ng: line 117: /home/ai/Workspace/espeak-ng/src/.libs/lt-espeak-ng: cannot execute binary file: Exec format error src/espeak-ng: line 117: /home/ai/Workspace/espeak-ng/src/.libs/lt-espeak-ng: Success Makefile:2800: recipe for target 'phsource/phonemes.stamp' failed make: *** [phsource/phonemes.stamp] Error 126

i have the same question,how to solve it ,thank you

**Comment by jaacoppi** [comment]
You have cross-compiled src/espeak-ng. Then make install tries to use that program.

I'm no expert at cross-compiling, but shouldn't you compile on the host program (which you've done) and then install on the target computer, not the host? You won't be able to run the program on the host computer anyway.

https://duckduckgo.com/?t=ffab&q=cannot+execute+binary+file%3A+Exec+format+error&ia=web
