### ISSUE TITLE
Can't find Japanese language code.

### ISSUE THREAD

**Issue by gelodefaultbrain** [espeak-ng/espeak-ng#864]
Hello, I saw on your documentation on supported languages [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages.md) 

I am using the latest version that I downloaded [here](https://github.com/espeak-ng/espeak-ng/releases).

Clearly stated here
`jpx | ja | Japanese | Japanese[3]`

But when I tried it on my computer, there's no such thing

```
C:\Users\LENOVO>espeak-ng --version
eSpeak NG text-to-speech: 1.50  Data at: C:\Program Files\eSpeak NG\/espeak-ng-data
```

```
C:\Users\LENOVO>espeak-ng --voices
Pty Language       Age/Gender VoiceName          File                 Other Languages
 5  af              --/M      Afrikaans          gmw\af
 5  am              --/M      Amharic            sem\am
 5  an              --/M      Aragonese          roa\an
 5  as              --/M      Assamese           inc\as
 5  az              --/M      Azerbaijani        trk\az
 5  bg              --/M      Bulgarian          zls\bg
 5  bn              --/M      Bengali            inc\bn
 5  bs              --/M      Bosnian            zls\bs
 5  ca              --/M      Catalan            roa\ca
 5  cmn             --/M      Chinese_(Mandarin) sit\cmn              (zh-cmn 5)(zh 5)
 5  cs              --/M      Czech              zlw\cs
 5  cy              --/M      Welsh              cel\cy
 5  da              --/M      Danish             gmq\da
 5  de              --/M      German             gmw\de
 5  el              --/M      Greek              grk\el
 5  en-029          --/M      English_(Caribbean) gmw\en-029           (en 10)
 2  en-gb           --/M      English_(Great_Britain) gmw\en               (en 2)
 5  en-gb-scotland  --/M      English_(Scotland) gmw\en-GB-scotland   (en 4)
 5  en-gb-x-gbclan  --/M      English_(Lancaster) gmw\en-GB-x-gbclan   (en-gb 3)(en 5)
 5  en-gb-x-gbcwmd  --/M      English_(West_Midlands) gmw\en-GB-x-gbcwmd   (en-gb 9)(en 9)
 5  en-gb-x-rp      --/M      English_(Received_Pronunciation) gmw\en-GB-x-rp       (en-gb 4)(en 5)
 2  en-us           --/M      English_(America)  gmw\en-US            (en 3)
 5  eo              --/M      Esperanto          art\eo
 5  es              --/M      Spanish_(Spain)    roa\es
 5  es-419          --/M      Spanish_(Latin_America) roa\es-419           (es-mx 6)(es 6)
 5  et              --/M      Estonian           urj\et
 5  eu              --/M      Basque             eu
 5  fa              --/M      Persian            ira\fa
 5  fa-latn         --/M      Persian_(Pinglish) ira\fa-Latn
 5  fi              --/M      Finnish            urj\fi
 5  fr-be           --/M      French_(Belgium)   roa\fr-BE            (fr 8)
 5  fr-fr           --/M      French_(France)    roa\fr               (fr 5)
 5  ga              --/M      Gaelic_(Irish)     cel\ga
 5  gd              --/M      Gaelic_(Scottish)  cel\gd
 5  gn              --/M      Guarani            sai\gn
 5  grc             --/M      Greek_(Ancient)    grk\grc
 5  gu              --/M      Gujarati           inc\gu
 5  hi              --/M      Hindi              inc\hi
 5  hr              --/M      Croatian           zls\hr               (hbs 5)
 5  hu              --/M      Hungarian          urj\hu
 5  hy              --/M      Armenian_(East_Armenia) ine\hy               (hy-arevela 5)
 5  hyw             --/M      Armenian_(West_Armenia) ine\hyw              (hy-arevmda 5)(hy 8)
 5  ia              --/M      Interlingua        art\ia
 5  id              --/M      Indonesian         poz\id
 5  is              --/M      Icelandic          gmq\is
 5  it              --/M      Italian            roa\it
 5  jbo             --/M      Lojban             art\jbo
 5  ka              --/M      Georgian           ccs\ka
 5  kl              --/M      Greenlandic        esx\kl
 5  kn              --/M      Kannada            dra\kn
 5  ko              --/M      Korean             ko
 5  ku              --/M      Kurdish            ira\ku
 5  ky              --/M      Kyrgyz             trk\ky
 5  la              --/M      Latin              itc\la
 5  lfn             --/M      Lingua_Franca_Nova art\lfn
 5  lt              --/M      Lithuanian         bat\lt
 5  lv              --/M      Latvian            bat\lv
 5  mk              --/M      Macedonian         zls\mk
 5  ml              --/M      Malayalam          dra\ml
 5  mr              --/M      Marathi            inc\mr
 5  ms              --/M      Malay              poz\ms
 5  mt              --/M      Maltese            sem\mt
 5  my              --/M      Myanmar_(Burmese)  sit\my
 5  nb              --/M      Norwegian_Bokmål  gmq\nb               (no 5)
 5  nci             --/M      Nahuatl_(Classical) azc\nci
 5  ne              --/M      Nepali             inc\ne
 5  nl              --/M      Dutch              gmw\nl
 5  om              --/M      Oromo              cus\om
 5  or              --/M      Oriya              inc\or
 5  pa              --/M      Punjabi            inc\pa
 5  pap             --/M      Papiamento         roa\pap
 5  pl              --/M      Polish             zlw\pl
 5  pt              --/M      Portuguese_(Portugal) roa\pt               (pt-pt 5)
 5  pt-br           --/M      Portuguese_(Brazil) roa\pt-BR            (pt 6)
 5  ro              --/M      Romanian           roa\ro
 5  ru              --/M      Russian            zle\ru
 5  si              --/M      Sinhala            inc\si
 5  sk              --/M      Slovak             zlw\sk
 5  sl              --/M      Slovenian          zls\sl
 5  sq              --/M      Albanian           ine\sq
 5  sr              --/M      Serbian            zls\sr
 5  sv              --/M      Swedish            gmq\sv
 5  sw              --/M      Swahili            bnt\sw
 5  ta              --/M      Tamil              dra\ta
 5  te              --/M      Telugu             dra\te
 5  tn              --/M      Setswana           bnt\tn
 5  tr              --/M      Turkish            trk\tr
 5  tt              --/M      Tatar              trk\tt
 5  ur              --/M      Urdu               inc\ur
 5  vi              --/M      Vietnamese_(Northern) aav\vi
 5  vi-vn-x-central --/M      Vietnamese_(Central) aav\vi-VN-x-central
 5  vi-vn-x-south   --/M      Vietnamese_(Southern) aav\vi-VN-x-south
 5  yue             --/M      Chinese_(Cantonese) sit\yue              (zh-yue 5)(zh 8)
```

Also I downloaded the version `1.49.1` of  `espeak-ng` clearly it was stated this

```
new languages:

ar (Arabic) -- Taha Zerrouki
jp (Japanese) -- Reece Dunn (NOTE: Hiragana and Karakana only.)
```

There is japanese but when I tried it, there's **NOTHING** may I ask... do you really have it?

**Have I installed an old version? or am I just not getting something? What is happening? Why is there Japanese on the .md file where there is NOTHING in mine?** 
If so where is the lastest  version link download? I need to have this, this is a cool software! Thank you!

**Comment by jaacoppi** [comment]
That's strange, japanese should be there and `espeak-ng -v ja "わかります"` should work.

Can you check that ja_dict is really missing from `C:\Program Files\eSpeak NG\/espeak-ng-data`

**Comment by gelodefaultbrain** [comment]
Hello @jaacoppi  , Thank you for replying this software is really cool! I'm amazed how this is made in the C Programming Language.

First of all this `espeak-ng -v ja "わかります"` does not work also this one `C:\Program Files\eSpeak NG\/espeak-ng-data`  does not have the `ja_dict` when I installed the latest version [here](https://github.com/espeak-ng/espeak-ng/releases) as it is posted.


Now what I did is I downloaded the OFFICIAL SOURCE CODE of espeak-NG from the latest version & YES! I noticed that the RELEVANT files for Japanese are on the official source code but NOT when Installed them. So what I did is I copied those files & put them on the `C:\Program Files\eSpeak NG\/espeak-ng-data` , on this path by the way I put here the `ja_dict` file & on the voices I put there is `jpx/ja` file. Now my question is why is it , those RELEVANT files for the Japanese are on the official source code? But when you install them... there is nothing.. as of now I think it's working fine, cause I am using this python package [phonemizer](https://github.com/bootphon/phonemizer) which uses the `espeak` to get the IPA of a string.

**Comment by gelodefaultbrain** [comment]
@jaacoppi  I suggest you install the latest version as stated [here](https://github.com/espeak-ng/espeak-ng/releases) & try to find the relevant files for Japanese & probably other languages as well... Cause I did install them & there's nothing :(

**Comment by gelodefaultbrain** [comment]
Take a look at this... I re-installed this `espeak-NG` and I installed the latest one from [here](https://github.com/espeak-ng/espeak-ng/releases). I installed this one **Version 1.50** , `espeak-ng-20191129-b702b03-x64.msi` now take a look at this.

###  There is no JAPANESE (probably some of the other languages that were mentioned too on the .md file where it says it supports the mentioned languages)

---
The only language that starts with `j` is  `jbo_dict`

![image](https://user-images.githubusercontent.com/55988471/103152614-b160b800-47c4-11eb-9cef-3059fa968b55.png)

Tried searching for `ja_dict` but nothing...

![image](https://user-images.githubusercontent.com/55988471/103152632-d35a3a80-47c4-11eb-9bcc-41492332d00e.png)

Also on the `voices/`   directory there is no `jpx/ja` file. **So the question is why is it when I install `espeak-NG` using the installer (latest version `espeak-ng-20191129-b702b03-x64.msi`) there is no Japanese?** (also probably OTHER LANGUAGES as well that were mentioned on the doc that it supports the language... I am worried about it cause I'll be using this cool software in the FUTURE! Thank you for making this <3 )

**Comment by jasondiab** [comment]
Hey @gelodefaultbrain 
I'm having the same issue with the Arabic language, it seems like you found a way to get the ja_dict and paste it into the espeak-ng-data file? If this is the case (or you managed to find another solution) I would appreciate any leads to help me get it to work.

**Comment by gelodefaultbrain** [comment]
> Hey @gelodefaultbrain
> I'm having the same issue with the Arabic language, it seems like you found a way to get the ja_dict and paste it into the espeak-ng-data file? If this is the case (or you managed to find another solution) I would appreciate any leads to help me get it to work.

@jasondiab    Hello! Yes that's what I did I just got the file and copied them or transferred them to their respective needed locations. Are you using phonemize too?

**Comment by jasondiab** [comment]
I can't find the ar_dict unfortunately in the Source code as you suggested, would be great if you could help (and I'm not using phonemize)

**Comment by gelodefaultbrain** [comment]
Hello @jasondiab  I'm not sure if it could be `ar_dict` probably it could be something else that is for arabic. Have you downloaded the  latest posted source code?

**Comment by kanjieater** [comment]
> Take a look at this... I re-installed this `espeak-NG` and I installed the latest one from [here](https://github.com/espeak-ng/espeak-ng/releases). I installed this one **Version 1.50** , `espeak-ng-20191129-b702b03-x64.msi` now take a look at this.
> 
> ### There is no JAPANESE (probably some of the other languages that were mentioned too on the .md file where it says it supports the mentioned languages)
> The only language that starts with `j` is `jbo_dict`
> 
> ![image](https://user-images.githubusercontent.com/55988471/103152614-b160b800-47c4-11eb-9cef-3059fa968b55.png)
> 
> Tried searching for `ja_dict` but nothing...
> 
> ![image](https://user-images.githubusercontent.com/55988471/103152632-d35a3a80-47c4-11eb-9bcc-41492332d00e.png)
> 
> Also on the `voices/` directory there is no `jpx/ja` file. **So the question is why is it when I install `espeak-NG` using the installer (latest version `espeak-ng-20191129-b702b03-x64.msi`) there is no Japanese?** (also probably OTHER LANGUAGES as well that were mentioned on the doc that it supports the language... I am worried about it cause I'll be using this cool software in the FUTURE! Thank you for making this <3 )
> 
> But on the **official source code** again **SOURCE CODE** (not on the program files when you install the software) when I download it! It has this `ja_dict` file also the `ja` file. So I'm thinking probably the INSTALLER isn't UPDATED... right? if not then what could be the solution or at least the developers can update it so that I can use the Japanese & other languages as well that might not be on the INSTALLER but it is on the `.md` file where it says the language is available. Thank you so much! This software really helped me a lot and I'm sure too other people as well :D
> 
> ![image](https://user-images.githubusercontent.com/55988471/103154276-65684000-47d1-11eb-8c2c-8ff79ea84141.png)
> ![image](https://user-images.githubusercontent.com/55988471/103154287-731dc580-47d1-11eb-91f7-8669af6d7100.png)

I'm running into this. When I download the source code I can find
`espeak-ng-master\espeak-ng-data\lang\jpx\ja`
but not the `ja_dict`. Any pointers? or can you upload the file here until there's a fix?

**Comment by gelodefaultbrain** [comment]
Yes, on the source code there are the relevant files for `ja` but when you install the installer and I check on the folder from program files . It is missing. Probably it's just not updated.

**Comment by kanjieater** [comment]
> Yes, on the source code there are the relevant files for `ja` but when you install the installer and I check on the folder from program files . It is missing. Probably it's just not updated.

Thank you for your reply. There are no ja_dict files in the source. Could you please directly link to where the ja_dict file is? Do I need to build it manually with `make` to find those files?

> That's strange, japanese should be there and `espeak-ng -v ja "わかります"` should work.
> 
> Can you check that ja_dict is really missing from `C:\Program Files\eSpeak NG\/espeak-ng-data`

I'm experiencing the same thing on unix
![image](https://user-images.githubusercontent.com/32607317/117127706-11163380-ad62-11eb-9afe-b4315791318b.png)

**Comment by jaacoppi** [comment]
> Thank you for your reply. There are no ja_dict files in the source. Could you please directly link to where the ja_dict file is? Do I need to build it manually with `make` to find those files?

`make` will compile it for you. Another option is to use `espeak-ng --compile=ja`.

I've attached the file here.
[ja_dict.zip](https://github.com/espeak-ng/espeak-ng/files/6427828/ja_dict.zip)

**Comment by kanjieater** [comment]
> espeak-ng --compile=ja

Thank you for the quick reply. I'll try to figure out where to plug that file in now

On Unix i still get:

> espeak-ng --compile=ja
> Error: The specified espeak-ng voice does not exist.

This is reproducible with this Dockerfile: https://gist.github.com/kanjieater/79d86540215facb1cc383bbc73e34c08

**Comment by jaacoppi** [comment]
The _dict files go to `/usr/share/espeak-ng-data/` on a typical install.

That error message seems weird in this situation. Check if you can compile other languages, like English (en). You'll need the files in dictsource/en_rules in your $PWD.

**Comment by valdisvi** [comment]
@kanjieater

> This is reproducible with this Dockerfile: https://gist.github.com/kanjieater/79d86540215facb1cc383bbc73e34c08

Standard way to install built package of espeak-ng is `sudo apt-get install espeak-ng` or `yum install espeak-ng` etc. If this or other non-standard way to set up espeak-ng doesn't work, please report it to provider of that package or installation manager. We maintain only building process [from the source](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md).

**Comment by kanjieater** [comment]
> @kanjieater
> 
> > This is reproducible with this Dockerfile: [gist.github.com/kanjieater/79d86540215facb1cc383bbc73e34c08](https://gist.github.com/kanjieater/79d86540215facb1cc383bbc73e34c08)
> 
> Standard way to install built package of espeak-ng is `sudo apt-get install espeak-ng` or `yum install espeak-ng` etc. If this or other non-standard way to set up espeak-ng doesn't work, please report it to provider of that package or installation manager. We maintain only building process [from the source](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md?rgh-link-date=2021-05-08T18%3A56%3A34Z).

I'm not sure which part in particular would be non-standard. As a Dockerfile it's already running as root. The `apt-get install` command then has `espeak-ng` in it. This seems like it's an issue with the building process.

```
# Make sure to install sudo to match command
RUN set -x \
      && apt-get update \
      && apt-get install -y sudo 

RUN sudo apt update \
 && sudo apt-get install -y espeak-ng
```
Surely something like this would be supported? Japanese is not found when espeak is installed `espeak-ng --voices`
![image](https://user-images.githubusercontent.com/32607317/117551771-6de94680-b00d-11eb-8cd1-f512aa8f4e5b.png)

**Comment by kanjieater** [comment]
> The _dict files go to `/usr/share/espeak-ng-data/` on a typical install.
> 
> That error message seems weird in this situation. Check if you can compile other languages, like English (en). You'll need the files in dictsource/en_rules in your $PWD.

I don't think the standard install from apt-get is working. There is no `usr/share/espeak-ng-data` when you install by `sudo apt-get install espeak-ng`

**Comment by jaacoppi** [comment]
Fixed with 1.51.

**Comment by gelodefaultbrain** [comment]
> Fixed with 1.51.

Amazing! Thanks!

**Comment by sipie800** [comment]
1.51 it is happening again

**Comment by cpuQ** [comment]
this seems to work to fix it
https://github.com/open-mmlab/Amphion/issues/323#issuecomment-2646709006
