### ISSUE TITLE
Please create klingon language voice

### ISSUE THREAD

**Issue by AnonymousUser6** [espeak-ng/espeak-ng#868]
Please Someone Create Klingon language  for in eSpeakNG

**Comment by AnonymousUser6** [comment]
https://en.m.wikipedia.org/wiki/Klingon_language

**Comment by valdisvi** [comment]
I have added initial configuration, you [improve it yourself](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md).
