### ISSUE TITLE
Trouble adding new language

### ISSUE THREAD

**Issue by jasondiab** [espeak-ng/espeak-ng#882]
[e

**Comment by jaacoppi** [comment]
Post all your patches as attachments or as a link to your git repo and we'll see.

**Comment by valdisvi** [comment]
Without specific question, we can give only general answers.
Guide to add/improve languages is described in [Contribution Guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#contribution-guide). Guide to build eSpeak NG from source code is described in [Building eSpeak NG](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md), all other things are in [Documentation](https://github.com/espeak-ng/espeak-ng#documentation).
