### ISSUE TITLE
Problem reading Polish letter ó.

### ISSUE THREAD

**Issue by Qchristensen** [espeak-ng/espeak-ng#884]
One of our NVDA users reported an issue in recent NVDA versions reading the Polish letter ó.  They advised that eSpeak-NG simply cuts it off.

NVDA 2020.4 (and the previous version 2020.3) use eSpeak-NG 1.51-dev, commit 1fb68ffffea4

**Comment by jaacoppi** [comment]
Can you explain a bit more? Is the problem same with all words? Is the problem only with the pronunciation of ó, or does it affect the rest of the word in some way?

Everything seems to work. Last Polish-specific changes have been made in 2018.

Here's a debug example: espeak-ng -v pl -qx -X "którym ó"

Flags:  którym  $u+ $strend
Translate 'którym'
  1     k        [k]

  1     t        [t]

 36     ó       [u]

  1     r        [R]

  1     y        [y]

  1     m        [m]
 22     m (_     [m_]

Translate 'ó'
 36     ó       [u]

kt,uRym_ 'u

**Comment by Qchristensen** [comment]
I asked my user for more details, and they advised they have resolved the issue by using NDVA's symbol pronunciation dailog, adding an entry for ó and having it read as u, which they advised works for them.

I don't have any further information on it, so if no-one else is reporting it and you're confident that it's working as it should already, I'm happy for this to be closed.

**Comment by jaacoppi** [comment]
ó is supposed to be replace by u by espeak-ng. For some reason it wasn't for this user.

Let's close this since there's not enough information to debug further.
