### ISSUE TITLE
SSML <audio> garbles 8-bit wavs

### ISSUE THREAD

**Issue by jaacoppi** [espeak-ng/espeak-ng#885]
This works with 16 bit wavs:
```
src/espeak-ng -m "<speak>This works: <audio src=\"$PWD/phsource/h/ha.wav\"></speak>"

file phsource/h/ha.wav
phsource/h/ha.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 22050 Hz
```

However, if the file is an 8-bit file (for example converted with sox input.wav -b 8 output.wav), the output of the wav is garbled.

Possibly related to #88.

**Comment by valdisvi** [comment]
As far as I know, espeak-ng supports only one single wav format: PCM, 16 bit, mono 22050 Hz, therefore #88 is marked as a feature request.

**Comment by jaacoppi** [comment]
The solution for this looks simple.

https://github.com/espeak-ng/espeak-ng/blob/0cb4b1b6542666919ae8b177f7bdb045e84e55ab/src/libespeak-ng/readclause.c#L352

Adding a `-b 16` option to sox forces the original audio to 16 bits. It shouldn't affect files that are already 16 bits, but fixes playing 8 bit wavs. 

MP3 files seem to be unaffected by this bug anyway. I didn't check with any other file types.

Do you think I should push this `-b 16` or this there something that I'm missing? I don't know much about audio playback in espeak-ng.

**Comment by valdisvi** [comment]
I don't know either, but if espeak-ng uses command line interface of sox, adding this parameter looks ok to me.
