### ISSUE TITLE
Please Someone add Sanskrit and Hmong 

### ISSUE THREAD

**Issue by Animegirl3** [espeak-ng/espeak-ng#887]
Click here https://en.m.wikipedia.org/wiki/Sanskrit
Click here https://en.m.wikipedia.org/wiki/Hmong_language

**Comment by Animegirl3** [comment]
Click here https://en.m.wikipedia.org/wiki/Sanskrit 
Click here https://en.m.wikipedia.org/wiki/Hmong_language

**Comment by Animegirl3** [comment]
@valdisvi Please add Sanskrit and Hmong but I like experimenting these asian languages voices and I am curious Please add it in the demo odo.lv/Espeak Thank you @valdisvi

**Comment by Animegirl3** [comment]
@valdisvi Please add Sanskrit and Hmong but I like experimenting these asian languages voices and I am curious Please add it in the demo https://odo.lv/Espeak Thank you @valdisvi

**Comment by 0x5066** [comment]
Do it yourself, there are guides on how you can contribute.

**Comment by Animegirl3** [comment]
@0x5066 I don't want to do myself I am not a programmer

**Comment by Animegirl3** [comment]
don't want to do myself I don't know how to add  but just I want to experiment

**Comment by Animegirl3** [comment]
I don't want to do myself and but I don't know how to add language but just I want to experimenting myself please

**Comment by luiscarlos2000** [comment]
You know I'm not the only person who does language creation by itself, but we really need more language creators and or developers which is lacking. Right now I'm trying, or planning to add support for Interlingue (Occidental), Novial, and Volapuk, all of them constructed languages, or eaven Occitan, Romanch, Wallon (sorry if I mispelled it), Arromanian and or Sardinian (all romance languages), but time in university and all working in 10 subjects is really getting my head spinning like crazy.

**Comment by 0x5066** [comment]
Agreed, eSpeak-NG could benefit from more language contributors, however it won't work if you keep bugging people just because _you_ want something included.

[The contributing guide exists for a reason,](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md) and if you can't work on it yourself, maybe it would also be a good idea to not waste everyone's time by begging for something to be added.

**Comment by Animegirl3** [comment]
I am so sorry to bother you but can you add the language including Sanskrit and Hmong help me @valdisvi but I will be 😊happy you added and thank you at advance and this is for the blind people @valdisvi thank you
