### ISSUE TITLE
espeak-ng produces question marks as phoneme output sometimes

### ISSUE THREAD

**Issue by RuABraun** [espeak-ng/espeak-ng#890]
```
echo "urteil" | espeak-ng --stdin -v de -x -q --ipa=1 --stdout
_ˈ??_t_aɪ_l
```

I know there is an existing issue for this: https://github.com/espeak-ng/espeak-ng/issues/616

However I am certain this used to work. And I have now noticed this happening for relatively frequent words (in German, that's where I'm testing it) where again I'm certain I've used to have good outputs. I have double checked my locale settings and they seem fine. So I'm asking here to double check whether there might be some basic error I made or whether such basic words really do not have pronunciations?

**Comment by 0x5066** [comment]
As valdisvi had mentioned in [issue #616](https://github.com/espeak-ng/espeak-ng/issues/616#issuecomment-503569784) you can review the file in question for missing IPA entries

**Comment by deepalianeja** [comment]
I installed espeak-ng on Windows using the executable with no errors. I am able to run the example fine.

```
espeak-ng -x "This is a test" 
DIs Iz a# t'Est
```

However, I am getting question marks in the output if I choose the ipa option.

```
espeak-ng -x "This is a test" --ipa=1
d_?_s ?_z ? t_'?_s_t
```

Do we need a package or dictionary downloaded at a particular location?

**Comment by iamanigeeit** [comment]
This was broken 5 years ago with pull request https://github.com/espeak-ng/espeak-ng/pull/595 and hasn't been corrected since??

Here's the commit that broke everything: https://github.com/espeak-ng/espeak-ng/pull/595/commits/e07002a1c9e517e0d6de8dc49f3192712b860996

Just reverse the changes there and it should work.

**Comment by trenslow** [comment]
@iamanigeeit im having the same problem on my side and cant believe its gone this long without being fixed. i submitted a PR to fix it. hopefully it will be picked up for the next release!
