### ISSUE TITLE
Mapping phonemes back to words

### ISSUE THREAD

**Issue by tdeboissiere** [espeak-ng/espeak-ng#896]
Hi,

is there a straightforward way to map each phoneme back to the word to which it belongs ?

Example:

```
Input text: with the cat
Output IPA: wɪððə kˈæt

then

wɪð belong to `with`
ðə belong to `the`
kˈæt belong to `cat`

```

**Comment by valdisvi** [comment]
In short — no.
For details look at [Text to Phoneme Translation](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md) and configuration files for English: [en_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/en_rules), [en_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/en_list) and [ph_english](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_english).

**Comment by tdeboissiere** [comment]
Thanks !
