### ISSUE TITLE
Regression: en+klatt4 voice produces different/random wave output

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#906]
Run following command with most recent espeak-ng build:

```
make check
```
and note that one of tests fail:
```
testing en+klatt4 ... 
1c1
< 377767780368115863cde5cc11c0203cfdd48476
---
> 22614e6fa2882ab58eef4e9fccf534287d5747f5
```
also note, that actual sha1sum is changing randomly, which you can check with just command:

```
espeak-ng -ven+klatt4 "The quick brown fox jumps over the lazy dog" --stdout|sha1sum
```
If you run it with older build of espeak-ng, then wav output is always the same:
```
377767780368115863cde5cc11c0203cfdd48476 
```
If you listen to produced sound, e.g. with just:
```
espeak-ng -ven+klatt4 "The quick brown fox jumps over the lazy dog"
```
then additional clipping/popping sounds appear for consonants.

**Comment by valdisvi** [comment]
It looked like it was problem on my computer. Full reconfiguration and rebuild fixed this issue.

**Comment by jaacoppi** [comment]
I just realized klatt hasn't been installed on my machine so I've never run this test. Now that I've installed klatt, this kooks like yet another compiler problem:
Gcc 10.2.0 fails with random results even after starting from scratching (cloning the git repo and building)
Gcc 7.5.0 fails constantly with sha1sum c729418de850360db91e2f233964e5df1aae9037

See discussion in https://github.com/espeak-ng/espeak-ng/pull/867. We currently have at least two tests that depends on the correct compiler version.

**Comment by yiluzhuimeng** [comment]
hi，i have the same issue with additional clipping/popping sounds appear for consonants. how to Full reconfiguration and rebuild? how to installed klatt ?

**Comment by yiluzhuimeng** [comment]
> I just realized klatt hasn't been installed on my machine so I've never run this test. Now that I've installed klatt, this kooks like yet another compiler problem: Gcc 10.2.0 fails with random results even after starting from scratching (cloning the git repo and building) Gcc 7.5.0 fails constantly with sha1sum c729418de850360db91e2f233964e5df1aae9037
> 
> See discussion in #867. We currently have at least two tests that depends on the correct compiler version.

hi，i have the same issue with additional clipping/popping sounds appear for consonants. how to Full reconfiguration and rebuild? how to installed klatt ?
