### ISSUE TITLE
Understanding English text to phoneme for `of the`

### ISSUE THREAD

**Issue by tdeboissiere** [espeak-ng/espeak-ng#913]
Hi,

I would like to better understand the text to phoneme conversion for `of the` with espeak-ng==1.50

I can see the `of the` is part of the rules in `en_list`

```bash
(of the)         %%02vD@2		$nounf
```

so I assumed that it would always be converted to a sequence of contiguous phonemes without space, but if I change the prefix in the sentence, this is not always the case:

```bash
# calling espeak-ng 'most of the card' -x -q  -v en-us  --ipa:
mˈoʊst əv ðə kˈɑːɹd

# calling espeak-ng 'more of the card' -x -q  -v en-us  --ipa:
mˈoːɹ ʌvðə kˈɑːɹd
```

Where can I find information to know when `of the` will be converted to IPA without space and when it will not be ?

**Comment by jaacoppi** [comment]
Use the -X parameter to see which rule is used. If you need to adjust which rule to follow, change the order of lines in *_rules and *_list.


espeak-ng 'most of the card' -X -q  -v en-us  --ipa
Found: 'most of
' ***@***.***  
Found: 'the' ***@***.***   $nounf $only
Translate 'card'
  1	c        [k]

 36	ar       [A@]
  1	a        [a]

  1	d        [d]

mˈoʊst əv ðə kˈɑːɹd

espeak-ng 'more of the card' -X -q  -v en-us  --ipa
Translate 'more'
  1	m        [m]

 61	_m) or   [O@]
 36	or       [o@]
 57	ore      [o@]
 82	_m) ore  [o@]
 56	or (A    ***@***.***
  1	o        [0]
  4	X) o     [0#]

Found: 'of the
' ***@***.***   $nounf
Translate 'card'
  1	c        [k]

 36	ar       [A@]
  1	a        [a]

  1	d        [d]

mˈoːɹ ʌvðə kˈɑːɹd

**Comment by tdeboissiere** [comment]
I see thanks, looks like I missed the fact that `most of` was also part of `en_list`.

Is the reason that the `most of` rule is applied before the `of the` rule simply due to precedence in `en_list` (i.e. `most of` is on line 5192, which is before `of the` on line 5220).

**Comment by valdisvi** [comment]
Rules are applied in order of *_list file first, then _rules file and inside file in order of appeared lines. In general, longer matching string wins but for *_rules file weight of some matching patterns [can be increased or decreased](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#special-characters-only-in-post).

**Comment by tdeboissiere** [comment]
Thank you @valdisvi , closing !
