### ISSUE TITLE
speak on Mac OS error

### ISSUE THREAD

**Issue by bwanaaa** [espeak-ng/espeak-ng#916]
macOS mojave (10.14.6)
installed TTS and espeak
ran:
`tts --text "this is big bullshit" --model_name "tts_models/en/ek1/tacotron2" --vocoder_name "vocoder_models/universal/libri-tts/wavegrad"`

got

`RuntimeError: language "en-gb-x-rp" is not supported by the espeak backend`

**Comment by 0x5066** [comment]
this seemingly has nothing to do with espeak? considering you're attempting to use a neural network and somehow got an error from espeak

**Comment by jaacoppi** [comment]
Are you using espeak-ng or espeak? Espeak-ng supports en-gb-x-rp, I don't know if espeak does.

espeak-ng -v en-gb-x-rp "This is big" -xq
DIs Iz b'Ig

Next, find out what options tts passes to espeak-ng. Check that the environment is set correctly. See docs/building.md

**Comment by bwanaaa** [comment]
yes my mistake. i was using espeak. And compiling speak-ng on the mac is beyond me.

**Comment by ryandesign** [comment]
So then this issue should be closed since it is not related to this project.
