### ISSUE TITLE
How to make espeak-ng even more lightweight (for embedded application)

### ISSUE THREAD

**Issue by Nafihahmd** [espeak-ng/espeak-ng#918]
Hi all, I am a ES engineer working on Text to Speech (TTS) project. I first tinkered with [Festival](http://festvox.org/docs/manual-2.4.0/festival_toc.html) and flite but soon realized that Espeak has upper hand in resource constrained environments like mine. (I am trying to bring down the ROM/FLASH usage by the whole TTS system below 500 KB)

So after building espeak-ng from source as per the instruction I used the strip command to even reduce the size of shared library
`strip src/.libs/libespeak-ng.so`
This reduced the size of shared library from **1.56 MB to 512 KB** which still is not enough.

So my question is **can I remove unnecessary languages to save space, i.e, reduce size?** I only require English and few indic languages (in contrast to 100+ languages in Espeak-ng). 
If yes how can I remove a language from espeak-ng? I searched all over the internet but nowhere  found any information regarding this. 

Thanks in advance,
Nafih

**Comment by Nafihahmd** [comment]
I am sharing here to scripts that I used for cloning and building espeak-ng quick. 
[do_scripts.zip](https://github.com/espeak-ng/espeak-ng/files/6335019/do_scripts.zip)

**Comment by Bhupendra514** [comment]
Hai please provide E.speech TTS latest New Voices for android thank you

**Comment by Nafihahmd** [comment]
@Bhupendra514 hmm it seems like you are working in a completely different project than mine. Can you give more details about what you want?

**Comment by Bhupendra514** [comment]
I want to E.speech or other new TTS for Android

**Comment by graduatemazada** [comment]
dear Nafihahmd could you please share more details
