### ISSUE TITLE
Sound doesn't play when inputted from powershell, but the same text is played when read from file

### ISSUE THREAD

**Issue by m3M0ryHuN73R** [espeak-ng/espeak-ng#923]
I am trying to use the ccs/ka (Georgian) language to synthesize text of UTF-8 encoding:
გამარჯობა
I try to run:
espeak-ng -v ka გამარჯობა
but there is no sound played.
But when I create a file e.x. file.txt and write გამარჯობა inside that, it reads and plays without problem.
My ultimate goal is to run this without reading it from a file. I am trying to implement this in Python to use it on my project by using a wrapper from pip, or by using the subprocess module to run shell commands.

Notable things:
$text = Get-Content .\file.txt
espeak-ng -v ka $text

If I run this in Powershell, it reads file and also plays the sound.
$text prints as áƒ’áƒƒ›áƒƒ áƒ¯áƒ.  I am not sure of what encoding this is or how to convert this to a readable form.

**Comment by jaacoppi** [comment]
What happens if you 
1) enclose the text in quotation marks 
2) pipe the input?
Atleast out-file an option "-encoding utf8". I don't know how to change the powershell encoding for other redirection methods.

**Comment by m3M0ryHuN73R** [comment]
> What happens if you 1) enclose the text in quotation marks 2) pipe the input? Atleast out-file an option "-encoding utf8". I don't know how to change the powershell encoding for other redirection methods.

1. No change with the quotation marks.
2. What does piping the input mean?

**Comment by m3M0ryHuN73R** [comment]
I think it's not just Georgian that's this way, but UTF8 characters are just ignored. The only way to play them is probably reading them from a file. -b 1 argument doesn't help

**Comment by beqabeqa473** [comment]
piping georgian text to espeak executable works just fine.

On 4/23/21, David ***@***.***> wrote:
> I think it's not just Georgian that's this way, but UTF8 characters are just
> ignored. The only way to play them is probably reading them from a file. -b
> 1 argument doesn't help
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/923#issuecomment-825444683


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by m3M0ryHuN73R** [comment]
> piping georgian text to espeak executable works just fine.
> 
> On 4/23/21, David ***@***.***> wrote:
> > I think it's not just Georgian that's this way, but UTF8 characters are just
> > ignored. The only way to play them is probably reading them from a file. -b
> > 1 argument doesn't help
> >
> > --
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/espeak-ng/espeak-ng/issues/923#issuecomment-825444683
> 
> 
> -- 
> with best regards Beqa Gozalishvili
> Tell: +995593454005
> Email: ***@***.***
> Web: https://gozaltech.org
> Skype: beqabeqa473
> Telegram: https://t.me/gozaltech
> facebook: https://facebook.com/gozaltech
> twitter: https://twitter.com/beqabeqa473
> Instagram: https://instagram.com/beqa.gozalishvili
> 

Could you please give an explanation of what does piping mean and how its done

**Comment by 0x5066** [comment]
`espeak-ng "Some text" | someotherprogram`

The "|" denotes that the output of a program is sent to another (i.e. creating a pipe), this works the other way around too so that espeak can accept text input from a text file

**Comment by m3M0ryHuN73R** [comment]
> `espeak-ng "Some text" | someotherprogram`
> 
> The "|" denotes that the output of a program is sent to another (i.e. creating a pipe), this works the other way around too so that espeak can accept text input from a text file

Understood. How to I pipe espeak?

**Comment by m3M0ryHuN73R** [comment]
I had no idea what piping was until now. It works! Thank you a lot guys!
