### ISSUE TITLE
Short word error in smj: some three-letter words are read as abbreviations/character names separately.

### ISSUE THREAD

**Issue by kathiasi** [espeak-ng/espeak-ng#927]
![espeak_testi_27_4](https://user-images.githubusercontent.com/39489061/116382036-2816cc00-a81e-11eb-8e73-6c6e446bb046.png)

As in the terminal screenshot, at least words 'man', 'vat' and 'lav' are spoken as character names although they should be normal words. I checked that these short words are in the smj_list file and that there are no duplicates of them anymore.

**Comment by jaacoppi** [comment]
It starts to work if dictsource/smj_rules is overwritten with dictsource/fi_rules.

That means there's a syntax error somewhere in smj_rules. I'll keep digging.

**Comment by jaacoppi** [comment]
You were missing the rule for letter "a". Add the correct phoneme. In the diff below I just removed the comment so that "a" becomes "A". 

When fixing this, also check if you can remove other commented lines from smj_rules. It makes debugging easier.

```
diff --git a/dictsource/smj_rules b/dictsource/smj_rules
index 2b469273..49d3db35 100644
--- a/dictsource/smj_rules
+++ b/dictsource/smj_rules
@@ -48,7 +48,7 @@
 
 
 .group a
-//          a          A
+          a          A
           a (@       A // back vowel
        @) a          a:
           artihkal   ar.t'ihkAl
```
