### ISSUE TITLE
Message: "unknown phoneme table: 'en'" while building the phonemes

### ISSUE THREAD

**Issue by jbowler** [espeak-ng/espeak-ng#928]
It reads like an error message and is followed by "Can't read dictionary file:" which definitely looks like an error yet the step completes with no error and en_dict is generated.  Text from the make output:

`ESPEAK_DATA_PATH=/home/jbowler/src/espeak-ng/dunn src/espeak-ng --compile-intonations && \
        ESPEAK_DATA_PATH=/home/jbowler/src/espeak-ng/dunn src/espeak-ng --compile-phonemes && \
        touch phsource/phonemes.stamp
Compiled 30 intonation tunes: 0 errors.
Unknown phoneme table: 'en'
Can't read dictionary file: '/home/jbowler/src/espeak-ng/dunn/espeak-ng-data/en_dict'
Compiling phoneme data: /home/jbowler/src/espeak-ng/dunn/espeak-ng-data/../phsource/phonemes`

`Refs 4336,  Reused 3366
Compiled phonemes: 0 errors.`

This was reproed with commit 490538b715e9271d75adf121ca02a60acae56feb on a fresh clone using:

`./autogen.sh
./configure  --prefix=home/jbowler/local
make`

I've attached the log files for each step:
[autogen.sh.log](https://github.com/espeak-ng/espeak-ng/files/6394556/autogen.sh.log)
[configure.log](https://github.com/espeak-ng/espeak-ng/files/6394559/configure.log)
[make.log](https://github.com/espeak-ng/espeak-ng/files/6394560/make.log)

**Comment by valdisvi** [comment]
Try to run `make clean` before everything and `make -B` at the end.

**Comment by jbowler** [comment]
I'm not sure what you mean exactly.  The bug is that en_dict is used before it is built; **make -B** does not remove the generated en_dict and neither does **make clean**.  **make distclean** does, although it leaves stuff behind that should be removed in espeak-ng-data, dictsource and phsource (that's a separate bug).

Anyway I tried all the variants I could think of using **make clean** and **make -B** and this did reveal how bad a bug it is...

I did this first:

> jbowler@hippopopus ~/src/espeak-ng $ git clone dunn en_dict.problem
> Cloning into 'en_dict.problem'...
> done.
> jbowler@hippopopus ~/src/espeak-ng $ cd en_dict.problem
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ git status --ignored
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> nothing to commit, working tree clean
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ mkdir LOGS
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ls espeak-ng-data
> lang  voices
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ls espeak-ng-data/lang
> aav  bat  cel  esx  gmw  ine  itc  map  qu   sem  trk  zls
> art  bnt  cus  eu   grk  ira  jpx  myn  roa  sit  urj  zlw
> azc  ccs  dra  gmq  inc  iro  ko   poz  sai  tai  zle
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ./autogen.sh >&LOGS/autogen.sh.log; echo $?
> 0
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ./configure --prefix="$HOME/local" >&LOGS/configure.log; echo $?
> 0
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ make clean >&LOGS/clean.log
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ make >&LOGS/make.log
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ echo $?; make -B >&LOGS/make-B.log; echo $?
> 0
> 0

"make clean" doesn't do anything; it doesn't either create en_dict or remove any of the source files from the git clone.  The output of "git status --ignored" contains just the stuff generated by autogen and configure.

The "make" step still contains the error and this is how I worked out what the error is; the make -B step does *not* show the error because it uses the en_dict from the _previous_ build.  If I replace my first make with make -B it produces the same errors.  If I run make -B a second time but after changing Makefile.am to use this:

>         ESPEAK_DATA_PATH=$(CURDIR) src/espeak-ng --compile-intonations && \
>                 false && \
>                 ESPEAK_DATA_PATH=$(CURDIR) src/espeak-ng --compile-phonemes && \
>                 touch $@

I.e. to stop after the --compile-intonations step I can see what is happening with en_dict:

> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ls -l espeak-ng-data/en_dict
> -rw-r--r-- 1 jbowler jbowler 166620 **Apr 28 15:03** espeak-ng-data/en_dict

Then "make -B" (which regenerates Makefile from the modded Makefile.am):

> config.status: config.h is unchanged
> ESPEAK_DATA_PATH=/home/jbowler/src/espeak-ng/en_dict.problem src/espeak-ng --compile-intonations && \
>         false && \
>         ESPEAK_DATA_PATH=/home/jbowler/src/espeak-ng/en_dict.problem src/espeak-ng --compile-phonemes && \
>         touch phsource/phonemes.stamp
> Compiled 30 intonation tunes: 0 errors.
> make[1]: *** [Makefile:2994: phsource/phonemes.stamp] Error 1
> make[1]: Leaving directory '/home/jbowler/src/espeak-ng/en_dict.problem'
> make: *** [Makefile:832: all] Error 2
> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ls -l espeak-ng-data/en_dict
> -rw-r--r-- 1 jbowler jbowler 166620 **Apr 28 15:03** espeak-ng-data/en_dict

Oops... same date stamp, but deleting the "false" and running "make -B" to completion:

> jbowler@hippopopus ~/src/espeak-ng/en_dict.problem $ ls -l espeak-ng-data/en_dict
> -rw-r--r-- 1 jbowler jbowler 166620 **Apr 28 15:11** espeak-ng-data/en_dict

So it uses the *old* en_dict and then generates the correct one; there's a circular dependency which is a bad enough bug in itself but what happens with the "intonations" in my repro (starting from a clean clone, or after **git clean -dfx**, which will destroy all unknown files and directories in the clone [dangerous])?  It sounds like the build should certainly fail in this case because surely the intonations compiled are bad?

**Comment by jbowler** [comment]
Wrong analysis; the problem is entirely within compile-phonemes.  I removed the spurious &&\ joining of the separate make commands in the Makefile to make it clearer where the error comes from and added some temporary 'find' commands to work out what gets created where.  make output:

> find . -type f -print | egrep -v '^./LOGS/' | sort >LOGS/intonations-files.txt
> ESPEAK_DATA_PATH=/home/jbowler/src/espeak-ng/en_dict.problem src/espeak-ng --compile-phonemes
> Unknown phoneme table: 'en'
> Can't read dictionary file: '/home/jbowler/src/espeak-ng/en_dict.problem/espeak-ng-data/en_dict'
> Compiling phoneme data: /home/jbowler/src/espeak-ng/en_dict.problem/espeak-ng-data/../phsource/phonemes
> 
> Refs 4336,  Reused 3366
> Compiled phonemes: 0 errors.
> find . -type f -print | egrep -v '^./LOGS/' | sort >LOGS/phonemes-files.txt

So compile-phonemes uses en_dict before it generates it as well as, I think, phontab?

**Comment by jbowler** [comment]
The merge of the pull request, #930 fixed this.
