### ISSUE TITLE
Regression: commit c944a17 doesnt speak

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#93]
Tested with commit c944a17 on Lubuntu 14.04
Clean compilation:
```
./autogen.sh --prefix=/usr
./configure
make
sudo make LIBDIR=/usr/lib/x86_64-linux-gnu install
```
Then test:
```
ESPEAK_DATA_PATH=`pwd` LD_LIBRARY_PATH=src:${LD_LIBRARY_PATH} src/espeak-ng -vlv -X "ēnu diena."
espeak-ng -vlv -X "ēnu diena."
```
doesn't produce any sound.

**Comment by rhdunn** [comment]
This works for me. Did you build and install the new [pcaudiolib](https://github.com/rhdunn/pcaudiolib.git) dependency? You may need to install it to `/usr` at present as I don't currently have `pkg-config` support for it yet.

I have replaced the audio code in espeak (portaudio, pulseaudio, sada) with this new project to help with Windows audio support and to share the audio code with my Cainteoir Text-to-Speech project.

NOTE: Passing arguments to `autogen.sh` does not do anything -- you need to pass them to `configure`.

**Comment by ValdisVitolins** [comment]
Thanks!
I compiled and installed [pcaudiolib](https://github.com/rhdunn/pcaudiolib) and also recompiled espeak-ng (with proper commands :-P).
It is speaking now again.
