### ISSUE TITLE
Install it in google colab? RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by krigeta** [espeak-ng/espeak-ng#935]
Hello, i tried to install it by using 

!pip install espeak 

```
ERROR: Could not find a version that satisfies the requirement espeak (from versions: none)
ERROR: No matching distribution found for espeak
```

!pip install python-espeak but getting this errors

```
Building phoneme dictionary: ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0.0%
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/Multilingual_Text_to_Speech/utils/text.py in _phonemize(text, language)
     90         seperators = Separator(word=' ', phone='')
---> 91         phonemes = phonemize(text, separator=seperators, backend='espeak', language=language)
     92     except RuntimeError:

9 frames
**RuntimeError: espeak not installed on your system**

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/epitran/simple.py in _load_g2p_map(self, code, rev)
     90         except IndexError:
     91             raise DatafileError('Add an appropriately-named mapping to the data/maps directory.')
---> 92         with open(path, 'rb') as f:
     93             reader = csv.reader(f, encoding='utf-8')
     94             orth, phon = next(reader)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/epitran/data/map/chinese.csv'
```

**Comment by valdisvi** [comment]
Standard way to install built package of espeak-ng is `sudo apt-get install espeak-ng` or `yum install espeak-ng` etc. If this or other non-standard way to set up espeak-ng doesn't work, please report it to provider of that package/installation manager. We maintain only building process [from the source](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md).

**Comment by krigeta** [comment]
when i try to use this to install it in python

`!pip install espeak-ng`

I got this error

```
ERROR: Could not find a version that satisfies the requirement espeak-ng (from versions: none)
ERROR: No matching distribution found for espeak-ng
```

**Comment by Nafihahmd** [comment]
Try 
```
pip install py-espeak-ng
```

Espeak and Espeak-ng are different by the way

**Comment by zzzgit** [comment]
> espeak-ng

So, espeak-ng is the new version of espeak?

**Comment by rmcpantoja** [comment]
The espeak-ng package in apt is up to version 1.50 for now. Given the significant improvements for some languages, it would be nice to update for the next version to be released as it can be useful for using a phonemizer. I had a lot of errors compiling espeak-ng in Google colab, really.

**Comment by zzzgit** [comment]
> The espeak-ng package in apt is up to version 1.50 for now. Given the significant improvements for some languages, it would be nice to update for the next version to be released as it can be useful for using a phonemizer. I had a lot of errors compiling espeak-ng in Google colab, really.

There's only a `espeak' package in MacOS's package manager homebrew, no `espeak-ng`

**Comment by GemsFord** [comment]
use
!apt-get install espeak

**Comment by rmcpantoja** [comment]
Hi @GemsFord, 
The ^espeak^ package is obsolete, and abandoned as of 2015. That's why the main developer passed away and it was changed to espeak-ng which adds many improvements.

**Comment by GemsFord** [comment]
Okay so may be then
!apt-get install espeak-ng

As in my case pip command gave error

**Comment by rabiaedayilmaz** [comment]
Installing it by `brew install espeak-ng espeak` locally solved my problem running on Google Colab.
