### ISSUE TITLE
autogen.sh succeeds only on second try

### ISSUE THREAD

**Issue by jasonhemann** [espeak-ng/espeak-ng#941]
On my system, building from source, executing `autogen.sh` fails the first time due to a missing file `ltmain.sh`. Running autogen twice seems to succeed. I don't yet have a running executable, so it might be this has just masked the problem, however. 

Logs:

```
-bash-4.2$ ./autogen.sh
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:3: installing './install-sh'
configure.ac:4: error: required file './ltmain.sh' not found
configure.ac:3: installing './missing'
Makefile.am:436: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:447: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:450: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './INSTALL'
Makefile.am:209: warning: compiling 'src/espeak-ng.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'
Makefile.am: installing './depcomp'
-bash-4.2$ ./autogen.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
Makefile.am:436: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:447: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:450: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:209: warning: compiling 'src/espeak-ng.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'
```

**Comment by jasonhemann** [comment]
Update: After I configure for my system, the `Makefile` almost works out of the box. `make` complains about line 2417, but after commenting that line (it's for building documentation) the executable builds and runs fine.

**Comment by jaacoppi** [comment]
Have you checked that your system has all the dependencies listed in docs/building.md? Specifically autotools for ltmain and ronn/kramdown for documentation.

**Comment by jasonhemann** [comment]
No, I had not. And no, it does not.

**Comment by jasonhemann** [comment]
@rhdunn , no it did not, actually. Although that change moves the problematic line to line num 2438.

**Comment by ryandesign** [comment]
> executing `autogen.sh` fails the first time due to a missing file `ltmain.sh`

You did not mention whether you were building 1.50 or master. If 1.50, then this could be a duplicate of #911 which was already fixed on master but there has been no new release since then.

**Comment by jasonhemann** [comment]
Close as duplicate of #911
