### ISSUE TITLE
tests/ssml.test:test_ssml_audio <prosody>: wrong test fails

### ISSUE THREAD

**Issue by jbowler** [espeak-ng/espeak-ng#947]
When I run "make check" the first <prosody> check fails, the second, which the comments say "should fail" succeeds.  This is the output with a slightly modified test_ssml_audio which accepts a fourth "IGNORE" argument:

```
testing <prosody> IGNORE
1c1
< fcb28f00670959980038171ceda3c6bdec61b884
---
> 5ea0dcd3dc9682adacebcaf3d2fa6c8d6fa6e4aa
test_ssml_audio: WARNING: ignored
testing <prosody> bug #410 
testing <audio> 
```

Reproed using 88c4a452fe40413a146d21e31856fcfa9e7e4eea (current pull request, necessary for me to get to these tests, HEAD-1 is f6d092a9c13d864ede78c493f64a7d32cde41f09) and I added the attached 'ssml.test.patch' (.txt is just to make this dialog accept the file), then:

```
git clean -dfx
./autogen.sh
./configure
make check
```

*With* the patch 'make check' will complete, but it has ignored the error in the first test_ssml_audio (log fragment posted above).  Without the patch of course it fails before executing the second test_ssml_audio.

I added a "tee audio.out" to see what is actually getting output.  Kwave reports it as corrupted, but it is a RIFF so who knows:

audio.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 22050 Hz

Groove Music on Windows opens it just fine and it seems to have the correct speech for the input (with the correct prosody).  I've attached the output file as a gzip (this dialog does not support any audio files, but it does allow arbitrary gzip'ed files!)

[audio.wav.gz](https://github.com/espeak-ng/espeak-ng/files/6512065/audio.wav.gz)
[ssml.test.patch.txt](https://github.com/espeak-ng/espeak-ng/files/6511992/ssml.test.patch.txt)

**Comment by jaacoppi** [comment]
I don't know why the first test fails.

I've explained the second test poorly. We're all hoping it would fail. It checks for a known bug #410 which has not yet been fixed.  When the bug is fixed, the test will fail and needs to be changed. 

What compiler and OS are you using?

**Comment by jbowler** [comment]
- gcc (Gentoo 11.1.0 p1) 11.1.0
- Linux hippopopus 5.12.5-gentoo #1 SMP Thu May 20 09:29:16 PDT 2021 x86_64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz GenuineIntel GNU/Linux
- The OS is Gentoo running the KDE Plasma 17.1 desktop profile:
/usr/portage/profiles/default/linux/amd64/17.1/desktop/plasma
- The audio is:
AUDIO_USE="jack pulseaudio openal"

In what way is the test failing?  I.e. what has gone wrong?

Note that this seems related to #945; in both cases an incorrectly formatted piece of text results from spurious (#945) or missing (#947) sentence terminators.

**Comment by jbowler** [comment]
Could you add the phoneme output for the first test case?  I.e. the phonemes that you would get from espeak-ng -xq?

**Comment by rhdunn** [comment]
I also see:
```
testing <prosody>
1c1
< fcb28f00670959980038171ceda3c6bdec61b884
---
> 5ea0dcd3dc9682adacebcaf3d2fa6c8d6fa6e4aa
```
on my setup -- gcc 8.3.0-6 on Debian buster. The test in #945 passes for me, and all the tests pass on Travis, so I'm not sure what is happening here.

**Comment by jbowler** [comment]
French shows the same parsing behavior, hardly surprising as the number parsing seems to be based on the language separators not the language itself:

0.8 zero _|pwE~ _|y'it
0,8 zero virgyl _|y'it

Supposedly (according to my 0 levels ;-) I can speak french but I was never taught decimal fractions but it looks like the French word being used in 0.8 is "point", not "période", though the French "point" has the same ambiguity as the English IRC (in fact, I think the English is from the French.)

Neverfheless this is off topic - the question is why the a ->a# (a#_3) phoneme replacement is occuring now when, apparently, it didn't before.  BTW this happens with -O0 too, so it doesn't look likely to be either an out-of-bounds or uninitialized memory issue or, for that matter, a compiler issue.

**Comment by jbowler** [comment]
Tests are not an issue.
