### ISSUE TITLE
Espeak takes too long to phonemize on colab

### ISSUE THREAD

**Issue by Jaskaran170599** [espeak-ng/espeak-ng#954]
I'm using phonemizer which uses espeak-ng as backend and phonemize the sentence in (hindi and marathi) .
For some words it takes too long (20-30mins +).
I need to use it on google colab for my training and I'm not able to proceed with these exceptions :
I installed espeak-ng with sudo apt-get install espeak-ng 
my espeak version : eSpeak NG text-to-speech: 1.49.2  Data at: /usr/lib/x86_64-linux-gnu/espeak-ng-data

examples:
Hindi: 'प्रभाव , ज्ञान , छेदन , रूचि , स्वभाव'
Marathi: 'इथे तुंगा, सती, सुनी, कीर्ती, व भृंगारी, व पाच छोटया नद्यांचा, संगम आहे.'

**Comment by jaacoppi** [comment]
Version 1.49.2 is from 2017. I suggest you try with a newer version.

What's your pipeline? What commands are you using?

For example, with version 1.50 or current git version this only takes a few seconds for me: espeak-ng -v hi "प्रभाव , ज्ञान , छेदन , रूचि , स्वभाव" -xq

**Comment by Jaskaran170599** [comment]
Hi ,I'm training for TTS model and want to convert my hindi sentences into phonemized version using espeak-ng.
Im using a python package called Phonemizer.

How do I install version 1.50 on colab?

**Comment by jaacoppi** [comment]
Installation instructions are in https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md

Post the relevant parts of your source code. What function calls are you making to initialize and call espeak-ng?

**Comment by Jaskaran170599** [comment]
I think version is the issue it does work fine on the 1.50 version but I need ubuntu 20.4 version for that and i want to run it on colab , I'll try installing the 1.50 version on colab by the installing instructions.
these are the commands:

!sudo apt install espeak-ng #1.48.03  04.Mar.14  Data at: /usr/lib/x86_64-linux-gnu/espeak-data
!pip install phonemizer

import phonemizer
text=phonemizer.phonemize(txt,
                    language=lang,
                    backend='espeak',
                    strip=True,
                    preserve_punctuation=True,
                    with_stress=False,
                    njobs=1,
                    punctuation_marks=';:,.!?¡¿—…"«»“”()',
                    language_switch='remove-flags')
