### ISSUE TITLE
voices with different intonation or tunes definitions

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#962]
a number of years ago with normal Espeak, the old version, I was able to modify its tunes definitions files by first downloading and installing Espeakedit. By doing this you could do anything from making ESpeak sound like Keynote gold, or give it a singing novelty voice. I would like to ask someone to make new voices or variants with different intonation or tunes definitions so ESpeak will emulate the pitch and inflection and speaking style of Keynote gold, DoubleTalk, etcetera. Maybe add some novelty voices such as voices that  sound like they are singing, etcetera. thanks. Tunes or intonations definitions files as i remember correctly are, or were, very powerful and by changing them you could greatly expand how Espeak would talk, and even sing, and someone on twitter named Gillam years ago gave me an intonations files and voice and when I applied it, ESpeak sounded like the keynote gold tts from humanware.

**Comment by valdisvi** [comment]
eSpeak Edit is available as `espeakedit` package on Debian-based Linux distributions, for example, Ubuntu. You install it with graphical installer for particular distribution or running `sudo apt-get install espeakedit` in command line.

**Comment by hozosch** [comment]
Well but what about Windows?

**Comment by joshknnd1982** [comment]
Is ESpeakEdit available for windows10? That is what I use.



Sent from Mail for Windows 10
