### ISSUE TITLE
Help on updating stress rules for Basque

### ISSUE THREAD

**Issue by agonzalezd** [espeak-ng/espeak-ng#971]
Hello everyone.

I wanted to update (by now locally) the stress rules for Basque language involving long words. For words with 4 syllables or more, the primary stress goes on the second syllable and the secondary stress on the last one. Currently, espeak adds a secondary stress each two syllables. As an example regarding declensions of The Americas:

word: "Ameriketan"
espeak: "amˈeɾikˌetan"
should be: "amˈeɾiketˌan"

word: "Ameriketara"
espeak: "amˈeɾikˌetaɾˌa"
should be: "amˈeɾiketaɾˌa"

word: "Ameriketarako"
espeak: "amˈeɾikˌetaɾˌako"
should be: "amˈeɾiketaɾakˌo"

However, I cannot find where these rules have been implemented. I have checked [ph_basque](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_basque), [eu_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/eu_list) and [eu_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/eu_rules). 

Could I have any guidelines on where these changes should be updated, or how to update stress rules for Basque?

Thanks in advance

**Comment by sukiletxe** [comment]
Hi,
I am the original maintainer of eSpeak in Basque (I can't say I have done a good job though). If I remember correctly, these things were set in the source code itself, at least in eSpeak. Now things may have changed though. I know that in the docs there are references to intonations.

**Comment by jaacoppi** [comment]
Stress rule for Basque is currently set here:
https://github.com/espeak-ng/espeak-ng/blob/ab11439b18238b7a08b965d1d5a6ef31cbb05cbb/src/libespeak-ng/tr_languages.c#L765

Some of the possible values are listed here:
https://github.com/espeak-ng/espeak-ng/blob/ab11439b18238b7a08b965d1d5a6ef31cbb05cbb/src/libespeak-ng/translate.h#L361-L366

The code that handles the check start here:
https://github.com/espeak-ng/espeak-ng/blob/ab11439b18238b7a08b965d1d5a6ef31cbb05cbb/src/libespeak-ng/dictionary.c#L1119

Note that the switch case in dictionary.c has values that are not listed in translate.h. That's a problem that needs fixing. You should read through all the comments in the switch cases and see if there's one that works for Basque. If not, we'll need to add a new switch case. Do you have programming skills?

**Comment by agonzalezd** [comment]
Yes, thanks to both of you!

I managed to make a pull request with the stress rules updated for Basque. Let's see if it gets accepted.
