### ISSUE TITLE
intonation change in SSML stack

### ISSUE THREAD

**Issue by alex19EP** [espeak-ng/espeak-ng#975]
## system info

- system: Arch Linux
- espeak-ng version: gf269acf2

## problem

`espeak-ng -v ru+max -s 380 -m "<speak>включено.<mark name=foo/></speak>"`

raises pitch while

`espeak-ng -v ru+max -s 380 -m "<speak>включено.</speak>"`

does not.

**Comment by jaacoppi** [comment]
Happens with other languages as well. Most likely this is yet another SSML stack issue. There are many similar issues open at the moment.

**Comment by guest271314** [comment]
Reproducible on  5.4.0-42-lowlatency
[espeakng_ssml_parsing_with_without_mark_element.zip](https://github.com/espeak-ng/espeak-ng/files/6797182/espeakng_ssml_parsing_with_without_mark_element.zip)

Per specification 3.3.2 mark Element https://www.w3.org/TR/2010/REC-speech-synthesis11-20100907/#edef_mark `<mark>` element does not affect speech synthesis output

> The [mark](https://www.w3.org/TR/2010/REC-speech-synthesis11-20100907/#edef_mark) element does not affect the speech output process.
