### ISSUE TITLE
Espeak Turkish has trouble pronouncing words with double apostrophies

### ISSUE THREAD

**Issue by burakyuksek** [espeak-ng/espeak-ng#987]
When you type in a word such as "Kur'an'da", Espeak Turkish says "anda", it needs to say "Kuran'da".

**Comment by jaacoppi** [comment]
This has been fixed in the development version. Update to the version in git. I will close this issue. Continue the discussion in #875. 

The current fix might not be perfect, Can you help? Use espeak-ng -x to see the output. Are these correct?

```
espeak-ng  -v tr "Kur'an'da" -x
ku*and'a

espeak-ng  -v tr "Celâ'led'din" -x
dZelalEdd'In 

```
