### ISSUE TITLE
At what point does espeak output a multi-line IPA sequence ?

### ISSUE THREAD

**Issue by tdeboissiere** [espeak-ng/espeak-ng#988]
Hi, 

I've noticed that the call below:

```bash
espeak-ng "Two eight six two zero eight nine nine eight six two eight zero three four eight two five three four two one one seven zero six seven nine eight two one four eight zero eight six five one three two eight two three zero six six four seven zero nine three eight four four six zero nine five five zero five eight two two three one seven two five three five nine four zero eight one two eight four eight one one one seven four five zero two eight four one zero two seven zero one nine three eight five two one one zero five five five nine six four four six two two nine four eight nine five four nine three zero three eight one nine six four four two eight eight one zero nine seven five six six five nine three three four four six a" -x  -q  en-us  --ipa
```
Leads to a multi line output with espeak-ng 1.50

At which point does espeak start writing multiple lines to stdout ?

**Comment by valdisvi** [comment]
If text has commas, full stops or two linebreaks (empty lines), they are used as natural breaks of the text. If text doesn't have them, text is broken at the last word of 800 bytes buffer, defined in  [translate.h as N_TR_SOURCE](https://github.com/espeak-ng/espeak-ng/blob/01f094346d72d26bcb42af2dbf46f94fbfd11f19/src/libespeak-ng/translate.h#L43). If text doesn't have even spaces, then it is broken at the end of the buffer. As far as I remember, details should be in [readclause.c ReadClause](https://github.com/espeak-ng/espeak-ng/blob/master/src/libespeak-ng/readclause.c#L463) function.

**Comment by tdeboissiere** [comment]
Thanks !
