### ISSUE TITLE
ALSA Error on launch

### ISSUE THREAD

**Issue by MEth0** [espeak-ng/espeak-ng#99]
![issue](https://cloud.githubusercontent.com/assets/17335793/13709890/8c457100-e7b6-11e5-9b77-28350b5d5ae2.png)

OS : Antergos

**Comment by rhdunn** [comment]
The audio logic has changed in `espeak-ng` from espeak. Can you retry with `espeak-ng`?

On some systems, the default audio device does not work. Because of this, in `espeak-ng` you can use the `-d DEVICE_NAME` option, e.g. `espeak-ng -d sysdefault`.

**Comment by valdisvi** [comment]
What happens, if you try to invoke it indirectly with paplay? For example:
```
espeak-ng "Hello" --stdout | paplay
```
