### ISSUE TITLE
Mac: Makefile.am: error: required file './ChangeLog.md' not found

### ISSUE THREAD

**Issue by anderoonies** [espeak-ng/espeak-ng#995]
When building, I need to manually run `git log > ChangeLog` to run `autogen.sh`, which isn't possible when installing with brew.

M1 Mac, MacOS Big SUr

**Comment by jaacoppi** [comment]
The only file we're actually using is CHANGELOG.md.

Looks like the build system has dependencies to "ChangeLog" as well. I'm pretty sure it's unnecessary and could be removed. I'm not an expert with build systems so I'll wait for a second opinion.


grep ChangeLog Makefile*
Makefile:       $(srcdir)/espeak-ng.pc.in AUTHORS COPYING ChangeLog INSTALL \
Makefile:EXTRA_DIST = ChangeLog $(vim_registry_DATA) \
Makefile:##### ChangeLog:
Makefile:ChangeLog:
Makefile:       git log > ChangeLog
Makefile:dist-hook: ChangeLog
Makefile:.PHONY: ChangeLog
Makefile.am:##### ChangeLog:
Makefile.am:ChangeLog:
Makefile.am:    git log > ChangeLog
Makefile.am:dist-hook: ChangeLog
Makefile.am:.PHONY: ChangeLog
Makefile.am:EXTRA_DIST += ChangeLog
Makefile.in:    $(srcdir)/espeak-ng.pc.in AUTHORS COPYING ChangeLog INSTALL \
Makefile.in:EXTRA_DIST = ChangeLog $(vim_registry_DATA) \
Makefile.in:##### ChangeLog:
Makefile.in:ChangeLog:
Makefile.in:    git log > ChangeLog
Makefile.in:dist-hook: ChangeLog
Makefile.in:.PHONY: ChangeLog

**Comment by valdisvi** [comment]
`CHANGELOG.md` is short overview updated manually. `ChangeLog` file is updated automatically with detailed `git log` entries, when package is built with `make dist`.

**Comment by anderoonies** [comment]
So the resolution of this would be the home brew formula using make dist
rather than make?

**Comment by jaacoppi** [comment]
I think you should be able to run "make" and it should not depend on ChangeLog.

Can you first do "make clean" and the post the output of "make --debug"

**Comment by anderoonies** [comment]
without running `autogen.sh` first there's no Makefile, and `autogen.sh` depends on ChangeLog.
after manually making ChangeLog (`git log > ChangeLog`), here's the output of make --debug
[out.txt](https://github.com/espeak-ng/espeak-ng/files/6911691/out.txt)

**Comment by jaacoppi** [comment]
Can't see anything related to ChangeLog in your "make --debug" log.

What about the log for running autogen.sh (when ChangeLog file has not been created)?

**Comment by anderoonies** [comment]
I’m afk currently, but I believe you can replicate it by installing
espeak-ng via homebrew, as that formula runs “make”

brew install anarchivist/espeak-ng/espeak-ng

**Comment by jaacoppi** [comment]
Sorry, haven't had access to a Mac since 2009. Post the output when you have time.

**Comment by anderoonies** [comment]
```
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:4: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
Makefile.am:485: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:496: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:505: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:508: warning: *F: non-POSIX variable name
Makefile.am:1040: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: error: required file './ChangeLog.md' not found
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
```

**Comment by jaacoppi** [comment]
That's strange. 
1) Makefile.am does not depend on ChangeLog.md. No such file is ever mentioned in the output of my grep command earlier.
2) even if ChangeLog.md was required,, git log > ChangeLog wouldn't create it so I don't see how it solves anything.

**Comment by ryandesign** [comment]
[MacPorts has espeak-ng](https://ports.macports.org/port/espeak-ng) and does not experience this problem, so this problem is either specific to Homebrew or to the user's system.
