### ISSUE TITLE
eSpeak NG only speaks when executing a command

### ISSUE THREAD

**Issue by EG244** [espeak-ng/espeak-ng#997]
i tried to execute a command to read .txt files, but he only speaks instead of execute the command.

**Comment by valdisvi** [comment]
Look at [command line options](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.1.ronn).

**Comment by EG244** [comment]
> Look at [command line examples](https://github.com/espeak-ng/espeak-ng/blob/master/src/espeak-ng.1.ronn#examples).

i didnt worked it only speaks

**Comment by valdisvi** [comment]
So, what do you want it to do? To bake the cake?

**Comment by jaacoppi** [comment]
Please post the exact command you used. Are you using linux or Windows?

**Comment by EG244** [comment]
Windows

**Comment by EG244** [comment]
i tried to make espeak ng speak the txt file
espeak-ng -f test.txt
but he didnt speaked the txt file

_sorry if my english is bad, i'm brazillian_

**Comment by EG244** [comment]
### no help i will close this issue###

**Comment by valdisvi** [comment]
Parameters for `espeak-ng` are correct. But it may be file is not found. Similarly to graphical file managers, also in terminal important setting is current folder. `test.txt` is valid parameter, only if this file is in current folder of the terminal. If you are not sure, use file name like `c:/Users/Data/test.txt`.
