### ISSUE TITLE
en-GB-Standard-A

### ISSUE THREAD

**Issue by Adeleine** [espeak-ng/espeak-ng#998]
Hi. I've been searching for a long time . . . I want to be able to use tts with ssml tags to generate a wav or mp3 file with the voice in the picture below OFFLINE. I'm concerned about it vanishing or being altered over time, and I need it for a project (personal use only). 

Does this application allow this? 

If so, how do I do it? (I haven't tried it yet). 

If not, do you know of any that does? (commercial or free doesn't matter, my priority is pc and offline).

![Text-to-Speech_ Lifelike Speech Synthesis  _  Google Cloud and 1 more page - Profile 1 - Microsoft​ Edge 8_3_2021 7_15_43 AM](https://user-images.githubusercontent.com/29347937/128006837-941cdd24-6528-4816-98ff-4bf813672c62.png)

**Comment by valdisvi** [comment]
This question should be asked to Google. What you can do with eSpeak NG is described [here](https://github.com/espeak-ng/espeak-ng/#documentation).

**Comment by Adeleine** [comment]
@valdisvi Okay. I wasn't sure if they owned that voicebank, or not. I noticed a lot of sites have it but they're online only and don't offer software for use offline.

**Comment by jaacoppi** [comment]
Closed until further information from original author is received.
